### ISSUE TITLE
"unreadable content" when inserting BMP images into slide (similar to bug 56)

### ISSUE THREAD

**Issue by johnsug** [davidgohel/officer#101]
I'm running into the exact same issue as in https://github.com/davidgohel/officer/issues/56, except for I'm trying to submit a bitmap (bmp) instead of a gif/png/jpeg. (My apologies for not submitting code, however I thought it would be a bit redundant in light of the identical error happening in #56)

I'm using a png in my script for now to get around the issue, but this would be a nice fix in the next major release. Thanks,

**Comment by davidgohel** [comment]
Thanks, I understand.

I will add support for bmp in the next development session.

**Comment by davidgohel** [comment]
it's ok now. Thanks!
