### ISSUE TITLE
Issue with ">=" and "<=" in ctree plotting

### ISSUE THREAD

**Issue by weixing777** [davidgohel/officer#102]
Hi, thank you for developing this great package and it really helps me to export graphics to power point in a better way. 

I use a lot of decision tree to show how some simple decisions could be make, and one minor issue I encountered is that "<=" and ">=" are not correctly exported. I wonder if this would be an easy fix?

Here is an reproducible example:

```
library(officer)
library(rvg)
library(magrittr)
library(partykit)

tree_model <- ctree(data = iris, Species~.)

read_pptx() %>% 
    add_slide(layout = "Title and Content", master = "Office Theme") %>% 
    ph_with_vg(code = plot(tree_model), type = "body") %>%
    print("test.pptx")
```

Here is result from sessioninfo:

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils    
[6] datasets  methods   base     

other attached packages:
[1] partykit_1.2-0 rpart_4.1-12   mvtnorm_1.0-6 
[4] libcoin_1.0-1  magrittr_1.5   rvg_0.1.7     
[7] officer_0.2.1 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13      Formula_1.2-2     xml2_1.1.1       
 [4] splines_3.4.3     uuid_0.1-2        lattice_0.20-35  
 [7] R6_2.2.2          tools_3.4.3       R.oo_1.21.0      
[10] htmltools_0.3.6   yaml_2.1.14       survival_2.41-3  
[13] digest_0.6.12     inum_1.0-0        Matrix_1.2-12    
[16] zip_1.0.0         base64enc_0.1-3   R.utils_2.5.0    
[19] compiler_3.4.3    gdtools_0.1.6     R.methodsS3_1.7.1
```

**Comment by davidgohel** [comment]
Thanks,

Please follow the guidelines of the issue template :)

**Comment by davidgohel** [comment]
I can't see any issue.

**Comment by weixing777** [comment]
Thanks for the quick response. I opened your file and it doesn't display the correct sign either. I guess this might be some issue on my system.
Here is the test output from my side.
[test.pptx](https://github.com/davidgohel/officer/files/1647050/test.pptx)

**Comment by davidgohel** [comment]
Follow the guidelines, can you do that PLEASE?

**Comment by weixing777** [comment]
Sorry about that, I just updated the issue. Would this fit the requirement?

**Comment by davidgohel** [comment]
yes, thank you!

I will have a try on a Windows system later today or this we. You are using the latest version but on Windows... I think that's an *hell* non UTF8 encoding issue...

**Comment by davidgohel** [comment]
Might be related to https://github.com/davidgohel/rvg/issues/19

**Comment by davidgohel** [comment]
Good news

I worked on `rvg` and the issue is now solved (you need to update `davidgohel/rvg` from github, the new version is not yet on cran).

Because the `<=` is not part of the Symbol font, we need to specify to use Arial as font for symbol (it contains our symbol):

```
library(officer)
library(rvg)
library(magrittr)
library(partykit)

tree_model <- ctree(data = iris, Species~.)

read_pptx() %>% 
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with_vg(code = plot(tree_model), type = "body", font = list(symbol = "Arial")) %>%
  print("test.pptx")
```

[test.pptx](https://github.com/davidgohel/officer/files/1697297/test.pptx)

**Comment by weixing777** [comment]
Thanks! It works.
