### ISSUE TITLE
cursor_reach() fails with parenthesis

### ISSUE THREAD

**Issue by slarge** [davidgohel/officer#104]
First off, thanks for a fantastic suite of packages. I am trying to cursor_reach() to a specific piece of text that unfortunately contains a parenthesis (see attached .docx and code below).
```
library(officer)
library(magrittr)

ex = officer::read_docx("cursor_reach_example.docx")

## No problem
ex %>% 
cursor_reach(keyword = "Some text")

## Oh no
ex %>% 
  cursor_reach(keyword = "Some text (with an unfortunate use of a regex symbol)")

> Error: Some text (with an unfortunate use of a regex symbol) has not been found in the document

sessionInfo()

> R version 3.4.2 (2017-09-28)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] magrittr_1.5  officer_0.2.1
> 
> loaded via a namespace (and not attached):
>  [1] compiler_3.4.2    R6_2.2.2          htmltools_0.3.6   tools_3.4.2       base64enc_0.1-3  
>  [6] yaml_2.1.14       Rcpp_0.12.14      uuid_0.1-2        xml2_1.1.1        R.methodsS3_1.7.1
> [11] digest_0.6.13     zip_1.0.0         R.utils_2.6.0     R.oo_1.21.0     

```

Looking into the package source code, it seems that adding the option for regex arguments within cursor_reach() might be useful. For example:

```
## a fix
ex_summary <- docx_summary(ex)
grep("Some text (with an unfortunate use of a regex symbol)", ex_summary$text)
>integer(0)
grep("Some text (with an unfortunate use of a regex symbol)", ex_summary$text, fixed = TRUE)
>[1] 6
## Not run, but example of how the function could be expanded
# ex %>% 
 #  cursor_reach(keyword = "Some text (with an unfortunate use of a regex symbol)", fixed = TRUE)
```
If you agree, I'd gladly add via a pull request (should be as simple as adding ", ,.." to a few grepl()s in cursor_reach). Thanks again for all your hard work.
[cursor_reach_example.docx](https://github.com/davidgohel/officer/files/1659956/cursor_reach_example.docx)

**Comment by davidgohel** [comment]
Hi

In your case, you should run:

    ex <- cursor_reach(ex, keyword = "Some text \\(with an unfortunate use of a regex symbol\\)")

I have just added a note in the documentation explaining that the argument `keyword` is a regexpr pattern. 

I am not sure that's necessary but maybe I miss something. What would be the benefits of adding `...`? I dropped `grepl` options as ... the more you provide, the more you have to support/explain/etc :)

David

**Comment by slarge** [comment]
Hi David,
 Of course... thank you so much for the concise answer. I agree that it is probably easier to make the keyword as a regex rather than deal with the repercussions of adding additional arguments to the function. I think the documentation that you mention will be a useful reminder, regardless. Thanks and best wishes,

SL
