### ISSUE TITLE
Automated generation of annotated layouts for templates

### ISSUE THREAD

**Issue by john-harrold** [davidgohel/officer#105]
I'm working with a  PowerPoint template at work and I find going back and forth with the layout_properties/add_slide functions to be a little tedious and confusing. I think it be convenient if Officer could create an annotated layout to make identifying layouts, masters, and indices a little easier. The attached code will load all of the layouts in a given template. For each layout it will create a title indicated the layout and master names. For each body it will identify the index. Basically I use the resulting file to help me identify (visually) the layouts and indices to make coding a little more straight forward. Before, if I had a layout with a bunch body fields, I would just start putting in values, generate the output file, look at it, go back and modify my code. 

This is an example script:
[make_layout.txt](https://github.com/davidgohel/officer/files/1674738/make_layout.txt)

This is what the generated file looks like:
[annotated_layout.pptx](https://github.com/davidgohel/officer/files/1674719/annotated_layout.pptx)

I really like Officer and I think it's going to be very useful for me. I think something like this might make it a little better.

**Comment by davidgohel** [comment]
That's a very good idea, thanks!

Could you make a PR? If not, I will integrate your function next week (or within the following next weeks)

**Comment by john-harrold** [comment]
I've never made PR before, but I'll read through the docs and give it a try tonight.

**Comment by davidgohel** [comment]
Thanks!

Don't worry... this will be my second review :) I can help if necessary

**Comment by john-harrold** [comment]
Ok I think I've got it. I just need to fork officer, make whatever changes I want to my fork, commit those to the fork and then create a pull request comparing your master to my fork. Does that sound correct?

**Comment by davidgohel** [comment]
yes, and then we can comment and validate changes
