### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tammoterhark** [davidgohel/officer#11]
Hi, I would very much like to test this. Is there any documentation available?

**Comment by davidgohel** [comment]
Hi

on top of the github page :)
https://davidgohel.github.io/officer/

**Comment by tammoterhark** [comment]
OK, I was already afraid that this was it... I will try. Thanks.

**Comment by davidgohel** [comment]
what's wrong with the documentation?

**Comment by tammoterhark** [comment]
For me, as a beginner, it is not enough. I would be helped very much with a small tutorial with some examples. Like here: http://davidgohel.github.io/ReporteRs/

**Comment by davidgohel** [comment]
Did you read that:

https://davidgohel.github.io/officer/articles/word.html

**Comment by tammoterhark** [comment]
OK, this is great. Did I overlook something or was this document not linked to the page you referred me to earlier? The one at: http://davidgohel.github.io/ReporteRs/

**Comment by tammoterhark** [comment]
Now I see. The top row is a menu. I overlooked that.

**Comment by davidgohel** [comment]
Have a look here also (the module for advanced tables: https://davidgohel.github.io/flextable/articles/overview.html). flextable and officer are working well together.

Feedbacks are welcome when doc is unclear!

**Comment by tammoterhark** [comment]
Thank you. It is indeed much clearer now, since you separated ReporteRs into officer and flextable.
