### ISSUE TITLE
Could we find and replace in PPT ?

### ISSUE THREAD

**Issue by Fitousimon** [davidgohel/officer#110]
Hello, I begin to use OfficeR to work on PPT with R scripts. And I really need to do a "find and replace" function, to replace some words in an existing ppt with an R script. 
Do you think there is a way to manage it with officeR ?

Thank you. 

Simon

**Comment by davidgohel** [comment]
Simon,

> I really need to do a "find and replace" function, to replace some words in an existing ppt with an R script.

You also really need to follow the guidelines (the text you deleted to write that message) ;)

1. Are you working for Criteo?
2. Why is it that important?

David
