### ISSUE TITLE
Draft watermark

### ISSUE THREAD

**Issue by maislind** [davidgohel/officer#111]
Feature request:
I routinely have to iterate through reports with collaborators and it would be great to be able to trigger a 'DRAFT' watermark to be placed in the Word document on each run without having to open each document and do this by hand.

**Comment by davidgohel** [comment]
Hi, 

Unfortunately, implementing that option in R is not easy for now (this is a complex XML structure to write in an xml header file to be attached in the relevant sections of the document :/).

But you can add this watermark in the docx *template* (see argument `path` of `read_docx()`.

**Comment by maislind** [comment]
I suspected it would not be too simple, thanks for confirming. The draft template approach is reasonable enough for now. If I get around to trying to implement this, I will send a pull request for consideration.

**Comment by davidgohel** [comment]
OK, I will close the issue then. 

> If I get around to trying to implement this, I will send a pull request for consideration.

Given the complexity of the xml and that there is a solution via the template, I am not sure it worth the effort. Also it could conflict with headers and footers management.
