### ISSUE TITLE
Allow the user to alter the margins of a Word Document

### ISSUE THREAD

**Issue by jon23cooper** [davidgohel/officer#112]
I have the need to alter the Word document's margins, so that the contents fits on 1 page.
I have therefore made amendments to body_end_section and body_default_section to allow this. 
[section margins.txt](https://github.com/davidgohel/officer/files/1725480/section.margins.txt)

**Comment by davidgohel** [comment]
Thanks, it looks like a nice improvment!

I will work on it soon. It looks like easy to integrate.

David

**Comment by davidgohel** [comment]
Done, thanks!
