### ISSUE TITLE
Enhancement Request: `body_add_tot()` and `body_add_tof()`

### ISSUE THREAD

**Issue by atanasj** [davidgohel/officer#113]
When inserting `tables` or `figure` in a `word.docx`, it would useful to add a table of tables or figures e.g., `body_add_tot()` or `body_add_tof()`. 

This would particularly come in handy when working with dissertations, or other long-from writing where the output is `.docx`.

**Comment by davidgohel** [comment]
I think you are looking for `body_add_toc` function: https://davidgohel.github.io/officer/reference/body_add_toc.html

See here for a full example: https://davidgohel.github.io/officer/articles/word.html#table-and-image-captions
The code that will interest you is:

```
[...] %>% 
 body_add_par(value = "Table of tables", style = "heading 2") %>% 
  body_add_toc(style = "table title") %>% 
  body_add_par(value = "Table of graphics", style = "heading 2") %>% 
  body_add_toc(style = "graphic title")

```
