### ISSUE TITLE
Border thickness doesn't translate to Word

### ISSUE THREAD

**Issue by ksnap28** [davidgohel/officer#115]
I'm unable to adjust the line thickness of tables in Word docs. In the example below, I'm formatting a table with flextable. The different thicknesses are displayed as expected in the RStudio viewer and in the flextable HTML output, but not the Word doc.

```
library(flextable)
library(officer)
library(magrittr)

my_df = data.frame(col_a = c(1, 2, 3), col_b = c('a', 'b', 'c'))
my_tb = regulartable(my_df) %>%
    border(i = 1, border.top = fp_border(width = 2))
my_doc = read_docx()
my_doc = body_add_flextable(my_doc, my_tb)
print(my_doc, target = 'border_example.docx')
```

> > sessionInfo()
> R version 3.4.3 (2017-11-30)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] magrittr_1.5    officer_0.2.1   flextable_0.4.2

**Comment by davidgohel** [comment]
Thanks. It was half the expected size in docx documents, thanks for reporting that! Should be fixed now (you will need to update from this github repository)
