### ISSUE TITLE
Add formatted image?

### ISSUE THREAD

**Issue by noamross** [davidgohel/officer#119]
In **ReporteRs**, one could set the paragraph properties of an inserted image like so.

`addImage(..., par.properties = parProperties(padding=0)`

In **officer**, this doesn't seem to be possible. I think to do so one needs a way to put an image into an `fpar()`, and then use `body_add_fpar`, but I don't see an equivalent of `ftext()` for images.  Am I missing something or is this function not available yet?

**Comment by davidgohel** [comment]
The first example [here](https://davidgohel.github.io/officer/articles/word.html#slip_in_-functions) should help. The idea is to reuse an existing style.

The image equivalent to `ftext` is `external_img`. You can either: 
* add an empty fpar and then use `slip_in_img` 
* or use `body_add_fpar` with `external_img` (but it is not well documented).

Let's keep this issue opened until I improve the documentation and maybe make this easier to do.

**Comment by noamross** [comment]
But `external_img()` does not take `prop=` like `ftext()`.  So for an empty fpar with properties, could I set the style like so?
```
body_add_fpar(ftext("", prop = fp_par(padding=0))) %>%
    slip_in_img(...)
```

**Comment by davidgohel** [comment]
Sorry for the delay.  The following code (>= officer 3.0) is providing the alternative with `officer`.

I think `officer` is covering now all functionalities of `ReporteRs` :)

```
library(magrittr)
library(officer)

img.file <- file.path( R.home("doc"), "html", "logo.jpg" )
bl <- block_list(
  fpar(ftext("hello", shortcuts$fp_bold())),
  fpar(fp_p = fp_par(text.align = "center", padding=0),
    ftext("hello", shortcuts$fp_bold()),
    stext(" world", "strong"),
    external_img(src = img.file, height = 1.06, width = 1.39)
  )
)

x <- read_docx() %>%
  body_add_blocks( blocks = bl ) %>%
  print(target = "body_add_bl.docx")
```
