### ISSUE TITLE
object '_officer_wml_run_pic' not found

### ISSUE THREAD

**Issue by azhong9** [davidgohel/officer#120]
I am trying to add a ggplot to a word document or powerpoint deck.

```
g <- ggplot(mtcars, aes(x = cyl, y = gear , fill = hp))
newplot <- g + geom_bar(position = "fill", stat = "identity")
test <- read_docx()
test <- body_add_par(test, value = "graph", style = "heading 1")
test <- body_add_gg(test, value = newplot, style = "centered")
```

```
Error in wml_run_pic(as.character(x), width = dims$width * 72, height = dims$height *  : 
  object '_officer_wml_run_pic' not found
```

Similarly, I get the analagous error when using the powerpoint version of the function, "ph_with_gg()":

```Error in pml_run_pic(as.character(x), width = dims$width * 72, height = dims$height *  : 
  object '_officer_pml_run_pic' not found
```

Is this an issue with a dependency?

**Comment by davidgohel** [comment]
I can't reproduce, could you please follow the guidelines explained in the template (it is in the form when creating an issue)

**Comment by davidgohel** [comment]
Could you provide the `sessionInfo()`? 

> The results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example.

**Comment by azhong9** [comment]
> library(officer)
> library(ggplot2)
> 
> g <- ggplot(mtcars, aes(x = cyl, y = gear , fill = hp))
> newplot <- g + geom_bar(position = "fill", stat = "identity")
> test <- read_docx()
> test <- body_add_par(test, value = "graph", style = "heading 1")
> test <- body_add_gg(test, value = newplot, style = "centered")
**Error in ContinuousRange$new() : `inherit` must be a R6ClassGenerator.**
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_1.0.1 officer_0.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16      digest_0.6.8      MASS_7.3-43       R.methodsS3_1.7.1 grid_3.2.2        R6_2.1.1          plyr_1.8.3        gtable_0.1.2      magrittr_1.5     
[10] scales_0.5.0      zip_1.0.0         stringi_1.0-1     reshape2_1.4.1    uuid_0.1-2        R.oo_1.21.0       R.utils_2.6.0     xml2_1.1.1        proto_0.3-10     
[19] tools_3.2.2       stringr_1.0.0     munsell_0.4.2     colorspace_1.2-6  base64enc_0.1-3   htmltools_0.2.6  

I am now seeing the error: Error in ContinuousRange$new() : `inherit` must be a R6ClassGenerator.

**Comment by davidgohel** [comment]
Did you see that the error you declared has nothing to do with the new error you reported yesterday??

:)

So, you should probably update your packages (ggplot2 for example, officer then).

**Comment by azhong9** [comment]
Thank you David. Is this problem likely caused by one package trying to reference another package that is not updated?
