### ISSUE TITLE
error on read_docx: error in data.frame... arguments imply differing number of rows

### ISSUE THREAD

**Issue by jzadra** [davidgohel/officer#122]
Are there any limitations on the level of complexity in a docx file for what read_docx() can handle?

The doc I'm trying to read contains images, footers, tables, etc.  I get this error:

`Error in data.frame(stringsAsFactors = FALSE, style_type = xml_attr(all_styles,  : 
  arguments imply differing number of rows: 33, 10`

When I create a blank word document and add some text, read_docx() works fine.

**Comment by davidgohel** [comment]
No, it should not happen :/

Could you share the Word document or is it confidential?

**Comment by jzadra** [comment]
The doc I was working on is confidential, but I just tried it with our template and the same problem occurs.  I've attached it here.

Note that this originated as a google doc, and was "downloaded as .docx" if that sheds any light on the problem.
[Long Doc Template.docx](https://github.com/davidgohel/officer/files/1880463/Long.Doc.Template.docx)

**Comment by davidgohel** [comment]
Perfect, I can reproduce :)

**Comment by davidgohel** [comment]
OK, it should be fixed. Note that you will have to make sure your document has properties, this can be done by adding a value in one of the field of a *Word document properties pane* (see [here](https://support.office.com/en-us/article/view-or-change-the-properties-for-an-office-file-21d604c2-481e-4379-8e54-1dd4622c6b75))

**Comment by jzadra** [comment]
Working great on my actual file too. And the error message is great.  Thank you for the quick fix!!
