### ISSUE TITLE
Having issue adding text box to slides

### ISSUE THREAD

**Issue by cinkie** [davidgohel/officer#124]
I was trying to add text box and have no luck with `officer` package. 

In previous `ReporteRs` package, I could use `addParagraph` and `pot` to draw a text box and add text information to it. I went through the examples on https://davidgohel.github.io/officer/articles/powerpoint.html#add-content-into-a-placeholder, it only supports adding text to a existing placeholder. 

I also tried using `ph_empty_at`, `ph_add_par`, `ph_add_text` but the powerpoint says they found a problem in the targeting powerpoint and need to repair the content. After clicking Repair, it won't show anything.

Is there a better way just to add text box without a placeholder?

**Comment by davidgohel** [comment]
Can you follow the guidelines detailed in the issue template? Particulary:

- [ ] The code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example.
