### ISSUE TITLE
enhancement: width argument for `body_add_flextable()`

### ISSUE THREAD

**Issue by januz** [davidgohel/officer#125]
it would be great if one could set the width for the whole table (preferably as percent of text/page width) when printing a `flextable` to a docx document with `body_add_flextable()`.

Thanks for your your awesome packages!

**Comment by davidgohel** [comment]
Unfortunately, I don't think it can be done.

The flextable size is the sum of its columns widths and and sum of its rows heights. Implementing such an option would conflict with this concept.

**Comment by januz** [comment]
OK, thank you for clarification!
