### ISSUE TITLE
Support for Track Changes

### ISSUE THREAD

**Issue by ekatko1** [davidgohel/officer#132]
It is currently not possible to see neither tracked edits nor comments that are recorded in the Word documents. It would be great to have for several reasons. 

1) In Word, one can set a password that does not allow one to turn the Track Changes feature off, so loading a document that has been edited in this mode will generate incorrect output. (see reproducible example below).

2) This would be a first step towards closing the loop that would allow collaboration between people using RMarkdown to write manuscripts and their collaborators working on the Word versions of the document. Being able to read the changes from the Word file would allow me to write code that would allow me to apply those same changes to the source RMarkdown file, greatly facilitating collaboration. 
[https://stackoverflow.com/questions/35945728/ms-word-track-changes-and-rmarkdown](https://stackoverflow.com/questions/35945728/ms-word-track-changes-and-rmarkdown)

**Example**
The file Test.docx has been edited, with Track changes enabled and "great" replaced with "WONDERFUL" as well as a comment added. The read_docx returns "great WONDERFUL", not keeping track of the deletion, nor the comment.

[Test.docx](https://github.com/davidgohel/officer/files/1993730/Test.docx)

```
> library(officer)
> bob<-read_docx("Test.docx")
> bob
rdocx document with 2 element(s)

* styles:
                Normal Default Paragraph Font           Normal Table                No List 
           "paragraph"            "character"                "table"            "numbering" 
                 Table   annotation reference        annotation text      Comment Text Char 
               "table"            "character"            "paragraph"            "character" 
    annotation subject   Comment Subject Char           Balloon Text      Balloon Text Char 
           "paragraph"            "character"            "paragraph"            "character" 

* Content at cursor location:
  level num_id                   text style_name content_type
1    NA     NA Bob is great WONDERFUL         NA    paragraph
```

**Implementation**
An additional function might generate a dataframe that records all of the tracked changes.

Several changes can be made to and recorded in Word documents: 
- Large scale moving of paragraphs
- Changing of styles
- Within-paragraph deletions and insertions

**Comment by davidgohel** [comment]
Hi,

The purpose is to let people write Word and PowerPoint document. Your idea is excellent but I doubt I can find the time to do it :/

I also found another project which looks like close to what you are looking for: 
https://github.com/ropenscilabs/trackmd

David

**Comment by ekatko1** [comment]
Hi David,

That's amazing! I see it's been started only a couple of days ago at
ROpenScience unconference. Let's hope it succeeds!

Best,
Egor
