### ISSUE TITLE
body_replace_img_at_bkm() does not remove the previous img from media/ 

### ISSUE THREAD

**Issue by RboDev** [davidgohel/officer#134]
First many thanks for this very useful package !

I noticed an issue using the ```body_replace_img_at_bkm()``` function to update some images in an existing document. The function gives the expected result when the document is opened in Word.   

However the Word document file size increases after each update. All previous replaced images are not erased from the Word document itself (word/media/ directory contains all the versions).

Here a minimal sample code to reproduce the issue.

```
library(officer)
library(ggplot2)
library(magrittr)

# create a figure to be inserted in the doc
w = 6.5
h = 5.5
p <- ggplot(mtcars, aes(hp, mpg)) + geom_point()
ggsave("p1.png", width=w, height = h)

# create a new doc with one title and one figure
doc <- read_docx()

doc %<>%
  body_add_par("Plot 1", style="heading 1") %>%
  body_bookmark("bmk_title") %>%
  body_add_par("", style="Normal") %>%
  body_add_img("p1.png", width = w, height = h) %>%
  body_bookmark("bmk_fig1")

print(doc,"doc.docx")

# check the file size
file.size("doc.docx")  # 25856

# generate new plot image
plot2 <- ggplot(mtcars, aes(mpg)) + geom_histogram()
ggsave("plot2.png", width=w, height = h)

# Now modify the previous doc to change the title and the figure image
doc <- read_docx("doc.docx")

doc %<>%
  body_replace_text_at_bkm("bmk_title", "Plot 2") %>%
  body_replace_img_at_bkm("bmk_fig1",
                          external_img(src = "plot2.png", width = w, height = h))

print(doc, "doc.docx")
# Everything is fine, the doc is updated when opened with Word.
# however the size of the file has increased
file.size("doc.docx") #34467

# and keep increasing each time the image is replaced as the previous image is not erased from word/media 
```

**Comment by davidgohel** [comment]
The only solution I can imagine for that is a `sanitizer` function that would do some cleaning. I will see if it is easy to implement.

**Comment by RboDev** [comment]
Hi David,

Thanks for your answer.
I had a look to the package source code. The function ```cursor_replace_first_img``` form docx_part.R file is called to replace the image.  I see the code is looking for the bookmark then replaces the XML node and copy the new image to the /media directory without deleting the previous one.

I try to figure out how to retrieve the old image and remove it.
I found that ```doc$doc_obj$rel_df()``` returns a data frame that gives the relation between the ```id``` and the target file ```media/filexxxxxxxxx.png```.

The ```sanitizer``` approach is good too. I assume that the function will parse the XML to find all references to images in the /media directory and remove the orphan files.

I was thinking that having the option to keep the original image file name instead of generating a random one could be an easy way to fix the problem. Then the actual function will just overide the previous image instead of generating a new random image name.

I let you know if I find a solution. It's a good way to learn and I'll be glad to contribute.

Best regards,
Romain,

**Comment by davidgohel** [comment]
fixed with new function `sanitize_images`
