### ISSUE TITLE
lock aspect ratio of image pasted into a pdf (feature request)

### ISSUE THREAD

**Issue by GeraldCNelson** [davidgohel/officer#135]
I paste a collection of images into a pdf for a variety of uses. OfficeR accepts the pdf as an image (nice!) but then seems to automatically resize the image to fit in the location where I paste it. Can the package add an option to turn this automatic resizing off?

**Comment by davidgohel** [comment]
No sorry :) this would need to add lot of dependancies only to compute PDF dimensions and get the aspect ratio.

**Comment by GeraldCNelson** [comment]
The title of the request should really have been something like "don't change the aspect ratio". I want to just add the pdf image without it being automatically resized to the coordinates of the object it is being dropped into. Isn't there an automatic resize option somewhere that could be turned off?

**Comment by davidgohel** [comment]
sorry, no. To add an image, we NEED the width and the height.
