### ISSUE TITLE
Docx file : how to add a line break in a paragraph ?

### ISSUE THREAD

**Issue by FrancoisRidremont** [davidgohel/officer#136]
Hi,

My different attempts in adding a line break in a paragraph led to deadlock.
May you help me to script it correctly ?

Here is my script from the "_body_add_part()_" function and the different: 

doc <- read_docx() %>%
  body_add_par("Hello world! **\n** New line in the file", style = "Normal") %>%
print(doc, target = "body_add_par.docx" )

I try too : 
- body_add_par("Hello world! **\r** New line in the file", style = "Normal")
- body_add_par("Hello world! **\r \n** New line in the file", style = "Normal")

Thanks a lot.

Regards,

François

**Comment by davidgohel** [comment]
Hi,

You will have to call body_add_par each time you want to add a paragraph (a paragraph of text ends with a new line):

See: 
https://stackoverflow.com/questions/50350416/how-to-add-line-breaks

KR
David

**Comment by FrancoisRidremont** [comment]
Dear David,

Thank you very much.
I'm an addict of stackoverflow, but I haven't seen this post.

Regards,
François
