### ISSUE TITLE
print.rpptx misses character encoding for filename?

### ISSUE THREAD

**Issue by luke-a** [davidgohel/officer#138]
Thanks for this great package! I stumbled across an issue when saving a pptx with umlauts: 

```
library(officer)
packageVersion("officer")
# [1] ‘0.3.0’
pp <- read_pptx()
fn <- "filenameäüöß.pptx"
print(pp, tf<-file.path(tempdir(), fn))
list.files(tempdir(), pattern="^filename.*\\.pptx$")
# [1] "filenameÃ¤Ã¼Ã¶ÃŸ.pptx"
```

**Comment by davidgohel** [comment]
Hi,

You did not add your sessionInfo() results. I suspect you are on Windows and you are using RStudio. 

If this is the case, could you test your example in the good old R Gui?

David

**Comment by luke-a** [comment]
Hey @davidgohel , you are right: Win 7 + RStudio. However, `Rgui.exe` yields the same result. My `sessionInfo()` is: 
```

R version 3.4.0 (2017-04-21)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] officer_0.3.0

loaded via a namespace (and not attached):
 [1] compiler_3.4.0    R6_2.2.2          magrittr_1.5      htmltools_0.3.6   tools_3.4.0       base64enc_0.1-3   Rcpp_0.12.17     
 [8] uuid_0.1-2        xml2_1.2.0        R.methodsS3_1.7.1 digest_0.6.15     zip_1.0.0         R.utils_2.6.0     R.oo_1.21.0   
```

**Comment by davidgohel** [comment]
Thanks for the `sessionInfo()`. 

OK, one last try please ;) Could you try with the following?

```
library(officer)
pp <- read_pptx()
fn <- enc2utf8("filenameäüöß.pptx")
print(pp, tf<-file.path(tempdir(), fn))
```

**Comment by luke-a** [comment]
Sure. :) I had tried `enc2utf()`, `enc2native()` and even some `iconv(...)` - all to no avail. The result stays the same.

**Comment by luke-a** [comment]
Fwiw, the error seems to come from the encoding here: https://github.com/davidgohel/officer/blob/0ba550a5d70baf30632b48d0af4cf24d7d1d640c/R/pack_folder.R#L16

**Comment by davidgohel** [comment]
That's only necessary for win users...

**Comment by davidgohel** [comment]
you tried to delete this command and it worked?

**Comment by davidgohel** [comment]
@luke-a it is fixed now (on github version for now). 

Thanks for reporting that!
