### ISSUE TITLE
Feature request: prevent from overwriting existing files

### ISSUE THREAD

**Issue by GegznaV** [davidgohel/officer#139]
Is it possible to add a parameter to `print` methods (e.g., `print(..., overwrite = FALSE)`), that enables checking if a file with an indicated name already exists in the directory and prevents from accidental overwriting?
It would be nice if it were the default behavior of the function.

**Comment by davidgohel** [comment]
Sorry, I don't think that's a good idea; I know some users have implemented scripts that overwrite existing files. 

As a workaround, you can use `if(file.exists(...))` in your scripts.
