### ISSUE TITLE
persistent temporary working directory in case of print pptx crash

### ISSUE THREAD

**Issue by MaximeBrt** [davidgohel/officer#14]
Hi David,

I noticed when you try to write on an opened pptx and it crashes, as it should, that the working directory is not set back to its initial state. 

P.S.: this is not a big thing, but I will let you know the few errors i might encounter as I believe it can help you for your development. Thanks for your work btw :)

Regards,
Maxime

**Comment by davidgohel** [comment]
Thanks Maxime, I will fix that next week
