### ISSUE TITLE
add_slide at an index

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/officer#140]
There is a need for an option to let users add slides at a given position and not only at the end of the slidedeck.  Ideally, it should add just after the slide where the cursor is positioned.

**Comment by cfriszell** [comment]
Hi David!

Sorry to bug you, but just curious - Do you have any idea if this will be released soon? 

Thanks!
Cody

**Comment by davidgohel** [comment]
Sorry, no I don't know, did a try last week and there will be work :( 

The function is more likely to be `move_slide()` than `add_slide(index = ...)`

**Comment by cfriszell** [comment]
a move_slide() style function would still be perfect and solve all problems I've got :P 
Thanks for the update.

**Comment by davidgohel** [comment]
I think it is ok now, the new function is `move_slide()`. The modification is only in Github for now.

**Comment by cfriszell** [comment]
Sorry for my ignorance - Not entirely used to github or its uses just yet.

I tried to download the code using the devtools::install_github("davidgohel/officer") in the R command line, and got nothing.

I then just manually downloaded a clone from github, but I'm not entirely sure what the next step is to make the officer library (with the new move_slide()) work. 
Any pointers? Sorry for the dumb questions.

**Comment by davidgohel** [comment]
No worry, there is no dumb version :)

Maybe you have no compiler, I don't know. Please send results from `sessionInfo()`, I will learn from that your platform and your R version.

**Comment by davidgohel** [comment]
Thanks,

The function `move_slide` is available. It seems you already installed the necessary version :)

**Comment by cfriszell** [comment]
This is a snippet of the result from my code right now, I still am not having luck getting it to work properly. 

`> ##############################
> 
> ##############################
> # Slide 5 : RL #
> ##############################
> my_ppt<- on_slide(my_ppt, index = 3) #move cursor to slide at index3
> my_ppt <- move_slide(my_ppt, index = 3, to = 2)
Error in move_slide(my_ppt, index = 3, to = 2) : 
  could not find function "move_slide"
> `

Is there something that I'm doing wrong that could cause this to appear? I would think that would throw an error rather than an inability to find the function, no?

Thanks for your time!

**Comment by cellocgw** [comment]
@cfriszell  it would appear you didn't purge the old officer package from you library.   Try that, as well as removing it from your workspace, and see if that helps.

**Comment by davidgohel** [comment]
thanks @cellocgw for helping. That's a good suggestion :)

**Comment by cfriszell** [comment]
Okay, so I tried a few things but it was still giving me the same sort of issues.
I removed the old officer package from my library, and cleared my workspace -- no good.
I just uninstalled R, Rstudio, and all of the packages with it (which was really only magrittr, reporters, and officer).
I just reinstalled R and Rstudio, and then redownloaded the .ZIP of the newest officer code manually from github. Then, in Rstudio I went to tools>install packages > selected officer-master zip and installed. 
Afterwards, it displays this in the console :
`> install.packages("~/R/officer-master.zip", repos = NULL, type = "win.binary")
Installing package into ‘C:/Users/cfriszell/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)`

After that, I try to run my code again and none of the officer functions work properly.
I've tried including both library(officer) as well as library(officer-master) to no avail.

Any ideas?
Thank you guys again so much for taking your time to help.

**Comment by cfriszell** [comment]
also! This is to show my working directory is correct, and the new sessionInfo, now that I've reinstalled R and Rstudio. 
`> getwd()
[1] "C:/Users/cfriszell/Documents/R"
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0   `


This leads me to believe it's not downloaded correctly..

**Comment by davidgohel** [comment]
@cfriszell to install the package from Github, you can run the following command:

    devtools::install_github("davidgohel/officer")

As there is some cpp code to compile, you need also Rtools installed on your machine. 

**From what you told us, everything was ok.** So you don't need to try to reinstall it, it worked. 

Now if you don't find `move_slide`, it certainly mean you loaded an older version, that you have two different `officer` installed in 2 locations and that R is finding first the old one and don't load the last one. It's hard to tell you what to do as this would require to be able to dive into your machine to see what is installed, where, etc.

**Comment by cfriszell** [comment]
I think i figured it out.

My Rtools and R versions were incompatible, so it was having some issues with downloading, but I got it!
I had to revert my R version back to 3.3.x and then get the compatible Rtools for that, and from there everything works!

Thank you for your patience and work David, it is greatly appreciated!
