### ISSUE TITLE
doesn't work body_add_docx method

### ISSUE THREAD

**Issue by SergeyNosov** [davidgohel/officer#141]
doesn't work body_add_docx method
https://stackoverflow.com/questions/51066250/insert-an-external-docx-using-officer-pakage
```
library(officer)
library(magrittr)

read_docx(path = "/home/user/page1.docx") %>% # load page1.docx as base document
  body_add_break() %>% # add page break
  body_add_docx(src="/home/user/page2.docx") %>% #FIXME: This method doesn't work
  print(target = "/home/user/out.docx") # out.docx conteins only page1.docx !?
```

**Comment by davidgohel** [comment]
I can not reproduce. Please, follow the guidelines explained in the template of *new issue*.

**Comment by SergeyNosov** [comment]
Example from documentation 
```
img.file <- file.path( R.home("doc"), "html", "logo.jpg" )
if( file.exists(img.file) ){
  # create a example file to be inserted later in the final doc----
  doc <- read_docx()
  doc <- body_add_img(x = doc, src = img.file, height = 1.06, width = 1.39 )
  print(doc, target = "external_file.docx")

  # insert external_file.docx in the final doc----
  final_doc <- read_docx()
  doc <- body_add_docx(x = doc, src = "external_file.docx" )
  print(doc, target = "final.docx")
}
```
This just overwrite doc variable. In src parametr I can pass any string and I get the same result
`doc <- body_add_docx(x = doc, src = "external_file.docx" )`
And this `final_doc <- read_docx()` I can delet and also will get the same result

**Comment by davidgohel** [comment]
OK, thanks, I will correct, it should be:

```
library(officer)
img.file <- file.path( R.home("doc"), "html", "logo.jpg" )
if( file.exists(img.file) ){
  # create a example file to be inserted later in the final doc----
  doc <- read_docx()
  doc <- body_add_img(x = doc, src = img.file, height = 1.06, width = 1.39 )
  print(doc, target = "external_file.docx")
  
  # insert external_file.docx in the final doc----
  final_doc <- read_docx()
  final_doc <- body_add_docx(x = final_doc, src = "external_file.docx" )
  print(final_doc, target = "final.docx")
}
```

However, what is the issue with your first code? Could you please explain what *does not work*. Also please add `sessionInfo()`.

**Comment by SergeyNosov** [comment]
Sorry, but your corrected code also doesn't work. I get empty final.docx.
I use:
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

other attached packages:
[1] magrittr_1.5  officer_0.3.1

officer package installed from cran

**Comment by davidgohel** [comment]
I asked you to explain "does not work". I won't ask a third time, I don't have time for that.

**Comment by davidgohel** [comment]
that is what I get: [final.docx](https://github.com/davidgohel/officer/files/2144935/final.docx)

You never provided what you get nor describe the error nor answer my questions.
