### ISSUE TITLE
FR: Both width and style of table

### ISSUE THREAD

**Issue by pank** [davidgohel/officer#142]
Hi,

Thank you for providing and working on `officer`.  It is a very neat tool!  I hope this is the right place to ask this (as opposed to the `flextable` issues page or stackoverflow).

In a `docx` file, I hope to make a table with a certain width and a certain Word style, defined by the initial document.
As far as I can tell, I can get my desired width via `flextable` and my desired style via  `officer` (`body_add_table`), but I am struggling to get both. 

Example:

```R
library(magrittr)
library(officer)
library(flextable)

desired_style='Table Professional' # really my_imposed_word_table_style

df <- with(list(var=LETTERS[1:3], val=1:3,
                blank0=rep("", 3),
                blank10=rep(strrep("", 10))),
           data.frame(Variable=var,
                      Initial.value=val,
                      Addition=blank0,
                      Reason=blank10,
                      Total=blank0))

cm_to_inches <- 0.3937008
desired_width <- c(3, 1.75, 1.75, 8, 1.75) * cm_to_inches
ft <- flextable(df) %>% width(seq_along(df), desired_width)

doc <- read_docx()
doc %<>% body_add_par(paste("The desired outcome is a table in the 'desired' style",
                            "that is the width of the page, or at least a certain width."),
                      style="Normal") %>%
    body_add_par("", style = "Normal") %>%
    body_add_par("This table will be too short, as some values will only be filled out later",
                 style = "Normal") %>%
    body_add_par("", style = "Normal") %>%
    body_add_table(df, style=desired_style) %>%
    body_add_par("", style = "Normal") %>%
    body_add_par("For the flextable, I can't seem to specify my desired style",
                 style = "Normal") %>%
    body_add_par("", style = "Normal") %>%
    body_add_flextable(ft)
print(doc, target="dummy.docx")
```

Output:

![dummy](https://user-images.githubusercontent.com/666845/42582690-1b46c32c-8530-11e8-98ab-3f0b33aa6fa6.PNG)

Additional notes:

- I am not a Word expert, but it seems that I cannot fix this with a new style [as styles cannot dictate the width](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_mac/preferred-table-width-in-table-style/dc06b951-6d0a-4599-8f7e-5227560252c5). 
- I tried to insert `a long string` to get the desired proportions of the `body_add_table` table and replacing `a long string` with `""` later, but it did not work.
- I don't know anything about office xml, but looking at the two following strings, it seems that the style of the `officer` table is determined by `<w:tblStyle w:val=\"Table Professional\"/>`.  However, I don't know if that would "overrule" all the inlined style of `ft_str` (probably not).  Would it be possible to have a "blank" `flextable` theme that simply adds a `w:tblStyle`?  E.g. `ft %>% theme_word_style(style=desired_word_document_style)` 
```R
of_str <- officer:::wml_table(officer:::characterise_df(df), desired_style)
ft_str <- flextable:::docx_str.regulartable(ft)
```

Thank you for reading this,
Rasmus

PS: `sessionInfo`

```R
sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Danish_Denmark.1252  LC_CTYPE=Danish_Denmark.1252    LC_MONETARY=Danish_Denmark.1252
[4] LC_NUMERIC=C                    LC_TIME=Danish_Denmark.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5    flextable_0.4.4 officer_0.3.1  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17    lattice_0.20-35 zoo_1.8-2       rprojroot_1.3-2 digest_0.6.15   grid_3.4.3      R6_2.2.2       
 [8] backports_1.1.2 evaluate_0.10.1 zip_1.0.0       stringi_1.1.7   gdtools_0.1.7   uuid_0.1-2      xml2_1.2.0     
[15] xts_0.10-2      rmarkdown_1.10  functional_0.6  tools_3.4.3     stringr_1.3.1   compiler_3.4.3  base64enc_0.1-3
[22] htmltools_0.3.6 knitr_1.20
```

**Comment by davidgohel** [comment]
Hello Rasmus

Thanks, your email is very clear. I will take time later to answer your question (probably this we).

**Comment by davidgohel** [comment]
This is what I would do to reproduce your table: 

```
library(magrittr)
library(officer)
library(flextable)

df <- with(list(var=LETTERS[1:3], val=1:3,
                blank0=rep("", 3),
                blank10=rep(strrep("", 10))),
           data.frame(Variable=var,
                      Initial.value=val,
                      Addition=blank0,
                      Reason=blank10,
                      Total=blank0))

ft <- flextable(df) %>% 
  theme_box() %>% 
  bg(bg = "black", part = "header") %>% 
  color(color = "white", part = "header") %>% 
  bold(bold = TRUE, part = "header") %>% 
  fontsize(size = 12, part = "all") %>% 
  font(fontname = "Cambria", part = "all") %>% 
  autofit()

doc <- read_docx() %>% 
  body_add_flextable(ft)
print(doc, target="dummy.docx")
```

<img width="319" alt="capture d ecran 2018-07-17 a 10 35 13" src="https://user-images.githubusercontent.com/4331618/42805859-313c20ce-89ad-11e8-9ac9-22566e96a644.png">


I am not sure how to help on the width aspect of you columns. You can use [`autofit`](https://davidgohel.github.io/flextable/reference/autofit.html), it will auto adjust width (so that content always fit on one row). You can also use [`dim_pretty`](https://davidgohel.github.io/flextable/reference/dim_pretty.html) and use all computed widths except the corresponding width for `Addition`. 

> Would it be possible to have a "blank" flextable theme that simply adds a w:tblStyle? 

No, there are already some `theme_` functions. They do not depend of any Word template. Also you can derivate one of these functions to create your own style.

**Comment by pank** [comment]
Thanks for the example.

I have been given a table template by my organization which I am supposed to use for their documents.  It would be better to use the official style rather than reproducing it, but perhaps that is the only way to gain the added flexibility of flextables.

Kind regards,
Rasmus

**Comment by davidgohel** [comment]
OK, 

I will give a try later :)

**Comment by davidgohel** [comment]
Need to be able to specify widths with function `body_add_table()`

**Comment by davidgohel** [comment]
This issue is opened since too much time. Sorry. I will re open when I will find time for it

KR
David
