### ISSUE TITLE
cursor_reach to the header or the footer of word pages?

### ISSUE THREAD

**Issue by eusebe** [davidgohel/officer#144]
Hi, 

Thank you for your wonderfull package.

When creating a word document, it seems impossible to use 'cursor_reach' to place the virtual cursor in the header or the footer. I think it could be usefull, for example to show up the author of a document in the header of all pages, or whatever. 

Is it a feasible option? Or is there another way to do that?

Best wishes, 
David Hajage

**Comment by davidgohel** [comment]
Hi,

There are functions to replace content in headers or footers:

https://davidgohel.github.io/officer/reference/index.html#section-replace-content-in-word-documents

Also flextable can be inserted (recently implemented): https://github.com/davidgohel/flextable/blob/master/R/body_add_flextable.R#L39

But there is no virtual cursor ability in headers and footers. 

To summarize, you can not dive with cursor in headers and footers but you can replace existing content (designed in the original doc/template). 

Does that help?

**Comment by eusebe** [comment]
Perfectly!
I am really sorry, I totally missed this feature...

Thanks, 
David
