### ISSUE TITLE
Download pptx object from Shiny app

### ISSUE THREAD

**Issue by markhwhiteii** [davidgohel/officer#145]
I am using `mschart` and `officer` to create charts in a `.pptx` file in Shiny, and I'd like the user to be able to download it. I noticed this issue from `officer`'s predecessor, https://github.com/davidgohel/ReporteRs/issues/18, but wasn't sure if there was a way to do this using the `officer` package?

**Comment by davidgohel** [comment]
The proposed solution should work unless I am missing something.

**Comment by markhwhiteii** [comment]
The recommendation is:

```
utput$out_docpptx = downloadHandler(
    filename = function() {
      "yourfile.pptx"
    },

    content = function(file) {
        #... your_doc_object is the docx or pptx object

      my_temp_file = tempfile( fileext = ".pptx")
      writeDoc( your_doc_object, my_temp_file )
      file.rename( from = my_temp_file, to = file )
    }
  )
```

But `writeDoc` was in the `ReporteRs` package, not `officer`.

I have an object, `chart` that I'm trying to export. I use this function, for example:

```
gen_pptx <- function(chart, file) {
  read_pptx() %>% 
    add_slide(layout = "Title and Content", master = "Office Theme") %>% 
    ph_with_chart(chart = chart) %>% 
    print(target = paste0(file, ".pptx"))
}
```

And then put it in the `downloadHandler` like:

```
downloadHandler(
  filename = function() paste0("chart_", Sys.Date()),
  content = function(file) {
    gen_pptx(chart, file)
  }
)
```

There's no error, but my browser tells me it "Failed - no file"

**Comment by markhwhiteii** [comment]
Here's a reproducible example:

```
library(shiny)
library(officer)
library(mschart)
library(dplyr)

gen_pptx <- function(chart, file) {
  read_pptx() %>% 
    add_slide(layout = "Title and Content", master = "Office Theme") %>% 
    ph_with_chart(chart = chart) %>% 
    print(target = paste0(file, ".pptx"))
}

chart <- data.frame(x = letters[1:3], y = 1:3) %>% 
  ms_barchart(x = "x", y = "y")

ui <- fluidPage(
  downloadButton("chart", "Get Chart")
)

server <- function(input, output) {
   output$chart <- downloadHandler(
     filename = paste0("chart", Sys.Date()),
     content = function(file) {
       gen_pptx(chart, file)
     }
   )
}

shinyApp(ui = ui, server = server)
```

**Comment by davidgohel** [comment]
Sorry, I was talking about `file.rename` not about `writeDoc`...

Thanks for the reproducible example. That helps to help :)

```
library(shiny)
library(officer)
library(mschart)
library(dplyr)

gen_pptx <- function(chart, file) {
  read_pptx() %>% 
    add_slide(layout = "Title and Content", master = "Office Theme") %>% 
    ph_with_chart(chart = chart) %>% 
    print(target = file)
}

chart <- data.frame(x = letters[1:3], y = 1:3) %>% 
  ms_barchart(x = "x", y = "y")

ui <- fluidPage(
  downloadButton("chart", "Get Chart")
)

server <- function(input, output) {
  output$chart <- downloadHandler(
    filename = function() paste0("chart_", Sys.Date(), ".pptx"),
    
    content = function(file) {
      file_pptx <- tempfile(fileext = ".pptx")
      gen_pptx(chart, file_pptx)
      file.rename( from = file_pptx, to = file )
    }
  )
}

shinyApp(ui = ui, server = server)
```

**Comment by markhwhiteii** [comment]
Thanks @davidgohel. If you have time, could you explain why it is we have to make a `tempfile` first?

**Comment by davidgohel** [comment]
@markhwhiteii I don't remember :/ (I am in holidays, will try to answer that next week, *beep* me if I forget)

**Comment by markhwhiteii** [comment]
No problem, thanks for taking time out of your holidays to respond!

**Comment by ponnet** [comment]
Seems like it is no longer downloading the file with the above code :)
In flexdashboard:

> output$downBtn <- downloadHandler(
>     filename = function() paste0("datpresentation", Sys.Date(), ".pptx"),
>     
>     content = function(file) {
>       file_pptx <- tempfile(fileext = ".pptx")
>       gen_pptx(list(startdt = input$startdate,
>                     enddt = input$enddate), 
>                dat1(), 
>                dat2(), 
>                file_pptx)
>       file.rename( from = file_pptx, to = file )
>     }
> )

**Comment by WilDoane** [comment]
Updated for current version of officer:

```
library(shiny)
library(officer)
library(mschart)
library(dplyr)

gen_pptx <- function(chart, file) {
  read_pptx() %>% 
    add_slide(layout = "Title and Content", master = "Office Theme") %>% 
    ph_with("Example Chart", location = ph_location_type("title")) %>%  # not necessary
    ph_with(chart, location = ph_location_type("body")) %>%  # necessary change
    print(target = file)
}

chart <- data.frame(x = letters[1:3], y = 1:3) %>% 
  ms_barchart(x = "x", y = "y")

ui <- fluidPage(
  downloadButton("chart", "Get Chart")
)

server <- function(input, output) {
  output$chart <- downloadHandler(
    filename = function() paste0("chart_", Sys.Date(), ".pptx"),
    
    content = function(file) {
      file_pptx <- tempfile(fileext = ".pptx")
      gen_pptx(chart, file_pptx)
      file.rename( from = file_pptx, to = file )
    }
  )
}

shinyApp(ui = ui, server = server)
```

**Comment by davidgohel** [comment]
@WilDoane This thread is 4 yo. and I think the solution in the documentation is simpler than the one you wrote here as "the solution"?  https://ardata-fr.github.io/officeverse/faq.html#how-to-create-a-report-within-shiny-application

Also it implies that you need one solution per version of officer. Which seems wrong to me.

Can you explain why not the documented solution and your code instead? Why "current version of officer"? The same code is used since the beginning to create a pptx or a docx, no??

**Comment by WilDoane** [comment]
You're right that the documentation solution is cleaner. The code as presented on this issue no longer worked due to removal of ph_with_chart, so I was offering a modest change to the old proposed code that reflected that change.

I didn't intend to suggest this was a preferred solution, just that it brought this issue up to date with a workable answer.
