### ISSUE TITLE
inserting a svg image produces a corrupted word document

### ISSUE THREAD

**Issue by bradrg** [davidgohel/officer#146]
inserting a svg image using body_add_img, e.g.:

`body_add_img(src = "facts.svg", width = 4, height = 2.3, pos = "before")`

produces a corrupted word document

**Comment by davidgohel** [comment]
I thought SVG was not supported in MS Word (on my macOS, it is not). From what I just read, support for SVG is only for Microsoft Office 365. 

I assume you produced the svg with R... If vector graphic format is important for you, I'd advise following example that can be read here: https://davidgohel.github.io/officer/articles/offcran/graphics.html#r-plots. If vector graphic format is not important, you can rasterize your file using the excellent package `rsvg`. See https://cran.r-project.org/package=rsvg

**Comment by bradrg** [comment]
Thank you. Yes, my version of Word (Office 365) supports insertion of SVG images.  It would be great if this was directly supported in the future, but in the meantime I will review the links you suggest.

**Comment by davidgohel** [comment]
I have no sample doc to see what the final result is in a Word document, I suspect this will create an *invalid* document for the majority of the people that read the document (those who are not using office 365). 

Could you post in that thread an example so that I could have a look a the generated structure? (drag and drop the file in your answer, it should upload the doc)

**Comment by bradrg** [comment]
Happy to. Example DOCX with SVG inserted attached.
[svg_test.docx](https://github.com/davidgohel/officer/files/2287653/svg_test.docx)

**Comment by davidgohel** [comment]
Thanks!

I was wrong :) There is a fallback. If svg is not supported, a raster version is used (the svg is transformed as a png). 

This then can be implemented. I will not do it now but will try later (be patient please!)

**Comment by bradrg** [comment]
FYI, thank you for the original links, I was able to solve my image quality issues by using the EMF files.  This reduces my immediate need for this feature.  Thank you for all your hard work on this package!

**Comment by timelyportfolio** [comment]
I have locally a powerpoint function that converts svg with `rsvg` and then uses the image function.  Let me know if you have interest in a pull.

**Comment by davidgohel** [comment]
@timelyportfolio yes sure, thank you! I am a little bit annoyed by the dependency, can it go to `suggests`?

**Comment by tobwen** [comment]
I've just tested the docx provided by @bradrg in Office 2003. The fallback to images works! So these files are compatible even for older versions.

**Comment by timelyportfolio** [comment]
@davidgohel @tobwen Sorry for the delay, but I wanted to make sure I had clearance from the project with respect to sharing.  The prototype code looks like this, but unfortunately I have not found a way to make it work with fonts :(

```
library(rsvg)
library(svglite)
library(officer)

ph_with_svg_at <- function (x, value, width, height, left, top, ...) 
{
    if (!requireNamespace("rsvg")) 
        stop("package rsvg is required to use this function")
    stopifnot(inherits(value, c("character","svg")))
    file <- tempfile(fileext = ".png")
    options(bitmapType = "cairo")
    rsvg_png(svg = charToRaw(value), file = file)
    #on.exit(unlink(file))
    print(file)
    ph_with_img_at(x, src = file, width = width, height = height, 
        left = left, top = top)
}

fileout <- tempfile(fileext = ".pptx")
doc <- read_pptx()
doc <- add_slide(doc, layout = "Title and Content", master = "Office Theme")

doc <- ph_with_svg_at(x = doc, value = svg_test, width=4, height=2, left = 0.25, top = 0.25 )

print(doc, target = fileout )
```

**Comment by davidgohel** [comment]
I added a fix to handle svg as suggested by @timelyportfolio . I find that solution better as I don't have to create a new wrapper for that specific need. I am not sure I understood what was the issue with fonts - i will fix it later if something is to be fixed.
