### ISSUE TITLE
Enhancement: Screen Shot of Slide

### ISSUE THREAD

**Issue by hathawayj** [davidgohel/officer#147]
### Screen Shot of Slide 

*Caveat:*  I am not even sure this is possible.  So forgive me if this is the wrong package to request such a feature.

It is really nice to be able to rip images from slides.  I have used your package extensively over the last two weeks.  However, many times there are 2-3 images that are overlaid to make one full image in slides.  It is a problem of using PowerPoint as Photoshop.  Or maybe even cheating on ggplot2 theme settings.

Additionally: tables often have quite a bit of editing to convey a message beyond the raw values.

**Request:**  Is there a way to have a 'screenshot' or 'slideshot' functionality?

- `shot_slide`:  saves a full image of the slide.
- ` shot_table`: saves a full image of the table on the slide.
- `shot_images`: saves a full image of the images on the slide.  This function could have an option to say which images should be in the shot.
- `shot_text`: saves a full image of the text with bullets and colors

Thanks!

**Comment by davidgohel** [comment]
That's possible but the solution I have depends on libreoffice. Here is the code I am using. Hope it will help. I've hard-coded libreoffice path then you probably will have to adapt or improve the code. 

The code is transforming a *PPTX* or *DOCX* file to *PDF* then to *PNG*.
```
library(pdftools)
office_shot <- function( file, wd = getwd() ){
  cmd_ <- sprintf(
    "/Applications/LibreOffice.app/Contents/MacOS/soffice --headless --convert-to pdf --outdir %s %s",
    wd, file )
  system(cmd_)
  
  pdf_file <- gsub("\\.(docx|pptx)$", ".pdf", basename(file))
  pdf_file <- file.path(wd, pdf_file)
  screen_imgs <- pdftools::pdf_convert(pdf = pdf_file, format = "png", verbose = FALSE)
  unlink(pdf_file)
  screen_imgs
}
office_shot(file = "your_presentation.pptx")
```
