### ISSUE TITLE
Hide background graphics supported but a bit too string

### ISSUE THREAD

**Issue by MaximeBrt** [davidgohel/officer#15]
Hi David,

Small thing I noticed: when you have the "Hide background graphics"check box checked in a layout, it hides not only background graphics but some of the regular ones too.

Best,
Maxime

**Comment by davidgohel** [comment]
Hi

I am not sure I understood how to reproduce the example, can you provide a template and a code example?

David

**Comment by MaximeBrt** [comment]
Hi,

Not sure my company is ok with sharing the templates but I can try to make myself clearer:
in powerpoint templates in Slide Master view, you have, in the SLIDE MASTER tab, a checkbox you can check if your template has background graphics (that you can not change easily), called "Hide background graphics" (in the background sub task).
If you check it in your ppt template that you want to use, then it hides the background graphics as it should, but also some of the other regular form objects you have in your template and you would like to keep (not all of them strangely). 
If it is still not clear (not easy to picture you're right), I'll try to get you an example template.

Off topic: do you have an example of the ph_with_vg function used with a ggplot ?

Maxime

**Comment by davidgohel** [comment]
OK, I will try with your description, thanks

off-topic answer: the second example of this section is using `ph_with_vg`: https://davidgohel.github.io/officer/articles/offcran/graphics.html#powerpoint-documents-and-graphics 

And `ph_with_vg_at` will also be implemented soon...

**Comment by davidgohel** [comment]
I checked. 

I can't do anything about that, it's a PowerPoint feature that says *do not display* images. If you add an image in your template and check the option after, you will see your image disappearing.
