### ISSUE TITLE
Feature request: Highcharts Objects to Powerpoint

### ISSUE THREAD

**Issue by MarkusLang1987** [davidgohel/officer#150]
First of all, thank you very much for the package! It helped me a lot to provide better products to our customers :-).

I have one request: We use the Highcharts Package for our Shiny-Apps and I wanted to ask if it is possible to implement the gg_obj feature for highcharts too, since every time we offer a downloadble Powerpoint, we have to rebuild the plots with ggplot.

Or is that even already possible?

Kind regards,
Markus

**Comment by davidgohel** [comment]
Thanks!

Unfortunately, this is not possible. Highcharts is an htmlwidget and is made for HTML display. 

The workaround is to use webshot to create a png from the htmlwidget instance and then to insert the result with `ph_with_img()`.

Kind regards,
David

**Comment by MarkusLang1987** [comment]
Thank you very much for your answer. Too bad :-(
