### ISSUE TITLE
Officer: issue while opening generated ppt report

### ISSUE THREAD

**Issue by ashwininepa** [davidgohel/officer#154]
Hi @davidgohel , I am getting this error of corrupt file when I try to open the pptx report prepared using Officer. I am using our office template for it and using mschart to dump the charts in ppt. Can you please provide some input on this? 

And even if I use blank template to create the ppt from scratch, I get this issue. 

My sessionInfo() is:

```
sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats graphics grDevices utils datasets methods base

other attached packages:
[1] DBI_1.0.0.9000 bindrcpp_0.2.2 flextable_0.4.5 mschart_0.2.3 rvg_0.1.9
[6] officer_0.3.2 nepa_0.3.17 RCurl_1.95-4.10 bitops_1.0-6 rvest_0.3.2
[11] xml2_1.2.0 lubridate_1.7.4 forcats_0.3.0 stringr_1.3.1 dplyr_0.7.6
[16] purrr_0.2.5 readr_1.1.1 tidyr_0.8.1 tibble_1.4.2 tidyverse_1.2.1
[21] ggplot2_3.0.0

loaded via a namespace (and not attached):
[1] Rcpp_0.12.17 lattice_0.20-35 assertthat_0.2.0 rprojroot_1.3-2 digest_0.6.15
[6] psych_1.8.4 R6_2.2.2 cellranger_1.1.0 plyr_1.8.4 odbc_1.1.6
[11] backports_1.1.2 evaluate_0.10.1 httr_1.3.1 pillar_1.2.3 gdtools_0.1.7
[16] rlang_0.2.1 lazyeval_0.2.1 uuid_0.1-2 readxl_1.1.0 rstudioapi_0.7
[21] data.table_1.11.4 blob_1.1.1 rmarkdown_1.10 foreign_0.8-70 bit_1.1-14
[26] munsell_0.5.0 broom_0.4.5 compiler_3.5.1 modelr_0.1.2 pkgconfig_2.0.1
[31] base64enc_0.1-3 mnormt_1.5-5 htmltools_0.3.6 tidyselect_0.2.4 crayon_1.3.4
[36] withr_2.1.2 grid_3.5.1 nlme_3.1-137 jsonlite_1.5 gtable_0.2.0
[41] magrittr_1.5 scales_0.5.0 writexl_1.0 zip_1.0.0 cli_1.0.0
[46] stringi_1.1.7 reshape2_1.4.3 tools_3.5.1 bit64_0.9-7 glue_1.2.0
[51] hms_0.4.2 parallel_3.5.1 yaml_2.1.19 colorspace_1.3-2 knitr_1.20
[56] bindr_0.1.1 haven_1.1.2
```

While, I create my theme as:

```
mytheme <- mschart_theme(
  axis_title_x = fp_text(font.size = 10, italic = TRUE),
  axis_title_y = fp_text(font.size = 10, italic = TRUE),
  legend_text = fp_text(font.size = 10), axis_text = fp_text(),
  legend_position = "r",
  grid_major_line_y = fp_border(color = "#99999999", style = "dashed"),
  grid_major_line_x = fp_border(width = 0))
```

Creating the plot as:

```
c1 <- mschart::ms_linechart(test, "week", "value", group = "question") %>%
  chart_labels(xlab = "Week", ylab = "Value") %>%
  chart_data_labels(position = "r") 
c1 <- set_theme(c1, mytheme)
```

And dumping the graphs on slides in the pre-defined corporate template as:

```
doc <-  read_pptx("Template.pptx")

doc <- doc %>% 
  on_slide(2) %>%
  ph_with_chart(chart = c1, type = "body")
```

**Comment by davidgohel** [comment]
Hi,

Sorry, can not reproduce the issue. Please make it reproducible. i.e define `test`.

**Comment by ashwininepa** [comment]
Hey, I solved this thing. There was an issue with the data only. It took some time to figure that out. Needed to categorize the data properly and then it got solved. 

Thank you very much for your reply :)

**Comment by davidgohel** [comment]
Hi sorry 

I am still interested to see the data as it seems you should get a warning or a message saying "it will generate a corrupted file". I would be happy to add few tests/warnings so that users won't spend too much time finding out what is wrong with the dataset.

**Comment by ashwininepa** [comment]
Hey, can I get your email id, so that I can share the file with you, as I can not share it publicly?

**Comment by davidgohel** [comment]
Thanks!

It's written here : https://github.com/davidgohel/officer/blob/master/DESCRIPTION#L7

David

**Comment by ashwininepa** [comment]
Thanks!

**Comment by davidgohel** [comment]
Thanks for sharing. I am not able to reproduce but I am on a macOS.

I found that in one of the *answer*, there is a letter `Ö` and I am pretty sure this is why you had trouble - your data file is ISO-8859-1 encoded. 

I need to test the following on Windows OS but I am pretty sure this could solve your problem.

````
library(mschart)
library(officer)
library(magrittr)
library(readr)
library(fpeek)

guess_encoding("yourfile.csv")
# this is ISO-8859-1 encoded, let's encode it as UTF-8 :
peek_iconv(path = "yourfile.csv", from = "ISO-8859-1", newfile = "yourfile_UTF8.csv")
test <- read_csv("yourfile_UTF8.csv") 

mytheme <- mschart_theme(
  axis_title_x = fp_text(font.size = 10, italic = TRUE),
  axis_title_y = fp_text(font.size = 10, italic = TRUE),
  legend_text = fp_text(font.size = 10), axis_text = fp_text(),
  legend_position = "r",
  grid_major_line_y = fp_border(color = "#99999999", style = "dashed"),
  grid_major_line_x = fp_border(width = 0))

c1 <- mschart::ms_linechart(test, "week", "value", group = "answer") %>%
  chart_labels(xlab = "Week", ylab = "Value") %>%
  chart_data_labels(position = "r") 
c1 <- set_theme(c1, mytheme)

doc <-  read_pptx()

doc <- doc %>% 
  add_slide( layout = "Two Content", master = "Office Theme") %>%
  ph_with_chart(chart = c1, type = "body") %>% 
  print(target = "test.pptx")
````

**Comment by davidgohel** [comment]
I will test that tomorrow

**Comment by ashwininepa** [comment]
Hey, thank you very much for your time looking into this thing. I will also check on my side how it goes and update the same here!

**Comment by davidgohel** [comment]
@ashwininepa Sorry, I have not been able to reproduce the issue, I tried on my mac and on a Windows computer... Maybe you have a setting I don't have. I am not able to reproduce!

**Comment by davidgohel** [comment]
If you meet that issue again, please let me know.

**Comment by ashwininepa** [comment]
Hi @davidgohel , I also could not find the thing whether that is because of encoding. Let's see if I face again the same in near future. 

Again thank you very much for your time :)
