### ISSUE TITLE
Issue with Office version

### ISSUE THREAD

**Issue by Pauline6010** [davidgohel/officer#155]
Hi @davidgohel , I am facing an issue about officer and Office version on my computer. Indeed, when I try this code : 
```
library("officer")
library("dplyr")
doc <- read_docx() %>%
  body_add_par("Table 1") %>%
  body_add_par("", style = "Normal") %>%
  body_add_table(mtcars)

print(doc, target = "essai.docx")
```
I cannot open the exported document if I have Microsoft Office 2007 installed (I have an error message about problem detected in the document). However, I manage to open it if I install Microsoft Office 2016 instead. Is there something to adjust in the code to export document openable with Office 2007 ?

Here is my sessionInfo : 
```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.6   officer_0.3.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18     crayon_1.3.4     digest_0.6.16    assertthat_0.2.0 R6_2.2.2         magrittr_1.5    
 [7] pillar_1.3.0     zip_1.0.0        rlang_0.2.2      uuid_0.1-2       rstudioapi_0.7   bindrcpp_0.2.2  
[13] xml2_1.2.0       tools_3.5.1      glue_1.3.0       purrr_0.2.5      compiler_3.5.1   pkgconfig_2.0.2 
[19] base64enc_0.1-3  htmltools_0.3.6  tidyselect_0.2.4 bindr_0.1.1      tibble_1.4.2  
```
Thanks in advance !

**Comment by davidgohel** [comment]
Sorry you have that issue, I never heard about that before today. To answer your question, no, there is no option to *adjust* document to 2007. 

Can you open the file without the table?

```
library("officer")
library("dplyr")
doc <- read_docx() %>%
  body_add_par("Table 1") %>%
  body_add_par("", style = "Normal")
print(doc, target = "essai.docx")
```

**Comment by davidgohel** [comment]
OK, at least I know where is the issue ;) 

I will work on that later, sorry for the delay it will take!

**Comment by vectorson** [comment]
@davidgohel I think a `<w:tblGrid/>` needs to be added after to the table to comply with `wml.xsd` which might solve this issue. I'll create a PR with the change but since it's in C++ I have no way to test it.

**Comment by davidgohel** [comment]
Thanks, I will work on that later

**Comment by davidgohel** [comment]
@Pauline6010 can you test @vectorson PR please? I don't have MS Word 2007...

**Comment by vectorson** [comment]
I managed to rebuild the package (was easier than I thought thanks to RStudio 😄) and generate a new file. @Pauline6010 can you try opening [this new file](https://github.com/davidgohel/officer/files/2507844/essai.docx) with Word 2007 and see if the issue is resolved?

**Comment by Pauline6010** [comment]
Hi @vectorson , thank you for your help !
Unfortunately, I can't open the new document you sent.

**Comment by vectorson** [comment]
@Pauline6010 OK that's too bad! Are you able to get any more details from the error message? E.g. like the screenshot in this issue:
https://github.com/davidgohel/officer/issues/149

**Comment by Pauline6010** [comment]
Of course !
Here it is : 
![erreur_word](https://user-images.githubusercontent.com/18577723/47418293-1f8b3980-d77a-11e8-8029-f00f290629f7.png)

Sorry it's in French :)

**Comment by vectorson** [comment]
@Pauline6010 merci, but please click the `Details >>>` button also. 😄

**Comment by Pauline6010** [comment]
Oops, sorry about that.
![erreur_word2](https://user-images.githubusercontent.com/18577723/47419909-7cd4ba00-d77d-11e8-9d39-843c2a03397c.png)

**Comment by vectorson** [comment]
OK @Pauline6010 that helped alot! Here is a new file for you to test: [essai.docx](https://github.com/davidgohel/officer/files/2509894/essai.docx)

**Comment by Pauline6010** [comment]
It's great, I can open it !

**Comment by Pauline6010** [comment]
Thank you very much !
I am not really used to install packages directly from GitHub, but I tried to install the version with @vectorson fix by doing `devtools::install_github("davidgohel/officer")`
It is now version 0.3.3.001 on my computer. Unfortunately, I am still getting the error message. What am I doing wrong ?

**Comment by vectorson** [comment]
@Pauline6010 have you made sure to restart your R session and reload the package? If yes, are the details of the error message identical? Can you also attach an `essai.docx` created by your system with the new version of officer?

**Comment by Pauline6010** [comment]
@vectorson yes I have restarted my R session and reloaded the package. The details of the error message are identical. Here is my [essai.docx](https://github.com/davidgohel/officer/files/2513755/essai.docx) !

**Comment by vectorson** [comment]
@Pauline6010 thank you. I can see from your file that your officer still uses the old code for some reason. In other words it hasn't recompiled the adjusted .cpp-file. Try a clean reinstall and see if it helps:
`remove.packages("officer")
devtools::install_github("davidgohel/officer")`

**Comment by vectorson** [comment]
Nice to hear that the fix worked. Happy reporting!
