### ISSUE TITLE
Serialization & Deserialization of rdocx object

### ISSUE THREAD

**Issue by JacquesBisschoff** [davidgohel/officer#156]
Hi @davidgohel, I was wondering if you could add some features to serialize a rdocx object in R.  The reason for this request is to store the serialized rdocx object in a database, then _deserialize_ it when the rdocx needs editing. Please advice if this is possible.

**Example**
library(officer)

doc <- officer::read_docx()
s_doc <- base::serialize(doc,NULL)
doc2 <- base::unserialize(s_doc)

Error in doc_namespaces(doc) : external pointer is not valid

**Comment by davidgohel** [comment]
Hi,

I agree this would be a good things...

That's in the middle/long term plans. The issue here is the mapping between R and a temporary directory (stored in `tempdir()`).

**Comment by JacquesBisschoff** [comment]
That would be great, and thank you for the good work and cool features already implemented.

**Comment by davidgohel** [comment]
Hi 

Sorry, I am closing that issue as it implies too much refactoring for now. I may reopen later (hopefully)
