### ISSUE TITLE
Please add pdf print option to the package

### ISSUE THREAD

**Issue by eplaymaker** [davidgohel/officer#159]
First of all, thanks a lot for your amazing package. Do you have any plans to add “pdf print” option for power point presentations? It would amazing to export pdf reports rather than ppt’s.

**Comment by Ljupch0** [comment]
The same function is found in the docxtractr package as well. `docxtractr::convert_to_pdf`

**Comment by davidgohel** [comment]
And in https://cran.r-project.org/package=doconv for more options with word exe
