### ISSUE TITLE
Add option to manipulate / remove background color

### ISSUE THREAD

**Issue by BirgerNi** [davidgohel/officer#162]
Hej @davidgohel, I was wondering if you could add an option to manipulate / remove background color. You can find a detailled description of the problem and a hacky solution on [stackoverflow](https://stackoverflow.com/questions/53052341/replace-text-and-background-color-of-a-word-document). Please let me know if you need more information.

**Comment by davidgohel** [comment]
Hi, sorry for the delay. I will add ability to modify paragraph and character styles in the next dev run.

**Comment by davidgohel** [comment]
This issue is opened since too much time. Sorry. I will re open when I will find time for it

KR
David

**Comment by danwwilson** [comment]
Any chance that this could be revisited, or that there is a branch that has some of the progress made on this?

**Comment by davidgohel** [comment]
@danwwilson 

You can compose a paragraph with text formatted. see https://ardata-fr.github.io/officeverse/paragraphs-chunks.html

You can't change a style name by another style name with `officer::change_styles()`
