### ISSUE TITLE
Why my document doens't have the style 'centered'?

### ISSUE THREAD

**Issue by Andryas** [davidgohel/officer#163]
my_doc <- read_docx("losango_cdc/doc.docx")
styles_info(my_doc)

|style_type |style_id                 |style_name                   |is_custom |is_default |
|:----------|:------------------------|:----------------------------|:---------|:----------|
|paragraph  |Normal                   |Normal                       |FALSE     |TRUE       |
|paragraph  |Ttulo1                   |heading 1                    |FALSE     |FALSE      |
|paragraph  |Ttulo2                   |heading 2                    |FALSE     |FALSE      |
|paragraph  |Ttulo3                   |heading 3                    |FALSE     |FALSE      |
|paragraph  |Ttulo4                   |heading 4                    |FALSE     |FALSE      |
|paragraph  |Ttulo5                   |heading 5                    |FALSE     |FALSE      |
|paragraph  |Ttulo6                   |heading 6                    |FALSE     |FALSE      |
|paragraph  |Ttulo7                   |heading 7                    |FALSE     |FALSE      |
|paragraph  |Ttulo8                   |heading 8                    |FALSE     |FALSE      |
|paragraph  |Ttulo9                   |heading 9                    |FALSE     |FALSE      |
|character  |Fontepargpadro           |Default Paragraph Font       |FALSE     |TRUE       |
|table      |Tabelanormal             |Normal Table                 |FALSE     |TRUE       |
|numbering  |Semlista                 |No List                      |FALSE     |TRUE       |
|paragraph  |Cabealho                 |header                       |FALSE     |FALSE      |
|paragraph  |Rodap                    |footer                       |FALSE     |FALSE      |
|paragraph  |Sumrio4                  |toc 4                        |FALSE     |FALSE      |
|paragraph  |Sumrio1                  |toc 1                        |FALSE     |FALSE      |
|paragraph  |Sumrio2                  |toc 2                        |FALSE     |FALSE      |
|paragraph  |Sumrio3                  |toc 3                        |FALSE     |FALSE      |
|paragraph  |Sumrio5                  |toc 5                        |FALSE     |FALSE      |
|paragraph  |Sumrio6                  |toc 6                        |FALSE     |FALSE      |
|paragraph  |Sumrio7                  |toc 7                        |FALSE     |FALSE      |
|paragraph  |Sumrio8                  |toc 8                        |FALSE     |FALSE      |
|paragraph  |Sumrio9                  |toc 9                        |FALSE     |FALSE      |
|character  |Hyperlink                |Hyperlink                    |FALSE     |FALSE      |
|paragraph  |OGPRC                    |OGPRC                        |TRUE      |FALSE      |
|paragraph  |Textodebalo              |Balloon Text                 |FALSE     |FALSE      |
|character  |TextodebaloChar          |Texto de balão Char          |TRUE      |FALSE      |
|character  |Ttulo3Char               |Título 3 Char                |TRUE      |FALSE      |
|character  |longtext                 |long_text                    |TRUE      |FALSE      |
|character  |hps                      |hps                          |TRUE      |FALSE      |
|character  |HiperlinkVisitado        |FollowedHyperlink            |FALSE     |FALSE      |
|paragraph  |DecimalAligned           |Decimal Aligned              |TRUE      |FALSE      |
|paragraph  |Textodenotaderodap       |footnote text                |FALSE     |FALSE      |
|character  |TextodenotaderodapChar   |Texto de nota de rodapé Char |TRUE      |FALSE      |
|character  |nfaseSutil               |Subtle Emphasis              |FALSE     |FALSE      |
|table      |SombreamentoClaro-nfase1 |Light Shading Accent 1       |FALSE     |FALSE      |
|table      |Tabelacomgrade           |Table Grid                   |FALSE     |FALSE      |
|paragraph  |TableText                |Table Text                   |TRUE      |FALSE      |
|paragraph  |SubTitle                 |Sub Title                    |TRUE      |FALSE      |
|paragraph  |PargrafodaLista          |List Paragraph               |FALSE     |FALSE      |
|paragraph  |NormalWeb                |Normal (Web)                 |FALSE     |FALSE      |
|paragraph  |Subttulo                 |Subtitle                     |FALSE     |FALSE      |
|character  |SubttuloChar             |Subtítulo Char               |TRUE      |FALSE      |
|character  |Refdecomentrio           |annotation reference         |FALSE     |FALSE      |
|paragraph  |Textodecomentrio         |annotation text              |FALSE     |FALSE      |
|character  |TextodecomentrioChar     |Texto de comentário Char     |TRUE      |FALSE      |
|paragraph  |Assuntodocomentrio       |annotation subject           |FALSE     |FALSE      |
|character  |AssuntodocomentrioChar   |Assunto do comentário Char   |TRUE      |FALSE      |
|paragraph  |Reviso                   |Revision                     |FALSE     |FALSE      |
|character  |RodapChar                |Rodapé Char                  |TRUE      |FALSE      |
|table      |ListaColorida-nfase2     |Colorful List Accent 2       |FALSE     |FALSE      |
|table      |ListaColorida            |Colorful List                |FALSE     |FALSE      |
|paragraph  |Corpodetexto             |Body Text                    |FALSE     |FALSE      |
|character  |CorpodetextoChar         |Corpo de texto Char          |TRUE      |FALSE      |
|paragraph  |tahoma                   |tahoma                       |TRUE      |FALSE      |
|character  |TextodoEspaoReservado    |Placeholder Text             |FALSE     |FALSE      |
|paragraph  |Default                  |Default                      |TRUE      |FALSE      |

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252    LC_MONETARY=Portuguese_Brazil.1252 LC_NUMERIC=C                       LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] officer_0.3.2   bindrcpp_0.2.2  forcats_0.3.0   stringr_1.3.1   dplyr_0.7.6     purrr_0.2.5     readr_1.1.1     tidyr_0.8.1     tibble_1.4.2    ggplot2_3.0.0   tidyverse_1.2.1
[12] lubridate_1.7.4 WordR_0.3.1    

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.4   haven_1.1.2        lattice_0.20-35    colorspace_1.3-2   htmltools_0.3.6    yaml_2.2.0         base64enc_0.1-3    rlang_0.2.2        pillar_1.3.0      
[10] glue_1.3.0         withr_2.1.2        RColorBrewer_1.1-2 modelr_0.1.2       readxl_1.1.0       uuid_0.1-2         bindr_0.1.1        plyr_1.8.4         munsell_0.5.0     
[19] gtable_0.2.0       cellranger_1.1.0   rvest_0.3.2        zip_1.0.0          evaluate_0.11      labeling_0.3       knitr_1.20         broom_0.5.0        Rcpp_0.12.18      
[28] scales_1.0.0       backports_1.1.2    jsonlite_1.5       hms_0.4.2          digest_0.6.18      stringi_1.1.7      grid_3.5.1         rprojroot_1.3-2    cli_1.0.1         
[37] tools_3.5.1        magrittr_1.5       lazyeval_0.2.1     crayon_1.3.4       pkgconfig_2.0.2    xml2_1.2.0         assertthat_0.2.0   rmarkdown_1.10     httr_1.3.1        
[46] rstudioapi_0.7     R6_2.2.2           nlme_3.1-137       compiler_3.5.1

**Comment by davidgohel** [comment]
because your template does not have the style 'centered'.
