### ISSUE TITLE
double line header

### ISSUE THREAD

**Issue by elong0527** [davidgohel/officer#165]
Hi David: 

I am trying to create double line border using `fp_border` to define the begin and end of a table. However it currently only allow "none" or "solid" or "dotted" or "dashed". 

I am willing to work on this feature if you could provide some hint. 

Best,

Yilong

**Comment by davidgohel** [comment]
Hi really sorry for the delay.

A PR would be welcome. I know a doc to help people to contribute is necessary - this will be done (see #175)
