### ISSUE TITLE
Ampersand problems with officer's slip_in_text function but not with body_add_par

### ISSUE THREAD

**Issue by martinjroberts** [davidgohel/officer#166]
Hi David,
I am trying to move across from ReporteRs to officer but have immediately encountered a problem that I don't understand. In the folowing 3 lines of code why does the second line work but the third throws an error? And is there a solution?
`myDoc<-read_docx()`
`myDoc<-myDoc %>% body_add_par("A&B")`
`myDoc<-myDoc %>% slip_in_text("A&B")`

The error message reads:
_Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  EntityRef: expecting ';' [23]_

I am using:
_R version 3.5.0
officer_0.3.2_

Regards,
Martin

**Comment by davidgohel** [comment]
I will solve that in the next run :)

**Comment by martinjroberts** [comment]
Hi David,
That's good news - thank you.
Thanks also for your work on this and the preceding ReporteRs package which has been a godsend to us.
Kind regards,
Martin

**Comment by szego** [comment]
Has this issue been fixed?
