### ISSUE TITLE
Corrupted file if special character is inserted in bookmark

### ISSUE THREAD

**Issue by DanChaltiel** [davidgohel/officer#167]
Hi David,

Whenever I try to use `body_replace_text_at_bkm` with some special characters like accent letters or €, the doc file ends up not readable.

Here is a simple reprex:

```
read_docx() %>%
  body_add_par(value = "Change this") %>% 
  body_bookmark("Document_Title") %>%
  body_replace_text_at_bkm("Document_Title", "eeee é") %>%
  print(target = "xxx.docx")
```

This wont print any error in the R console, but Word won't be able to open "xxx.docx", saying "problems have been detected in the content". It works just fine if you remove the "é". 

I think the problem comes from UTF-8 because this doesn't happen with standards metacharacters (I tried with /, #, $ and ç). I tried to save my file with UTF-8 but it didn't fix the thing though.

Indeed, this may be linked to [enc2utf8](https://github.com/davidgohel/officer/search?q=enc2utf8&unscoped_q=enc2utf8), which you use in [`cursor_replace_first_text `and `replace_all_text`](https://github.com/davidgohel/officer/blob/7d8a4991aba69aefcbf5588b5e973c915670af05/R/docx_part.R) but not in [`body_add_xml`](https://github.com/davidgohel/officer/blob/fc7b6393fc601f627c85b24194e98767745bab8e/R/docx_add.R).

Thanks for this great library !

**Comment by davidgohel** [comment]
Hi, sorry for the delay! 

I think this is solved but only with the github version for now. Could you try the github version please?

David

**Comment by davidgohel** [comment]
This has been tested by someone with a windows computer and it is fixed now.

David

[xxx.docx](https://github.com/davidgohel/officer/files/2859654/xxx.docx)
