### ISSUE TITLE
body_bookmark(x, id) > add value as 3rd parameter (enhancement)

### ISSUE THREAD

**Issue by BIviz** [davidgohel/officer#17]
it would be convenient if with this function the bookmark content could differ from the bookmark name

    body_bookmark(x, id, value)
    doc <- read_docx() %>% 
      body_add_par("centered text", style = "centered") %>%
      body_bookmark(id = "ref1", value = "text_to_replace")

In word bookmarks can define not only a position in the document but also  #a (text) range as well.

Great job BTW!

**Comment by davidgohel** [comment]
Sorry, `body_bookmark` need to stay simple. If I do so, then I will have to implement a replacements method for ranges and ranges lookup is costing too much... 

Depending on the use case you want to cover, but `body_add_fpar` may help, it lets you add paragraphs made of several chunk of formatted text (or images).
