### ISSUE TITLE
Font apply on chinese doesn't work

### ISSUE THREAD

**Issue by yvhkgdsk0** [davidgohel/officer#171]
Hi David,
I am trying to set font on Chinese, but failed. I mannully checked on MS word, the English part worked, but Chinese part failed. Need tricks to make it work on Chinese?
library(officer)
library(magrittr)
library(flextable)

data <- data.frame(A=c("中国","China","中国","China","中国","China"),B=c("祖国","Country","祖国","Country","祖国","Country"))
ft <- flextable(data)
ft <- font(ft, fontname = "Arial Black", part = "all")
ft <- autofit(ft)
doc <- read_docx() %>% body_add_flextable(ft)
print(doc,target="trouble.docx")

I am using:
R version 3.5.0
officer_0.3.2

Regards,
Qi

**Comment by clementinejager** [comment]
Hi,

What did you mean by "Chinese part failed"?

I tested your program, it worked with html and pptx formats, the font is changed as expected.
For MS Word, I see the character but the font isn't the expected font (but "MS Mincho"). When I tried to change in Word the Chinese character manually, it doesn't work. 
I also tried with another font ("Yu Gothic") which seems to accept Chinese character but the font is still "MS Mincho". 
I think that Word changes the font with "MS Mincho" for this sort of character.

```
library(officer)
library(magrittr)
library(flextable)
data <- data.frame(A=c("中国","China","中国","China","中国","China"),B=c("祖国","Country","祖国","Country","祖国","Country"))
ft <- flextable(data)
ft <- font(ft, i = c(2,4,6), fontname = "Arial Black", part = "body")
ft <- font(ft, i = c(1,3,5), fontname = "Arial Black", part = "body")
ft <- bold(ft, bold = TRUE, part = "body")
ft <- autofit(ft)
doc <- read_docx() %>% body_add_flextable(ft)
print(doc,target="trouble.docx")
print(ft, preview = "pptx")
ft
```
Word:
![image](https://user-images.githubusercontent.com/44028020/50594840-701bc300-0e9e-11e9-9173-8101a7b76140.png)

PowerPoint:
![image](https://user-images.githubusercontent.com/44028020/50594866-92154580-0e9e-11e9-9ecf-ebe4e9de2519.png)

html:
![image](https://user-images.githubusercontent.com/44028020/50595162-8a09d580-0e9f-11e9-8979-301552786334.png)

Next time, remember to add the session info. 

Clémentine

**Comment by yvhkgdsk0** [comment]
Hi Clémentine,

Thanks for quick response!

Sorry for my poor English. Your description is exact what I was trying to say. No matter what font I was trying to set, the Chinese character always end up with "MS Mincho" in MS Word.

Word
![ms mincho](https://user-images.githubusercontent.com/13662922/50601157-51451d00-0eee-11e9-97c5-5add4c47c983.png)

As you said. The PowerPoint works fine with Chinese character and Word come from the same Office suite. Word should works fine too. Any idea why it won't work and Any solutions?

Regards,
Qi

**Comment by clementinejager** [comment]
Hi,

We don't have any solution yet as we don't have a clear diagnostic, sorry. 
We are still investigating.

Clémentine

**Comment by clementinejager** [comment]
Hi, 

The issue should be fixed.

![image](https://user-images.githubusercontent.com/44028020/50632714-1d4b1580-0f49-11e9-8526-95b970639655.png)


Clémentine

**Comment by yvhkgdsk0** [comment]
Hi Clémentine,

I tried the newest version on github. It works. Bravo!

Thanks very much!

Best Regards
Qi

**Comment by clementinejager** [comment]
Thanks for your feedback!
