### ISSUE TITLE
How to disable CAPS on feature in a 'Title' Placeholder while creating power point using officer package ?

### ISSUE THREAD

**Issue by ashishnelson94** [davidgohel/officer#177]
I am trying to build a ppt deck using an existing template given to us by the client. 
Placeholder type: Title
Is there an option or a way in R to disable the ALL CAPS in Font while we define a placeholder in a slide?
![image](https://user-images.githubusercontent.com/10890679/52413258-16df2900-2b07-11e9-9e24-d24c663e057e.png)

**Comment by davidgohel** [comment]
Hi, no sorry, there is no option for that.

**Comment by ashishnelson94** [comment]
Hi David,
Thanks a lot for your swift response. :)

Is this happening because I'm using an existing template as a reference in read_pptx("xyz.pptx")?
I am using ph_empty_at to define a new title placeholder but using an existing template, but when I use a default ppt template by using read_pptx(), then I don't see content in ALL Caps.

Thanks again :)

**Comment by davidgohel** [comment]
Could you provide a reproducible example? a short code and the template your are using...

**Comment by ashishnelson94** [comment]
Hi David,
Please find below the code for the R Code that I have created so far.
Your valuable inputs is highly appreciated :)
[Click_Outcome_Template_Reference.pptx](https://github.com/davidgohel/officer/files/2841031/Click_Outcome_Template_Reference.pptx)

my_pres <- read_pptx("Trial1.pptx") %>% 
  add_slide(layout = "Title Cover", master = "rajaampat") %>% 
  #ph_with_text(type = "title", str ="") %>%
  #ph_remove(type="title",id_chr=2) %>%
  ph_empty_at(left = 0.6 , top = 3,width = 9,height = 2,bg="transparent",rot = 0,template_type = "title")%>%
  ph_add_par()%>%
  ph_add_text(type = "title",id_chr = 2, str ="") %>%
  ph_with_text (type="body",index = 2,str = sprintf("Report Period:%s to %s ",min(df_api_final$day),max(df_api_final$day)))


#ph_with_text(type = "title", str = sprintf(" Xaxis Click Performance For %s , %s ",advertiser_name,campaign_name))


text_prop <- fp_text(color = "#29ADE3", font.size = 32 , font.family = "Arial Black (Headings)")
text_prop1 <- update(text_prop, color = "white" )
my_pres <- my_pres %>% 
  ph_add_text( type ="title" ,id_chr=2,str = "Xaxis Click Performance For", style = text_prop1 )%>%
  ph_add_text( type ="title" ,id_chr=2,pos = "after",str = sprintf(" %s , %s ",advertiser_name,campaign_name), style = text_prop )
slide_summary(my_pres)




#print(my_pres, target = "Trial1Output.pptx")





#slide_summary(my_pres)

text_prop2 <- update(text_prop, font.size = 20,color = "#525b6e" ) 



#Slide 2

#Step 1
my_pres1 <- my_pres %>% add_slide(layout = "Subtitle/Image Split", master = "rajaampat") 




my_pres1 <- my_pres1 %>% on_slide(index=2) %>%
            ph_empty_at(left = 0.5 , top = 0.4,width = 5.7,height = 0.71,bg="transparent",rot = 0,template_type = "title")%>%
            ph_add_par(type = "title") %>%
            ph_add_text(type = "title", str = "Campaign Overview", style = text_prop2 )


my_pres1 <- my_pres1 %>% on_slide(index=2) %>%
           ph_empty_at(left = 0.5 , top = 2.03,width = 5.7,height = 4.4,bg="transparent",rot = 0)%>%
          ph_add_par(type = "body") %>%
            ph_add_text(type = "body",str = tolower("Campaign Overview"), style = text_prop2 )

my_pres1 <- my_pres1 %>% on_slide(index=2) %>%
  ph_with_img_at( src = "split.jpg", left = 6.7 ,top =0 , rot=0, height = 7.5, width = 6.60 )

layout_properties ( x = my_pres1, layout = "Subtitle/Image Split", master = "rajaampat" )

slide_summary(my_pres1)

print(my_pres1, target = "Trial1Output.pptx")

**Comment by davidgohel** [comment]
Can I summarize your issue with that bit of code:

```
my_pres <- read_pptx("Click_Outcome_Template_Reference.pptx") %>%
  add_slide(layout = "Title Cover", master = "rajaampat") %>%
  ph_empty_at(left = 0.6 , top = 3,width = 9,height = 2, 
              bg="transparent",rot = 0,template_type = "title")

print(my_pres, target = "Trial1Output.pptx")
```

And there you got a big white area that you want to be transparent. Is that your issue?

**Comment by ashishnelson94** [comment]
Hi David , 

So the problem that  I am facing right now is that whenever I try to put any text via ph_add_text

E.g.
ph_add_text(type = "title", str = "Campaign Overview", style = text_prop2 )

The text though its entered in lower case , it appears all Upper case in PPT, which is why I inquired initially if there's a possibility to un-check ALL CAPS option via R Script

**Comment by davidgohel** [comment]
OK, I could not really reproduce your code but has been able to play with it:

```
library(magrittr)
library(officer)

text_prop <- fp_text(color = "#29ADE3", font.size = 32, font.family = "Arial")
text_prop1 <- update(text_prop, color = "white")

my_pres <- read_pptx("~/Downloads/Click_Outcome_Template_Reference.pptx") %>%
  add_slide(layout = "Title Cover", master = "rajaampat") %>%
  ph_empty_at(left = 0.6, top = 3, width = 9, height = 2, bg = "transparent", rot = 0) %>%
  ph_add_par() 

id_chr <- slide_summary(my_pres)$id

my_pres <- ph_add_text(my_pres, type = "body", id_chr = id_chr, str = "") %>%
  ph_add_text(type = "body", id_chr = id_chr, str = "Xaxis Click Performance For", style = text_prop1) %>%
  ph_add_text(type = "body", id_chr = id_chr, pos = "after", str = sprintf(" %s , %s ", "advertiser_name", "campaign_name"), style = text_prop) %>% 
  ph_with_text(type = "body", index = 2, str = "Report Period" )

print(my_pres, target = "Trial1Output.pptx")
```

The CAP property is defined as a general defaut property and officer was not specifying anything about CAP so the default property was always applied. 

I made a minor update and now the text is always defined as *no cap*. 

The new version of officer contain new functions that will make that kind of operations easier - the following code is doing the same thing but with the new functions: 

```
library(magrittr)
library(officer)

text_prop <- fp_text(color = "#29ADE3", font.size = 32, font.family = "Arial")
text_prop1 <- update(text_prop, color = "white")

pars <- block_list(
  fpar(ftext("Xaxis Click Performance For", text_prop)),
  fpar(ftext(sprintf("%s , %s ", "advertiser_name", "campaign_name"), text_prop1))
)
my_pres <- read_pptx("~/Downloads/Click_Outcome_Template_Reference.pptx") %>%
  add_slide(layout = "Title Cover", master = "rajaampat") %>%
  ph_with(pars, location = ph_location_type(type = "title") ) %>%
  ph_with_text(type = "body", index = 2, str = "Report Period" )

print(my_pres, target = "Trial1Output.pptx")
```

<img width="567" alt="capture d ecran 2019-02-10 a 22 28 32" src="https://user-images.githubusercontent.com/4331618/52539870-4ac68280-2d83-11e9-8d6f-bf4c2ffaa377.png">

**Comment by davidgohel** [comment]
Note you will need to update your package from github as this modification is not on CRAN yet
