### ISSUE TITLE
Add a text box

### ISSUE THREAD

**Issue by ABSOD** [davidgohel/officer#179]
I want to add a text box to a word document.  I have a series of panels I want to include in my document, see the attached docx.  file.  The plots are  ggplot images saved to disk a inserted using the body_add_img command.

In word, these text boxes can contain text and information, which we will add in post processing.

Any ideas how to do this using officer?
Thanks.  AB
[Glenwood Springs Community Summary.docx](https://github.com/davidgohel/officer/files/2843054/Glenwood.Springs.Community.Summary.docx)

 
--
  |

**Comment by davidgohel** [comment]
Hi

Yes, you could use flextable to put your elements in a table and add that table to the document 

A flextable can easily be used to layout plots and text, see here for an example:

https://stackoverflow.com/a/54551454/3315962

**Comment by ABSOD** [comment]
Thanks for the code suggestion, David.  I was able to create the layout I want.  However, the resolution of the chart is pretty bad.  Is there any way to improve this?
Cheers
AB

My code:
# Creating the Image.  pop1$plot is ggplot object, "tempPlot" is a pathname
pop1 <- pop_timeseries(DBPool=DOLAPool,lvl=level,listID=idList,endyear=curYr,base=12)
ggsave(paste0(tempPlot,"P1.png"),pop1$plot, device="png", height = 5 , width = 7, dpi=600)

# Flextable/officer code
plt1 <- data.frame("plot" = "", "text"= "")
plt1tab <- flextable(plt1) %>% 
  compose(i = 1, j = 1, value = as_paragraph(as_image(paste0(tempPlot,"P1.png"), height=3, width=5))) %>% 
  set_header_labels(plot = "Population Estimates, 2017", text="") %>%
  merge_at(i=1,j = 1:2,part="header") %>%
  autofit() %>%
  width(j = 1, width = 5) %>%
  width(j = 2, width = 3) %>%
  align(i=1,j = 1, align="left",part="header")

inDoc <- read_docx()
inDoc <- inDoc %>% body_add_flextable(plt1tab)
print(inDoc,target = outDoc )

Output:

[Test.pdf](https://github.com/davidgohel/officer/files/2845905/Test.pdf)

**Comment by ABSOD** [comment]
btw, here is the original plot
HTH
![p1](https://user-images.githubusercontent.com/32849428/52491380-38cac100-2b84-11e9-961e-8f468985bf4c.png)

**Comment by davidgohel** [comment]
Thanks for that. It seems the wrapper around `as_image` is rendering at 72 ppi. I will fix that soon.

Another solution is to use a template with bookmarks and to write the content in that bookmarks: https://davidgohel.github.io/officer/articles/word.html#replace-content

**Comment by ABSOD** [comment]
Thanks.  I'll give this a shot.  AB

**Comment by davidgohel** [comment]
I just fixed the resolution issue. You will need to update your package from github.
```
library(ggplot2)
library(magrittr)

pop1 <- ggplot(iris, aes(Sepal.Length, Sepal.Width)) + geom_point()
ggsave(paste0("P1.png"),pop1, device="png", height = 5 , width = 7, dpi=600)

plt1 <- data.frame("plot" = "", "text"= "")
plt1tab <- flextable(plt1) %>%
  compose(i = 1, j = 1, value = as_paragraph(as_image("P1.png", height=5, width=7))) %>%
  set_header_labels(plot = "Population Estimates, 2017", text="") %>%
  merge_at(i=1,j = 1:2,part="header") %>%
  autofit() %>%
  width(j = 1, width = 5) %>%
  width(j = 2, width = 3) %>%
  align(i=1,j = 1, align="left",part="header")

print(plt1tab, preview = "docx")
```


<img width="785" alt="capture d ecran 2019-02-10 a 11 55 34" src="https://user-images.githubusercontent.com/4331618/52532816-d6f88b80-2d2a-11e9-87bc-825101707a69.png">

**Comment by ABSOD** [comment]
Awesome.
Thanks!
AB
