### ISSUE TITLE
pos = "on" and slip_in functions

### ISSUE THREAD

**Issue by tammoterhark** [davidgohel/officer#18]
Referring to your documentation at: https://davidgohel.github.io/officer/articles/word.html#cursor-manipulation

I received an error message when using: 
```
cursor_reach(keyword = "Hierdatum")%>%
slip_in_text(datum, pos = "on", style = "Default Paragraph Font")%>%

```
```
Error in slip_in_xml(x = x, str = xml_elt, pos = pos) : 
  unknown pos 'on', it should be 'after' or 'before'
```

**Comment by tammoterhark** [comment]
also with:
```
cursor_reach(keyword = "Hierdatum")%>%
  slip_in_text(datum, style = "Default Paragraph Font", pos = "on")%>%
```

**Comment by tammoterhark** [comment]
Use case: multilingual project with single template. Want to reach certain "magic words" and slip in some text over these magic words.

**Comment by tammoterhark** [comment]
Using github version of officer.

**Comment by davidgohel** [comment]
*Text and images can be inserted at the beginning or the end of the selected paragraph (selection made by the cursor).*

`?slip_in_text`

**Comment by tammoterhark** [comment]
OK, so I cannot replace text in the document, except by body_remove?

**Comment by tammoterhark** [comment]
What is the use case for:
on will replace the selected element in the document by a new element.

**Comment by davidgohel** [comment]
1. No, you can't. You can use `fpar` for composite and complex strings.

2. insert content at a specific location

**Comment by tammoterhark** [comment]
Sorry to keep asking: but where is "on" used?

**Comment by davidgohel** [comment]
Have a look at documentations pages for `?officer::body_add_par` and all other `officer::body_add_*` functions

**Comment by tammoterhark** [comment]
OK, thanks. This helps. Still a bit confused about the difference between body_add_* and slip_in_

Will experiment.

**Comment by davidgohel** [comment]
https://davidgohel.github.io/officer/articles/word.html#adding-elements

I made modifications to word vignette, hope it's better.
