### ISSUE TITLE
Low performance when creating docx file with significant number of add_xxx

### ISSUE THREAD

**Issue by AntoineBrisacier** [davidgohel/officer#184]
Hello,

We are using "officer" R package to produce some of reporting outputs in docx with of significant number of pages (it could be over 1000 pages). Unfortunately, the gain of using R for our analysis to speed up time processing is lost when generating final docx file with officer.
We tried to figure out if there were some possibility to do some parallelisation, but without any success so far.

The following code with 1,000 iteration shows how running time increases when reading docx file with increasing number of pages. I guess that it is an issue with reading xml file each time before adding image, table ... or any component.

Here is the overall running time after iteration:

- 1st iteration 0.559 sec
- 10th 1.594 sec
- 100th 39.433 sec
- 300th 793.304 sec
- 600th 5866.651 sec
- 1000th 26129.372 sec (roughly 7 hours running time for the whole program)

So you may understand that it is very unconvenient. Apart from that we are happy of using officer package. If you have any suggestion to deal with this issue or enhance the package ? Thanks

Antoine

```
# R version            : 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
# Platform             : x86_64-pc-linux-gnu (64-bit)
# Running under        : x86_64, linux-gnu
# CRAN repository      : 2019-01-21
# officer version 0.3.2
```
```
require(officer)
require(flextable)
require(png)
require(magrittr)

mydoc <- read_docx()
nOUT <- 1000

# matrice of time processing 
xt <- matrix(nrow=nOUT,ncol=1)

for(i in 1:nOUT) {
  
  xt[i,1] <- system.time({ 
    
    if (i>1){
      mydoc <- mydoc%>%
        body_add_break(pos="after") %>%
        body_end_section_portrait()
    }
    
    # png file location
    file_img <- "officer.png"
    dims <- attr(png::readPNG(file_img), "dim")
    
    # csv file location
    file_tab <- "officer.csv"
    file_csv <- read.csv(file_tab, check.names = F)[, -1]
    ft <- flextable(file_csv)
    
    ### Test with add_img
    body_add_img(mydoc, src = file_img, width = 2, height = (dims[1]*2/dims[2]), pos = "after", style = "centered")

    ### test with add_flextable
    body_add_par(mydoc, value="", pos = "after", style = "Normal")
    body_add_flextable(mydoc, value = ft, pos = "after")
    
    
    body_add_par(mydoc, value="", pos = "after", style = "Normal")
    
  })[3]
  
}

appOut <- "officer.docx"
xtOut <- "officer_runtime.csv"

print(mydoc, target = appOut)
write.table(xt, file=xtOut, row.names=FALSE, col.names=FALSE)
```

**Comment by davidgohel** [comment]
Thanks Antoine! This is highly appreciated.

I will work on officer soon to release a new version. I am going to try to find a solution for that and keep you informed.

David

**Comment by jd4ds** [comment]
Hi David,

thank you so much for your amazing work on the officer package. It has really helped us a lot with our standardised reports.

I would really like to back this enhancement because at moment it is really time intense for us to generate reports, which kind of defeats the purpose why we introduced officer in the first place. Also, i remember it being not as slow... If there is something I could do to help please let me now.

Thank you again!
Janis

**Comment by davidgohel** [comment]
Hi @jd4ds , sorry. This requires lot of time and I am not available for that now. I started refactor the whole code but I would need at least 3/4 full days of work on the subject (mainly get rid of xml2 or decrease its usage) and I don't have this time available.

**Comment by TJReece** [comment]
@AntoineBrisacier @jd4ds 

I have run into this same problem. The solution that has worked the best for me is to print the results of each iteration as individual docx files and then run a second loop using body_add_docx() to combine it all into one file. 
My run time went from 4+ hours to about 3 minutes.

Example:
for (i in seq_along(groups)) {
  lots of tables
  print(doc, target = paste0('path/temp/', groups[i], ".docx"))
}

for(i in seq_along(groups)){
  path <- paste0('path/temp/', groups[i], ".docx")
  doc1 <- body_add_docx(doc, path, pos = "after")
}

# print combine doc
print(doc1, target = paste0('path', "combined document", ".docx"))

# clear out all the temporary files
unlink("'path/temp/*")

**Comment by jd4ds** [comment]
@TJReece thank you for your suggestion. I work with templates that have a lot of bookmarks at various places. Therefore I think your approach of appending work documents to each other does not really work in this case, am I right?

**Comment by davidgohel** [comment]
If some of you want to add some code, please, format it (with backticks) as illustrated below:

`````

```
# this is a comment
mycall(blah blah blah)
```
`````

**Comment by davidgohel** [comment]
This issue is opened since too much time. Sorry. I will re open when I will find time for it

Meanwhile you can use `body_add_docx` as a workaround.

KR
David
