### ISSUE TITLE
how to do text highlighting using the package

### ISSUE THREAD

**Issue by Madeehab** [davidgohel/officer#185]
@davidgohel 
How to to do text highlighting for the text printed in a PPT using officers package.
I tried using shading.color option in fp_text object but it seems to be not working.

Below is an example of what I am trying to achieve - highlighting text with any color - eg. yellow as shown below
![image](https://user-images.githubusercontent.com/47552032/53225797-25991480-369f-11e9-9fed-7237fb4877d3.png)

**Comment by qfazille** [comment]
Hi Madeehab,

Could you provide the code you have done so far ?

**Comment by Madeehab** [comment]
@davidgohel 
please find below my code

my_pres <- read_pptx() %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>%
  ph_empty_at(left = 0.6 , top = 3,width = 9,height = 2,bg="transparent",rot = 0,template_type = "title")%>%
  ph_add_par()%>%
  ph_add_text( type ="title" ,id_chr=2,str = "Testing for text highlighting", 
               style = fp_text(color = "black", font.size = 32 , font.family = "Arial Black (Headings)",shading.color = "#29ADE3") )
  
print(my_pres,"test.pptx")

**Comment by qfazille** [comment]
looks suspicious indeed.

When we will have some time we'll get into that. Thanks for reporting !

**Comment by Madeehab** [comment]
@qfazille 
shading.color is not working in the example given in API document as well.
It would be really great if you could fix this feature asap.

**Comment by Madeehab** [comment]
@davidgohel 
Do i need to re-install the package to make it work?

**Comment by davidgohel** [comment]
@Madeehab yes

**Comment by Madeehab** [comment]
@davidgohel 
Unfortunately its not working.

please find below my code

my_pres <- read_pptx() %>%
add_slide(layout = "Title and Content", master = "Office Theme") %>%
ph_empty_at(left = 0.6 , top = 3,width = 9,height = 2,bg="transparent",rot = 0,template_type = "title")%>%
ph_add_par()%>%
ph_add_text( type ="title" ,id_chr=2,str = "Testing for text highlighting",
style = fp_text(color = "black", font.size = 32 , font.family = "Arial Black (Headings)",shading.color = "#29ADE3") )

**Comment by davidgohel** [comment]
<img width="984" alt="capture d ecran 2019-02-23 a 11 39 17" src="https://user-images.githubusercontent.com/4331618/53285354-b9cab080-375f-11e9-9bf8-2e8e3142721c.png">

PS: You don't need to `@` us, we are watching the project

**Comment by Madeehab** [comment]
Thank you!
