### ISSUE TITLE
Replace a Text in a shape of PowerPoint

### ISSUE THREAD

**Issue by nhnminh** [davidgohel/officer#186]
Hello David, 

I'm using your package and it is great ! However, I could only append the text to the object with ph_add_text, but not remove the current text to have a clear insertion. 

Could you please add the function of clearing the text before adding the new one to a specific shape? 

Thank you. 
MINH

**Comment by davidgohel** [comment]
Hi Ninh

You can remove an existing shape and create a new shape - also using template can help a lot. 
 
Can you describe more the use case?

**Comment by markheckmann** [comment]
I understand @nhnminh use case. I often have power points send to me which have some shapes placed in a specific way and I am asked to programmatically fill these shapes with some text etc.  I do not want to remove and replace the shape as this appears somewhat complicated to get the position, size and format correct. The best would be to simply rather replace its content / text. Would be great to reopen this issue :)

**Comment by davidgohel** [comment]
@markheckmann OK thanks for explaining. Why don't you want to use the layout? This is already supported by officer. You are totally free to design placeholder in layouts and reuse them later, and since latest versions you can get them with a label (which make things really easy).

David

**Comment by lucassouza89** [comment]
I'm having the same problem. It would be amazing if it had a ph_replace_text function to replace the text in a shape and not just add.

**Comment by davidgohel** [comment]
See #293 for a possible resolution.
