### ISSUE TITLE
Adding Comments to text

### ISSUE THREAD

**Issue by alapo** [davidgohel/officer#187]
I have become a big fan of this package. I wanted to post on a possible enhancement.  

One function that I think would add a ton of value is the ability to add comments when compiling your R-markdown document. 

Thanks for the great package.

**Comment by davidgohel** [comment]
thanks,

I am not sure I understood (officer is not managing R Markdown documents) - could you provide more details?

**Comment by davidgohel** [comment]
Hi, for now I am closing the issue - will re-open if necessary :)
