### ISSUE TITLE
zip problem in word

### ISSUE THREAD

**Issue by jfrancoiscollin** [davidgohel/officer#190]
Salut Dadou,

Avec la dernière version de officer j'ai ce message quand je charge le package:

library(officer)
Warning message:
replacing previous import ‘zip::unzip’ by ‘utils::unzip’ when loading ‘officer’

Ensuite tout marche mais maintenant dans Word (2007) il me met un message chelou avant d'ouvrir le doc:
'Microsoft office ne peut pas ouvrir ce fichier la version du fichier d'archive .zip n'est pas prise en charge"

Je sais pas si c'est lié mais ça à l'air.

 sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] officer_0.3.2

loaded via a namespace (and not attached):
 [1] compiler_3.5.2  R6_2.4.0        magrittr_1.5    htmltools_0.3.6
 [5] base64enc_0.1-3 Rcpp_1.0.0      uuid_0.1-2      xml2_1.2.0     
 [9] digest_0.6.18   zip_2.0.0

**Comment by jfrancoiscollin** [comment]
Ah en fait j'ai vu ta réponse, ça va bientôt être mis à jour, je vais prendre la version github.

bisou

**Comment by jfrancoiscollin** [comment]
Ah en fait j'ai vu ta réponse, ça va bientôt être mis à jour, je vais prendre la version github.

bisou

**Comment by davidgohel** [comment]
Salut Choupinou

Oui je sais
La version de zip 2.0 de rstudio a tout cassé mais c'est réparé et j'envoie la version corrigée aujourd'hui ou demain _ le temps de descendre de ma piste rouge...

**Comment by jfrancoiscollin** [comment]
t'inquiète c bon, ça marche avec la version github

enjoy le ski!

🙂
________________________________
De : David Gohel <notifications@github.com>
Envoyé : jeudi 28 février 2019 14:40
À : davidgohel/officer
Cc : jfrancoiscollin; State change
Objet : Re: [davidgohel/officer] zip problem in word (#190)


Salut Choupinou

Oui je sais
La version de zip 2.0 de rstudio a tout cassé mais c'est réparé et j'envoie la version corrigée aujourd'hui ou demain _ le temps de descendre de ma piste rouge...
