### ISSUE TITLE
Unable to put two mscharts in the same paragraph

### ISSUE THREAD

**Issue by enricoseven** [davidgohel/officer#192]
Hello David,
first of all thank you for this amazing package.
I am not able to put 2 mscharts in the same line. I think the issue is that body_add_chart is creating a new paragraph each time is called.
Then, I am not able to "delete" the linebreak in anyway (the body_replace function does not find neither "\n" nor "\r\n").

Is there any solution to this problem?
Let me know if the question is not clear or if you need a reproducible example. Thank you!
Thank you so much,
Enrico

**Comment by davidgohel** [comment]
Hello,

Yes, there is no *chunk* implementation, only in a paragraph. You could use a section with two columns as a layout (see https://davidgohel.github.io/officer/reference/sections.html).

About `\n` or `\r\n`, these are new lines in text files, not in Word. In Word, content is stored in XML and does not support  `\n` or `\r\n` (it has no effect)

**Comment by enricoseven** [comment]
Thank you so much,
now everything is more clear.
One last question (not super relavant with the title of the issue, so let me know if it is better to close this): is there anyway to make the external border of a mschart graph transparent? I can do it in excel but was not able to find a solution with your package.

Sorry for disturbing you and hope you have a great day.

**Comment by davidgohel** [comment]
sorry for the delay

I don't remember having implemented that option, sorry. I will keep that in mind for later(note the dev of mschart is very slow as I am more focus on officer/flextable for now)
