### ISSUE TITLE
officer corrupts .docx documents

### ISSUE THREAD

**Issue by RABxx** [davidgohel/officer#193]
I have a word (.docx) template, but no matter what I try and add to using officer it the output becomes corrupted with the error: 

"The file cannot be opened because there are problems with the contents" 

Under the 'details' table I get additional info that:

"Microsoft Office cannot open this file because the .zip archive file is an unsupported version".

I have attached the file (Template.docx) and below is the most minimal code that corrupts the output (SR.docx). I have also attached the error message.

    library(officer)
    library(magrittr)
    read_docx("Template.docx") %>%
       print("SR.docx") 

I have made sure I'm in the right directory, and I've removed all images from the template, but it seems to be corrupting the output no matter what I do.

![image](https://user-images.githubusercontent.com/48337093/53996755-c4d50600-418d-11e9-94fd-aa07ad00b651.png)

[Template.docx](https://github.com/davidgohel/officer/files/2943766/Template.docx)

**Comment by RABxx** [comment]
Not sure how to edit the post, but this started happening around the time the warning message "replacing previous import ‘zip::unzip’ by ‘utils::unzip’ when loading ‘officer’ " appeared when loading officer. Not sure if that's related

**Comment by davidgohel** [comment]
Hi

Probably #188

**Comment by davidgohel** [comment]
@RABxx Can I close this issue or is this still happening after you update officer package?
