### ISSUE TITLE
Add option to docx_summary to only extract text

### ISSUE THREAD

**Issue by ttime12** [davidgohel/officer#194]
Officer is a great package for transforming a docx document into a dataframe as it parses the document better than other packages -- e.g. it retains each paragraph as one string.

However, when the documents become long (e.g. 400 pages), docx_summary becomes slow and can take up to 15 minutes to parse the contents of a docx. I suspect this is due to the analysis that is required to summarise all aspects of the word document, e.g. paragraph style. 

In comparison, the textreadr package parses the same document within 5 seconds. However, as mentioned above, it does not parse the document as well as the officer pacakage.

Therefore, it would be useful to add an option to the docx_summary method to only parse the text of the document and leave out all other columns (content_type, style_name, is_header...).

`doc <- read_docx('test.docx')`
`docdf <- docx_summary(doc, textonly = TRUE)`

**Comment by davidgohel** [comment]
Hi,

Sorry for the limit. I don't have time to do that - I think it would require at least few days of work (but I may be wrong). 

Did you recommend that solution because you tested it? If yes, could you propose a PR?

KR
David

**Comment by ttime12** [comment]
Fair enough, I was assuming it was a quick fix as the solution would be a sub-process of an already established method.

Unfortunately I am not skilled enough to propose a PR.
Thanks again for the oterwise awesome package!

**Comment by davidgohel** [comment]
No, it's about reading a huge XML into an R session. 

Thnaks 
David
