### ISSUE TITLE
Word throw unreadable content warning when docx has both header and footer

### ISSUE THREAD

**Issue by MajoroMask** [davidgohel/officer#197]
[proto_test.docx](https://github.com/davidgohel/officer/files/2986202/proto_test.docx)
This is my template with pre-edited header and footer. I can open it without any warnings. But simply read into R session then output will trigger the "unreadable content" warning. 

```
library(officer)

docx <- read_docx("proto_test.docx")
print(docx, target = "test_unreadable.docx")
```

I tried debug and found out that this problem would be fixed by removing **either** header **or** footer, which is kinda interesting. I do not know if it's a bug or something's wrong with my preset header/footer. 

FYI
`sessionInfo()`
```
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] officer_0.3.2

loaded via a namespace (and not attached):
 [1] compiler_3.5.2  R6_2.4.0        magrittr_1.5    htmltools_0.3.6 tools_3.5.2     base64enc_0.1-3
 [7] yaml_2.2.0      Rcpp_1.0.0      uuid_0.1-2      xml2_1.2.0      digest_0.6.18   zip_1.0.0  
```
Office Word version 16.22 (190211)

**Comment by davidgohel** [comment]
Thanks for reporting this, 

I had trouble to understand what was going on. It was an issue with unique id. This should be solved now.
