### ISSUE TITLE
ph_with image size inconsistent for  external_img

### ISSUE THREAD

**Issue by mlduarte** [davidgohel/officer#201]
Hi - I have just downloaded the latest version of the OfficeR package and think the new functionality is great; I had to create some hacky functions (one example below, much to my embarrassment) in the previous version I had downloaded to get the index by label as I updated my master PPTX template file when creating the PPT and the indexes kept changing.

I have noticed however, in the latest version, that the image size seems to be inconsistent between `ph_with(external_img)` and `ph_with_img(type, index, src = external_img)`.  There are three example slides below; the second slide is what I was trying to update my code to, however the image size is no longer correct (unless I were to redefine the height and width).

```
# requires document (x) with current slide saved
get_label_index <- function (x, label = NA, type = "body", index = 1) 
{
  stopifnot(type %in% c("ctrTitle", "subTitle", "dt", "ftr", 
    "sldNum", "title", "body"))
  stopifnot(!is.na(label))
  slide <- x$slide$get_slide(x$cursor)
  data <- slide$get_xfrm()
  layout <- data[1, "name"]
  master <- data[1, "master_name"]
  data <- x$slideLayouts$get_xfrm_data()
  data <- data[data$name == layout & data$master_name == master & data$type == type, ]
  which(data$ph_label == label)[index]
}
environment(get_label_index) <- asNamespace('officer')

require(ggplot2)

gg_plot <- ggplot(data = iris ) +
  geom_point(mapping = aes(Sepal.Length, Petal.Length),
    size = 3) + theme_minimal()
ggsave("temp_plot.png", height = 12.57, width = 11.22, units = "cm")

doc <- read_pptx()

#layout_summary(doc)
#layout_properties(x = doc, layout = "Two Content", master = "Office Theme") 

# size is great
doc <- add_slide(doc, layout = "Two Content", master = "Office Theme")
doc <- ph_with(x = doc, value = gg_plot, location = ph_location_label(ph_label = "Content Placeholder 3") )

# size is very small
doc <- add_slide(doc, layout = "Two Content", master = "Office Theme")
doc <- ph_with(x = doc, value = external_img("temp_plot.png"), location = ph_location_label(ph_label = "Content Placeholder 3") )


# size is great
doc <- add_slide(doc, layout = "Two Content", master = "Office Theme")
doc <- ph_with_img(doc, type = "body", index = get_label_index(doc, label = "Content Placeholder 3"), src = "temp_plot.png")

print(doc, target = "ph_with_demo.pptx")
```

SessionInfo: 
> sessionInfo()

> R version 3.5.1 (2018-07-02)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
> [4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    
> 
> attached base packages:
> [1] grid      stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] stringr_1.4.0    dplyr_0.8.0.1    purrr_0.3.2      readr_1.3.1      tidyr_0.8.3      tibble_2.1.1    
>  [7] ggplot2_3.1.0    tidyverse_1.2.1  readxl_1.3.1     png_0.1-7        lubridate_1.7.4  knitr_1.22      
> [13] forcats_0.4.0    dbplyr_1.3.0     dbplot_0.3.1     glue_1.3.1       DBI_1.0.0        odbc_1.1.6      
> [19] scales_1.0.0     kableExtra_1.1.0 flextable_0.5.1  magrittr_1.5     officer_0.3.3    DT_0.5          
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.1        lattice_0.20-38   assertthat_0.2.1  digest_0.6.18     packrat_0.5.0    
>  [6] R6_2.4.0          cellranger_1.1.0  plyr_1.8.4        backports_1.1.3   evaluate_0.13    
> [11] httr_1.4.0        pillar_1.3.1      gdtools_0.1.7     rlang_0.3.2       lazyeval_0.2.2   
> [16] uuid_0.1-2        rstudioapi_0.10   data.table_1.12.0 blob_1.1.1        magick_2.0       
> [21] rmarkdown_1.12.3  labeling_0.3      webshot_0.5.1     selectr_0.4-1     htmlwidgets_1.3  
> [26] bit_1.1-14        munsell_0.5.0     broom_0.5.1       modelr_0.1.4      compiler_3.5.1   
> [31] xfun_0.5          pkgconfig_2.0.2   base64enc_0.1-3   htmltools_0.3.6   tidyselect_0.2.5 
> [36] viridisLite_0.3.0 withr_2.1.2       crayon_1.3.4      nlme_3.1-137      jsonlite_1.6     
> [41] gtable_0.2.0      zip_2.0.1         cli_1.1.0         stringi_1.4.3     xml2_1.2.0       
> [46] generics_0.0.2    tools_3.5.1       bit64_0.9-7       hms_0.4.2         yaml_2.2.0       
> [51] colorspace_1.4-1  rvest_0.3.2       haven_2.1.0   
> 

Kind regards
Marie

**Comment by davidgohel** [comment]
Thanks for that. It was a stupid error. I used the width and height of `external_img` instead of the values of the location object. 

It is solved now.
