### ISSUE TITLE
ph_with_text removes object background color

### ISSUE THREAD

**Issue by mlduarte** [davidgohel/officer#202]
Hi David, 

I am not sure how to maintain the template document shape properties, i.e. background and font colour, when using `ph_with()`.  I was able to maintain the formatting in an earlier version of Officer.

I am attaching the standard PPT template, modified so that the background of the "Two Content" layout objects are grey background with red font.
[eg_template.pptx](https://github.com/davidgohel/officer/files/3011612/eg_template.pptx)

```
doc <-read_pptx("eg_template.pptx")
# no background colour
doc <- add_slide(doc, layout = "Two Content", master = "Office Theme")
doc <- ph_with(x = doc, value = "with() ... background not grey", location = ph_location_label(ph_label = "Content Placeholder 3") )
doc <- ph_with_text(doc, type = "body", index = 1, str = "with_text() ... background not grey")

doc <- add_slide(doc, layout = "Two Content", master = "Office Theme")
doc <- ph_empty(x = doc, location = ph_location_label(ph_label = "Content Placeholder 3") )
doc <- ph_empty(doc, location = ph_location_label(ph_label = "Content Placeholder 2"))
doc <- ph_add_par(doc, ph_label = "Content Placeholder 2")
doc <- ph_add_text(doc, str = "Text not red", ph_label = "Content Placeholder 2")

print(doc, target = "ph_with_demo.pptx")
```

> sessionInfo()

> R version 3.5.1 (2018-07-02)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
> [4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    
> 
> attached base packages:
> [1] grid      stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] stringr_1.4.0    dplyr_0.8.0.1    purrr_0.3.2      readr_1.3.1      tidyr_0.8.3      tibble_2.1.1     ggplot2_3.1.0   
>  [8] tidyverse_1.2.1  readxl_1.3.1     png_0.1-7        lubridate_1.7.4  knitr_1.22       forcats_0.4.0    dbplyr_1.3.0    
> [15] dbplot_0.3.1     glue_1.3.1       DBI_1.0.0        odbc_1.1.6       scales_1.0.0     kableExtra_1.1.0 flextable_0.5.1 
> [22] magrittr_1.5     officer_0.3.3    DT_0.5          
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.1        lattice_0.20-38   assertthat_0.2.1  digest_0.6.18     packrat_0.5.0     R6_2.4.0         
>  [7] cellranger_1.1.0  plyr_1.8.4        backports_1.1.3   evaluate_0.13     httr_1.4.0        pillar_1.3.1     
> [13] gdtools_0.1.7     rlang_0.3.2       lazyeval_0.2.2    uuid_0.1-2        rstudioapi_0.10   data.table_1.12.0
> [19] blob_1.1.1        magick_2.0        rmarkdown_1.12.3  labeling_0.3      webshot_0.5.1     selectr_0.4-1    
> [25] htmlwidgets_1.3   bit_1.1-14        munsell_0.5.0     broom_0.5.1       modelr_0.1.4      compiler_3.5.1   
> [31] xfun_0.5          pkgconfig_2.0.2   base64enc_0.1-3   htmltools_0.3.6   tidyselect_0.2.5  viridisLite_0.3.0
> [37] withr_2.1.2       crayon_1.3.4      nlme_3.1-137      jsonlite_1.6      gtable_0.2.0      zip_2.0.1        
> [43] cli_1.1.0         stringi_1.4.3     xml2_1.2.0        generics_0.0.2    tools_3.5.1       bit64_0.9-7      
> [49] hms_0.4.2         yaml_2.2.0        colorspace_1.4-1  rvest_0.3.2       haven_2.1.0      
> > 

Regards,
Marie

**Comment by davidgohel** [comment]
Thanks again Marie!

This was a issue with default values, again ;)

It is now fixed.

Regards,
David
