### ISSUE TITLE
Feature request: remove proofErr tag added by MS Office Word

### ISSUE THREAD

**Issue by MajoroMask** [davidgohel/officer#203]
Hi @davidgohel , I found that by triggering MS Office Word's spell checking, it would add a pair of `<w:proofErr w:type="spellStart"/>` and `<w:proofErr w:type="spellEnd"/>` tag around spell error. From what I know I can create a method to merge the `<w:proofErr>` to the `<w:r>` nearby to avoid this. Or try to tell everyone who may open my document to close spell/gramma-check before they save/overwrite it. Can you add a method like `erase_error()` do deal with this kind of error tag?

A instance: 

```
library(officer)
library(tidyverse)

if (dir.exists("unzip")) unlink("unzip", recursive = TRUE)
dir.create("unzip")
demo1 <- 
  read_docx() %>% 
  body_add_par("Officer is useful.") %>% 
  body_add_par("Even better to be used with flextable.")
print(demo1, target = "demo1.docx")
system("unzip -d unzip/1st demo1.docx")

# manually open demo1.docx in MS Office Word, edit around the word 'flextable' to
# trigger Word to check spelling, then save it to 'demo2.docx'

system("unzip -d unzip/2nd demo2.docx")
```

By checking and compare the resulting xml files (namely `unzip/1st/word/document.xml` and `unzip/2nd/word/document.xml`), you can find the `proofErr` tag be added around the word "flextable". 

Much obliged for your possible assistance. :)

**Comment by davidgohel** [comment]
Hi,

No sorry, I think it should be done in the Word template. 

Even if not, I don't want to add a step that would probably significantly decrease the speed - as this is the most important subject in the next dev. runs.
