### ISSUE TITLE
read file names with accents

### ISSUE THREAD

**Issue by fm555** [davidgohel/officer#204]
I am using officer (officer_0.3.3) in R to read Word and PowerPoint files.
Some of the files have accents in the name, for instance "Presentación.pptx".
If I do:

read_pptx("Presentación.pptx")

It gives the following error:

Error in zip::unzip(zipfile = file, exdir = folder) : 
 zip error: `Cannot open zip file'

If I use list.files(), it properly reads the name of the files with accents (so it shows "Presentación.pptx" as the file name), but when I try to use read_pptx, or read_docx (with another file named for instance "Presentación.docx"), it does not work.

If I rename the file to delete the accent ("Presentacion.pptx"), then it works well. But the problem is that I have to read several Word and PowerPoint files that include accents in the name, so I would need to find a quick solution for this.
How can I solve this issue? What is your suggestion?
Maybe there is a workaround that I can use to read files with accents in their name using read_docx and read_pptx?

I need to solve this isuue as soon as possible.
Let me know if you need additional information.
Thank you.

**Comment by davidgohel** [comment]
Thanks, please do not forget the `sessionInfo()` as requested in the form.

About the delay, I am afraid I am not available to solve that ASAP.

**Comment by fm555** [comment]
Sorry, I forgot to include the details about the sessionInfo():

R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                   LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] officer_0.3.3 jsonlite_1.6  httr_1.4.0   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0      digest_0.6.18   R6_2.4.0        magrittr_1.5    zip_2.0.0       rlang_0.3.3     uuid_0.1-2      curl_3.3        xml2_1.2.0     
[10] tools_3.5.0     jpeg_0.1-8      yaml_2.1.19     compiler_3.5.0  base64enc_0.1-3 htmltools_0.3.6

In case you are not available to solve that ASAP, I would still appreciate any quick fix solution you may have, or another solution you may have at some point (not as soon as possible, but as soon as you are available to solve that issue) :)

Let me know if you need more information.
Thanks again for your quick reply.

**Comment by davidgohel** [comment]
thanks

The unzipping is made by package `zip`. I don't do anything particular with this - just using the function... 

Maybe you could try to change your filename with `enc2native` or `enc2utf8`, if that does not work, I don't have other ideas for now :/

**Comment by fm555** [comment]
Following your suggestions, I have tried:

read_pptx(enc2native("Presentación.pptx"))

read_pptx(enc2utf8("2019 Plantilla Presentación.pptx"))

Were you suggesting to do something similar to the lines above? Or something different?
Both options give the same error with zip that before:

Error in zip::unzip(zipfile = file, exdir = folder) : 
  zip error: `Cannot open zip file `C:\Documents\PresentaciÃ³n.pptx` for reading` in file `zip.c:238`

For some reason, with accents it seems that is trying to use zip. It does not read "Presentación", but it is reading "PresentaciÃ³n" (strange characters instead of accent).

**Comment by davidgohel** [comment]
ok, that was what I would try. 

I guess zip package has an issue with accent on windows... Could you also try ?

`zip::unzip(zipfile = "Presentación.pptx", exdir = "anything")`

However the package recently changed and is deprecating a function used by officer (and openxlsx) and does not offer an alternative so I may have to use the good old zip program soon

**Comment by fm555** [comment]
I tried: 

zip::unzip(zipfile = "Presentación.pptx", exdir = "anything")

But it is giving the same error (zip error) ...

**Comment by davidgohel** [comment]
OK, then I am innocent :)

Thanks, there is nothing I can do for now. Note your code will certainly work if used under linux or mac os X.

**Comment by fm555** [comment]
Thank you.
Let me know if you find a solution at some point.

**Comment by davidgohel** [comment]
It should be fixed now. I made a workaround

**Comment by fm555** [comment]
Hi David,

Thank you. I have reinstalled officer (devtools::install_github(“davidgohel/officer”)),but when I try to read a pptx with a file name with an accent, I am still getting a zip error. Am I missing something to fix this error?

Thank you.
Cheers,

Francesc

________________________________
De: David Gohel <notifications@github.com>
Enviado: lunes, abril 29, 2019 1:57 p. m.
Para: davidgohel/officer
CC: fm555; Author
Asunto: Re: [davidgohel/officer] read file names with accents (#204)


It should be fixed now. I made a workaround

**Comment by davidgohel** [comment]
Can you show the `sessionInfo()` please

**Comment by fm555** [comment]
It works now!
There were missing updates for some packages (Rcpp, rlang and zip), and the updated version of officer did not get properly installed (sorry, I did not realize). I manually installed the updated packages Rcpp, rlang and zip, and after that I downloaded the latest officer version from github. Now, officer can read file names with accents without problems.

Thank you so much!
Cheers,

Francesc

________________________________
De: David Gohel <notifications@github.com>
Enviado: lunes, mayo 13, 2019 9:51 a. m.
Para: davidgohel/officer
CC: fm555; Author
Asunto: Re: [davidgohel/officer] read file names with accents (#204)


Can you show the sessionInfo() please
