### ISSUE TITLE
zip::zip() is now deprecated

### ISSUE THREAD

**Issue by davidski** [davidgohel/officer#205]
As of [zip v2.0.1](https://github.com/r-lib/zip/blob/master/NEWS.md#201), the `zip::zip()` function is deprecated and `zip::zipr()` is now recommended. This causes warnings to be thrown to the user (and possibly CRAN).

While I _think_ this is a drop in replacement for the `zip::zip()` call in the `pack_folder()` function, I've not tested this so I'm not submitting a PR just yet. 😄 

https://github.com/davidgohel/officer/blob/2ad7516525deb700a501db1b72591d960a55d083/R/pack_folder.R#L33

**Comment by davidgohel** [comment]
I am aware of it - the `zipr` function does not produce valid files (or I am not able to use it correctly). I may have to use `utils::zip`. 

If you feel like you can help, you are very welcome :)

David

**Comment by davidski** [comment]
Doh! I just noticed your issue at https://github.com/r-lib/zip/issues/31. I'll try and see if I can figure anything out.

**Comment by davidgohel** [comment]
This will be fixed in package `zip`. I have hidden the `deprecated` message for now.
