### ISSUE TITLE
How to easily add  multi-paragraphs with different style into doc

### ISSUE THREAD

**Issue by ZhuLeZi** [davidgohel/officer#206]
Hi David:
I am trying to create multi-paragraphs with different style using body_add_par() . However it currently only allow one by one.

Here I thought other solution:
1. library('ReporteRs')
   tt<-c("a","av","sv")
   doc<- docx( title = 'My document' )
   doc<-addParagraph(doc,tt,stylename = "BulletList")
   in this way how to set multi styles ,i try c("BulletList","Normal","Normal") it's not success

Or is there any other way to solve this problem?
Best,
zhulezi

**Comment by davidgohel** [comment]
Hi 

You can use `block_list`. See examples here:

https://davidgohel.github.io/officer/reference/body_add_blocks.html

David
