### ISSUE TITLE
headers_replace_all_text/footers_replace_all_text not working with multiple sections in Word

### ISSUE THREAD

**Issue by EDLUT2019** [davidgohel/officer#208]
Hello,
when trying to use the headers_replace_all_text or footers_replace_all_text function with a .docx (Word 2016) document which contains more than one header/footer section, I am always getting the following error message:
Warning message:
In header$replace_all_text(old_value, new_value, only_at_cursor,  :
  Found 0 instances of 'text' in the document.

The function works greatly if there is only one header/footer section.

Would it be easy to fix this bug? It would help us to save a lot of time.

Thanks,
Mark

**Comment by davidgohel** [comment]
Dear Mark, 

Can you provide a reproducible code as written in the guidelines (displayed when you opened that issue)? I need also your `sessionInfo()`.

Are you saying argument `warn=FALSE` has no effect?

**Comment by davidgohel** [comment]
A warning is not an error. Did you use option to change warnings as errors?

**Comment by EDLUT2019** [comment]
Hello,
I checked the function again, added the argument warn=FALSE and this time it worked perfectly (without any warning message). The text strings have been replaced as expected.
Sorry, for having you unnecessarily bothered with this issue.
Thanks again for the great tool.

**Comment by davidgohel** [comment]
OK, no problem. I feared a bigger issue ;)
