### ISSUE TITLE
Docx in Shiny

### ISSUE THREAD

**Issue by myneuronews** [davidgohel/officer#209]
Could you please provide a basic example of creating a docx document in Shiny?

**Comment by davidgohel** [comment]
```
library(shiny)
library(officer)

ui <- fluidPage(
    downloadLink('downloadData', 'Download')
)

server <- function(input, output) {

    output$downloadData <- downloadHandler(
        filename = function() {
            paste('data-', Sys.Date(), '.pptx', sep='')
        },
        content = function(con) {
            x <- read_pptx()
            print(x, target = con)
        }
    )

}
```

**Comment by myneuronews** [comment]
You are a star!

Thanks

**Comment by matthanc** [comment]
Does this still work? I can't seem to get this or the below example from the book to work.

`library(shiny)
library(officer)
library(ggplot2)

ui <- fluidPage(

    # Application title
    titlePanel("Old Faithful Geyser Data"),
    sidebarLayout(
        sidebarPanel(
            sliderInput("bins", "Number of bins:", min = 1, max = 50, value = 30),
            downloadButton("downloadReport", "Download report")
        ),
        mainPanel(
           plotOutput("distPlot")
        )
    )
)

server <- function(input, output) {

    my_plot <- reactive({
        ggplot(faithful, aes(eruptions)) + geom_histogram(bins = input$bins)
    })
    output$distPlot <- renderPlot({
        my_plot()
    })
    output$downloadReport <- downloadHandler(
        filename = function() {
            paste("report-", Sys.Date(), ".docx", sep="")
        },
        content = function(file) {
            doc <- read_docx()
            doc <- body_add_gg(doc, value = my_plot())
            print(doc, target = file)
        }
    )
}

shinyApp(ui = ui, server = server)`

**Comment by davidgohel** [comment]
@matthanc thanks a lot for your interesting and documented question. Yes it still works.
