### ISSUE TITLE
Flextable in Landscape Mode

### ISSUE THREAD

**Issue by mbaqiraltaf** [davidgohel/officer#21]
Hi,

I need to add flextable inside word document in landscape mode as my table has many columns. I seen this function body_end_section and tried to use it for above purpose but its not working. Can you help me with this please? I tried below code

```
read_docx() %>%
          body_add_par(value = "Hi", style = "Normal") %>%
          body_end_section(landscape = TRUE) %>%
          body_add_flextable(flexTableObj) %>%
          body_end_section(landscape = TRUE )
```

Thanks

**Comment by davidgohel** [comment]
Hi,

Thanks for reporting that. Sections can only be attached to a paragraph in a Word document but I didn't checked that; it's been fixed by throwing an error if section is added on something else than  a paragraph.

You will need to add an extra empty paragraph just after the flextable:

```
read_docx() %>%
  body_add_par(value = "Hi", style = "Normal") %>%
  body_end_section(landscape = TRUE) %>%
  body_add_flextable(flextable(head(iris))) %>%
  body_add_par(value = "", style = "Normal") %>%
  body_end_section(landscape = TRUE )
```
