### ISSUE TITLE
Highlighting Text in Word Doc

### ISSUE THREAD

**Issue by ponnet** [davidgohel/officer#211]
Hi All,

I am trying to do a seemingly simple task.
I put a table in Word and want to highlight certain key words in that table. For example highlight below:
![image](https://user-images.githubusercontent.com/25302978/57321061-6b764e00-70ce-11e9-89cf-5f3c3e63d9f6.png)

Many thanks!

**Comment by MajoroMask** [comment]
Dear @ponnet :
Try add formatted paragraph by `body_add_fpar()`.
Check the manual which have a simple example just meet your demand:
https://davidgohel.github.io/officer/reference/body_add_fpar.html

**Comment by ponnet** [comment]
Hmm... Still no avail.

Looks like for the body_add_fpar() you have to add the text sequentially before and then after. I need to just highlight certain words that are already in the document's table

**Comment by davidgohel** [comment]
Hi, sorry for the delay

You can not format existing text in a document with officer. 

This could be an option later but not in a short term period.
