### ISSUE TITLE
How to center text in an existing textbox on a ppt slide

### ISSUE THREAD

**Issue by CamilleMartinelli** [davidgohel/officer#213]
Hi David, 

Is it possible to center text in an existing textbox in a ppt template ?

I use the function ph_add_text but I can't find any parameter that allows to center the text in my textbox. 

I tried to format the textbox before loading the ppt template in R, but the format of the textbox is not kept after putting some text inside with the function ph_add_text.

My textbox has the id_chr "3" and my ppt template is named ppt.

```
style.1= fp_text(color = "#595959", font.family = "Calibri", font.size = 8, underlined = F, bold = F)

ppt = on_slide(ppt, index =1) %>%
ph_add_text(str = "hello", id_chr = 3, style = style.1, pos="before")
```

Thank you very much for your help,
Camille

**Comment by davidgohel** [comment]
Hi Camille,

There was an issue that has been fixed (in the github repo for now), thanks for reporting it. The following code (and pptx template [template.pptx](https://github.com/davidgohel/officer/files/3315238/template.pptx)) should help:


````
library(officer)

style.1 <- fp_text(color = "white", font.family = "Calibri", 
                   font.size = 8, underlined = F, bold = F)

bl <- block_list(
  fpar(ftext("hello world", style.1)),
  fpar( ftext("hello", style.1),
        ftext(" world", style.1) ) )

fileout <- tempfile(fileext = ".pptx")

doc <- read_pptx(path = "template.pptx") %>% 
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(bl, location = ph_location_label(ph_label = "MyPlaceholder"))

print(doc, target = fileout ) 
# browseURL(fileout)
````

In the image below, you can see how is defined the "MyPlaceholder" placeholder

<img width="1293" alt="Capture d’écran 2019-06-21 à 17 54 40" src="https://user-images.githubusercontent.com/4331618/59935946-2bd1ae80-944f-11e9-8547-859d7cf2aa94.png">

And then the final result:


<img width="1052" alt="Capture d’écran 2019-06-21 à 18 06 25" src="https://user-images.githubusercontent.com/4331618/59936036-57ed2f80-944f-11e9-89ad-12637fec5851.png">

**Comment by ellisp** [comment]
I don't think this addresses the issue. I also want to add text to an existing placeholder with `ph_add_text()` and I don't see how to center-justify it. The solution above seems to be about creating a new placeholder, and also doesn't center the text. Is it possible to center text that is being appended to a placeholder with `ph_add_text()`?

**Comment by davidgohel** [comment]
@ellisp yes, sorry, I don't remember that one and it seems the answer is related to another issue...

**Comment by davidgohel** [comment]
If possible, I discourage using `ph_add_text ()` (it makes the code complex). 

---

You can use `fpar` instead. It has an argument 
`fp_p` where you can specify paragraph settings (where text alignment is defined):

```
library(officer)

fpt_blue_bold <- fp_text(font.size = 50, color = "#006699", bold = TRUE)
fpt_red_italic <- fp_text(font.size = 50, color = "#C32900", italic = TRUE)

value <- block_list(
  fpar(ftext("hello world", fpt_blue_bold)),
  fpar(
    ftext("blah ", fpt_blue_bold), 
    ftext("blah blah", fpt_red_italic), 
    fp_p = fp_par(text.align = "center")))
value

doc <- read_pptx()
doc <- add_slide(doc)
doc <- ph_with(doc, value, location = ph_location_type(type = "body"))
print(doc, target = "example.pptx")

```

<img width="915" alt="Capture d’écran 2020-08-05 à 19 50 20" src="https://user-images.githubusercontent.com/4331618/89446579-fd975700-d754-11ea-871d-0c7aa111e0e2.png">


[example.pptx](https://github.com/davidgohel/officer/files/5030260/example.pptx)

---

Another solution is to reuse template properties:

```
doc <- read_pptx(path = "~/Downloads/template.pptx")
doc <- add_slide(doc)
doc <- ph_with(doc, "hello world", location = ph_location_label(ph_label = "MyPlaceholder"))
print(doc, target = "example2.pptx")
```

<img width="765" alt="Capture d’écran 2020-08-05 à 19 58 45" src="https://user-images.githubusercontent.com/4331618/89447388-2e2bc080-d756-11ea-8f16-4d5bce431065.png">


[template.pptx](https://github.com/davidgohel/officer/files/5030286/template.pptx)
[example2.pptx](https://github.com/davidgohel/officer/files/5030287/example2.pptx)

**Comment by ellisp** [comment]
Thanks, this is more or less what I ended up doing (using `fpar` and inserting it with `ph_with`).
