### ISSUE TITLE
Turning Off Inplace Modification Of PPTX Files

### ISSUE THREAD

**Issue by gfleetwood** [davidgohel/officer#214]
Hi,

I'm using officer to remove a slide from a pptx file (5 slides) and save the new slideshow. However, when I do this:

```
te = officer::read_pptx("~/../Downloads/test.pptx") # 1
officer::remove_slide(te, 1) # 2
te2 = officer::remove_slide(te, 1) # 3
print(te2, target = "~/../Downloads/test2.pptx") # 4
```

The new file has 3 slides instead of four because it seems that line 2 modifies the original file in place. I ultimately want to save all 5 slides as separate pptx files, and would like to operate on the original file once instead of having to constantly read it in five times.

Is there a way to turn off modifying in place?

**Comment by davidgohel** [comment]
Hi,

Sorry no, at least not in a short term period :( 
You can read more about this here #137.

David
