### ISSUE TITLE
Problem showing .emf files in Word imported via officer - recent Microsoft update likely cause?

### ISSUE THREAD

**Issue by stekay** [davidgohel/officer#216]
I've been using officer with DEVemf package to produce Word docs for the last few months. All has gone well (was using Word 2016, Windows 7 with all updates).  Standard way of using body_add_img after creating the emf. All Word files saved fine and viewed fine (emf figures looked great).
About a week ago Windows 7 updated itself on booting up. Now the same Word files previously created no longer show the emf image - they have the right sized placeholder for it but is it a clear white rectangle. Chatting with Microsoft support did not help. I actually upgraded to Word 365 and Windows 10. Doing such a completely fresh install helped and I could now view my old Word files and the emf images perfectly. However when I then ran my usual R script that creates such Word docs using officer (ie created a completely new Word doc) not only did the problem of not being able to see the emf file reappear for this new document, when I then opened up my old Word files that had been fixed they to no longer showed the emf file (same blank rectangle). If I open these files in the online version of Word 365 they view perfectly. It is my hard-drive version of Word 365 that has the problem. I thought that what had happened meant that the officer program had somehow altered the normal template used by my hard-drive version. I deleted the template (it automatically creates a new one when such happens but it has made no difference).  What is interesting is that it never use to open the Word files in "compatability mode", now it always does when the emf files are present.  Any advice much appreciated- be surprised if I'm the only one with this problem.

Thanks for making a great free product.

Best,

Steve

**Comment by kestrel99** [comment]
I agree, tremendous package! 

I'm having the same issue with EMF files suddenly (just the last few days). It seems the most recent Windows update did indeed break something.

**Comment by davidgohel** [comment]
Hi,

A colleague nicely ran a test for us (I don't have any Windows machine) and we are able to reproduce (that was the good news). 

However, it may be an issue with `devEMF` as the graphs cannot be opened in windows since the update. Can you confirm the produced graph cannot be viewed (without office to wrap it in a pptx or docx doc)?

**Comment by jekriske-lilly** [comment]
A temporary fix is to add emfPlus=TRUE, emfPlusFont=TRUE, emfPlusRaster =TRUE when creating the emf files. When doing this it will create the emf files just fine, 

officer, however, will only add the emf file on version 0.3.2, both 0.3.4. and 0.3.5 result in a corrupt word file for me.

**Comment by stekay** [comment]
It is a little frustrating. Now my online Word 365 version cannot view the emf files in my old docs that it could before. My PowerPoint version when inserting into a slide an emf file created by devEMF also has same problem - just shows a blank rectangle. I'm using the 64 bit versions of both Windows 10 and Office 365 (possibly the 32 bit office version might show a difference?).  Looks like its back to png.

Like your style David - not having Word yet doing all this super programming for it!

**Comment by davidgohel** [comment]
@stekay :) I have Office 365 but on a mac-os. (but there is no issue in my configuration).

The update of the system did change something as we ran it this morning and then we were able to reproduce. We will have a look in the following days

**Comment by davidgohel** [comment]
Hi,

You need to update `devEMF` package, a new release has been published today on CRAN and it solved the issue:

```
v3.6-3 -- 20 June 2019
  -Workaround for recent Microsoft security patch that breaks the EMF
   specification and does not allow viewing of EMF files containing
   certain Font-related records in Microsoft Office.  Files using only
   EMF+ fonts are not affected.  The relevant CVE seems likely to be
   https://www.zerodayinitiative.com/advisories/ZDI-19-557/
```
