### ISSUE TITLE
Add option to change slide aspect ratio

### ISSUE THREAD

**Issue by Oleksii-Sh** [davidgohel/officer#218]
Hello David,

thanks for this great package!

AFAIU, now pptx slides are generated with a Standard aspect ratio (4:3).

Is it possible to add a feature to change it, e.g., in `read_pptx()` function? To have a possibility to switch to Widescreen, or to set my own ratio?

Sometimes a presentation should be generated in a Widescreen mode, and it could be tricky to fit everything manually.

**Comment by davidgohel** [comment]
Hello,

You can provide a template when calling `read_pptx`. You can reuse an existing template (pptx doc) that you defined with the correct aspect ratio.

https://davidgohel.github.io/officer/reference/read_pptx.html

David

**Comment by jhelvy** [comment]
I came up with a somewhat hacky fix for this issues in my [package](https://github.com/jhelvy/xaringanBuilder) that converts xaringan slides to different output types (see [this issue](https://github.com/jhelvy/xaringanBuilder/issues/15)). 

I included two blank pptx files (`4-3.pptx` and `16-9.pptx`) and put them in the `inst/extdata` folder. Then inside the function that creates a blank pptx doc, I read them in using the `system.file()` function:

```r
# Pick whichever blank template you want
file <- "16-9.pptx"
file <- "4-3.pptx"

# Get the path to the template file:
template <- system.file("extdata", file, package = "xaringanBuilder", mustWork = TRUE)

# Read in the template:
officer::read_pptx(template)
```

This is inside [this package function](https://github.com/jhelvy/xaringanBuilder/blob/master/R/pptx.R), so once the package is installed it will work.
