### ISSUE TITLE
height in body_add_gg

### ISSUE THREAD

**Issue by gilleschapron** [davidgohel/officer#22]
Hi David,

I am very interested by your new package. I use until now ReporteRs but Java dependency is one of my (little) problem with it.

So I am starting to look at officer.
If I  think there is a problem with the way that graphics are resize in the document.
In this example using `body_add_gg` the two plots have the same height, but content, especially fonts, are deformed.

```r
library(ggplot2)
doc <- read_docx()

gg_plot <- ggplot(data = iris ) +
  geom_point(mapping = aes(Sepal.Length, Petal.Length))

doc <- body_add_gg(doc, value = gg_plot, style = "centered", height = 3)
doc <- body_add_gg(doc, value = gg_plot, style = "centered", height = 6)

print(doc, target = "body_add_gg.docx" )
```
In your definition of the function you forget to change default values as variables:
```r
body_add_gg <- function( x, value, width = 6, height = 5, style = NULL, ... ){
  stopifnot(inherits(value, "gg") )
  file <- tempfile(fileext = ".png")
  png(filename = file, width = width, height = height, units = "in", res = 300, ...)
  print(value)
  dev.off()
  on.exit(unlink(file))
  body_add_img(x, src = file, style = style, width = 6, height = 5)
}
```

Regards,
Gilles

**Comment by davidgohel** [comment]
Hi Gilles

Shame on me, thanks for reporting that!

David
