### ISSUE TITLE
`annotate_base` should also include `ph_label`

### ISSUE THREAD

**Issue by jeffreyxparker** [davidgohel/officer#224]
I believe `annotate_base` is using the placeholder type. When this happens, the text formatting follows the uppermost placeholder (perhaps this is a separate feature request). See [this](https://stackoverflow.com/questions/56974328/formatting-text-in-placeholders/56979018#56979018) Stackoverflow. For example:

```
# Uses upper most formatting
my_pres <- my_pres %>% 
  ph_with(value = "Hello world", location = ph_location_type(type = "title")) 

# Uses placeholder formatting
my_pres <- my_pres %>% 
  ph_with(value = "Hello world", location = ph_location_label(ph_label = "Title 1")) 
```
My request is for `annotate_base` should to be based off the `ph_label` and also include that in the output.

Something to consider though is that there can be duplicate `ph_labels` in a template and only the first placeholder gets populated.

**Comment by john-harrold** [comment]
I'm also finding that ph_with, ph_with_gg, etc. don't seem to be taking the location information from the index number. These are the calls I'm using:

ph_with_gg(x=rpt, type = "body", index = 10, src = ggplot())
ph_with(x=rpt,  location = ph_location_type(type = "body"), index = 10, value="text")

It's basically putting everything on the top of the slide like Jeffrey described. Is there any way to use the index number to get the ph_with* functions to place the content in the correct locations?

**Comment by john-harrold** [comment]
Ok I feel kind of dumb now. I didn't realize you could name the labels manually. So you can ignore this :)

**Comment by davidgohel** [comment]
Hi,

I have updated `annotate_base()` so that it reflects the `ph_label` values in each produced shape. Also I updated the id that can be used bu `ph_location_type`.

This is part of a larger subject about the documentation, it should be improved soon.
