### ISSUE TITLE
openxlsx zip_internal error 

### ISSUE THREAD

**Issue by juve0811** [davidgohel/officer#226]
Received this error message from R when using 'openxlsx' package, not sure where to look.

**Error in zip_internal(zipfile, files, recurse, compression_level, append = FALSE, : Some files do not exist**

Does anyone have any suggestions? thanks.

The code is simple:

library(openxlsx)
df1 <- cars
write.xlsx(df1, file = 'cars.xlsx')

**Comment by davidgohel** [comment]
Hi

You are not in the correct repository. You should report this in `openxlsx` repo instead :)
