### ISSUE TITLE
Cannot write docx under Rapache

### ISSUE THREAD

**Issue by tammoterhark** [davidgohel/officer#23]
I am not sure if I am barking up the right tree here, but my script works flawlessly in Rstudio, but I keep running into error 500 under Rapache. 

Can you see if I am doing something wrong, or if I ran into a bug?

code that is executed:
print(doc, target = "output/report.docx")

Attributes of the output directory: 777

Error in the error log:
[Tue May 30 14:52:09.976480 2017] [:error] [pid 8657] [client 213.127.237.217:55812] rApache Notice!
Loading required package: officer
Loading required package: magrittr
Loading required package: xlsx
Loading required package: rJava
Loading required package: xlsxjars
Loading required package: limer
Loading required package: ggplot2
Loading required package: mailR
Loading required package: flextable
Saving 178 x 178 mm image
Error in value[[3L]](cond) : 
  Could not write '/home/admin/domains/reporting.toolsforresearch.com/public_html/project/gw/output/demo-Werkgelukmeter.docx' [Can't create zip file entry]
Traceback:
11: stop("Could not write ", shQuote(target), " [", e$message, "]")
10: value[[3L]](cond)
9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
8: tryCatchList(expr, classes, parentenv, handlers)
7: tryCatch(zip(zipfile = target, files = list.files(all.files = TRUE, 
       recursive = TRUE)), error = function(e) {
       stop("Could not write ", shQuote(target), " [", e$message, 
           "]")
   }, finally = {
       setwd(curr_wd)
   })
6: pack_folder(folder = x$doc_obj$package_dirname(), target = target)
5: print.rdocx(doc, target = report_file_name)
4: print(doc, target = report_file_name)
3: eval(expr, envir, enclos)
2: eval(exprs[i], envir)
1: sys.source(file = "/home/admin/domains/reporting.toolsforresearch.com/private_html/project/gw/wgofficer.R", 
       envir = .rAenv)

**Comment by tammoterhark** [comment]
Sorry: this was the original code...

print(doc, target = "output/demo-Werkgelukmeter.docx")

**Comment by davidgohel** [comment]
Could you confirm you can write any other file?

**Comment by tammoterhark** [comment]
I can confirm that I can write .png files from GGPlot to the same output
directory


2017-05-30 15:19 GMT+02:00 David Gohel <notifications@github.com>:

**Comment by tammoterhark** [comment]
I can confirm that I can output other files (.png from GGPlot) to that same directory called 'output' (right under the directory that holds the script).

**Comment by davidgohel** [comment]
Can you try `cat("", file = "output/demo-Werkgelukmeter.txt")`

**Comment by tammoterhark** [comment]
Yes, I did. It creates demo-Werkgelukmeter.txt in output. File length = 0.

**Comment by davidgohel** [comment]
and can you try that:

`pack_folder("output", "test.zip")`

**Comment by davidgohel** [comment]
I got that in zip package source: 

https://github.com/gaborcsardi/zip/blob/master/src/rzip.c#L21

I don't think it's about officer but with your settings.

**Comment by tammoterhark** [comment]
I gues that you are right, because:

[Tue May 30 16:43:25.839819 2017] [:error] [pid 11318] [client 213.127.237.217:57762] rApache Notice!
Loading required package: officer
Loading required package: magrittr
Loading required package: xlsx
Loading required package: rJava
Loading required package: xlsxjars
Loading required package: limer
Loading required package: ggplot2
Loading required package: mailR
Loading required package: flextable
Saving 178 x 178 mm image
Error in value[[3L]](cond) : 
  Could not write '/home/tammo/domains/pcx2tammo.toolsforresearch.com/public_html/project/gw/test.zip' [Can't create zip file entry]
Traceback:
9: stop("Could not write ", shQuote(target), " [", e$message, "]")
8: value[[3L]](cond)
7: tryCatchOne(expr, names, parentenv, handlers[[1L]])
6: tryCatchList(expr, classes, parentenv, handlers)
5: tryCatch(zip(zipfile = target, files = list.files(all.files = TRUE, 
       recursive = TRUE)), error = function(e) {
       stop("Could not write ", shQuote(target), " [", e$message, 
           "]")
   }, finally = {
       setwd(curr_wd)
   })
4: pack_folder("output", "test.zip")
3: eval(expr, envir, enclos)
2: eval(exprs[i], envir)
1: sys.source(file = "/home/tammo/domains/pcx2tammo.toolsforresearch.com/private_html/project/gw/wgofficer.R", 
       envir = .rAenv)

**Comment by tammoterhark** [comment]
Thank you very much for helping me trouble shoot this! I will go on..

**Comment by Jan-E** [comment]
Hi David,

> I don't think it's about officer but with your settings.

Tammo's business-partner here. I had a hard time troubleshooting this one. I first made sure everything was running with the same user:group. That took some juggling with mod_ruid2.so (under Directadmin).

But even then we were running into the same error. It worked in RStudio, it worked in plain R, but it failed in (R)Apache. A PHP-script running on the same spot with the same user:group did not fail.

In the end I removed the call to the zip package and replaced it with a crude system call to /usr/bin/zip. The change is here: https://github.com/toolsforresearch/officer/commit/3e2c49e8cdc417b52e52924afc84993783cca72a

For the moment this is working in our case. Tammo switched back from ReporteRs (which had no problems with creating a zip- or docx-file) to toolsforresearch/officer

**Comment by Jan-E** [comment]
Tammo did an upgrade by using 
`devtools::install_github("davidgohel/officer")`
and stumbled into the same error.

So I had to fix it once again:
`devtools::install_github("toolsforresearch/officer")`

Please review https://github.com/davidgohel/officer/issues/36

**Comment by davidgohel** [comment]
Seriously?

OK, glad we can use that tone! It sometimes difficult to answer politely. 

I could not reproduce the problem. I used opencpu that is using rapache and no issue occured. That's why I did not comment, your issue is not reproducible for now. 

> I had to fix it again

From my point of view, I have to take free time again to try to solve **your** specific issue that is not reproducible. Also, why spending time on `officer` while your issue is with function `zip` which is not in officer package. You could instead fix the zip package?

> Please review and merge this PR or find a more suitable solution.

The PR you submited is only working on your system and will break many other systems - what do you propose to solve the issue you are introducing for Window/linux/mac users that don't have program zip in their path? Of I see "merge or find a more suitable solution"... smart, very smart!

Please, if you want to submit a PR, be sure:

- it will not break anything
- it does not reverse something that has already be changed (I guess you did not ask yourself the question why the zip package was used instead of zip function of R)
- do not be gross and do not give order to people that work for you for free

To reproduce the issue, I will have to create a new Linux machine, learn about rapache and test officer in it. As I can only work on that during free time and as there is no contract between us, you will have to wait.
