### ISSUE TITLE
Section break type changed by officer

### ISSUE THREAD

**Issue by RABxx** [davidgohel/officer#230]
I have noticed a strange behaviour with section breaks when a document is passed through officer.

Say I have a `Section Break (Next Page)` break in a document (see section_test.docx), when I simply read it, then print it with officer it changes the section break to `Section Break (Continuous)`. This is not ideal as I like all of my sections to be on new pages, so this way I have to manually change things after the file is printed. 

**code**
```
read_docx('section_test.docx') %>%
  print("section_out.docx")
```

Is there a way to keep the section break the same type after it's read into R?

**input file (has new sections on the next page)**
[section_test.docx](https://github.com/davidgohel/officer/files/3449154/section_test.docx) 

**output file (bunches up the sections)**
[section_out.docx](https://github.com/davidgohel/officer/files/3449155/section_out.docx)

**Comment by davidgohel** [comment]
Thanks!

It is fixed now.

**Comment by RABxx** [comment]
it has started happening again sadly. I just updated to the latest officer version and it happens for some of my breaks :(
