### ISSUE TITLE
Error when having & in text

### ISSUE THREAD

**Issue by slfan2013** [davidgohel/officer#234]
R code: ` slip_in_text("&", style = "Default Paragraph Font", pos = "after")`

The above code returns an error of `Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  xmlParseEntityRef: no name [68]`

**Comment by davidgohel** [comment]
Hi, thanks, it is fixed now

**Comment by slfan2013** [comment]
Now it returns an error of `Error: $ operator is invalid for atomic vectors`
