### ISSUE TITLE
Changing Line Height/SPacing while adding text to docx

### ISSUE THREAD

**Issue by rishi-gupta-md** [davidgohel/officer#235]
Hi

Thank you so much for developing this wonderful package. It makes life so much easier!!

One option that I could not locate was how to change the "Line Height/Line Spacing" of text while adding it to docx (in the fpar function.

Changing the "Padding" option does not solve the issue as that only changes the space around paragraphs, not between individual lines of a paragraph. 

I do not want to use predefined word styles, and want to specify my own styling rules (bold, underlined etc).

Am I missing some simple option? I searched all over the web, and could not come up with an answer.

Thank you.

Regards

**Comment by davidgohel** [comment]
Hi,

No sorry, there is no option for Line Height/Line Spacing implemented with `fp_par`. You can only achieve that by using templates and word styles.

KR
David

**Comment by rishi-gupta-md** [comment]
Ok. Thank you. Could you point me to some guide which explains how to do it
using templates? Also, if I use a template generated on my computer, will
the formatting remail the same if someone else opens the document on their
own computer?

Regards
*Rishi Gupta*
Senior Resident
Department of Psychiatry and NDDTC
All India Institute of Medical Sciences
New Delhi, India
Mob: 9810113166

**Comment by davidgohel** [comment]
> Could you point me to some guide [...]

Yes, you can read https://davidgohel.github.io/officer/articles/word.html#quick-start

> Also, if I use a template generated [...]

Yes

**Comment by rishi-gupta-md** [comment]
Thank you so much. Regards.
On 19-Aug-19 9:41:20 PM, David Gohel <notifications@github.com> wrote:
Could you point me to some guide [...]
Yes, you can read https://davidgohel.github.io/officer/articles/word.html#quick-start [https://davidgohel.github.io/officer/articles/word.html#quick-start]
Also, if I use a template generated [...]
Yes
