### ISSUE TITLE
ph_hyperlink does not create a hyperlink (officer 0.3.5) - corporate environment

### ISSUE THREAD

**Issue by vladimir-bac** [davidgohel/officer#236]
I'm trying to create a PowerPoint with a hyperlink and am running example from ?ph_hyperlink (I've changed only the filepath; code below). The PowerPoint generated by this code contains only "Un titre 1" text field with no hyperlink.

See sessionInfo() below. Additional information: I run it on a corporate computer and external links are blocked in many cases by our firewall.

My hypothesis: reference to "http://schemas.openxmlformats.org/drawingml/2006/main\" inside ph_hyperlink gets blocked by a corporate firewall (I can't access it via browser either). If so, this should be the case for many other organizations with similar cyber security settings.

Code:
```
> library(package)
> 
> fileout <- "test.pptx" #in getwd()
> doc <- read_pptx()
> doc <- add_slide(doc, layout = "Title and Content", master = "Office Theme")
> doc <- ph_with_text(x = doc, type = "title", str = "Un titre 1")
> slide_summary(doc) # read column ph_label here
> #>   type id ph_label offx      offy cx   cy       text
> #> 1 body  2  Title 1  0.5 0.3003478  9 1.25 Un titre 1
> doc <- ph_hyperlink(x = doc, ph_label = "Title 1",
>                     href = "https://cran.r-project.org")
> 
> print(doc, target = fileout)

```

Configuration:

```
> `>` sessionInfo()
> R version 3.6.0 (2019-04-26)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
> [4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] rvg_0.2.1       flextable_0.5.5 magrittr_1.5    dplyr_0.8.3     ggplot2_3.2.1   zoo_1.8-6       lubridate_1.7.4 tidyr_0.8.3    
>  [9] readxl_1.3.1    officer_0.3.5  
> 
> loaded via a namespace (and not attached):
>  [1] tidyselect_0.2.5  xfun_0.8          remotes_2.1.0     purrr_0.3.2       lattice_0.20-38   colorspace_1.4-1  testthat_2.2.1   
>  [8] usethis_1.5.1     htmltools_0.3.6   base64enc_0.1-3   rlang_0.4.0       pkgbuild_1.0.4    pillar_1.4.2      glue_1.3.1       
> [15] withr_2.1.2       gdtools_0.1.9     sessioninfo_1.1.1 uuid_0.1-2        stringr_1.4.0     munsell_0.5.0     gtable_0.3.0     
> [22] cellranger_1.1.0  zip_2.0.3         devtools_2.1.0    evaluate_0.14     memoise_1.1.0     knitr_1.24        callr_3.3.1      
> [29] ps_1.3.0          curl_4.0          Rcpp_1.0.2        backports_1.1.4   scales_1.0.0      desc_1.2.0        pkgload_1.0.2    
> [36] fs_1.3.1          digest_0.6.20     stringi_1.4.3     processx_3.4.1    rprojroot_1.3-2   grid_3.6.0        cli_1.1.0        
> [43] tools_3.6.0       lazyeval_0.2.2    tibble_2.1.3      crayon_1.3.4      pkgconfig_2.0.2   data.table_1.12.2 xml2_1.2.2       
> [50] prettyunits_1.0.2 rmarkdown_1.14    assertthat_0.2.1  rstudioapi_0.10   R6_2.4.0          compiler_3.6.0  
```

**Comment by davidgohel** [comment]
Yes,

Are you suggesting to leave a note in the doc about the subject?

**Comment by vladimir-bac** [comment]
Is it possible to add the information sourced from these external websites into the package itself?

**Comment by davidgohel** [comment]
`"http://schemas.openxmlformats.org/drawingml/2006/main\"` is a namespace, like an identifier. This page does not exists. You can get more details here: https://docs.microsoft.com/en-us/openspecs/office_standards/ms-xlsx/6624db33-496c-47f7-a562-a54cb01b133f

PowerPoint does not read it from the web. 

Did you observed your issue when the slide was opened in the `slide show`? (PowerPoint does not let you open the link when in edit mode)

**Comment by davidgohel** [comment]
The hyperlink is placed on the placeholder, not the text, you need to click on the shape, not the text. 

<img width="938" alt="Capture d’écran 2019-08-12 à 18 50 44" src="https://user-images.githubusercontent.com/4331618/62882405-1e8bbe80-bd32-11e9-9c2f-9959e94916b8.png">

**Comment by vladimir-bac** [comment]
Right. Thanks!
