### ISSUE TITLE
Feature request: allow new_value argument to be numeric

### ISSUE THREAD

**Issue by RABxx** [davidgohel/officer#239]
This is a feature request for all functions to replace anything in the body, header or footer, eg:

- `body_replace_all_text`
- `footers_replace_all_text`
- `headers_replace_all_text`

A good feature would be to allow the new_value to be numeric. 

Currently 2 throws an error, but "2" doesn't.

If you need to to be a character, just wrap it in as.character() or something internally.

**Comment by davidgohel** [comment]
Sorry, I like the fact that the author of the function did restrict to only character so that we don't have to cover several cases that would not work (i.e. an object with no `as.character` method)
