### ISSUE TITLE
Justify (alignment) headers_flextable_at_bkm

### ISSUE THREAD

**Issue by AntoineBrisacier** [davidgohel/officer#242]
I tried to add flextable in header at bookmark with headers_flextable_at_bkm(). It works !
However it would be great if we could have similar functionnalities as body_add_flextable() such as : 
- align
- pos
 
Because I  was not able to justify "left" the added flextable. And same issue for footers_flextable_at_bkm

Kind regards
Antoine

**Comment by davidgohel** [comment]
Thanks for the suggestion.

Sorry, I am not able to add new features to the package for now. I will re open that issue later when I will have time for it.
