### ISSUE TITLE
How to add ggsurvplot() object to Word document?

### ISSUE THREAD

**Issue by nguyenjq** [davidgohel/officer#244]
Hi,

Is the only way to add a ggsurvplot() object to save it as an image and then use body_add_img()? I was hoping for a easier solution (like using body_add_gg, but it doesn't work with the survplot object). 

Thanks!

**Comment by davidgohel** [comment]
Hi,

This is caused by `ggsurvplot` that pops up an empty graphic then the correct graphic. `body_add_gg` is expecting a ggplot object.

**Comment by nguyenjq** [comment]
What is the solution? I would also like to be able to add these plots into a Power Point document as well, and my issue is similar to the one posted here with the old reporteR package: https://github.com/kassambara/survminer/issues/110#ref-commit-21110f3
