### ISSUE TITLE
slip_in_* function not properly working

### ISSUE THREAD

**Issue by Madpentiste** [davidgohel/officer#245]
slip_in_* functions erase paragraphs of the document. 
I tried slip_in_img and got the document blanked - without that line of code, everything else was working, giving a document with all I wanted.
To illustrate the issue, when I try the snippet provided in the documentation, I get the document attached here.
As can be seen, I get "This is the R logo" with the desired image inside it, but the rest is blank (no SEQ Figure etc.).
[Essai exemple officer .docx](https://github.com/davidgohel/officer/files/3632721/Essai.exemple.officer.docx)

**Comment by davidgohel** [comment]
That is a known limitation. Documents need to be open with MS Word to benefit from MS `seqfield`. 

Sorry, if II misunderstood. I will reopen if it is the case.

**Comment by Madpentiste** [comment]
Yes, I think you misunderstood

What do you mean by "/need to be open/": document needs to be open 
/beforehand/, and /then /R will modify it? If so, documentation about 
the slip_in_* family of functions should be modified to say that.

A know limitation should be clearly stated in the primary documentation

Thanks


Le 03/10/2019 à 23:16, David Gohel a écrit :

**Comment by davidgohel** [comment]
> Yes, I think you misunderstood

Could you tell me what editor you used to open the document? I thought you were not using MS Word.

> [...] need to be open [...]

`SEQ Field` is a Word feature and only Word can use them. When Word open the document, it replace the code by its calculated value. This is also the case with `body_add_toc`. TOC is generated by Word (it's also a SEQ field).

**Comment by davidgohel** [comment]
I updated the doc : https://github.com/davidgohel/officer/commit/dd1ff3438a71091f84745b7b09feaae2f0e8d373

**Comment by davidgohel** [comment]
When you open the document you posted, you should see the following and click *yes* (My MS Office is in french):

<img width="423" alt="Capture d’écran 2019-10-04 à 13 44 10" src="https://user-images.githubusercontent.com/4331618/66205223-240be200-e6ad-11e9-870c-a1c17f64bf92.png">

Can you confirm you can not see it with your MS Word version. If this is the case, please provide the version number.

**Comment by Madpentiste** [comment]
I can confirm:

1. That I have the above message from Word
2. That I get exactly the document I had previously attached, that is with everything after the R logo missing

I do not know how much of a big deal this is, maybe there is workarounds, like moving the cursor and inserting things using other functions. I am new to officer, and just happened to find that the snippet given in the documentation for slip_in_* does not work for me.

**Comment by davidgohel** [comment]
The example is not supposed to add anything after the logo...
