### ISSUE TITLE
Feature Request:  Function to add text to Slide Notes

### ISSUE THREAD

**Issue by rlusch** [davidgohel/officer#246]
Best presentation practices are to keep powerpoint as a tool for visualization.  It would be beneficial to be able to add explanations for the presenters into the notes via code, considering I use OfficeR to generate 40 to 50 PowerPoint reports per month.  I would be able to expand some of the available information without detracting from the actual presentation.

**Comment by davidgohel** [comment]
Sorry, this would be a nice feature but this is lot of work. I will be happy to do it but this is not planned in a short term.
