### ISSUE TITLE
Text in object not printing

### ISSUE THREAD

**Issue by ChristopherBorders** [davidgohel/officer#249]
I have used ph_add_text() to three pre-existing objects:
- All three additions show up in the text line of their respective object labels,
  i.e. if I start with "Issued" the slide_summary(power_point object) shows "Issued: Date | Reporting as of Date"
- But when printed back to a powerpoint file only the second of the three prints the additions while the first and third one leave only the original text

I've tried manually forcing the same style, selecting position and trying to make sure the PowerPoint slide I'm loading is saved/closed with the cursors at the end, tried copy/pasting the object that worked and replacing the text in the PowerPoint slide I'm loading, tried to make sure the shape sizes are larger than the existing text. Why won't it print?  
 
```
pptx <- "C:/Users/cborders/Desktop/Reporting/Reporting Files from Sanket/Origination Reports/CBA Reporting Header Template - 2019-10-02.pptx"

base <- read_pptx(path = pptx)
# b <- slide_summary(base)  
# view(b)

test <- base %>%
        ph_add_text(str = "1", ph_label = "Rectangle 1", 
        style = fp_text(font.size = 44, color = "white")) %>%
        ph_add_text(str = " Client Name", ph_label = "Rectangle 2", style = fp_text(font.size = 40, color = "white")) %>%
        ph_add_text(str = " Date | Reporting as of Date", ph_label = "Rectangle 5",
                    style = fp_text(font.size = 28, color = "white", bold = TRUE)) 
      
t <- slide_summary(test)  
view(t)

print(test, target = "C:/Users/cborders/Desktop/Reporting/Reporting Files from Sanket/Origination Reports/CBA Test2 - 2019-10-03.pptx")           
```

**Comment by davidgohel** [comment]
Can you post also the template?

**Comment by ChristopherBorders** [comment]
[CBA Reporting Header Template - 2019-10-02.pptx](https://github.com/davidgohel/officer/files/3688078/CBA.Reporting.Header.Template.-.2019-10-02.pptx)
This is the one that wouldn't work. I tried (for a second time) copying the element that worked and changing the text back to the original and (the second time...) it managed to create a template that would work. I'm worried that when I start looping through to replace the names/dates it's going to break again and I have no idea why it wasn't working the first time or why what I did fixed it so would still appreciate determining what went wrong if possible. 

On another note, is there a way to print the slide in an R markdown result? i.e. if it ends up being easier to add the plots/tables in R markdown is there anything I can do to make sure the needed header slide this code results in gets included?

**Comment by davidgohel** [comment]
It does not print because `rectangle 5` does not exists in your base document. This works 

```
library(tidyverse)
library(officer)

pptx <- "test.pptx"

base <- read_pptx(path = pptx) %>%
  ph_add_text(str = "1", ph_label = "Rectangle 1", 
              style = fp_text(font.size = 44, color = "white")) %>% 
  ph_add_text(str = " Client Name", ph_label = "Rectangle 2", style = fp_text(font.size = 40, color = "white")) %>% 
  ph_add_text(str = " Date | Reporting as of Date", ph_label = "Rectangle 6",
              style = fp_text(font.size = 28, color = "white", bold = TRUE))


print(base, target = "coco.pptx")
```

```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] officer_0.3.5 magrittr_1.5 

loaded via a namespace (and not attached):
 [1] compiler_3.6.0  R6_2.4.0        htmltools_0.3.6 tools_3.6.0     base64enc_0.1-3 Rcpp_1.0.2      uuid_0.1-2      xml2_1.2.2     
 [9] digest_0.6.21   zip_2.0.4       packrat_0.5.0   rlang_0.4.0  
```

**Comment by davidgohel** [comment]
With the dev version, you should get an error saying:

> no shape with label 'Rectangle 5' has been found

**Comment by ChristopherBorders** [comment]
Rectangle 1 was printing for you though? Because originally only Rectangle 2 was printing. I had to delete 1/5 and copy two then change the text back which I think is 5/6 in the current version that works on my machine. 

Apologies if I sent a version that had a rectangle label off to start but even after updating that it had not printed... well, fingers crossed when I start looping whatever the issue doesn't come back.
