### ISSUE TITLE
Feature request: ph_replace

### ISSUE THREAD

**Issue by jarichardsonccbf** [davidgohel/officer#250]
Correct me if I am wrong but the current best method for replacing a part of a slide is to call:

```
ppt.name %>%
     on_slide(index = 2) %>%
     ph_remove(type = "body") %>%
     ph_with(code for new body)
```

Is it possible to eliminate the initial removal and just have something that might work as a straight replacement?

```
ppt.name %>%
      on_slide(index = 2) %>%
      ph_replace(type = "body", new.body)
```

This would be extremely useful for those of us overwriting parts of regularly generated reports.

Thanks!

**Comment by davidgohel** [comment]
Hi

Sorry, I am able to add this for now but if you want to propose a PR, I can review it.
