### ISSUE TITLE
Feature request: start new page numbering scheme (per DOCX section)

### ISSUE THREAD

**Issue by dswpg** [davidgohel/officer#251]
The OfficeXML standard (and MS Word) allows page numbering (as well as style of numbering - like roman numerals)  to restart at the beginning of a section.
See: http://officeopenxml.com/WPSectionPgNumType.php

I tried to make this work with the following, courtesy of Officer's non-exported wml_with_ns (which seemed to be the sort of thing I need, but I'm not sure) function and the body_add_xml function:

```
str <- paste0(officer:::wml_with_ns("w:p"),
              "<w:sectPr>",
              "<w:pgNumType w:start=\"25\"/>",
              "</w:sectPr>")

body_add_xml(x = the_document, str = str, pos = "before")
```

I don't really understand the XML structure of a word file well enough to be sure I was putting it in the right spot, or if that gets in me in the right XML node.
(I tried with with w:sectPr in wml_with_ns, and without it at all.)

I gather that that bit of code with the starting page number needs to be at the beginning of the current section.  It is not clear to me that I'm getting quite to the right spot with the cursor_reach that I used to get there - but I presume it should be doable. 
(Here on sections: http://officeopenxml.com/WPsection.php)

Thanks so much for your fabulous package,
D

**Comment by davidgohel** [comment]
Thanks for the suggestion.

Sorry, I am not able to add new features to the package for now. I will re open that issue later when I will have time for it.
