### ISSUE TITLE
Ordering Issue in Charts

### ISSUE THREAD

**Issue by nick-moffitt** [davidgohel/officer#253]
This last week I discovered a bug in the chart ordering process. This bug seems to be correlated with the v0.4.0 release of htmltools. Before the 4.0 release, charts would come out in the order specified in the data frame from which the mschart function pulled. However, now for any chart in which a user specifies colors for different values in fp_text(), those values always come out in alphabetical order in the chart and not the order specified in the data frame. 

Below I have attached some completely replicable code that shows how the charting function is now longer keeping everything in order:

```r 
library(officer)
library(magrittr)
library(mschart)
library(forcats)

text_settings <- list(
  'One' = fp_text(font.size = 12),
  'Two' = fp_text(font.size = 12),
  'Three' = fp_text(font.size = 12),
  'Four' = fp_text(font.size = 12),
  'Five' = fp_text(font.size = 12)
)
color_settings <- list(
  'One' = 'green',
  'Two' = 'blue',
  'Three' = 'purple',
  'Four' = 'red',
  'Five' = 'orange'
)
frequencies <- tibble::tibble(
  label = c('One', 'Two', 'Three', 'Four', 'Five'),
  result = rep(.2, 5)
) %>%
  mutate(label = fct_inorder(label))
chart <- ms_barchart(
  frequencies,
  x = 'label',
  y = 'result',
  group = 'label'
) %>%
  chart_settings(
    overlap = 100
  ) %>%
  mschart::chart_labels_text(
    values = text_settings
  ) %>%
  mschart::chart_data_fill(
    values = color_settings
  ) %>%
  mschart::chart_data_stroke(
    values = color_settings
  )
print(chart, preview = T)
```

**Comment by davidgohel** [comment]
It's fixed in package "mschart" since few versions

<img width="1010" alt="Capture d’écran 2021-11-07 à 17 07 52" src="https://user-images.githubusercontent.com/4331618/140652682-b4cf31b0-5073-405b-b9f4-3afd1782d220.png">
