### ISSUE TITLE
ph_with flextable quoted call

### ISSUE THREAD

**Issue by TarHeel45** [davidgohel/officer#254]
I updated a bunch of packages today, and I suspect this is the root of the problem. I'm trying to post a flextable into a PowerPoint slide and receiving a " '.call' must be a quoted call" error. 
```
library(officer)
library(flextable)

ft <- flextable(head(iris))
ppt <- add_slide(ppt, layout = "Title and Subtitle", master = "Vanilla") %>%
  ph_with(value = flextable(head(iris)), location = ph_location(left = .39, top = 1.11))
```

**Errors I'm receiving:** 
```
Error: `.call` must be a quoted call
`last_error()
<error/rlang_error>
`.call` must be a quoted call
Backtrace:
 1. officer::ph_with(...)
 2. flextable:::ph_with.flextable(...)
 4. officer:::ph_with.xml_document(...)
 5. officer::location_eval(rlang::enquo(location), x)
 6. rlang::call_modify(...)
 7. rlang:::abort_call_input_type(".call")
Call `rlang::last_trace()` to see the full backtrace.`

`> last_trace()
<error/rlang_error>
`.call` must be a quoted call
Backtrace:
    x
 1. +-officer::ph_with(...)
 2. \-flextable:::ph_with.flextable(...)
 3.   +-officer::ph_with(...)
 4.   \-officer:::ph_with.xml_document(...)
 5.     \-officer::location_eval(rlang::enquo(location), x)
 6.       \-rlang::call_modify(...)
 7.         \-rlang:::abort_call_input_type(".call")`
```

**Comment by davidgohel** [comment]
Thanks for reporting that. The issue is probably because of latest version of flextable (in Imports, it is officer (>= 0.2.0) but should be officer (>= 0.3.6)).

Can you post your `sessionInfo()`?

(A workaround should be to update officer and flextable.)

**Comment by TarHeel45** [comment]
Thanks for the quick response. I suspect you are right about the cause. All I did to fix the problem was to update both packages (so I'm no longer receiving the error). Thank you!!
