### ISSUE TITLE
body_add_gg: unable to provide res argument

### ISSUE THREAD

**Issue by Pakillo** [davidgohel/officer#256]
Issues are a great way to keep track of tasks, enhancements, and bugs for your projects (https://guides.github.com/features/issues/). When submitting, you need to provide the following elements:

### If you are reporting a bug:

- [X] The code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [X] the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [X] you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [X] you searched in the *open* and *closed* issues on the github repository.

### If you are asking an enhancement or a new function

Explain the value, describe the situation.

Avoid beeing anonymous, it's not pleasant for me not knowing who talked to me.

Any suggestions to make the documentation better is really appriciated.

### If you are asking a question

This is not the best place where to put questions. If you are looking for help on how to use 
the package correctly, please visit Stackoverflow and tag your question with `[r]` 
and `[package_name]`. I usually read them and answer when possible.

**Comment by Pakillo** [comment]
Hi @davidgohel 

Thanks a lot for the great package. I'm starting to use it and works great!

I think there is a problem with the function `body_add_gg`. Gives error when trying to provide a `res` argument to change the resolution of the PNG file inserted in the Word docx. Reproducible example below. There is a related question on SO: https://stackoverflow.com/q/49240961

I think the problem may be that `res` is already defined within the function: https://github.com/davidgohel/officer/blob/b832c89b1cea823e7e08da83c4de1ac039dc0e97/R/docx_add.R#L153. So the documentation should probably include this `res` argument already, or it should be taken out of the function? I'm happy to provide a pull request either way if you'd find that useful.

Thanks again,
Paco

``` r
library(officer)

if( require("ggplot2") ){
  doc <- read_docx()
  
  gg_plot <- ggplot(data = iris ) +
    geom_point(mapping = aes(Sepal.Length, Petal.Length))
  
  if( capabilities(what = "png") )
    doc <- body_add_gg(doc, value = gg_plot, style = "centered", res = 300 )
  
  print(doc, target = tempfile(fileext = ".docx") )
}
#> Loading required package: ggplot2
#> Error in png(filename = file, width = width, height = height, units = "in", : formal argument "res" matched by multiple actual arguments
```

<sup>Created on 2019-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.1 (2019-07-05)
#>  os       Windows 7 x64 SP 1          
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United Kingdom.1252 
#>  ctype    English_United Kingdom.1252 
#>  tz       Europe/Paris                
#>  date     2019-11-25                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.1)
#>  backports     1.1.5   2019-10-02 [1] CRAN (R 3.6.1)
#>  base64enc     0.1-3   2015-07-28 [1] CRAN (R 3.6.0)
#>  callr         3.3.2   2019-09-22 [1] CRAN (R 3.6.1)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.1)
#>  colorspace    1.4-1   2019-03-18 [1] CRAN (R 3.6.1)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.1)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.1)
#>  devtools      2.2.1   2019-09-24 [1] CRAN (R 3.6.1)
#>  digest        0.6.22  2019-10-21 [1] CRAN (R 3.6.1)
#>  dplyr         0.8.3   2019-07-04 [1] CRAN (R 3.6.1)
#>  ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.1)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.1)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.1)
#>  ggplot2     * 3.2.1   2019-08-10 [1] CRAN (R 3.6.1)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.1)
#>  gtable        0.3.0   2019-03-25 [1] CRAN (R 3.6.1)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.1)
#>  htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.1)
#>  knitr         1.26    2019-11-12 [1] CRAN (R 3.6.1)
#>  lazyeval      0.2.2   2019-03-15 [1] CRAN (R 3.6.1)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.1)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.1)
#>  munsell       0.5.0   2018-06-12 [1] CRAN (R 3.6.1)
#>  officer     * 0.3.6   2019-11-11 [1] CRAN (R 3.6.1)
#>  pillar        1.4.2   2019-06-29 [1] CRAN (R 3.6.1)
#>  pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.1)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 3.6.1)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.1)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.1)
#>  processx      3.4.1   2019-07-18 [1] CRAN (R 3.6.1)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.1)
#>  purrr         0.3.3   2019-10-18 [1] CRAN (R 3.6.1)
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.1)
#>  Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.1)
#>  remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.1)
#>  rlang         0.4.1   2019-10-24 [1] CRAN (R 3.6.1)
#>  rmarkdown     1.17    2019-11-13 [1] CRAN (R 3.6.1)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.1)
#>  scales        1.0.0   2018-08-09 [1] CRAN (R 3.6.1)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.1)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.1)
#>  testthat      2.3.0   2019-11-05 [1] CRAN (R 3.6.1)
#>  tibble        2.1.3   2019-06-06 [1] CRAN (R 3.6.1)
#>  tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.6.1)
#>  usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.1)
#>  uuid          0.1-2   2015-07-28 [1] CRAN (R 3.6.0)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.1)
#>  xfun          0.11    2019-11-12 [1] CRAN (R 3.6.1)
#>  xml2          1.2.2   2019-08-09 [1] CRAN (R 3.6.1)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)
#>  zip           2.0.4   2019-09-01 [1] CRAN (R 3.6.1)
#> 
#> [1] C:/Users/FRS/Documents/R/win-library/3.6
#> [2] C:/R/R-3.6.1/library
```

</details>

**Comment by davidgohel** [comment]
yes, I was thinking about that in the last run dev. I can add it as an option later or you could propose a PR, it will be welcomed.

**Comment by Pakillo** [comment]
Thanks. I've sent a pull request making the `res` argument explicit to the user. But do whatever you find most useful.
Cheers

**Comment by davidgohel** [comment]
thanks for the PR :)
