### ISSUE TITLE
Quick method for formatting text

### ISSUE THREAD

**Issue by john-harrold** [davidgohel/officer#259]
I've been exploring the `fpar` command to create formatted text. I think this will be really useful, but I find the `ftext` notation to be a little cumbersome. I was thinking about writing a function to take something in a markdown-ish format. Say something like this:

`<fp:c:red>Changing the color to red</fp>, and inserting greek letters: <fp:ff:symbol>D</fp>using superscripts: x<fp:va:superscript>2</fp>`

And automatically create something like this:

`fpar(ftext("Changing the color to red, ", prop=officer::fp_text(color = "red")),
ftext("and inserting greek letters: ", prop=NULL),
ftext("D ", prop=officer::fp_text(font.family = "symbol")), 
ftext("using superscripts: x", prop=NULL),
ftext("2", prop=officer::fp_text(vertical.align= "superscript")))`

Would anyone find this useful? If so are there any thoughts on what I've mapped out above in terms of ease of use?

**Comment by john-harrold** [comment]
Perhaps converting RMarkdown format into the appropriate `fpar()` syntax?

**Comment by john-harrold** [comment]
I don't know if folks would find this useful, but the function in the attached file ([md_example.R](https://github.com/davidgohel/officer/files/3992366/md_example.txt)) will convert the following string:

```
mdtext = "Text can be specified in markdown format as well. You can specify
*bold text*, **italicized text**, ^superscripts^ and ~subscripts~. These can
be combined as well *H*~*2*~*0*.

You can change colors to  <color:red>red</color>, <color:blue>blue</color>, etc and
change the <shade:#33ff33>shading</shade>. Again these can be combined
<shade:orange><color:green>both color and shading</color></shade>. You can also
change the font to things like <ff:symbol>*symbol*</ff>."
```

Into the appropriate `fpar` command to produce this:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/3170004/71320877-d21e6f80-24d7-11ea-88f7-ea3209cbbde3.png">

**Comment by davidgohel** [comment]
Hi John,

Sorry for the delay.

I understand the usecase but the maintainability of the solution would be a difficulty and it does not provide a way to catch user errors.

I could be possible by only covering the markdown language (for chunks). In that case, the solutions are either package `commonmark` or pandoc [AST](https://pandoc.org/using-the-pandoc-api.html). But again, I am not really enthusiast in maintaining that. 

The code to produce a complex paragraph made of different formatted chunks is verbose but this is the same with a graph where you want different colors, fonts, and other options. I think the more you customize, the more you need to add code for these customizations.

**Comment by john-harrold** [comment]
I cannot argue with you about the maintainability issue. I'm going to use it in my own package. I just put it here in case anyone finds it useful. 

Thanks again David for the work on Officer. I've integrated it directly into all of my workflows. It's very useful.

**Comment by davidgohel** [comment]
Maybe as a gist? I could add the gist in the documentation.

**Comment by john-harrold** [comment]
I think this is really just more of my own personal preference than anything else. If anyone else wants the code I've since rolled it into the reporting component of a package I maintain:

https://github.com/john-harrold/ubiquity/blob/1e08f4a86f64cf9b2d0c674461b1869a6da46aed/R/ubiquity.r#L10134

If officer was willing to support something similar, I was going to strip this out and use whatever ever officer would support.
