### ISSUE TITLE
Adding content to powerpoint objects

### ISSUE THREAD

**Issue by nykanenj** [davidgohel/officer#26]
To start off with: David this package is amazing!

This turned into an information share as I found the information I needed. I was having trouble with content placement, i.e. what is the type of certain placeholder in a powerpoint template (body, ftr, title etc.). Also it was hard to find the index or id of a placeholder and so on. 

Solution: slide_summary(pptvariable, index = slideindexno) function in the package shows all this information for placeholders that have content!

Edit: The placeholder id is determined by the "Send forward" "Send backward" commands in powerpoint. This is best viewed by opening the selection pane found at HOME > Select > Selection Pane

**Comment by davidgohel** [comment]
Thanks
