### ISSUE TITLE
preserving font.family in ftext/fp_text from the current style

### ISSUE THREAD

**Issue by john-harrold** [davidgohel/officer#260]
In this example I'm just changing the color of text using `ftext`. and when I create the paragraph using `body_add_fpar` the style I'm using ("Normal") uses the font Cambria.  Below I'm showing an image of what it looks like in Word. It appears that anytime I create a property using `fp_text` and I don't specify a font it will use Arial. Is there a way to have it just inherit or use the paragraph style font if no font is specified?

````
fpartext = fpar(
ftext("Formatted text can be created usin the ", prop=NULL),
ftext("fpar ", prop=officer::fp_text(color="green")),
ftext("command from the officer package", prop=NULL))

rpt =  body_add_fpar(rpt, value=fpartext, style="Normal")
````

What the output looks like in word for me:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/3170004/69901909-463c7c00-134d-11ea-8b1b-bf753795a1e5.png">

**Comment by davidgohel** [comment]
I agree this would be useful. Sorry, I don't have time for that now but let's keep that as a future improvement.

**Comment by john-harrold** [comment]
I completely understand. I do appreciate your consideration.

**Comment by davidgohel** [comment]
Hello,

I should have close that issue long time ago with https://github.com/davidgohel/officer/commit/a784c8989c2e0cd6b625a66be1d953b0dd1a75a1

```library(officer)
library(magrittr)


fpartext <- fpar(
  ftext("Formatted text can be created usin the ", prop = NULL),
  ftext("fpar ", prop = fp_text_lite(color = "green")),
  ftext("command from the officer package", prop = fp_text_lite(bold = TRUE))
)

read_docx() %>%
  body_add_fpar(value = fpartext) %>%
  print(target = "test.docx")
```

<img width="912" alt="Capture d’écran 2021-11-07 à 17 03 34" src="https://user-images.githubusercontent.com/4331618/140652502-e53b4465-c25c-4852-bf8c-83be7378b9f6.png">
