### ISSUE TITLE
Cannot output target plot using 'plot_instr()'

### ISSUE THREAD

**Issue by MingwuDuan** [davidgohel/officer#261]
Hi,
I use 'plot_instr()' to produce different plots, but I find only the first plot which the function 'ph_with()' adds exists in all slides of my exporting pptx.

>Fig1 <- plot_instr(code = { barplot(1:5, col = 2:6, main='Fig1') })
Fig2 <- plot_instr(code = { barplot(1:5, col = 2:6, main='Fig2') })
Fig3 <- plot_instr(code = { barplot(1:5, col = 2:6, main='Fig3') })
Fig4 <- plot_instr(code = { barplot(1:5, col = 2:6, main='Fig4') })
>
>myppt <- read_pptx()
myppt <- add_slide(myppt)
myppt <- ph_with(myppt, Fig3,  location = ph_location_fullsize(), pointsize = 12)
myppt <- add_slide(myppt)
myppt <- ph_with(myppt, Fig4,  location = ph_location_fullsize(), pointsize = 12)
print(myppt, target = "myppt.pptx")`

In myppt.pptx, both slides show "Fig3".

**Comment by davidgohel** [comment]
thanks for reporting this.

**Comment by davidgohel** [comment]
It should be solved now.
