### ISSUE TITLE
Unclear if possible to add a bullet list on a doc

### ISSUE THREAD

**Issue by stefanoborini** [davidgohel/officer#262]
It is unclear, and it seems that it's not possible at the moment, to add a bullet list to a doc file. If it's possible, the documentation does not report how. A google search came up inconclusive.

Is the feature supported? If not, this issue acts as a feature request.

**Comment by davidgohel** [comment]
This can be done by adding paragraphs with a style that has bullets.

[template.docx](https://github.com/davidgohel/officer/files/3922482/template.docx)

```
library(magrittr)

doc <- read_docx(path = "template.docx") %>%
  body_add_par("item 1", style = "bullet") %>%
  body_add_par("item 2", style = "bullet") %>%
  body_add_par("item 3", style = "bullet")

print(doc, target = "test.docx" )
```


<img width="250" alt="Capture d’écran 2019-12-04 à 16 03 09" src="https://user-images.githubusercontent.com/4331618/70153651-97cb6a80-16af-11ea-8e4f-622c7868611e.png">

**Comment by stefanoborini** [comment]
Uhh, thanks!

**Comment by davidgohel** [comment]
thanks for the recommandation

**Comment by stefanoborini** [comment]
For the record, this is apparently not working in 0.3.2

Warning: Error in : could not match any style named 'bullet' in c('Normal', 'heading 1', 'heading 2', 'heading 3', 'centered', 'graphic title', 'table title', 'toc 1', 'toc 2', 'Balloon Text')

**Comment by davidgohel** [comment]
What code did you used? 

In general, it helps to provide the elements described in the guidelines displayed when you open an issue (sessionInfo(), a reproducible example).

**Comment by davidgohel** [comment]
(I think you did not use the template attached in my answer)

**Comment by stefanoborini** [comment]
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.3

```
self$.doc <- officer::read_docx()            
p <- officer::body_add_par                                                        
p(self$.doc, "Input files provided", style = "heading 2")                         
p(self$.doc, "The following files were used to define the calculation:")          
p(self$.doc, paste("File: ", file$filename), style="bullet") 
```

**Comment by davidgohel** [comment]
so you did not used the template I attached

**Comment by stefanoborini** [comment]
Sorry I missed that.

**Comment by stefanoborini** [comment]
Excellent! thanks. sorry, too much to handle at the same time.
