### ISSUE TITLE
How can I add a block of text as verbatim quickly?

### ISSUE THREAD

**Issue by stefanoborini** [davidgohel/officer#263]
I am currently trying to add a consistent amount of generated text (on many, many lines) to a document (docx). I tried to add the text after passing it through paste() with collapse='\n', using a single paragraph and it works quickly, but the document contains no newlines, creating a single paragraph holding all the content in a single line.

I also tried with one paragraph per line, but it gets really, really slow and it takes an insane amount of time to generate anything, so much that I never actually run it to the end.

Is there a way to add a chunk of text as is, verbatim, to a document?

Sorry I am not willing to use stackoverflow because I don't like my questions to be either closed by random passer-by or ignored.

**Comment by cderv** [comment]
Hi @stefanoborini , can you provide a reproductible example of what you want to achieve ? 

I understand you want to generate text with R code and want this text to be a paragraph in docx, no R code output ? Am I right ? 

A small example of what you try, or an example of what you want would be great to work on  ? 
Thanks !

**Comment by stefanoborini** [comment]
@cderv 

This line creates a massive amount of text, with summary being a vector of strings.

report <- paste(capture.output({print(summary)}), collapse='\n')

if I use body_add_par(doc, report) I get a single paragraph with no enter. What I want is a verbatim section, in fixed size font, which can be achieved by a change of style, but it still won't have the individual lines each on a single line. The only option I thought of is to do a loop

for (line in capture.output({print(summary)}) {
   officer::body_add_par(doc, line)
}

which takes forever.

**Comment by john-harrold** [comment]
That print summary stuff didn't work for me, but this seems to demonstrate what you're talking about:
```
library("stringi")
library("officer")
library("ggplot2")

my_doc = read_docx() 


nps = seq(50, 800, 50)
add_times = c()

for(np in nps){
  cat(np, "\n")
  pgraphs = stri_rand_lipsum(np)
  
  ptm <- proc.time()
  for(pgraph in pgraphs){
    my_doc = officer::body_add_par(my_doc, pgraph)
  }
  
  print(my_doc, target = "tmp_par.docx")
  add_par_time  = proc.time() - ptm

  add_times = c(add_times, as.numeric(add_par_time[1]))
}

p = ggplot()
p = p +  geom_line(aes(x=nps, y=add_times/60))
p = p + geom_point(aes(x=nps, y=add_times/60))
p = p + ylab("Time in minues") + xlab("Number of Paragraphs")
ggsave("par_time.png")
```
The issue seems to be that the time to add paragraphs is nonlinear and it takes off after about 300 paragraphs:

![par_time](https://user-images.githubusercontent.com/3170004/70378666-fecb6800-18d7-11ea-9160-0375ff0485a2.png)

**Comment by stefanoborini** [comment]
@john-harrold That's exactly my point. I need to shove a large amount of text and if I do it trivially like that it will take me hours.

print(summary) doesn't matter. it's just a large vector of strings.

**Comment by john-harrold** [comment]
I was agreeing with you. This is of interest to some stuff I’m working on so I created the example above to better understand it. I posted the example here because @cderv asked for a working example and I thought it might add more information to what you’ve already provided.

**Comment by stefanoborini** [comment]
@john-harrold yes I suspect it's related to the size of the file. Probably there's a linear scan somewhere, or a temporary file is involved, and that will have a non-linear behavior.

**Comment by stefanoborini** [comment]
Related https://github.com/davidgohel/officer/issues/184

**Comment by davidgohel** [comment]
Dear all,

To answer the original question, there is no option to add a block of text as verbatim quickly.

On the discussion about performance, as written in the #184, I need few days to solve that and am unable to get these days of free time for now.

**Comment by stefanoborini** [comment]
Just for the record, when you have an issue and have no time to fix it, you should not close it. It's still an issue that needs to be solved.
