### ISSUE TITLE
Allow to specify rownames in body_add_table to add names for each row.

### ISSUE THREAD

**Issue by stefanoborini** [davidgohel/officer#264]
body_add_table should allow for the row names to be displayed as well. For example, shiny renderTable has a rownames logical to print the row names as well.

**Comment by davidgohel** [comment]
Dear Stefano,

Thanks for your suggestion. Unfortunately, it would introduce a complexity in the code I don't want to manage. 

To add row.names in the data.frame you want to render, you can use many R functions, the most popular solution is probably `tibble::rownames_to_column`.
