### ISSUE TITLE
PPT placeholder fill colour removed after writing ggplot

### ISSUE THREAD

**Issue by dustinlmharper** [davidgohel/officer#265]
If a fill colour is chosen for a placeholder in PPT, and then you try to write a ggplot to it using 'ph_location_label()', as shown below, the placeholder colour seems to be ignored.

ph_with(value = ggplot_1, location = ph_location_label("Content Placeholder 1"))

This becomes most apparent when the slide background colour is not white.  You can specify the ggplot panel background to match the slide, but the ggplot usually doesn't fit the placeholder perfectly.  After writing the plot to the placeholder, the white placeholder background appears, filling the space on the sides of the ggplot image.

Specifying the placeholder background colour works when you write text to the placeholder.  Any workarounds to get it to work for ggplots?

Everything else in this package and the flextable package has been really awesome.  Tons of flexibility.  Great work!

Thanks,
Dustin

**Comment by davidgohel** [comment]
Hi,

Current implementation does not handle these features but you are right, it should be implemented.

thanks for explaining the need, I will close the issue when issue will be fixed.

David

**Comment by davidgohel** [comment]
Thanks, it fixed now.
