### ISSUE TITLE
Line spacing in .pptx file

### ISSUE THREAD

**Issue by ddahora** [davidgohel/officer#266]
Hello,
How can I change the spacing between lines of text through officer function?
Thanks,
Diogo

**Comment by cderv** [comment]
I think this is the same as in this issue for docx https://github.com/davidgohel/officer/issues/235#issuecomment-522517946

You'll need to work on a custom template to change line spacing I think

**Comment by davidgohel** [comment]
Thanks @cderv 

Yes, this option is not implemented in `fp_par` and is not planned to be implemented. There are tons of properties in MS documents that will not be implemented. Those implemented are documented in `fp_text`, `fp_par`, `fp_cell`, `fp_border`. If a formatting option is not documented there, it means the option is not implemented. 

In these cases, it's easier to rely on on a custom template as Christophe wrote.
