### ISSUE TITLE
File cannot be downloaded from online documentation page.

### ISSUE THREAD

**Issue by niszet** [davidgohel/officer#267]
Hi, 

I tried to download sample docx files from officer online documentation page. But the links show "Page not found (404)". (For example, "first_example.docx". But maybe all files have "not found" link.)

https://davidgohel.github.io/officer/articles/offcran/word.html

Could you check and fix them?

Thanks,
Regards,
niszet

**Comment by davidgohel** [comment]
Thanks, this is fixed now
