### ISSUE TITLE
`ph_empty` or `ph_with` where `value = NULL`

### ISSUE THREAD

**Issue by jeffreyxparker** [davidgohel/officer#269]
**Feature Request:** It would be great to include the empty placeholder shapes in a presentation. This comes in handy when presentation graphics are updated through R, but a user still wants to write the takeaway statements in PowerPoint. It also closely matches the functionality of PowerPoint in PowerPoint. I think there are three routes:

1. When you `add_slide`, all the placeholder elements are included by default. Then in R, a users would need to remove them if they are unnecessary.
2. Update `ph_empty`. Right now if this is used, it PowerPoint throws a "Repair" error when opening the presentation.
3. Let `ph_with` accept `value = NULL` or something like that.

```
# Throws Error
my_pres <- read_pptx()
my_pres <- my_pres %>%
  add_slide(layout ="Title and Content", master = "Office Theme") %>%
  ph_empty(location = ph_location_label(ph_label = "Title 1"))
print(my_pres, target = "error.pptx")

# No Error
my_pres <- read_pptx()
my_pres <- my_pres %>%
  add_slide(layout ="Title and Content", master = "Office Theme") %>%
  ph_with(value = "Slide Title", location = ph_location_label(ph_label = "Title 1")) 
print(my_pres, target = "no_error.pptx")
```

**Comment by davidgohel** [comment]
Yes, 

That was almost ready. Thanks I was not aware of the issue with `ph_empty`.

I have implemented an object `empty_content` that can be used with `ph_with`. (ph_empty has also been fixed but is deprecated so it's better not to use it and use `ph_with(x, empty_content(), location = location)` instead.

**Comment by robertpdunn** [comment]
Is empty_content() a function in the updated version of officer?

**Comment by davidgohel** [comment]
@robertpdunn yes

I am planning to send it to CRAN soon
