### ISSUE TITLE
Writing Flextable to PDF

### ISSUE THREAD

**Issue by mbaqiraltaf** [davidgohel/officer#27]
Hi,

I want to export the flextable to PDF File, Do you have any idea how it can be done? I tried different ways but no success yet.

Thanks in advance

**Comment by davidgohel** [comment]
Hi

No. 

As written in the documentation (https://davidgohel.github.io/flextable): 

> Tables can be embedded within:
>
> R Markdown documents and Shiny web applications.
> Microsoft Word or PowerPoint documents.
