### ISSUE TITLE
Text Shadow in officer

### ISSUE THREAD

**Issue by ddahora** [davidgohel/officer#270]
Hi,
How can I add text shadow through officer functions?

**Comment by davidgohel** [comment]
Hi, 

You can achieve that with custom templates. If you are working with Word, use the specific style name you defined in the used template, if you are working with PowerPoint, use the specific shape you defined in the used template.

The documentation is explaining that in the first section for PowerPoint and Word

https://davidgohel.github.io/officer/index.html

KR
