### ISSUE TITLE
Get more information of styles 

### ISSUE THREAD

**Issue by TobiSonne** [davidgohel/officer#272]
Hi,

is it possible to get more information of styles in word documents?
```
my_doc <- read_docx()
head(styles_info(my_doc))
  style_type            style_id             style_name is_custom is_default
1   paragraph              Normal                 Normal     FALSE       TRUE
2   paragraph              Titre1              heading 1     FALSE      FALSE
3   paragraph              Titre2              heading 2     FALSE      FALSE
4   paragraph              Titre3              heading 3     FALSE      FALSE
5   character      Policepardfaut Default Paragraph Font     FALSE       TRUE
6       table       TableauNormal           Normal Table     FALSE       TRUE
7   numbering         Aucuneliste                No List     FALSE       TRUE
```

Is there a way to get the font family like Arial or the font size of a specific style like "heading 1"? 
Would be really important for me!

Thank you very much!

**Comment by davidgohel** [comment]
This question is cross posted here: https://stackoverflow.com/questions/59719956/how-to-get-formatting-of-styles-in-word-document-in-officer

**Comment by davidgohel** [comment]
Hi

No, that's not possible with officer right now - this is feature I'd like to bring but available time does not allow that it now.
