### ISSUE TITLE
Namespace load failed

### ISSUE THREAD

**Issue by ponnet** [davidgohel/officer#276]
### Trying to make download PPTX from R Shiny (Studio Server Pro): 

Library is loaded fine on the locally but not on the server:

> Warning: Error in : package or namespace load failed for 'officer' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
>  namespace 'zip' 2.0.1 is being loaded, but >= 2.0.3 is required
> 

Some info:

> platform       x86_64-redhat-linux-gnu     
> arch           x86_64                      
> os             linux-gnu                   
> system         x86_64, linux-gnu           
> status                                     
> major          3                           
> minor          5.1                         
> year           2018                        
> month          07                          
> day            02                          
> svn rev        74947                       
> language       R                           
> version.string R version 3.5.1 (2018-07-02)
> nickname       Feather Spray   
>

**Comment by ponnet** [comment]
I think it might be b/c server uses 'zip' version that is much earlier - need to make 'officer' use the version it installed along...

**Comment by davidgohel** [comment]
That annoying but I am not able to change this minimal version of zip.

Why can't you update zip? You will always be able to create specific libraries and use them on the same machine. You can also use tools such as packrat, renv, miniCRAN.

Change was there:

https://github.com/davidgohel/officer/commit/d8ceacc5b7303f391e61a7e11caa44178aa462ea#diff-35ba4a2677442e210c23a00a5601aba3

The previous officer version was 0.3.5, it can be downloaded here: https://cran.r-project.org/src/contrib/Archive/officer

So, you have 3 options (at least those I am thinking about): 

- you can use officer 0.3.5 (simplest solution) 
- add workaround in the code (from the link above you should have enough to make it work with your zip version) 
- install all dependencies in a dedicated library.
