### ISSUE TITLE
Combine PPTX documents

### ISSUE THREAD

**Issue by danwwilson** [davidgohel/officer#278]
I don't believe this feature exists yet, however I'm wondering if it would be possible to add a feature that allows two pptx documents to be combined.

The assumption would be that if they have different templates/styles, the first document would take precedence for formatting.

``` r
library(officer)
library(magrittr)

doc <- read_pptx() %>% 
  add_slide(layout = "Title Slide") %>% 
  ph_with("My PPTX Title", location = ph_location_type(type="title")) %>% 
  add_slide() %>% 
  ph_with("Slide 2", location = ph_location_type(type="title")) %>% 

doc2 <- read_pptx() %>% 
  add_slide() %>% 
  ph_with("Slide 3", location = ph_location_type(type="title")) %>% 
  add_slide() %>% 
  ph_with("Slide 4", location = ph_location_type(type="title")) %>% 

final_doc <- append_pptx(doc, doc2)
```

**Comment by davidgohel** [comment]
I am afraid this is not possible with officer at the moment. The slides would have to be copied and renamed but also charts, datasets, and many other folders that are not managed by officer. 

If you are running on Windows, maybe the best solution would be to do it via a VBA macro.

If your need is to mix different styles, you still can have several master layouts in the same slide.

**Comment by gacolitti** [comment]
I am scouring the internet trying to figure out how to programmatically combine two separate powerpoint files/slides. Seems like it should be easy.

In my particular use case, I have a Shiny app that generates slides using a master template that lives in the app. But I want to allow users to upload their own powerpoint files to be combined with slides generated in the app. Any suggestions would be much appreciated.
