### ISSUE TITLE
Change page dimensions and landscape-mode in document

### ISSUE THREAD

**Issue by TobiSonne** [davidgohel/officer#279]
I have a word file with many styles. It is in portrait but sometimes I want the same styles but I want the resulting file to be landscape. Yes, I know that I can copy the file and change this file to landscape. This is what I do so far. But this way doesn't seem to be the smartest solution to me. Now I've seen that you can see what the dimension of the document is and then I thought I can change them. I've done that but when I save this document it has no effect. The document is printed as it was before changing the dimensions.

```
> Document <- read_docx(Style.Document) # this is the path to the landscape document
> Document$sect_dim$page
 width height 
 11906  16838 
> Document$sect_dim$landscape
[1] TRUE
> Document$sect_dim$landscape <- FALSE
> Document$sect_dim
$page
 width height 
 11906  16838 

$landscape
[1] FALSE

$margins
   top bottom   left  right header footer 
  1418   1418   1701   1701    709    709 

> print(Document, target = "example.docx")
```

Is there a way to achieve what I want (in `R`)?
Thank you very much!

**Comment by davidgohel** [comment]
Hi,

You are accessing internal informations but they are not supposed to be changed by users. 

You need to use section: https://davidgohel.github.io/officer/articles/offcran/word.html#sections

I am working on documentation these days and will try to make documentation clearer also on that part :)


I am trying to improve the documentation these days and will

**Comment by davidgohel** [comment]
Below an example:

```
library(magrittr)
library(officer)

str1 <- "Lorem ipsum dolor sit amet, consectetur adipiscing elit. " %>%
  rep(5) %>% paste(collapse = "")
str2 <- "Aenean venenatis varius elit et fermentum vivamus vehicula. " %>%
  rep(5) %>% paste(collapse = "")

my_doc <- read_docx()  %>%
  body_add_par(value = "Default section", style = "heading 1") %>%
  body_add_par(value = str1, style = "centered") %>%
  body_add_par(value = str2, style = "centered") %>%
  
  body_end_section_continuous() %>%
  body_add_par(value = "Landscape section", style = "heading 1") %>%
  body_add_par(value = str1, style = "centered") %>%
  body_add_par(value = str2, style = "centered") %>%
  body_end_section_landscape() %>%
  
print(my_doc, target = tempfile(fileext = ".docx"))
```
