### ISSUE TITLE
body_add_gg() does not insert the plot correctly

### ISSUE THREAD

**Issue by Physikuss** [davidgohel/officer#280]
It turned out that `body_add_gg()` does not insert the image correctly in a new paragraph. 
I can reproduce it on the first page, where the plot appears in the paragraph just before the image.
On the second page this, for some reason, leads to the fact, that the image is inserted at the bottom. This behavior occurs after a page break `body_add_break()`.

Here is my example:
```R
library(officer)
library(stringi)            
library(ggplot2)
library(flextable)
library(magrittr)

df <- data.frame(x = seq(-2,2,by = 0.25), 
                 y = round(seq(-2,2,by = 0.25)^2,2))
read_docx() %>%
  body_remove() %>%
  body_add_par(stri_rand_lipsum(1)) %>%
  body_add_par(" ") %>%
  body_add_par(" ") %>%
  body_add_gg(
    ggplot(data = df, aes(x,y)) +
      geom_line()
  ) %>%
  body_add_par(" ") %>%
  body_add_flextable(flextable(as.data.frame(t(df)), cwidth = 0.4) %>% 
                       fontsize(size = 8, part = "all"), 
                     align = "left") %>%
  body_add_break() %>%
  body_add_par(stri_rand_lipsum(1)) %>%
  body_add_gg(
    ggplot(data = df, aes(x,y)) +
      geom_line()
  ) %>%
  body_add_par(" ") %>%
  body_add_flextable(flextable(as.data.frame(t(df)), cwidth = 0.4) %>% 
                       fontsize(size = 8, part = "all"), 
                     align = "left") %>%
  print(target = "test.docx")
```

**Comment by davidgohel** [comment]
Thanks, I can reproduce. I will fix it soon.

**Comment by davidgohel** [comment]
Could you try with the latest github version?

**Comment by Physikuss** [comment]
Hi, thanks for you quick response. 
It seems to work now, however, the empty paragraphs on the first page (2 times `body_add_par(" ")`) are not inserted consistently. Only one of them appears in the document. 
As far as I understand, every `body_add*` as a top container should generate a new paragraph.

**Comment by davidgohel** [comment]
OK,

I will work on that this week and resubmit to cran asap.

I worked on performances for Word and probably introduced issues. I will reverse the latest modification

**Comment by davidgohel** [comment]
It should be OK now. Could you test with latest github version? If ok, I will push to CRAN
