### ISSUE TITLE
Inserting a Line break using "body_replace_all_text()"

### ISSUE THREAD

**Issue by DragonflyStats** [davidgohel/officer#281]
Hi David
Thank you for officer. It is great for my work.

I have a query - I am trying to replace a bit of placeholder text inside a MS word table ( lets call it ""Info_Target") with replacement text that is best presented over multiple lines.

Suppose I want this to be the outcome
<pre><code>
Text_Piece_1
Text_Piece_2
</code></pre>

What I have in mind is to paste them together, seperated by the "newline" operator.
<pre><code>
Text_to_insert <- paste( "Text_Piece_1", "Text_Piece_2", sep ="\n")
</code></pre>

Then I would use ``body_replace_all_text()`` to change the text.

<pre><code>
my_doc %>% body_replace_all_text(   "Info_Target",   Text_to_insert,   only_at_cursor = FALSE)
</code></pre>

I have a feeling that ``sep="\n"`` is the wrong choice here, but I am not familiar with that stuff.

**Comment by davidgohel** [comment]
Hi, 

Sorry, the function do not enable to replace a string by another string with a soft return inside (right now, but with recent updates, it could be possible later).
