### ISSUE TITLE
why-does-slip-in-text-from-officer-seems-to-produce-unexpected-hyperlinks

### ISSUE THREAD

**Issue by TomGeens** [davidgohel/officer#282]
Hi David,
I posted a [question on stackoverflow](https://stackoverflow.com/questions/60530657/why-does-slip-in-text-from-officer-seems-to-produce-unexpected-hyperlinks-in-cer) for this problem before I realized this might be a bug.
Many thanks for having a look.
Tom.

### Bug Report
- [x] The code that is producing the error: [reprex.txt](https://github.com/davidgohel/officer/files/4321402/reprex.txt)
- [x] the results of R command `sessionInfo()`: [sessioninfo.txt](https://github.com/davidgohel/officer/files/4321404/sessioninfo.txt)
- [x] Check I had the latest version: yes, same issue in 0.3.6 as 0.3.7
- [x] Searched in the *open* and *closed* issues on the github repository: yes, did not see this
- [x] Output docx: [temp.docx](https://github.com/davidgohel/officer/files/4321405/temp.docx)

### Questions related to the bug: why does
- the slip_in_text in the advices() function show the correct hyperlink?
- the slip_in_text in the advices_function() called in advices() throws the yahoo link from the list on google.be?
- the document contains irreadable contents when the advices_function() is called multiple times?
- the last paragraph added through the advices_function() does not contain a single hyperlink?

**Comment by davidgohel** [comment]
Ah ok, thanks

It's a quite complex script - I really don't like slip_in_text. It's not efficient and make people write complex code. I will try to provide a simpler alternative and will let you know when ready

**Comment by davidgohel** [comment]
I have implemented a new function that works within `fpar`. A simple example where word "cran" is associated with an hyperlink:

```
library(magrittr)
library(officer)

my_face <- fp_text(bold = TRUE, font.size = 12, color = "gray")

mypar <- fpar(
  ftext("Hello ", prop = my_face), 
  hyperlink_ftext(
    text = "cran", 
    href = "https://cran.r-project.org/index.html", 
    prop = my_face))

read_docx() %>% 
  body_add_fpar(mypar) %>% 
  print(target = "test.docx")
```

<img width="993" alt="Capture d’écran 2021-01-03 à 21 11 15" src="https://user-images.githubusercontent.com/4331618/103487820-69671400-4e08-11eb-9127-cf6b8bceacfd.png">

**Comment by davidgohel** [comment]
Functions `slip_in_*` should now be avoided and will be deprecated in a future version. They all can be replaced with `fpar` that provides more functions and that is easier to use: https://ardata-fr.github.io/officeverse/paragraphs-chunks.html#fpar

**Comment by davidgohel** [comment]
@TomGeens let me know if you need more information or if you have questions

**Comment by TomGeens** [comment]
@davidgohel many thanks for this nice 2021 new year's gift :-) 
I'll test this new functionality, eliminate the use of slip_in_text, and get back in touch with you in the case there would be some remaining questions.

**Comment by davidgohel** [comment]
:) thanks and sorry for the delay.
