### ISSUE TITLE
Cannot use any style in body_add_img

### ISSUE THREAD

**Issue by LukaszDerylo** [davidgohel/officer#283]
Just like in title: no matter which style I use in `body_add_img` I always get image inserted with Normal style.

Toy example:

```
png('001.png')
plot(rnorm(100))
dev.off()

read_docx() %>%  
  body_add_img('001.png', style='centered', width=5, height=5) %>% 
print("report.docx" ) 
```

**Comment by davidgohel** [comment]
I messed things with the new `body_add` method, it should be soon solved - sorry for that

**Comment by LukaszDerylo** [comment]
Thanks! It works again :)
