### ISSUE TITLE
Problem adding objects to powerpoint slides when using manually created objects in template

### ISSUE THREAD

**Issue by sebaschur** [davidgohel/officer#284]
Hi, I'm having this problem. I'm working on a template to build automatic reports. The idea is to read data from an excel file, and automatically create the report on a powerpoint using the predefined template with your fantastic officer package.

Since the report has some quite design that doesn't fit on the predefined layouts automatically created by Powerpoint, we are creating the layout for each slide from scratch. We only need to add graphics and text on specific places, so the text of the titles or other texts that don't need to be changed go directly to the layout inside the template.

We then generate the slides using each specific layout.

The problem I found is this: when using a layout that has placeholders that were created using a layout an original Powerpoint slide-master (and then modifying for example the size and position of the placeholders) everything works fine.

But if I replicate the same design using placeholders manually created by me using the "Insert placeholder" tool inside the Slide-Master editor, then sometimes the added contents just don't show. The even stranger thing is that the objects are there. If you open the slide and change it's layout from inside Powerpoint, they appear, although in wrong places and sizes.

I solved the issue by re-creating the layouts using a pre-defined one and then editing it without adding or deleting the placeholders, but it would be great to know what I'm doing wrong, or if it's a bug, to solve it.

I'm attaching the template and here I copy the script to test it:

```
library(officer)
library(ggplot2)

graph1=ggplot(
  data.frame(
    group=c("A1","A2","A3"),
    value=c(30,20,50)
  ),
  aes(x=2,y=value,fill=group)) +
  geom_bar(stat="identity", width=1, color="white",size=1.5) +
  coord_polar("y", start=-0.5) + 
  theme_void() + 
  theme(legend.position="none") +
  geom_text(aes(label = paste(value,"%"),x=2),
            position=position_stack(vjust=0.5), color = "black", size=4) +
  geom_text(aes(label = group, x=3.2),
            position=position_stack(vjust=0.5), color = "black", size=3.5) +
  scale_fill_brewer(palette="Set1")+
  xlim(0.8,3.3)

graph2=ggplot(
  data.frame(
    group=c("B1","B2","B3","B4"),
    value=c(10,30,25,35)
  ),
  aes(x=2,y=value,fill=group)) +
  geom_bar(stat="identity", width=1, color="white",size=1.5) +
  coord_polar("y", start=-0.5) + 
  theme_void() + 
  theme(legend.position="none") +
  geom_text(aes(label = paste(value,"%"),x=2),
            position=position_stack(vjust=0.5), color = "black", size=4) +
  geom_text(aes(label = group,x=3.2),
            position=position_stack(vjust=0.5), color = "black", size=3.5) +
  scale_fill_brewer(palette="Set1")+
  xlim(0.8,3.3)

text1="Text describing graph1"
text2="Text describing graph2"

pres=read_pptx("my_template.pptx")

pres<-on_slide(pres,1)
pres<-ph_with(pres,value=graph1,location=ph_location_type("body",id=1))
pres<-ph_with(pres,value=graph2,location=ph_location_type("body",id=2))
pres<-ph_add_text(pres,text1,type="body",id=3)
pres<-ph_add_text(pres,text2,type="body",id=4)

pres<-on_slide(pres,2)
pres<-ph_with(pres,value=graph1,location=ph_location_type("body",id=1))
pres<-ph_with(pres,value=graph2,location=ph_location_type("body",id=2))
pres<-ph_add_text(pres,text1,type="body",id=3)
pres<-ph_add_text(pres,text2,type="body",id=4)

print(pres,target = "my_slides.pptx")
```

Please let me know if you need more info.

PS: I'm from Argentina, you may notice that some of the labels of the objects in the slides and layouts are in spanish since I work with the spanish version of Office, I don't know if that may be related to the problem...
[my_template.pptx](https://github.com/davidgohel/officer/files/4331462/my_template.pptx)

**Comment by davidgohel** [comment]
Hello, 

The process should be as follows. Create the desired arrangement in the "slide mask" mode - it can contain several shapes, formatting, etc. Each shape has a set of coordinates and an associated label. There is no need to also create the slides with these blank-filled shapes and then fill them in. The tool allows you to create slides from the slides defined in the slide template. The `ph_with` function adds content but does not replace the content of an existing shape in a slide. 

I updated your template. You can get it there: 
[my_template2.pptx](https://github.com/davidgohel/officer/files/4332845/my_template2.pptx)

Note I have deleted existing slides. Note also, I gave unique names to placeholders defined in the laout master:

<img width="1600" alt="Capture d’écran 2020-03-14 à 15 00 47" src="https://user-images.githubusercontent.com/4331618/76683486-b45b3500-6604-11ea-8858-61e1cbf06e16.png">


``` r
library(officer)
library(ggplot2)

graph1 <- ggplot(
  data.frame(
    group = c("A1", "A2", "A3"),
    value = c(30, 20, 50)
  ),
  aes(x = 2, y = value, fill = group)
) +
  geom_bar(stat = "identity", width = 1, color = "white", size = 1.5) +
  coord_polar("y", start = -0.5) +
  theme_void() +
  theme(legend.position = "none") +
  geom_text(aes(label = paste(value, "%"), x = 2),
    position = position_stack(vjust = 0.5), color = "black", size = 4
  ) +
  geom_text(aes(label = group, x = 3.2),
    position = position_stack(vjust = 0.5), color = "black", size = 3.5
  ) +
  scale_fill_brewer(palette = "Set1") +
  xlim(0.8, 3.3)

graph2 <- ggplot(
  data.frame(
    group = c("B1", "B2", "B3", "B4"),
    value = c(10, 30, 25, 35)
  ),
  aes(x = 2, y = value, fill = group)
) +
  geom_bar(stat = "identity", width = 1, color = "white", size = 1.5) +
  coord_polar("y", start = -0.5) +
  theme_void() +
  theme(legend.position = "none") +
  geom_text(aes(label = paste(value, "%"), x = 2),
    position = position_stack(vjust = 0.5), color = "black", size = 4
  ) +
  geom_text(aes(label = group, x = 3.2),
    position = position_stack(vjust = 0.5), color = "black", size = 3.5
  ) +
  scale_fill_brewer(palette = "Set1") +
  xlim(0.8, 3.3)

text1 <- "Text describing graph1"
text2 <- "Text describing graph2"

pres <- read_pptx("~/Downloads/my_template2.pptx")

layout_summary(pres)
#>                 layout      master
#> 1              layout1 my_template
#> 2 Diseño personalizado my_template

layout_properties(pres, layout = "layout1", master = "my_template")
#>   master_name    name type id                ph_label
#> 1 my_template layout1 body  3 Marcador de contenido 1
#> 2 my_template layout1 body 15 Marcador de contenido 2
#> 3 my_template layout1 body  9               object 28
#> 4 my_template layout1 body 12               object 51
#> 5 my_template layout1 body 13               object 52
#> 6 my_template layout1 body 14               object 57
#> 7 my_template layout1 body 16     Marcador de texto 1
#> 8 my_template layout1 body 17     Marcador de texto 2
#>                                          ph      offx     offy        cx
#> 1             <p:ph sz="quarter" idx="17"/> 0.5052089 3.598245  2.852430
#> 2             <p:ph sz="quarter" idx="18"/> 4.1442695 3.598245  2.852430
#> 3                                      <NA> 0.4993001 1.434830 10.412293
#> 4                                      <NA> 0.5059208 3.097130  2.852449
#> 5                                      <NA> 4.1888189 3.063811  2.814825
#> 6                                      <NA> 8.1797999 3.128811  2.974446
#> 7 <p:ph type="body" sz="quarter" idx="13"/> 0.4982644 6.738403  2.859374
#> 8 <p:ph type="body" sz="quarter" idx="14"/> 4.1442695 6.738403  2.859374
#>          cy
#> 1 2.8958333
#> 2 2.8958333
#> 3 1.2114381
#> 4 0.3085400
#> 5 0.3225645
#> 6 3.2754276
#> 7 1.0409799
#> 8 1.0409799

pres <- add_slide(pres, layout = "layout1", master = "my_template")
pres <- ph_with(pres, value = graph1, location = ph_location_label(ph_label = "Marcador de contenido 1"))
pres <- ph_with(pres, value = graph2, location = ph_location_label(ph_label = "Marcador de contenido 2"))
pres <- ph_with(pres, value = text1, location = ph_location_label(ph_label = "Marcador de texto 1"))
pres <- ph_with(pres, value = text2, location = ph_location_label(ph_label = "Marcador de texto 2"))


layout_properties(pres, layout = "Diseño personalizado", master = "my_template")
#>    master_name                 name type id                ph_label
#> 9  my_template Diseño personalizado body 13               object 28
#> 10 my_template Diseño personalizado body 14               object 51
#> 11 my_template Diseño personalizado body 15               object 52
#> 12 my_template Diseño personalizado body 16               object 57
#> 13 my_template Diseño personalizado body 17     Marcador de texto 1
#> 14 my_template Diseño personalizado body 18     Marcador de texto 2
#> 15 my_template Diseño personalizado body  3 Marcador de contenido 1
#> 16 my_template Diseño personalizado body 19 Marcador de contenido 2
#>                                           ph      offx     offy        cx
#> 9                                       <NA> 0.4993001 1.434830 10.412293
#> 10                                      <NA> 0.5059208 3.097130  2.852449
#> 11                                      <NA> 4.1888189 3.063811  2.814825
#> 12                                      <NA> 8.1797999 3.128811  2.974446
#> 13 <p:ph type="body" sz="quarter" idx="13"/> 0.4982644 6.738403  2.859374
#> 14 <p:ph type="body" sz="quarter" idx="14"/> 4.1442695 6.738403  2.859374
#> 15             <p:ph sz="quarter" idx="15"/> 0.4982633 3.574653  2.878472
#> 16             <p:ph sz="quarter" idx="16"/> 4.1233290 3.574653  2.878472
#>           cy
#> 9  0.6057196
#> 10 0.3085400
#> 11 0.3225645
#> 12 3.2754276
#> 13 1.0409799
#> 14 1.0409799
#> 15 2.9548611
#> 16 2.9548611

pres <- add_slide(pres, layout = "Diseño personalizado", master = "my_template")
pres <- ph_with(pres, value = graph1, location = ph_location_label(ph_label = "Marcador de contenido 1"))
pres <- ph_with(pres, value = graph2, location = ph_location_label(ph_label = "Marcador de contenido 2"))
pres <- ph_with(pres, value = text1, location = ph_location_label(ph_label = "Marcador de texto 1"))
pres <- ph_with(pres, value = text2, location = ph_location_label(ph_label = "Marcador de texto 2"))




print(pres, target = "my_slides.pptx")
```

The script is populating an empty presentation with two new slides and reuse your templates.

<img width="1014" alt="Capture d’écran 2020-03-14 à 15 17 16" src="https://user-images.githubusercontent.com/4331618/76683772-f7b6a300-6606-11ea-9e83-68192d11ac94.png">


----

In your code, we see 2 types of statements. The call to `ph_with` will add a new form with content in the slide. The call to `ph_add_text` will add text to an existing form in the slide. That's why on your slide both graphics are added on top of an existing form. This is difficult to see because the shapes are superimposed. 

<img width="1150" alt="Capture d’écran 2020-03-14 à 12 37 01" src="https://user-images.githubusercontent.com/4331618/76683515-f08e9580-6604-11ea-8aa5-085e27b349ae.png">

I don't think `ph_add_text` is necessary. Again, `ph_with` is creating a new shape based on the template. `ph_add_text` add some text to an existing shape in the slide.



> But if I replicate the same design using placeholders manually created by me using the "Insert placeholder" tool inside the Slide-Master editor, then sometimes the added contents just don't show. The even stranger thing is that the objects are there. If you open the slide and change it's layout from inside Powerpoint, they appear, although in wrong places and sizes.


I am unable to explain that. This not what I see with your example (right? or maybe I am missing something). Could you provide a specific reprex for that case?

**Comment by davidgohel** [comment]
Hi, I will reopen if necessary. for now I am closing as I don't think there is any bug there

**Comment by sebaschur** [comment]
Hi David, thanks. Sorry I didn't answer before, it's been crazy this last couple days. Didn't have time to try it out again, whenever I can I will get back to you on this if necessary.
Thanks again!

**Comment by davidgohel** [comment]
@sebaschur no problem, same situation here :)
