### ISSUE TITLE
Document gdrive and libre office known issues

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/officer#286]

**Comment by davidgohel** [comment]
Compatibility with LibreOffice and google docs is not tested. 

To my knowledge there are no problems but some Linux users have reported problems that could not be reproduced with LibreOffice:

* table cell merging issues (merge does not happen)

**Comment by rishi-gupta-md** [comment]
Hi

I have often noticed the following problems:

1) Large documents appear blank when opened in gdrive/gmail.
2) Images become completely blurry if copied to a new document.

I am not why this occurs.

Regards

**Comment by davidgohel** [comment]
Libreoffice does not manage Word sections

**Comment by TJReece** [comment]
Images added to a word document look fine in Word, but when opened in gdrive the size of the image is minuscule. For example, I have an image that shows up in Word as 2x6, but was resized to 0.03x0.08 when opened in google docs.
My stopgap solution has been to add the image with huge dimensions:
`body_add_img(doc, "f6.jpeg", height = 145, width = 433)`
This results in an image in google docs of 2 inches high and 6 inches wide. Of course, this makes the original Word file impractical to use.
