### ISSUE TITLE
body_add_toc works in version  0.3.6 in r 3.5.3 but not in 0.3.8 in R 3.6.3

### ISSUE THREAD

**Issue by jciconsult** [davidgohel/officer#290]
I have a number of production scripts.  The attached script works fine in both versions (0.3.6 and 0.3.8) with the exception that no TOC is produced in the later version
zip contains both generated docx and the script
[Uploading toc_issue.zip…]

**Comment by davidgohel** [comment]
Please follow the guidelines

At least `sessionInfo()` and a reprex

<img width="753" alt="Capture d’écran 2020-03-25 à 18 26 37" src="https://user-images.githubusercontent.com/4331618/77566636-3d585300-6ec6-11ea-9f51-b78b019362c9.png">
