### ISSUE TITLE
Reproducible example - toc works in 0.3.6 not in0.3.8

### ISSUE THREAD

**Issue by jciconsult** [davidgohel/officer#291]
The attached zip file contains all inputs for a test using 0.3.6 and 0.3.8.  The toc is generated only in0.3.6
sessioninfo is included in the scripts and the log files.
[Uploading officer_test.zip…]

**Comment by davidgohel** [comment]
Sorry, your zip file is not in the thread. Can you use this form to put your code and your `sessionInfo()` result (as required by the guidelines).

I can only see 

> [Uploading officer_test.zip…]

**Comment by jciconsult** [comment]
Here is a view link to the zip file which contains a session info and full tests.
https://1drv.ms/u/s!AvshLJjIqXW7gotdryqaVCFqxZyqLA?e=XWAC0J
Lots with sessions are below and code
[log_for_036.pdf](https://github.com/davidgohel/officer/files/4451292/log_for_036.pdf)
[log_for_038.pdf](https://github.com/davidgohel/officer/files/4451293/log_for_038.pdf)

#lfs plot dump
#this code will pick the source directory if possible
src_directory<-getSrcDirectory(function(x) {x})
print(src_directory)
if(src_directory !=""){
	setwd(src_directory)
	project_folder<-paste0(src_directory,"\\")
}
if(src_directory == ""|grepl("uments",getwd(),fixed=TRUE)){
	# setwd("D:\\OneDrive\\lfs_stuff")
	setwd("D:\\ops\\officer_test")
	
	# setwd("C:\\Users\\jciconsult\\SkyDrive\\lfs_stuff")
	project_folder<-paste0(getwd(),"\\")
	cat("setting project folder to",project_folder,"\n")
}
# library(tidyverse)
library(flextable)
library(lubridate)
library(openxlsx)
library(officer)
sessionInfo()
#define a function for lists
body_add_list<-function(this_doc,this_list){
	if(length(this_list)>0){
		for(this_item in this_list){
			this_doc<-body_add_par(this_doc,this_item,style="Bulleted List")
		}
	}
	body_add_list<-this_doc
}
edition_string<-Sys.Date()
doc_title<-paste0("JCI Chart Report -",edition_string)
mydoc<-read_docx(path=paste0(project_folder,"chart_template.docx"))
mydoc<-set_doc_properties(mydoc,title=doc_title,creator="Jacobson Consulting Inc.",
description="JCI report - not for circulation")
styles_info(mydoc)
mydoc<-body_remove(mydoc)
chart_heading<-paste("Labour Force Survey Test Charts - ",Sys.Date())
mydoc<-body_add_par(x=mydoc,chart_heading,style="Title")
mydoc<-body_add_break(mydoc)
mydoc<-body_add_toc(mydoc)
mydoc<-body_add_break(mydoc)
control_table<-read.xlsx("PNG_list_working_test.xlsx")
numb_tables<-nrow(control_table)
chart_scale<-.85
for(this_table in seq_along(control_table[,1])){
	input_png<-control_table$File_Name[this_table]
	title_left<-control_table$Title.Part[this_table]
	title_province<-control_table$Province[this_table]
	chart_height<-control_table$Height[this_table]
	chart_width<-control_table$Width[this_table]
	cat("doing",title_left,title_province,"\n")
	mydoc<-body_add_par(mydoc,paste0(title_left," - ",title_province),style="heading 2")
	mydoc<-body_add_img(mydoc,src=input_png,width=chart_scale*chart_width,
	height=chart_scale*chart_height)

	

}
print(mydoc,target=paste0("JCI_LFS_chart_3-3-6_",Sys.Date(),".docx"))

**Comment by davidgohel** [comment]
Sorry but:

* This is not a minimal reproducible example
* I don't want to use a hotmail account to read an attachment posted by an anonymous person

This is actually a code using `body_add_toc`. 


```
library(magrittr)
library(officer)
doc <- read_docx() %>% 
  body_add_par("title 1", style = "heading 1") %>% 
  body_add_par("title 1.2", style = "heading 2") %>% 
  body_add_toc()

print(doc, target = tempfile(fileext = ".docx") )
```

And this produces (after hitting F9 to refresh the TOC):

<img width="690" alt="Capture d’écran 2020-04-08 à 17 24 44" src="https://user-images.githubusercontent.com/4331618/78802220-dd7da400-79bd-11ea-9b4f-ec2a8bfbe0a5.png">

- Can you explain me your issue? 
- If you need to show me some code, make sure to make it short and put it in this form by typing:


    ```
    # Your R code
    ```

**Comment by davidgohel** [comment]
I will reopen if necessary
