### ISSUE TITLE
[0.3.8] Embedded files in initial Word document are lost when they are read and printed

### ISSUE THREAD

**Issue by juanmacarrillo** [davidgohel/officer#294]
When the initial Word document has some kind of embedded file ([test_PRE_officer.docx](https://github.com/davidgohel/officer/files/4481284/test_PRE_officer.docx)), when the document is read and printed as:

```
library(officer)
doc_test <- read_docx("test_PRE_officer.docx")
print(doc_test, target = "test_POST_officer.docx")
```
The file "[test_POST_officer.docx](https://github.com/davidgohel/officer/files/4481287/test_POST_officer.docx)" has lost the link to the embedded file.

The embedded file still inside it (```unzip -l test_POST_officer.docx```), but the icon on the document is an image not linked to the embedded file.

**Comment by davidgohel** [comment]
Hi, are you using MS Word to view the document? I have this: 

<img width="650" alt="Capture d’écran 2020-04-15 à 15 23 32" src="https://user-images.githubusercontent.com/4331618/79342201-2210be80-7f2d-11ea-9acc-f3b2d2369635.png">

**Comment by juanmacarrillo** [comment]
Yes, using MS Word to open the docx files.
Both documents are similar in appearance, but when you double-click on the icon of the PRE_officer file, an Excel spreadsheet will open; if you double-click on the same icon of the POST_officer file, nothing will happen, the link was broken.

**Comment by davidgohel** [comment]
Sorry, I did not check that, will try to fix that soon

**Comment by davidgohel** [comment]
It's OK now, thanks for reporting this
