### ISSUE TITLE
convert SVG to PowerPoint vectorgraphic

### ISSUE THREAD

**Issue by ckluss** [davidgohel/officer#295]
Hi

thanks for the great package! I like to plot a Graphviz Graph as PowerPoint Vector Grafic. Is there a trick to automatic import a SVG-File in PowerPoint? I could convert SVG as EMF, but there might be an easier way in officer?

Best wishes
Christof

```
library(DiagrammeR)
library(DiagrammeRsvg)
library(rsvg)
library(tidyverse)
library(officer)
library(rvg)


graph <- export_svg(grViz('digraph{a->b; c->a; c->b; c->d;}')) %>% 
  charToRaw %>% rsvg_svg("graph.svg")

read_pptx()  %>% 
  add_slide() %>% 
  ph_with( external_img("graph.svg"),
           location=ph_location_type(type="body")) %>%
  print(target = "graph.pptx")

```

**Comment by davidgohel** [comment]
Hi

No sorry, I am not aware of a way to do it
