### ISSUE TITLE
`change_styles` only handles paragraph styles, but does not check for paragraph styles

### ISSUE THREAD

**Issue by jarauh** [davidgohel/officer#298]
This is part bug and part feature request.

**Feature request:** It would be great if `change_styles` could handle all kind of word styles (character styles, paragraph styles, linked, list, but also table styles). Obviously, it would be nice to check whether the replacement makes sense - it does not make sense to replace a table style by a paragraph style, etc.

The **bug** is: (1) The documentation does not explain which kind of styles `change_styles` can handle. (2) The function does check that the style names in its arguments do exist, albeit without checking the style type.  However, when constructing the mapping, only paragraph styles are considered.  This may lead to weird error messages () when one of the supplied styles is a paragraph style and the other isn't:

> Fehler in data.frame(from = id_from, to = rep(id_to, length(from)), stringsAsFactors = FALSE) : 
>  arguments imply differing number of rows: 1, 0
> Ruft auf: <Anonymous> ... change_styles -> mapply -> <Anonymous> -> data.frame

When submitting a new issue:

- [ ] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [X] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example.

> sessionInfo() R version 3.6.3 (2020-02-29) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows Server x64 (build 14393)  Matrix products: default  locale: [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 [4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       loaded via a namespace (and not attached):  [1] bookdown_0.18        Rcpp_1.0.4.6         digest_0.6.25        R6_2.4.1             magrittr_1.5          [6] officedown_0.0.6.018 evaluate_0.14        highr_0.8            zip_2.0.4            gdtools_0.2.2        [11] rlang_0.4.5          uuid_0.1-4           xml2_1.3.1           rmarkdown_2.1        tools_3.6.3          [16] officer_0.3.9        xfun_0.13            yaml_2.2.1           compiler_3.6.3       systemfonts_0.2.0    [21] rvg_0.2.4            memoise_1.1.0        htmltools_0.4.0      knitr_1.28
--
 
- [X] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).
- [X] Make sure you searched in the *open* and *closed* issues on the github repository.

**Comment by davidgohel** [comment]
Thanks for your inputs

> (1) The documentation does not explain which kind of styles change_styles can handle.

The title of the function is `replace paragraphs styles`. I thought it was clear. I will repeat the information in description.

> (2) The function does check that the style names in its arguments do exist, albeit without checking the style type.

This is what I get when trying to use non-existing paragraphs:

``` r
library(magrittr)
library(officer)

mapstyles <- list( "centered" = c("Normalbalb") )
doc <- read_docx() %>%
  body_add_par("A title", style = "heading 1") %>%
  body_add_par("Another title", style = "heading 2") %>%
  body_add_par("Hello world!", style = "Normal") %>%
  change_styles( mapstyles = mapstyles )
#> Error: could not find style 'Normalbalb'.



mapstyles <- list( "centeredblah" = c("Normal") )
doc <- read_docx() %>%
  body_add_par("A title", style = "heading 1") %>%
  body_add_par("Another title", style = "heading 2") %>%
  body_add_par("Hello world!", style = "Normal") %>%
  change_styles( mapstyles = mapstyles )
#> Error: could not find style 'centeredblah'.
```

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So I guess, I only need to make sure people don't add "non paragraph" styles. You did not provide any reproducible example, but I was able to reproduce your error using non paragraph styles. 

So using this kind of arguments `mapstyles <- list( "centered" = c("Table Professional") )` will now trigger this error:

```
 Error : could not find paragraph style 'Table Professional'. 
```

> It would be great if change_styles could handle all kind of word styles (character styles, paragraph styles, linked, list, but also table styles

I am currently working on it (for officedown) and this function could change soon. I don't think changing table styles or linked list will be implemented. What are you trying to achieve? What is the use case you want to solve?

**Comment by jarauh** [comment]
Sorry for not adding a reproducible example, and thanks for your quick reply.

And sorry for overlooking the man page title. :-)

I would like to substitute a character style ("Verbatim Char") by another one ("Code").  And I would like to substitute a title style by another one.  Adapting the code (without the checks...) works without a problem for character styles and for table styles:

```r
replace_style <- function(x, from, to, type = "p") {
  all_nodes <- xml_find_all(x$doc_obj$get(),
                            sprintf(paste0("//w:", type, "Style[@w:val='%s']"),
                                    from))
  xml_attr(all_nodes, "w:val") <- rep(to, length(all_nodes))
  x
}
doc <- replace_style(doc , "Titel", "Titel-berschrift")
doc <- replace_style(doc , "Untertitel", "Titel-Subberschrift")
doc <- replace_style(doc , "Datum", "TitelseiteStand")
doc <- replace_style(doc , "VerbatimChar", "Code", "r")
doc <- replace_style(doc , "Table", "TabelleStandard", "tbl")
```

**Comment by davidgohel** [comment]
@jarauh change_style can now replace par, text and table styles

https://github.com/davidgohel/officer/commit/59979ee0b826f87cb85aee873194ede79e4d6a89

**Comment by jarauh** [comment]
Thanks.  I will have a look at it!
