### ISSUE TITLE
ph_add_par levels not working

### ISSUE THREAD

**Issue by Logowilliams** [davidgohel/officer#299]
I am trying to use the `ph_add_par` command to create a bulleted list on a slide. The code below creates the bulleted list with the styles that I want, but the `level=` command fails to indent the bullet points at all. I've followed reprex's online but none work. Is the `level=` command bugged or am I missing something?

`report%>%
    add_slide(layout = 'Title and Content', master = 'Office Theme')%>%
    ph_with(value = "Academy: Summary Notes", location = ph_location_type(type = "title"))%>%
    ph_with(value = empty_content(), location = ph_location_type(type = "body"))%>%
    ph_add_par(level = 1)%>%
    ph_add_text(str = sprint_1, type = "body", style = fp_text(color = "black", font.size = 28, bold = TRUE, underlined = TRUE))%>%
    ph_add_par(level = 2, type = "body")%>%
    ph_add_text(str = paste("compared to this time in ", params$pastyear, " (", tc_ytd19, " total crimes)", sep = ""),  type = "body", 
                style = fp_text(color = 'black', font.size = 24)) -> report`

**Comment by davidgohel** [comment]
Sorry, I am not able to reproduce and the required guidelines to report an issue are missing.

Use `unordered_list` instead of `ph_add_par`, it should help
