### ISSUE TITLE
add Plot to Powerpoint 

### ISSUE THREAD

**Issue by proadiga** [davidgohel/officer#3]
Hallo , 

I used the Package ReporteRs  and it's great and very helpfull but my Problem was that this Package need  rJava . 

Now I try with Officer to add a ggplot graphic into a Powerpoint Presentation . but it seems that there ist not a Specific function for this .

for example : the function` body_add_gg() `is availble just for .doc files .

is it available in officer to add a ggplot graphic "as vecotr" to a pptx file ?

like : 
`addPlot(myppt,width,height,vector.graphic = TRUE)` -- _from ReporteRs_  --

**Comment by davidgohel** [comment]
You can use `?ph_with_img` or package `rvg` (an example below):

```
library(officer)
library(rvg)
doc <- read_pptx()
doc <- add_slide(doc, "Title and Content", "Office Theme")
doc <- ph_with_vg(doc, code = barplot(1:5, col = 2:6), type = "body")
print(doc, target = "vg.pptx")
```

You may need to update your packages.

David

**Comment by proadiga** [comment]
Hallo David :)

thank you very much for your answer .yes this is what i searched for and its worked perfekt .


Best regards ,
