### ISSUE TITLE
cursor_bookmark error

### ISSUE THREAD

**Issue by mattantaliss** [davidgohel/officer#30]
This particular issue is about the `cursor_bookmark` function, but it may also apply to one or more of the other `cursor_*` functions.

I've a .docx file set up to serve as a template with all of the desired design and style details established, and I'm trying to modify some text that will serve as the document title. I have a bookmark set for that location, called "Document_Title", but when I attempt
```R
doc <- read_docx(path = "template.docx") %>%
  cursor_bookmark(id  = "Document_Title") %>%
  body_add_par(value = "New text", style = "Title", pos = "on")
```
I receive the following error: `Error: bookmark "Document_Title" does not end in the same paragraph (or is on the whole paragraph)`.

After tracking down where that comes from ([docx_document.R](https://github.com/davidgohel/officer/blob/757694f0671eeb1763b1d0003d5fc263a96a5a0c/R/docx_document.R)) and locally playing around with the code for `cursor_bookmark` (lines 68--90), I found that things seem to work correctly if each of the single forward-slashes (`/`) in the `xpath_` assignments are replaced with double forward-slashes (`//`).

**Comment by davidgohel** [comment]
unfortunately, I can't reproduce without template.docx. 

 If your have read the code, I am sure you saw that this error is raised in the code. If you set the bookmark **in** the paragraph (just set it at the beginning of the paragraph for example) and NOT on the whole paragraph, it will work. I will make a additionnal note for that in the documentation. For now, it's only documented in ReporteRs (the old version): https://davidgohel.github.io/ReporteRs/articles/bookmarks.html#declare-bookmark-in-word

**Comment by mattantaliss** [comment]
To follow-up, I looked at the formatting marks contained in my template document after seeing the documentation you linked to. In doing so, I realized it's the fact that my text is in a table cell that seems to be the root of my problems. There is an end-of-cell marker at the end of the text I'm trying to modify instead of a plain paragraph mark. Here is a simplified version of my template document for reference: [template.docx](https://github.com/davidgohel/officer/files/1078270/template.docx).

Is there a way to set a bookmark in a table cell or otherwise modify the text in a table cell?

**Comment by davidgohel** [comment]
To summarize, I understand you want a table because you want to add borders around a paragraph, right?

If it's the case, you could add a paragraph with a style that has borders, the rendering is the same.

**Comment by mattantaliss** [comment]
That did it. Thanks!

It took some time to make a paragraph style look and act like the table cell I was actually working with (it had some shading, padding, and an image to deal with), but once I got all of the settings just right, it worked like a charm.
