### ISSUE TITLE
Inconsistent xml output

### ISSUE THREAD

**Issue by jarauh** [davidgohel/officer#300]
It looks like the following line adds `<w:tc><w:trPr/>` when it should add `<w:tc><w:tcPr/>`:

https://github.com/davidgohel/officer/blob/63c41a85f61c880fed105001f7716ebd9b1eb4ef/R/ooxml_block_objects.R#L530

(more row properties instead of cell properties.)

**Comment by davidgohel** [comment]
No, this is not the case; however thanks for pointing that, it is not necessary as it means "apply the default row properties"!

**Comment by davidgohel** [comment]
Hum, my mistake, it was ignored but as you said, its parent was supposed to be *table row*
