### ISSUE TITLE
Instantiate latent Styles at read_docx()

### ISSUE THREAD

**Issue by stefanoborini** [davidgohel/officer#304]
Currently, if one opens a brand new doc, saves it, and opens it in officer, the Title style is not present. The reason, I guess, is that Title is a latent style (see styles.xml) and won't be concretised until you actually use it.

This feature request is therefore specified as follows: officer doc styles must contain both instantiated and latent styles, so that both are available at load time.

I was thinking of a workaround, but I need help. One option I came up with was to generate a template document where the latent styles are used, e.g. by writing dummy text with that style. I would then open the template and delete all its content, but I am not sure if it's the most elegant solution. Maybe there's a different way to instantiate latent styles from officer?

Thanks!

**Comment by davidgohel** [comment]
thanks,

I think the solution would be to implement first a function that can create new styles from R, it's a long time I am thinking about that. 

This will take some times as I can't dedicate time on that subject for now.

**Comment by davidgohel** [comment]
Implemented with functions `officer::docx_set_paragraph_style()` and `officer::docx_set_character_style()`.
