### ISSUE TITLE
Flextable with special characters

### ISSUE THREAD

**Issue by mbaqiraltaf** [davidgohel/officer#31]
Hi David,

I am facing an issue related to special characters in flextable. Actually, my dataframe has special characters "<" and ">", when I try to create flextable from it, it is successfully created. But, when I run below code, it throws an error:

```
doc <- read_docx() %>%
      body_add_flextable(flexTableObj) %>%
      body_end_section(landscape = TRUE )

    print(doc, target = filePath)
```

**Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  StartTag: invalid element name [68]**

I tried to change encoding of my dataframe column as well, but it did not work.

I seen some threads from ReporteRs package specifying same problem, for example:  #https://github.com/davidgohel/ReporteRs/issues/63 but it was solved there. Not sure whether its been resolved for the officer package or not.

Thanks

**Comment by davidgohel** [comment]
Hi mbaqiraltaf,

From the title it seems you opened a ticket in the wrong project, please avoid this.

You can use unicodes. I will try to change that next time I work on the project.
