### ISSUE TITLE
Error in value[[3L]](cond)

### ISSUE THREAD

**Issue by RussianNotSurrender** [davidgohel/officer#312]
Hello, excuse me please in advance for english. I tested package and encountered a kind of error. 

`my.doc <- read_docx() %>%
body_add_par('cmon bruh')
print(my.doc, target = 'result.docx')`

After that I got 
`Error in value[[3L]](cond) :
  Could not write "C:/officer/result.docx" [zip error: `Cannot add file `[Content_Types].xml` to archive `C:/officer/result.docx`` in file `zip.c:394`]`

I was looking for a solution and of course saw #258 and downloaded last version from github. Also I was trying to avoid an error changing the directory (from `"C:/Users/Администратор/Documents"` I changed to `"C:/officer"` and others). Anyway I get the same. The file is created but it`s blank. When I was trying do this with primary directory I got another error
`Error in dirname(target)
problem converting file name -- path too long?`

It may be different error on english because I translate it from russian.

`> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251
[4] LC_NUMERIC=C                    LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5       officer_0.3.13.005

loaded via a namespace (and not attached):
[1] compiler_4.0.2 R6_2.4.1       tools_4.0.2    uuid_0.1-4     xml2_1.3.2     zip_2.0.4`

If more information is needed please write. I will describe as much as I can. Thank you in advance.

**Comment by davidgohel** [comment]
OK

From a fresh new session, what do you get if running that code:

```
library(officer)

my.doc <- read_docx()
my.doc <- body_add_par(my.doc, 'test') 

print(my.doc, target = 'result.docx')
```

please post:

* the exact output (everything, erros if any)
* the file result.docx if no error

**Comment by davidgohel** [comment]
You can use https://github.com/tidyverse/reprex to help you get all together (except the file that will need to be uploaded manually)

**Comment by RussianNotSurrender** [comment]
Thank you for your patience. I hope I`ll use reprex correctly. From a fresh session.
``` r
getwd()
#> [1] "C:/Users/Àäìèíèñòðàòîð/AppData/Local/Temp/RtmpqKDrBr/reprex36c468b17ae"

  library(officer)
  
  my.doc <- read_docx()
  my.doc <- body_add_par(my.doc, 'test') 
  
  print(my.doc, target = 'result.docx')
#> Error in dirname(target): file name conversion problem -- name too long?
```


If I change the directory
``` r
setwd('D:/R'); getwd()
#> [1] "D:/R"
```
I get the same.

``` r
library(officer)

my.doc <- read_docx()
my.doc <- body_add_par(my.doc, 'test') 

print(my.doc, target = 'result.docx')
#> Error in dirname(target): file name conversion problem -- name too long?
```
The file is created but it`s blank. 
I changed language to english in R so potential issues related with translating are abolished.

**Comment by RussianNotSurrender** [comment]
I`m not sure it`s ok but if I change directory 
``` r
setwd("C:/R_files")
```
I get
``` r
setwd('C:/R_files')
library(officer)

my.doc <- read_docx()
my.doc <- body_add_par(my.doc, 'test') 

print(my.doc, target = 'result.docx')
#> Error in value[[3L]](cond): Could not write "C:/R_files/result.docx" [zip error: `Cannot add file `[Content_Types].xml` to archive `C:/R_files/result.docx`` in file `zip.c:394`]
```

**Comment by davidgohel** [comment]
thanks, I can reproduce now!

**Comment by davidgohel** [comment]
This happens in package `zip`. Could you run from a fresh session:

```
remotes::install_github("r-lib/zip")
remotes::install_github("davidgohel/officer")
```

After that step, everything should be ok.

Could you let me know?

**Comment by RussianNotSurrender** [comment]
yeeeeah it really works with no errors! The file was created with text in it given the fact that directory has specific symbols. Appreciate it and thank you very much.
[result.docx](https://github.com/davidgohel/officer/files/4952305/result.docx)
