### ISSUE TITLE
bold = FALSE not working for mschart 

### ISSUE THREAD

**Issue by dmklotz** [davidgohel/officer#315]
This seems to be a similar issue to [this closed one](https://github.com/davidgohel/officer/issues/40)

When modifying any fp_text() elements in mschart_theme, everything seems to work except bold = FALSE.  I'm just showing an example for main_title, but this also applies to the other labels.  Strangely, this is not the default for the standard PPT template.  If you create a new chart, the title is not bold. 

Here is one MRE:

```
library(officer)
library(mschart)
library(magrittr)

bold_theme <- mschart_theme(main_title = fp_text(bold = TRUE, font.family = "Segoe UI", font.size = 15))
plain_theme <- mschart_theme(main_title = fp_text(bold = FALSE, font.family = "Segoe UI", font.size = 15))

linec <- ms_linechart(data = iris, x = "Sepal.Length",
                      y = "Sepal.Width", group = "Species")

plain_linec <- set_theme(linec, plain_theme) %>% chart_labels(., title = "Should be Plain")
bold_linec <- set_theme(linec, bold_theme) %>% chart_labels(., title = "Should be Bold")

doc <- read_pptx()
doc <- add_slide(doc, layout = "Comparison", master = "Office Theme")
doc <- ph_with(doc, value = plain_linec, location = ph_location_left())
doc <- ph_with(doc, value = bold_linec, location = ph_location_right())
print(doc, target = "test_bold_chart.pptx")

```
![officer](https://user-images.githubusercontent.com/14988804/89661862-3c3a2800-d8a1-11ea-9ad6-1cb6635b543e.JPG)

**Comment by davidgohel** [comment]
Thanks for your time, it's a perfect reprex :)

It's solved now in the GitHub version
