### ISSUE TITLE
Header image is stripped if a section break exists

### ISSUE THREAD

**Issue by mattantaliss** [davidgohel/officer#317]
I'm working with a Word doc that includes an image in the header (an example: [Test_Doc_Input.docx](https://github.com/davidgohel/officer/files/5075913/Test_Doc_Input.docx)), and everything worked well with version 0.3.10. I updated to 0.3.12 yesterday and noticed that the header image was now being stripped out. After starting from a blank Word document and iterating on changes towards the actual Word doc I use until I find a step that breaks, it seems the presence of at least one section break in the document is the culprit.

Using the example document and the following code, you should see the header image has been stripped from the output file:
```
library(officer)

print(x = read_docx("Test_Doc_Input.docx"), target = "Test_Doc_Output.docx")
```

I have been able to produce that same behavior on both a Windows system and a Cent OS 7 system. The `sessionInfo()` details for each are as follows:

Windows:
> R version 4.0.2 (2020-06-22)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19041)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] officer_0.3.12
> 
> loaded via a namespace (and not attached):
> [1] compiler_4.0.2 R6_2.4.1       magrittr_1.5   tools_4.0.2    uuid_0.1-4    
> [6] xml2_1.3.2     zip_2.1.0

Cent OS 7:
> R version 4.0.0 (2020-04-24)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS:   /usr/lib64/R/lib/libRblas.so
> LAPACK: /usr/lib64/R/lib/libRlapack.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
>  [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
> [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] officer_0.3.12
> 
> loaded via a namespace (and not attached):
> [1] compiler_4.0.0 R6_2.4.1       magrittr_1.5   tools_4.0.0    uuid_0.1-4    
> [6] xml2_1.3.2     zip_2.1.0

**Comment by davidgohel** [comment]
Thanks 

This is already fixed in the github version. You can update your package with `remotes::install_github("davidgohel/officer")`
