### ISSUE TITLE
Adding Footer to Word Document

### ISSUE THREAD

**Issue by mbaqiraltaf** [davidgohel/officer#32]
Hi David,

Hope you are doing well. I have a requirement to add footer to the generated Word document. I searched the documentation, but could not find any function for that.

Secondly, I also want to add page numbers to the document.

Do you think above 2 tasks can be achieved?

Thanks in advance

**Comment by davidgohel** [comment]
Hi mbaqiraltaf

For request 1, there will be an option later for that (see at bottom of readme)

For request 2, you only have to add you page number in the initial document (see parameter path in read_docx)

**Comment by slarge** [comment]
Hi David,
 With regards to the header/footer functionality mentioned in request 1, above, it seems that it has been removed from the "to-do" list in [commit 7e769f3b](https://github.com/davidgohel/officer/commit/7e769f3b3355b4dd91cc38a337b3e7fceb75041f#diff-04c6e90faac2675aa89e2176d2eec7d8). Is it in your plan to add footer/header support? Or is it not feasible. Thanks in advance for your feedback. 

SL

**Comment by davidgohel** [comment]
Hi,

It is feasible but this won't be provided for now.
