### ISSUE TITLE
Some incorrect characters written docx file (Windows character encoding issue)

### ISSUE THREAD

**Issue by ksnap28** [davidgohel/officer#321]
Hi David,

Some incorrect characters are written out to the docx file (e.g. = instead of ≤) when I use the body_add_fpar function. I think it's due to my system running Windows, which doesn't seem to include ≤ as a native character. What's interesting is that this doesn't happen when text is added to the docx file using the body_add_par function.

I believe that I've pinpointed the source of the issue to the ftext function. It uses formatC on the text input, which ends up forcing all input text in to its native encoding.

This isn't a major issue for me but I thought I would point it out in case it is a problem for anyone else in the future. I wasn't sure if skipping the call to formatC in ftext was a viable option or not.

---------------------------------------------------

Here is my session info:

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5  officer_0.3.8

loaded via a namespace (and not attached):
[1] compiler_3.6.1 R6_2.4.1       tools_3.6.1    uuid_0.1-4     xml2_1.3.1     zip_2.0.4
```

---------------------------------------------------

Here is a reproducible example:

```
library(officer)
library(magrittr)

problem_value = "\u2264"

doc =
    read_docx() %>%
    body_add_par(value = paste("This value displays properly:", problem_value),
                 pos = "after") %>%
    body_add_fpar(value = fpar(ftext(paste("This value does not display properly:", problem_value),
                                     prop = fp_text(bold = FALSE))))
print(doc, target = tempfile(fileext = ".docx") )
```

![image001](https://user-images.githubusercontent.com/2623216/90677583-6c26eb00-e212-11ea-88c6-c64969d39eba.png)

**Comment by davidgohel** [comment]
Thanks for reporting that and for pointing out `formatC` was the issue!
