### ISSUE TITLE
R session aborts when printing to a .docx file that is currently open

### ISSUE THREAD

**Issue by mattantaliss** [davidgohel/officer#324]
If a .docx file is open when the user attempts to print to that same file, the R session aborts.

Example (execute the `print`, open 'test.docx', then execute the `print` again):
```
library(officer)

print(x = read_docx(), target = "test.docx")
```

Session info:
> R version 4.0.2 (2020-06-22)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19041)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] officer_0.3.13.011
> 
> loaded via a namespace (and not attached):
> [1] compiler_4.0.2 R6_2.4.1       magrittr_1.5   tools_4.0.2    uuid_0.1-4    
> [6] xml2_1.3.2     zip_2.1.0

If I am remembering correctly, when I would forget to close a document before printing to it again in earlier versions of `officer`, I'd get an error message about not being able to write to the file instead of a full session abort.

**Comment by davidgohel** [comment]
Thanks for that.

This is not coming from `officer` but from the latest version of package `zip` and only on Windows platform. 

It is a segmentation fault, but I am not able to analyze it. This can be observed if not using RStudio but R console instead.

I am closing the issue as I can't do anything about that.
