### ISSUE TITLE
Remove page break after final section

### ISSUE THREAD

**Issue by mattantaliss** [davidgohel/officer#325]
I was attempting to creating a one-page document that would have two-column content in the middle of the page (i.e., I'd have one-column, then two-column, then one-column sections on the one page). In trying to figure out how to do that, I came across [this answer you posted on SO](https://stackoverflow.com/a/63579122/5660762), and that was exactly the sort of thing I was looking for. However, when I implemented that solution, I found my output would always have a second page because the last section break (i.e., the last instance of `body_end_block_section`) would always be converted from the 'continuous' type I specified to a 'next page' type in Word.

After digging around some more, I _think_ this is actually a fundamental issue with Microsoft and Word, but I am curious to know if it is possible to not have (or to remove) the page break that occurs after the last section.

Here's a reprex (note the output has two pages instead of only one):
``` r
library(officer)
library(magrittr)

# Define one- and two-column section block specifications
portrait_one_column <-
  block_section(
    prop_section(
      page_size = page_size(width = 8.5, height = 11),
      type = "continuous"
    )
  )

portrait_two_columns <-
  block_section(
    prop_section(
      page_size = page_size(width = 8.5, height = 11),
      type = "continuous",
      section_columns =
        section_columns(widths = c(3.125, 3.125), space = 0.25, sep = TRUE)
    )
  )

# Create an example document
read_docx() %>%
  body_add_par(value = "Some text in a one-column section") %>%
  body_add_par(value = "") %>%
  # End the first one-column section
  body_end_block_section(value = portrait_one_column) %>%
  body_add_par(value = "Some text in a two-column section") %>%
  body_add_par(value = "More text in a two-column section") %>%
  body_add_par(value = "Yet more text in a two-column section") %>%
  # End the two-column section
  body_end_block_section(value = portrait_two_columns) %>%
  body_add_par(value = "") %>%
  body_add_par(value = "Some text in another one-column section") %>%
  # End the second one-column section
  body_end_block_section(value = portrait_one_column) %>%
  print("test.docx")
```

<sup>Created on 2020-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Session info:
> R version 4.0.2 (2020-06-22)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19041)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] magrittr_1.5       officer_0.3.13.011
> 
> loaded via a namespace (and not attached):
> [1] compiler_4.0.2 R6_2.4.1       tools_4.0.2    uuid_0.1-4     xml2_1.3.2    
> [6] zip_2.1.0

**Comment by davidgohel** [comment]
Yes sorry, maybe it's possible, but I don't think it is. I am not able to remove that last page and I stopped trying when I saw I was not able to do it by hand on Word.

**Comment by aavanesy** [comment]
@davidgohel I am able to remove the blank pages at the end using a manual trick, see in this loom
https://www.loom.com/share/ce96b15d8cb24bbe8a7a40646be98352
Let me know if this helps and if clear.
