### ISSUE TITLE
tableone and officer

### ISSUE THREAD

**Issue by butellyn** [davidgohel/officer#327]
I am trying to follow the example to create Table 1 here: https://www.r-bloggers.com/table-1-and-the-characteristics-of-study-population/, but `officer` has replaced `ReporteRs`. How would you go about exporting the table made in R using `tableone` to R? I tried `print(table1, target = "<path to Word docx>")`, but the table didn't export. Are `officer` and `tableone` compatible? Or does the `print` method not work in this case because the object returned by `CreateTableOne` isn't the same type of object as returned by `officer`? If so, is there a way to use `officer` to export a `tableone` object to a Word document? Thanks!

**Comment by davidgohel** [comment]
Sorry, I am not the author of tableone, I don't know. If you can get a data.frame from the  package, it should be ok to send it to `flextable`.

There are several packages that are producing "table one" summary, gtsummary for example (compatible with flextable)
