### ISSUE TITLE
Problem with body_add_gg and body_add_img

### ISSUE THREAD

**Issue by cyrille-f** [davidgohel/officer#328]
Hello,

Thanks a lot for your work. reporter and officer are very usefull.

I recently update some packages on my installation, automatically with rstudio. And since, body_add_gg and body_add_img print three plot instead of one... Normal size, smaller and smaller.. very strange

Merci encore !

Here is a code to try to reproduce

#-----------------------------
d <- read_docx()

dat <- data.frame(x = rnorm(1000) , y = rnorm(1000))

gg <- ggplot(data = dat , aes(x = x , y = y)) +
  geom_point()

d <- body_add_gg(d , gg , width = 6.3 , height = 6.3)

print(d , target = "testg.docx")
[testg.docx](https://github.com/davidgohel/officer/files/5175309/testg.docx)

**Comment by cyrille-f** [comment]
Ok this issue has already fixed ! Sorry I didn't checked. 

Merci aussi pour le paquet flextable.

Bonne continuation

Cyrille

**Comment by davidgohel** [comment]
Désolé pour ce bogue... J'ai mal revu une PR...
