### ISSUE TITLE
Could i turn to other master when run add_slide? PresentationTemplate2017

### ISSUE THREAD

**Issue by leechaowen** [davidgohel/officer#329]
add_slide(x, layout = "Title and Content", master = "Office Theme")

it seems the master has only one choose.  How to use the master="PresentationTemplate2017".Thanks your support

**Comment by davidgohel** [comment]
It does not seem to me: https://davidgohel.github.io/officer/reference/add_slide.html

`add_slide(x, layout = "a layout", master = "PresentationTemplate2017")`

**Comment by davidgohel** [comment]
Please read and follow the guidelines of the issue (you deleted them when you submitted that new issue)
