### ISSUE TITLE
generating native charts

### ISSUE THREAD

**Issue by ksedr** [davidgohel/officer#33]
Hello,
I started using the officer package recently and it works great.
I would like to generate PowerPoint documents with "native" charts, so a user can right-click on a chart and has options to edit data in Excel, change the chart type, etc. Is it possible to do that using the officer package (or some other R package that you know about)? If not, do you plan to implement such a feature?
Thanks!

**Comment by davidgohel** [comment]
Hello

No.

I understand that could be usefull but there is no plan for that right now (it would require several days of development and I don't have enough time for that).

Maybe later but no promise ;)
