### ISSUE TITLE
level_list option for no bullet

### ISSUE THREAD

**Issue by gmculp** [davidgohel/officer#332]
Good evening, David.

Is there a way to not bullet and indent items in an unordered list?  I attempted to set values in the level_list argument to NA, 0 and -1 in a attempt to achieve this outcome but was unsuccessful.  I am hoping to create something like the following in a PowerPoint slide...

![image](https://user-images.githubusercontent.com/5456352/93145168-aec8cf80-f6b9-11ea-8e82-52e5597bf94a.png)

```
doc <- read_pptx()

ul <- unordered_list(
  level_list = c(0,1,1,0,0,1,1),
  str_list = c("List1", "Item 1", "Item 2", "" ,"List 2", "Option A", "Option B"),
  style = fp_text(color = "gray25", font.size = 0) )

doc <- add_slide(doc)
doc <- ph_with(x = doc, value = ul,
               location = ph_location_type(type = "body") )

print(doc, target = "ph_with_ul.pptx")

```

Thanks!

GMC

**Comment by davidgohel** [comment]
Thanks for the suggestion, no promise but I'll try, I think it is not difficult to implement

**Comment by davidgohel** [comment]
Your suggestion has been implemented. Thank you

**Comment by padilla410** [comment]
Thank you, @davidgohel!
