### ISSUE TITLE
print functions not exported

### ISSUE THREAD

**Issue by clsh-ldw** [davidgohel/officer#334]
Hi,

it seems that officer (version 0.3.14 from CRAN and 0.3.15 from Github as well) does not export (among others) the print functions, although e.g. for print.rdocx there is an export statement in the description block:

https://github.com/davidgohel/officer/blob/32a097d2ebbf43a4ca51d045eda28bb57dc962b1/R/read_docx.R#L94

and in the NAMESPACE file:

https://github.com/davidgohel/officer/blob/32a097d2ebbf43a4ca51d045eda28bb57dc962b1/NAMESPACE#L54

I don't see why function export does not work, maybe you have an idea how to fix it...

**Comment by davidgohel** [comment]
I don't understand what is your issue. Please describe it with a reproducible example.

**Comment by clsh-ldw** [comment]
Sorry for being unclear. Explicit function calls like

my_doxc <- officer::read_docx() # works
officer::print.rdocx(my_docx) # raises error

don't work for some functions.

**Comment by davidgohel** [comment]
You don't call  `base::print.data.frame`, you call `print`, same principle here. See the documentation:

https://davidgohel.github.io/officer/reference/read_docx.html

```
my_doxc <- read_docx() 
print(my_docx, target = "ccc.docx") 
```

**Comment by clsh-ldw** [comment]
Nevertheless, 

```r
my_doxc <- officer::read_docx()
officer::print.rdocx(my_docx, target = "ccc.docx") 
```
doesn't work either

**Comment by davidgohel** [comment]
No, first  `print.rdocx` is not exported, then you made a typo. 

Please read the documentation. use `print`, `print` is a function located in `base`.

If you really need to use `::`, use the correct function:

```
my_doxc <- officer::read_docx()
base::print(my_doxc, target = "ccc.docx") 
```
