### ISSUE TITLE
Error in opening word doc

### ISSUE THREAD

**Issue by smhabbas** [davidgohel/officer#335]
Hi David: When I create a new docx using print function and get following error message opening word docx file
Thanks

![image](https://user-images.githubusercontent.com/26821183/94961669-abda3580-0527-11eb-8d1d-486468f5f9cd.png)
![OfficeR error](https://user-images.githubusercontent.com/26821183/94961714-c2808c80-0527-11eb-9e71-bf0d5ce0e531.PNG)

**Comment by davidgohel** [comment]
Could you follow the guidelines please?

When submitting a new issue:

- [ ] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [ ] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [ ] Make sure you searched in the *open* and *closed* issues on the github repository.
