### ISSUE TITLE
docProps/app.xml incorrect number of Pages

### ISSUE THREAD

**Issue by pythiantech** [davidgohel/officer#336]
I am generating a word document from an initial template which is only one page. After creating the document, which is say 10 pages, I need to add in the number of pages into the generated Word document. The way I am doing it is to save the generated document using the `print()` function. I then try to get the number of pages from the app.xml file of the document.

```
document_props <- system("unzip -p 'my_doc.docx' docProps/app.xml", intern = TRUE)
page_numbers <- unlist(qdapRegex::ex_between(document_props[2], left = '<Pages>', right = '</Pages>'))

```
I inspected the xml generated and found that the page count is always 1 no matter what the length of the generated document is. Is it because the initial template was only 1 page?

**Comment by davidgohel** [comment]
No, it is not
It is because this information can only be defined by Word but your document has not been edited by Word

You should use a computed field instead.
