### ISSUE TITLE
add a continous section in Word document

### ISSUE THREAD

**Issue by damienGB** [davidgohel/officer#34]
Hi David,
Hope you are doing well.
I have tested **officer** to generate word document, it is rather effective.
But I did not succeed in making continous break section (i have always a break page).
**It is possible ??**

An example of the expected result with ReporteRs
`# with ReporteRs
download.file("http://assets.howtobecome.com/assets/images/2014/01/police-officer.jpg", "img_test1.jpg")
download.file("https://russellkorets.files.wordpress.com/2013/09/police_officers.jpg", "img_test2.jpg")

doc <- ReporteRs::docx() %>% 
       ReporteRs::addParagraph(pot("Test ReporteRs"), textProperties(font.size = 24)) %>% 
       ReporteRs::addSection(ncol = 2, landscape = FALSE, columns.only = TRUE) %>%
       ReporteRs::addImage(filename = "img_test1.jpg", width = 3, height = 2 ) %>%
       ReporteRs::addImage(filename = "img_test1.jpg", width = 3, height = 2 ) %>%
       ReporteRs::addSection(ncol = 2, landscape = FALSE, columns.only = TRUE) %>%
       ReporteRs::addImage(filename = "img_test2.jpg", width = 3, height = 2 ) %>%
       ReporteRs::addImage(filename = "img_test2.jpg", width = 3, height = 2 )
doc <- addSection(doc, columns.only = TRUE)
ReporteRs::writeDoc(doc, "test_ReporteRs.docx")`

And my code with officer
`# with officer
download.file("http://assets.howtobecome.com/assets/images/2014/01/police-officer.jpg", "img_test1.jpg")
download.file("https://russellkorets.files.wordpress.com/2013/09/police_officers.jpg", "img_test2.jpg")

doc <- officer::read_docx() %>% 
       officer::body_add_par("Test officer", style = "Normal")
doc <- officer::body_end_section(doc, colwidths = c(1))  %>% 
       officer::body_add_img(src = "img_test1.jpg", width = 3, height = 2 ) %>%
       officer::body_add_img(src = "img_test1.jpg", width = 3, height = 2 ) %>%
       officer::body_end_section(colwidths = c(.5, .5)) %>%
       officer::body_add_img(src = "img_test2.jpg", width = 3, height = 2 ) %>%
       officer::body_add_img(src = "img_test2.jpg", width = 3, height = 2 ) %>% 
       officer::body_end_section(colwidths = c(.5, .5))
print(doc, "test_officer.docx")`

Thanks in advance, a ++

**Comment by davidgohel** [comment]
Yes, it should be possible. thanks for reporting this

**Comment by davidgohel** [comment]
Hi Damien 

I should work on that soon - sorry for the delay

David

**Comment by davidgohel** [comment]
Hi Damien,

It should be fixed now. Below the slightly modified code:

```
download.file("http://assets.howtobecome.com/assets/images/2014/01/police-officer.jpg", "img_test1.jpg")
download.file("https://russellkorets.files.wordpress.com/2013/09/police_officers.jpg", "img_test2.jpg")

doc <- officer::read_docx() %>%
  officer::body_add_par("Test officer", style = "Normal")
doc <- officer::body_end_section(doc, continuous = TRUE ) %>%
  officer::body_add_img(src = "img_test1.jpg", width = 3, height = 2 ) %>%
  officer::body_add_img(src = "img_test1.jpg", width = 3, height = 2 ) %>%
  officer::body_end_section(colwidths = c(.5, .5), continuous = TRUE) %>%
  officer::body_add_img(src = "img_test2.jpg", width = 3, height = 2 ) %>%
  officer::body_add_img(src = "img_test2.jpg", width = 3, height = 2 ) %>%
  officer::body_end_section(colwidths = c(.5, .5), continuous = TRUE)
print(doc, "test_officer.docx")
```

Can you test with the new github version? I will try to submit to CRAN very soon.

**Comment by damienGB** [comment]
Many thanks David! 
I was able to do what I wanted with **body_end_section** & new argument **continuous**

**Comment by davidgohel** [comment]
on its way to CRAN...
