### ISSUE TITLE
Manipulate Document With docx_summary(...)

### ISSUE THREAD

**Issue by gfleetwood** [davidgohel/officer#341]
Hi. I'm looking into making docx templates and then filling in values with the glue library. Currently my pipeline converts docx to text, fills in the template, outputs an Rmd, and then converts back to docx:

```
q1 = format(80000, big.mark=",") 
# t0.docx contains the string "{q1}" to be filled in
txt_docx = textreadr::read_docx("t0.docx")
update_doc = glue(paste(txt_docx, collapse = "\n"))
cat(update_doc, sep = "\n", file = "my_text.Rmd")
# Produces my_text.docx
rmarkdown::render("my_text.Rmd", word_document())
```

But this messes up the formatting in the docx. I wanted to use officer in the pipeline to get around that. Looking at the documentation the easiest method to leverage glue seems to be through docx_summary, but there doesn't seem to be a way to change a value in the dataframe produced by docx_summary and then update the rdocx object. 

Is there a method I'm missing, or do you have a recommendation for an alternate way?

**Comment by davidgohel** [comment]
From the manual, `docx_summary` read content of a Word document and return a data.frame representing the document, it's *read only*. 

I don't have method or solution to leverage package glue or for alternate way. I think best is to use the documented function.
