### ISSUE TITLE
fp_p bug using fpar ?

### ISSUE THREAD

**Issue by bthieurmel** [davidgohel/officer#35]
Hi David,

I try to define some center text using ``body_add_fpar``, ``fpar`` and ``fp_par`` without success.

Perhaps I do something wrong ? 

````
doc <- officer::read_docx()

doc <- doc %>% officer::body_add_fpar(
  officer::fpar(officer::ftext("I want a centered title", prop = officer::fp_text(font.size = 28)),
                                                      fp_p = officer::fp_par(text.align = 'center'))) 
  
print(doc, target = "title.docx")
````

**Comment by davidgohel** [comment]
Hi Benoit,

Yeah... that `fp_p` is a bad idea. I have improved `body_add_fpar` so that it understands `style` argument (you will need to update officer from github):

```
doc <- officer::read_docx()
doc <- doc %>% officer::body_add_fpar(
  officer::fpar(officer::ftext("I want a centered title", prop = officer::fp_text(font.size = 28))), style = "centered") 
  
print(doc, target = "title.docx")
```

This will concatenate ftext args into a paragraph made of chunks and apply paragraph property **centered** to the result.

**Comment by bthieurmel** [comment]
Thanks. An idea of delay before a new  CRAN submission ?

**Comment by davidgohel** [comment]
mid July. If you are in the hurry, note you can achieve that only with a Word template.
