### ISSUE TITLE
Add list styles in default template

### ISSUE THREAD

**Issue by DanChaltiel** [davidgohel/officer#350]
Hi David,

I just read the closed issue https://github.com/davidgohel/officer/issues/262, which you addressed by suggesting a template that included a "bullet" style. 

Wouldn't it be nice if the default template had such a "bullet" or "unordered_list" style? And hopefully an "ordered_list" style as well?

Of note, I second OP on the fact that it is still a bit unclear in the doc if you can add a bullet list or not in the doc. Indeed, when you search "r officer add list word" on Google, you end up on the documentation of `body_add_blocks` (not really related) and `unordered_list` (specific to PowerPoint). I'm not sure how and where you could clarify this though.

**Comment by davidgohel** [comment]
> Wouldn't it be nice if the default template had such a "bullet" or "unordered_list" style? And hopefully an "ordered_list" style as well?

Yes, it would be nice. Lists will be implemented (with real list styles and not paragraph styles with does not allow easily multi-levels lists), this is related to #314 

> [...] I second OP [...]

I just added a FAQ for that: https://ardata-fr.github.io/officeverse/faq.html#add-a-bullet-list-on-a-word-document-with-officer
