### ISSUE TITLE
fp_text unable to remove underlined feature

### ISSUE THREAD

**Issue by humoroussmile** [davidgohel/officer#352]
Why is it that when "fp_text" is used, this forces text to be underlined? The default, by my understanding, is that it should be FALSE. I cannot seem to turn this off without removing "fp_text" altogether. Example below.

REPRODUCIBLE EXAMPLE:
text_style <- fp_text(font.size = 12)
par_style <- fp_par(text.align = "justify")
my_doc <- read_docx()
my_doc <- body_add_fpar(my_doc, fpar( ftext("This is a test", prop = text_style), fp_p = par_style ) ) #UNDERLINE PRESENT DESPITE DEFAULT
my_doc <- body_add_fpar(my_doc, fpar( ftext("This is a test2"), fp_p = par_style ) ) #UNDERLINE removed
print(my_doc, target = "dummy.docx")
[dummy.docx](https://github.com/davidgohel/officer/files/5883318/dummy.docx)

**Comment by davidgohel** [comment]
This is a screenshot of the document you shared, I am sorry, I don't see underlined text here:

<img width="633" alt="Capture d’écran 2021-02-01 à 14 02 21" src="https://user-images.githubusercontent.com/4331618/106462272-24c9a980-6496-11eb-8622-eab699ac3eec.png">


Please next time, follow the guidelines detailed in the issue's form (sessionInfo, etc.)
