### ISSUE TITLE
Fractions and Supercript in a table 

### ISSUE THREAD

**Issue by alapo** [davidgohel/officer#353]
I have been trying to get a table to work using officedown and officer which contains both fractions and supercripts. I have attempted to post the question on [StackOverflow](https://stackoverflow.com/questions/65601119/fractions-and-superscript-in-a-table-while-knitting-to-docx-rmarkdown) but its been a month without any takers.

I have  uploaded an extremely detailed Rmd file below. Does anyone have any suggestions?

[RMarkdown-docx-tables.zip](https://github.com/davidgohel/officer/files/5912269/RMarkdown-docx-tables.zip)

**Comment by davidgohel** [comment]
Sorry, your code does not run, and it's not minimal. Please follow the guidelines you deleted when you posted that issue. 


```
Quitting from lines 12-54 (RMarkdown-docx-tables.Rmd) 
Error in as_sup(., str_extract("\\d+")) : 
  argument inutilisé (str_extract("\\d+"))
```

For now, fractions are not supported by flextable but there will be support for fractions. All other features are supported. The user manual is here:
https://ardata-fr.github.io/officeverse/officedown-for-word.html

More about flextable caption here: https://ardata-fr.github.io/flextable-book/layout-1.html#captions

You may also dig into `ftExtra` that is a very good extension with support for markdown and maybe equations.

**Comment by alapo** [comment]
@davidgohel very sorry. I was just trying to demonstrate all the efforts made. Thank you for recommending `ftExtra`
