### ISSUE TITLE
Issue with Footer in rdocx object

### ISSUE THREAD

**Issue by mayanklal** [davidgohel/officer#359]
On opening the file saved using print command, I am getting the error message saying that there is a problem with its contents. On checking further, I have identified that it is an issue with footer2.xml file.

I am using an existing docx file and adding external docx file to it. Both docx file doesn't have any footer in it.

The error message as given below:

`Location: Part: /word/footer2.xml, Line:0, Column:0 `

Is it possible to remove the footer before saving it? Or any other way to fix this issue?

**Comment by john-harrold** [comment]
Is it possible to recreate this with two empty or small documents and a short script? You should be able to drag all three of those into the comment window. It would be helpful in figuring out what's going on.

**Comment by mayanklal** [comment]
Sure, I will do it and share the files.

**Comment by mayanklal** [comment]
PFA the DOCX files (Cover_Page_SP.docx and report_body_2.docx) that I am merging to generate the output DOCX File (Sample_Report.docx).

Also, the code that I have used to merge the two DOCX files:

```
report_s1 <- read_docx(path =  'Cover_Page_SP.docx')
report_s1 <- body_add_break(report_s1)
report_s1 <- body_add_docx(report_s1,src = 'report_body_2.docx')

print(report_s1, target = 'Sample_Report.docx')
```


[report_body_2.docx](https://github.com/davidgohel/officer/files/6261773/report_body_2.docx)
[Cover_Page_SP.docx](https://github.com/davidgohel/officer/files/6261776/Cover_Page_SP.docx)
[Sample_Report.docx](https://github.com/davidgohel/officer/files/6261779/Sample_Report.docx)

**Comment by davidgohel** [comment]
my mistake, the issue does not occur if the image is deleted.

**Comment by davidgohel** [comment]
Closing the issue, I can't see any issue while running the reprex. and Opening a print dialog does not trigger any error message neither. So it's probably fixed by some other commits
