### ISSUE TITLE
body_add_plot throws an exception/error 

### ISSUE THREAD

**Issue by psc0425** [davidgohel/officer#361]
Just a simple test with officer

> doc <- read_pptx()
> doc <- add_slide(doc, 'Title and Content', 'Office Theme')
> doc <- officer::body_add_plot(doc,ggp,width = 7, height = 5)

body_add_plot throws an exception/error:

> Error: could not match any style named 'Normal' in c()
I didn't specify a style, I guess the default style name is 'Normal'
I can't find a style named 'Normal' in the default powerpoint start up template. 
What value I can put in its place?

**Comment by davidgohel** [comment]
yes, please read the manual https://ardata-fr.github.io/officeverse/officer-for-powerpoint.html

KR
