### ISSUE TITLE
Duplicate image printing when selecting images with the same name from different directories using the "body_add_fpar" or "compose" functions in a Word document.

### ISSUE THREAD

**Issue by EvPop21** [davidgohel/officer#365]
When I attempt to select different images with the same name from different folder directories using the "body_add_fpar" or "compose" functions in a Word document, officer repeats the first image each subsequent time rather than displaying each unique image. Note that this issue does NOT happen when using the "body_add_img" function.

Here is a small reproducible example:
```
my_doc <- read_docx()
my_doc <- body_add_fpar(my_doc, fpar(external_img(src = "./dir1/rlogo.png", height = 1, width = 1), fp_p = fp_par(text.align = "center")))
my_doc <- body_add_fpar(my_doc, fpar(external_img(src = "./dir2/rlogo.png", height = 1, width = 1), fp_p = fp_par(text.align = "center")))
print(my_doc, target = "test_doc.docx")
```
I've attached the two "rlogo.png". The first one in the example (in dir1) is the actual R logo and the second is a picture of a cat (in dir2). When the final document is printed, two images of the R logo are printed rather than one of the R logo and one of a cat.

![rlogo](https://user-images.githubusercontent.com/78435554/117209088-c076f880-adaa-11eb-8763-4804945b5999.png)
![rlogo](https://user-images.githubusercontent.com/78435554/117209103-c4a31600-adaa-11eb-9257-7c0b70a9f266.png)

Here is my sessioninfo():
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] officer_0.3.16

loaded via a namespace (and not attached):
[1] compiler_4.0.3 R6_2.5.0       tools_4.0.3    uuid_0.1-4     xml2_1.3.2     zip_2.1.1

**Comment by davidgohel** [comment]
thanks for reporting this.

PS: You should let people know you are cross posting... https://stackoverflow.com/questions/67511888/officer-r-duplicate-image-printing-when-selecting-images-with-the-same-name-fr

**Comment by davidgohel** [comment]
it is fixed in the github version
