### ISSUE TITLE
Control font size from body_add_table

### ISSUE THREAD

**Issue by brandonritchie** [davidgohel/officer#368]
I am trying to resize my tables that are being imported using body_add_table(). It would be nice if there was a way to resize the table by changing the font size. Thanks!

**Comment by davidgohel** [comment]
You can use argument `stylenames` and use defined stylenames (see `table_stylenames`). 

https://davidgohel.github.io/officer/reference/table_stylenames.html

You can also use package `flextable`

https://ardata-fr.github.io/flextable-book/
