### ISSUE TITLE
Would really like if add_slide() will not mutate the passed rpptx object

### ISSUE THREAD

**Issue by Sinha-Ujjawal** [davidgohel/officer#369]
Would really like if add_slide() or any other function in officer will not mutate the input

```r
library(officer)
library(magrittr)

x <- read_pptx()
# length(x) = 0

y <- x %>% add_slide()
# length(x) = 1
# length(y) = 1
```

All functions in officer mutates it's input and return the mutated rpptx object. This is kind of misleading for someone coming from functional programming paradigm, as he/ she will think that the input does not get mutated.

In my opinion, functions that mutates it's input should not return any value.

**Comment by davidgohel** [comment]
Thanks for your opinion. 

That implies to get rid of R6 which would require a lot of time. I am sorry I can't spend time on arguing about these things.
