### ISSUE TITLE
Appending slides to a PowerPoint object from an external file

### ISSUE THREAD

**Issue by cgrahamSRSA** [davidgohel/officer#371]
An interesting feature would definitely be something that would allow loading a powerpoint from a file and appending that to the current presentation object being worked on. This would make it so that closing slides or glossaries could be added based on template, rather then having to add such slides in post. This would be something similar to reading from the template in read_pptx, but it would simply append to the end of a current object

**Comment by davidgohel** [comment]
I am sorry, this would take lot of time - this is very difficult to achieve.
