### ISSUE TITLE
Error on summary of presentation containing a duplicated slide with a grouped object

### ISSUE THREAD

**Issue by davidjrea** [davidgohel/officer#373]
Found some weird behavior on summarizing a powerpoint slide resulting in the following error.

Error in x[, setdiff(col, colnames(x))] <- NA : 
  incorrect number of subscripts on matrix

This occurs when there is a duplicate slide with a grouped object AND additional content. Once the grouping is removed from the one of the slides, all is right with the world. 

An example presentation and code below can be [downloaded here](https://tinyurl.com/aaeex3ew). Deleting the second slide (or ungrouping the group on the second slide) results in a functioning summary. 

- [x] Provide the code that is producing the error, it has to be a minimal reproducible example.

[slide show and code download link again](https://tinyurl.com/aaeex3ew)
`
library(officer)
wd = ""
template.name = "2-slide grouped table.pptx"
pres_template<-read_pptx(paste0(wd,template.name))
pptx_summary(pres_template)
`
- [x] Provide the results of R command `sessionInfo()`.

R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] officer_0.3.18

loaded via a namespace (and not attached):
[1] compiler_4.0.5 R6_2.5.0       tools_4.0.5    uuid_0.1-4     xml2_1.3.2     zip_2.1.1  

- [x] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [x] Make sure you searched in the *open* and *closed* issues on the github repository.

**Comment by davidgohel** [comment]
thanks for reporting this bug

**Comment by davidgohel** [comment]
it's fixed only in the github version for now
