### ISSUE TITLE
Rotated Placeholder, angle is not preserved in PowerPoint 

### ISSUE THREAD

**Issue by pteridin** [davidgohel/officer#375]
Replacing a placeholder with an angle in the master slide with a value  removes the angle.

Minimal working example, Example.pptx contains a title that is angled 90°:
```r
library("officer")

read_pptx("Example.pptx") -> pptx

pptx %>% add_slide("Title and Content", "Office") -> pptx
pptx <- ph_with(pptx,
                 value = "Title",
                 location = ph_location_label("Title 1", "head"))

pptx %>% print("Example_Result.pptx")
```

Result: Example_Result.pptx contains a title that has no angle.

**Comment by davidgohel** [comment]
thanks for reporting this issue

**Comment by pteridin** [comment]
Cool. Thank you. 👍 
Will try it out.

**Comment by davidgohel** [comment]
@pteridin Thank. It's only on github for now and will be submitted to cran in few days.
