### ISSUE TITLE
Reading a DOCX with no "core properties"

### ISSUE THREAD

**Issue by dhicks** [davidgohel/officer#376]
I'm having problems using `officer` to read a DOCX file that doesn't appear to have "core properties."  

I don't fully understand how `officer` works, but things seem to happen as follows when I call `read_docx` on the attached file.  After creating a temporary folder to do the work, `unpack_folder()` unpacks the DOCX file into its various components.  `read_core_properties` is then called to parse the file `docProps/core.xml`, and specifically is looking at all of the children of the node `<cp:coreProperties>`.  However, in this case, there are no such children.  So `all_` and `names_` are lists of length 0.  `strplit` doesn't know what to do with this, resulting in `Error in strsplit(names_, ":") : non-character argument`.  

[EPA-HQ-OA-2018-0259-11819-1.docx.zip](https://github.com/davidgohel/officer/files/6703542/EPA-HQ-OA-2018-0259-11819-1.docx.zip)

Edit: Forgot to note that this is using `officer` 0.3.18 with R 4.1.0 on Mac OS 11.4.

**Comment by davidgohel** [comment]
thanks for reporting this. It's annoying but easy to fix!

**Comment by davidgohel** [comment]
Please, let me know if the latest github version fixed the problem

**Comment by dhicks** [comment]
Yes, that seems to have worked.  Thanks for the quick fix!

**Comment by mendald** [comment]
Does the CRAN version already contain this fix? I'm having the same problem. I get the following message: 

Error in strsplit(names_, ":") : non-character argument
In addition: Warning message:
In xml_find_all.xml_node(doc, "/cp:coreProperties/*") :
  Undefined namespace prefix [1219]
