### ISSUE TITLE
Unreadable content error when using hyperlink_ftext with ampersands

### ISSUE THREAD

**Issue by mat-x** [davidgohel/officer#377]
Using officer v0.3.18, when inserting a hyperlink containing an ampersand, Word reports that the content is unreadable. Looking at the xml it appears that `wml_link_hyperlink` is (silently) failing when these special characters are present.

Here's some code that works fine:
```
doc <- read_docx()
par <- fpar(hyperlink_ftext("click here", href = "http://www.google.com?a=1"))
doc <- body_add_fpar(doc, par)
print(doc, 'test1-noamp.docx')
```
... and here's some code which generates invalid/unreadable XML:
```
doc <- read_docx()
par <- fpar(hyperlink_ftext("click here", href = "http://www.google.com?a=1&b=2"))
doc <- body_add_fpar(doc, par)
print(doc, 'test1-amp.docx')
```

(NB. this looks similar to https://github.com/davidgohel/officer/issues/320 , but it seems to be a separate issue)

**Comment by mat-x** [comment]
As a workaround, removing the `htmlEscapeCopy` from `part_reference_hyperlink()` seems to work for my simple example.

**Comment by davidgohel** [comment]
Thanks, it is fixed
