### ISSUE TITLE
Export sparkline to officer

### ISSUE THREAD

**Issue by Temisesba** [davidgohel/officer#379]
Hello, first of all, thank you for all your contributions, I have the doubt if a flextable can be exported to office (word or power point) with its added sparkline.

I have tried but the table goes without the sparlines

**Comment by Temisesba** [comment]
I have done it by transforming it into an image but I would like to know how to do it and that the editable table format is maintained

**Comment by davidgohel** [comment]
Few minutes ago I recommend you to read the manual here: https://ardata-fr.github.io/flextable-book/cell-content-1.html#mini-charts

The chapter just before is talking about your question.

Please do not open issue each time you have a question. Read the manual first.
