### ISSUE TITLE
body_end_section_columns() not continous

### ISSUE THREAD

**Issue by hafabmedul** [davidgohel/officer#384]
modified from the given example of body_end_section_columns()

str1 <- "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
str1 <- rep(str1, 5)
str1 <- paste(str1, collapse = " ")

read_docx() %>% 
  body_add_par("test") %>% 
  body_end_section_continuous() %>% 
  body_add_par(value = str1, style = "Normal") %>% 
  body_add_par(value = str1, style = "Normal") %>% 
  body_end_section_columns() %>% 
  print("./temp.docx")

adds a page break after "test"

relevant lines (38-42) in document.xml of the word file:
> <w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml">
      <w:pPr>
        <w:sectPr>"/&gt;
<w:cols w:num="2" w:sep="0" w:space="360" w:equalWidth="0"><w:col w:w="3600" w:space="360"/><w:col w:w="3600"/></w:cols><w:pgSz xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" w:w="11900" w:h="16840"/><w:pgMar xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" w:top="1417" w:right="1417" w:bottom="1417" w:left="1417" w:header="708" w:footer="708" w:gutter="0"/></w:sectPr>
      </w:pPr>
    </w:p>

the error after <w:sectPr> is generated as such

the node is missing the following child to be continuous:
<w:type xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" w:val="continuous"/>

**Comment by davidgohel** [comment]
As a workaround or replacement functions, you can use the more generic `body_end_block_section()` instead of `body_end_section_columns()`. 

```
library(flextable)
library(officer)
library(magrittr)

library(officer)
str1 <- "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
str1 <- rep(str1, 20)
str1 <- paste(str1, collapse = " ")

ps <- prop_section(
  page_margins = page_mar(top = 1),
  section_columns = section_columns(),
  type = "continuous"
)

doc_1 <- read_docx()
doc_1 <- body_add_par(doc_1, value = str1, style = "Normal")
doc_1 <- body_add_par(doc_1, value = str1, style = "Normal")

doc_1 <- body_end_block_section(doc_1, block_section(ps))

doc_1 <- body_add_par(doc_1, value = str1, style = "Normal")

print(doc_1, target = "temp.docx")
```

**Comment by hafabmedul** [comment]
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2012 R2 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3    renv_0.14.0

**Comment by davidgohel** [comment]
Thanks, it's fixed now
