### ISSUE TITLE
Supporting short figure/table captions for list of figures/tables - Word output

### ISSUE THREAD

**Issue by paurrodri** [davidgohel/officer#388]
Issue based on https://github.com/rstudio/bookdown/issues/543, where the same feature has been discussed but for PDF output.

The captions of figures or tables often need to be long in order to provide the reader with an accurate explanation about what is being shown.
To prevent the list of figures from becoming too difficult to read, LaTeX is offering an optional argument in:
```
\caption[short description for list of figures/tables]{Here comes the full explanation, which can consist of multiple sentences. This is particularly useful when having multiple subfigures.}.
```
When knitting R markdown to pdf, there is already this option in argument "fig.scap"
```
{r foo, fig.cap="Long caption.", fig.scap="Short caption", out.extra=''}
```
However, using this argument when knitting to Word does not function, and the list of figures would still be using the "Long caption".

Could this be implemented in any way so that the list of figures/tables in Word can also accommodate shorter captions?

Thank you in advance.

**Comment by resistor4u** [comment]
This idea was raised in officedown [#57](https://github.com/davidgohel/officedown/issues/57) too. I was recently thinking `alt text` could offer a way to implement short captions. Officedown now enables alt-text in chunk options ([PR53](https://github.com/davidgohel/officedown/pull/53)), and I wonder if this could be hooked.

**Comment by resistor4u** [comment]
@paurrodri although not a fix, i had success testing with [this workaround](https://answers.microsoft.com/en-us/msoffice/forum/all/style-separator-in-word-2016-for-mac/200f764d-ab30-4ca4-86f3-02637884f7a1
) the other day.

**Comment by davidgohel** [comment]
This is about officedown not officer.

This is not a space for officedown, sorry for users that have reasonable needs/requests, officedown issues are not open for now.

@paurrodri I am sorry but Word does not allow short caption, it seems to me it's a pure PDF feature. So I can not be done.
