### ISSUE TITLE
Name drawing objects for `ggplot2` charts created using `rvg::dml`

### ISSUE THREAD

**Issue by daviddiviny** [davidgohel/officer#393]
This is a nice to have but it would be great if there was a way to name/label the objects created for editable vector graphics. 
As far as I can tell, the numbering of points in a `geom_point` scatter chart seems to follow the underlying data. 

![image](https://user-images.githubusercontent.com/6833387/140456003-950c3ace-66f7-470d-b735-5b4fbe50a1be.png)

**Comment by davidgohel** [comment]
This is not possible as it is made by R plot system

**Comment by davidgohel** [comment]
@daviddiviny this is officer repo, next time you want to open an issue, please go to RVG repo (don't know why I can't transfer it)

**Comment by davidgohel** [comment]
I forgot I closed the issue tab of RVG, my mistake
