### ISSUE TITLE
Several hyperlinks in a paragraph of a powerpoint file

### ISSUE THREAD

**Issue by cardiomoon** [davidgohel/officer#395]
Dear David,

I am maintainer of package rrtable.

I'd like to insert  several hyperlinks in a paragraph of a powerpoint file. For example, see the slide 16 of this link : https://view.officeapps.live.com/op/view.aspx?src=https://github.com/cardiomoon/rrtable/raw/master/inst/doc_examples/sampleData3.pptx

I have used ph_add_text() for this slide.

How I make this slide with multiple hyperlinks without ph_add_text() function?

I am tried ph_hyperlink() function, but failed to make the slide.

Sincerely,

Keon-Woong Moon

**Comment by davidgohel** [comment]
Dear Keon-Woong Moon,

To replace `ph_add_text ()`, you need to use a combination of `fpar()` and run function calls like `ftext()` and `hyperlink_ftext()`. You will find below an example:


```r 
library(officer)
library(magrittr)

par <- fpar(
  "You can download blabla: ",
  hyperlink_ftext(
    href = "https://cran.r-project.org/index.html",
    text = "some text"), 
  " - view some spoons ",
  hyperlink_ftext(
    href = "https://www.gettyimages.fr/photos/spoon",
    text = "some spoons")
)

ppt_template <- read_pptx() %>%
  add_slide() %>%
  ph_with(par, location = ph_location_type(type = "body")) %>% 
  print("demo.pptx")
```

<img width="1007" alt="Capture d’écran 2021-11-12 à 09 17 06" src="https://user-images.githubusercontent.com/4331618/141433830-43f07335-2610-46b0-ba52-cb49fe1e7238.png">

**Comment by cardiomoon** [comment]
Dear David,

Thank you very much !!
