### ISSUE TITLE
Alternative text for tables with chunk option

### ISSUE THREAD

**Issue by camitz** [davidgohel/officer#396]
As in davidgohel/officedown#53, but for tables. Same motivation, accessibility.

I haven't looked into much and as in pr davidgohel/officedown#53, I expect I'll make an attempt, although I find myself stressed for time at this moment....

`table.alt`?

**Comment by davidgohel** [comment]
This is now complete. Chunk options `tab.alt.title` and `tab.alt.description` can be used as alternative text for tables in Word (with officer and flextable since few versions and with officedown now).
