### ISSUE TITLE
Plots using the base plotting recorded to Object by recordPlot() not working on PPT

### ISSUE THREAD

**Issue by MSBICOE** [davidgohel/officer#406]
in the old package: ReporteRs, I can add the plot into the slides by recording a base plot to an Object by recordPlot(). foe instance:
plot(data)
mychart <-  recordPlot()

with ReporteRs this works:
myppt %>%   addPlot(print, x = mychart) 

However, this recorded chart is not working in Officer, as my below slides come with error:

ph_with(myppt, value =  mychart, location = ph_location_label(ph_label = "Content Placeholder 2"))

SO I have to save the mychart to an image and then added as an image. by adding an image then each element in the mychart was no longer editable which I was able to in the old package.

Could you help? if I did anything wrong here, or there is another way to do it?

Thanks!

**Comment by davidgohel** [comment]
This is a very, very difficult point (as difficult as to comply with the guidelines you deleted when posting that Q). If I explain, I'll probably end up advising you to read the `ph_with` manual and maybe even click on a link or read the examples section (you can't figure out how it is difficult!). 

<img width="1185" alt="Capture d’écran 2022-02-18 à 09 39 48" src="https://user-images.githubusercontent.com/4331618/154648309-02457fef-ec7f-43a4-91ea-01557e3cd0c8.png">

I don't think it's reasonable to ask users to read the doc that is available at any moment when using R, we should rather stop the discussion here.
