### ISSUE TITLE
Reading xls files

### ISSUE THREAD

**Issue by msgoussi** [davidgohel/officer#408]
I am using your package to read xlsx file and its properties (read_xlsx &  doc_properties)
however if the file extension is "xls", I get an error (Error: read_xlsx only support xlsx files)
is it possible that your fuction read_xlsx can read xls too

**Comment by davidgohel** [comment]
No, the only supported format is `xlsx` (see manual or html manual here: https://davidgohel.github.io/officer/reference/read_xlsx.html)

The function does only read files ending with `xlsx`.

It can not read for example: 

* `*.xlsm`
* `*.xls`
* LibreOffice
* CSV
