### ISSUE TITLE
how to locate ph_label when the ph_label in  slide is not unique

### ISSUE THREAD

**Issue by leechaowen** [davidgohel/officer#419]
hello, how to locate ph_label when the ph_label in the  current slide is not unique ? Please view the codes.

```

> my_presentation <- read_pptx(here("pptTemplate","MY.template.pptx"))
> 
> 
> 
> 
> (layout_properties ( x = my_presentation, layout = "Title Page",master='PresentationTemplate2017' ))
                 master_name       name     type    id               ph_label                                                  ph       offx      offy
5   PresentationTemplate2017 Title Page     body    15 Content Placeholder 11                       <p:ph sz="quarter" idx="12"/> 11.8240934 6.8211800
10  PresentationTemplate2017 Title Page     body    12 Content Placeholder 11                       <p:ph sz="quarter" idx="11"/>  9.0000000 6.8211800
11  PresentationTemplate2017 Title Page     body     3  Content Placeholder 2                       <p:ph sz="quarter" idx="10"/>  6.8246533 6.8211811
119 PresentationTemplate2017 Title Page ctrTitle 22531               Title_TM         <p:ph type="ctrTitle" hasCustomPrompt="1"/>  0.5243056 0.5208333
120 PresentationTemplate2017 Title Page subTitle 22530            SubTitle_TM <p:ph type="subTitle" idx="1" hasCustomPrompt="1"/>  0.5243056 4.5381944
           cx        cy rotation
5   0.9815212 0.3142356       NA
10  2.7504823 0.3142356       NA
11  2.0893252 0.3142345       NA
119 9.1354178 3.7812511       NA
120 5.9843766 2.2829867       NA
> 
> 
> my_presentation <- ph_with(my_presentation, "bala.bala,test test", 
+                            location = ph_location_label(ph_label = "Content Placeholder 2")) 

> my_presentation <- ph_with(my_presentation, "bala.bala something",
+                            location = ph_location_label(ph_label = "Content Placeholder 11"))
Error in fortify_location.location_label(location, doc = x) : 
  Placeholder "Content Placeholder 11" in the slide layout is duplicated. It needs to be unique.
 
```

![image](https://user-images.githubusercontent.com/44858442/164178486-ae36005f-403d-4f06-a44a-572cfe6fcf0d.png)

**Comment by leechaowen** [comment]
Could add such function  **ph_location_id**  . it seems the id is unique  when run layout_properties to check.


```
> my_presentation <- ph_with(my_presentation, "bala.bala something",
+                            location = ph_location_id(id=12))
Error in ph_location_id(id = 12) : 
  could not find function "ph_location_id"
```

**Comment by davidgohel** [comment]
labels/id should be unique. If you want to use two identical id, there is no way to guess which one you want to use.

Please read discussion https://github.com/davidgohel/officer/discussions/415

**Comment by leechaowen** [comment]
> labels/id should be unique. If you want to use two identical id, there is no way to guess which one you want to use.
> 
> Please read discussion #415

yes.  it seems there is no way to rename the labels by MS powerpoint when using the template design by others . i delete the duplicated placeholder , then click insert  same placeholder button one by one, ther ph_label is unique but it's tired. tired for users, what's worse changing  the raw template format. I think it's better to add such function ph_location_id . the id for all ph_labels in each slide is unique. Why not ?

**Comment by davidgohel** [comment]
Today, there are (from the doc here: https://ardata-fr.github.io/officeverse/officer-for-powerpoint.html#content-location): 

`ph_location_label(), ph_location_fullsize(), ph_location_left(), ph_location_right(), ph_location_template(), ph_location_type(), ph_location()`

With `ph_location_type()` you can select for example a *body* shape with id 12. Why would I write another function that do the same than `ph_location_type()`?

**Comment by leechaowen** [comment]
Thanks. it's wondelful. I'm on learning it.

**Comment by john-harrold** [comment]
I've run into this in the past. It's easier just to delete one of the placeholders and recreate it. It should (but you know, maybe it wont) create a new placeholder label.

**Comment by davidgohel** [comment]
Just to be sure, you can rename label which are used as ID in PowerPoint easily:

<img width="983" alt="Capture d’écran 2022-04-21 à 11 57 01" src="https://user-images.githubusercontent.com/4331618/164430648-c769ab55-b572-4b78-b9c7-c8adb0918792.png">
