### ISSUE TITLE
Landscape mode creates a blank page in portrait mode

### ISSUE THREAD

**Issue by mbaqiraltaf** [davidgohel/officer#42]
Hi David,

I am trying to create a Landscape section in the word document using Officer package. See below code:

`library(officer)

library(flextable)

library(dplyr)

df <- data.frame(replicate(5,sample(0:1,10,rep=TRUE)))

flexTableObj <- flextable::flextable(data = df)

doc <- officer::read_docx()

doc %>% officer::body_add_par(value = '\r\n', style = "Normal") 

doc %>% flextable::body_add_flextable(flexTableObj)

doc %>% officer::body_add_par(value = '\r\n', style = "Normal") 

doc %>% officer::body_end_section(landscape = TRUE)

print(doc, target = "E:/test.docx")`

The generated document has an empty page at the end in portrait mode and first page is in Landscape mode. So , I want to remove this last empty page, I tried below code snippet to solve this issue

`doc %>% cursor_end() %>% body_remove()`

It removed the portrait empty page but then it changed the alignment of entire document into portrait which is not required. I want entire document in landscape mode 

Thanks

**Comment by davidgohel** [comment]
yep, known issue: 

https://github.com/davidgohel/officer/blob/master/R/docx_add.R#L374

#34

**Comment by samiaab1990** [comment]
> yep, known issue:
> 
> https://github.com/davidgohel/officer/blob/master/R/docx_add.R#L374
> 
> #34

Hi David,
I'm having the same issue and a little confused understanding the solution. Is there a way to fix the last page printing an empty portrait mode page? 
Thank you

**Comment by Logowilliams** [comment]
Hi David,
I'm also having the same issue. It seems as though the solution was to use the `continuous` argument in `body_end_section` but that function is now defunct. Is there another solution to fix the last page printing an empty portrait mode page?
Thank you!

**Comment by davidgohel** [comment]
You can read #325
