### ISSUE TITLE
Set arbitrary properties in a doc

### ISSUE THREAD

**Issue by markpayneatwork** [davidgohel/officer#420]
In `officer` it is currently possible to set some of metadata fields associated with a docx via the `set_doc_properties()` function:

```
set_doc_properties(
  x,
  title = NULL,
  subject = NULL,
  creator = NULL,
  description = NULL,
  created = NULL
)
```

However, the range of values that can be set is a subset of all of the properties that are supported by Word. In addition, it is also possible to define custom properties.

**Suggestion** Add a `...` argument to `set_doc_properties()` that accepts a name-value pair for arbitrary document properties

**Why?** This is potentially very valuable if you are trying to create documents en-masse from R with `officer`, as it provides an easy way to insert arbitrary fields into e.g. a form letter. Given the challenges that can be encountered with find-and-replace in word, the use of document fields and quick text fields provides a much more robust approach to automatic document generation from R.

**Comment by davidgohel** [comment]
I did some trials, and this is indeed a very good suggestion. I'll provide something soon. 

All values will be expected as character values.

**Comment by davidgohel** [comment]
Now this code can work:

```r
library(officer)

doc <- read_docx()
doc <- set_doc_properties(x = doc, title = "zzz", coco = "value1", youyou = "value2") 
fp <- fpar(
  run_word_field(field = "DOCPROPERTY \"coco\""),
  ftext(" blah blah blah blah blah "),
  run_word_field(field = "DOCPROPERTY \"youyou\"")
)
doc <- body_add_fpar(doc, value = fp)
print(doc, target = "zz.docx")
#browseURL("zz.docx")

```

<img width="449" alt="Capture d’écran 2022-06-09 à 21 24 26" src="https://user-images.githubusercontent.com/4331618/172928190-c0bd8f83-341f-4d8b-943f-e51365fa95b8.png">

🎉
