### ISSUE TITLE
body_remove_before_cursor sister function for body_remove

### ISSUE THREAD

**Issue by luceydav** [davidgohel/officer#422]
I needed a way routinely to split many word documents into segments based on the title in separate sections as keywords, but this was not possible just with body_remove.  I asked and received a function which meets this objective on SO here: https://stackoverflow.com/a/72018891/9854823 by https://stackoverflow.com/users/9393213/the-mad-statter.

**Comment by davidgohel** [comment]
Thank you, I already had read that SO question and upvoted the answer.
