### ISSUE TITLE
example_toc.docx doesn't look like example in documentation. 

### ISSUE THREAD

**Issue by ltrainstg** [davidgohel/officer#425]
# Problem: example_toc.docx example doesn't seem to include table of figures or table of tables anymore. 

I was using the documentation [Here](https://ardata-fr.github.io/officeverse/officer-for-word.html). When I downloaded the example an updated the TOC the Table of figures and Table of tables don't include the tables as in the example picture on the site. 

![image](https://user-images.githubusercontent.com/16125810/168335851-34b19515-9793-4c38-bb7c-c9defde528c0.png)

# Questions: 
Where can I find the code that makes 'example_toc.docx?
Is this caused by an update in how word handles TOC or is this feature busted in the current version, I know it used to work on previous versions. 

# Info 
RVersion: ‘4.1.2’
Officer: '0.4.2'

**Comment by davidgohel** [comment]
I can't reproduce your issue

<img width="838" alt="Capture d’écran 2022-05-14 à 11 54 57" src="https://user-images.githubusercontent.com/4331618/168420804-1c87ffe5-11b5-4ca7-952e-0bf5a6807f5c.png">

> Where can I find the code that makes 'example_toc.docx?

This is in a private repo. So you can't find it. here it is:
[word_example.docx](https://github.com/davidgohel/officer/files/8692674/word_example.docx)
