### ISSUE TITLE
How do I "update" custom document properties after setting them?

### ISSUE THREAD

**Issue by tanho63** [davidgohel/officer#433]
Hello! Been looking into filling word documents with character strings from R lately and I see you've just added some features for this with `set_doc_properties()` which is super exciting!

I'm having trouble "rendering" the properties once they're set with R. Screen recording of issue here:

https://user-images.githubusercontent.com/38083823/173363713-dc3df12c-4b15-49f0-8bcb-fdafaf0ef0ef.mp4

### Reprex files:
[reprexdoc.docx](https://github.com/davidgohel/officer/files/8891407/reprexdoc.docx)
[output.docx](https://github.com/davidgohel/officer/files/8891408/output.docx)

### Code
```r
library(officer)
x <- read_docx("reprexdoc.docx")
doc_properties(x)
x <- set_doc_properties(
  x,
  tan_custom_field_one = "Tan's Custom Field #1",
  tan_custom_field_two = "Tan's Custom Field #2"
)
doc_properties(x)
print(x,target = "output.docx")
```

<details> <summary> Session Info </summary> 

```
> sessioninfo::session_info()
- Session info -----------------------------------------------------------------------------
 setting  value                       
 version  R version 4.1.1 (2021-08-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_Canada.1252         
 ctype    English_Canada.1252         
 tz       America/New_York            
 date     2022-06-13                  

- Packages ---------------------------------------------------------------------------------
 package     * version date       lib source                             
 cachem        1.0.6   2021-08-19 [1] standard (@1.0.6)                  
 callr         3.7.0   2021-04-20 [1] standard (@3.7.0)                  
 cli           3.3.0   2022-04-25 [1] standard (@3.3.0)                  
 crayon        1.5.1   2022-03-26 [1] standard (@1.5.1)                  
 curl          4.3.2   2021-06-23 [1] standard (@4.3.2)                  
 desc          1.4.0   2021-09-28 [1] standard (@1.4.0)                  
 devtools      2.4.2   2021-06-07 [1] standard (@2.4.2)                  
 ellipsis      0.3.2   2021-04-29 [1] standard (@0.3.2)                  
 fastmap       1.1.0   2021-01-25 [1] standard (@1.1.0)                  
 fs            1.5.2   2021-12-08 [1] standard (@1.5.2)                  
 glue          1.6.2   2022-02-24 [1] standard (@1.6.2)                  
 httr          1.4.3   2022-05-04 [1] standard (@1.4.3)                  
 joker         0.0.3   2021-09-29 [1] Github (tanho63/joker@0adc9db)     
 lifecycle     1.0.1   2021-09-24 [1] standard (@1.0.1)                  
 magrittr      2.0.3   2022-03-30 [1] standard (@2.0.3)                  
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.1.2)                     
 officer     * 0.4.3   2022-06-13 [1] Github (davidgohel/officer@36254b8)
 pkgbuild      1.2.0   2020-12-15 [1] standard (@1.2.0)                  
 pkgload       1.2.2   2021-09-11 [1] standard (@1.2.2)                  
 prettyunits   1.1.1   2020-01-24 [1] standard (@1.1.1)                  
 processx      3.5.3   2022-03-25 [1] standard (@3.5.3)                  
 ps            1.7.0   2022-04-23 [1] standard (@1.7.0)                  
 purrr         0.3.4   2020-04-17 [1] standard (@0.3.4)                  
 R6            2.5.1   2021-08-19 [1] standard (@2.5.1)                  
 remotes       2.4.1   2021-09-29 [1] standard (@2.4.1)                  
 rlang         1.0.2   2022-03-04 [1] standard (@1.0.2)                  
 rprojroot     2.0.2   2020-11-15 [1] standard (@2.0.2)                  
 rstudioapi    0.13    2020-11-12 [1] standard (@0.13)                   
 sessioninfo   1.1.1   2018-11-05 [1] standard (@1.1.1)                  
 testthat      3.0.4   2021-07-01 [1] standard (@3.0.4)                  
 usethis       2.0.1   2021-02-10 [1] standard (@2.0.1)                  
 uuid          0.1-4   2020-02-26 [1] standard (@0.1-4)                  
 withr         2.5.0   2022-03-03 [1] standard (@2.5.0)                  
 xml2          1.3.3   2021-11-30 [1] standard (@1.3.3)                  
 zip           2.2.0   2021-05-31 [1] standard (@2.2.0)                  

[1] C:/Users/TanHo/Documents/R/win-library/4.1
[2] C:/Program Files/R/R-4.1.1/library
```
</details>

**Comment by tanho63** [comment]
I believe I'm looking for the equivalent of calling "Ctrl-A, F9" (but from R)

**Comment by davidgohel** [comment]
Hello

I am afraid I can't do anything here. Package officer do not rely on VBA or COM/OLE technologies.

There are solutions to be run after the docx generation:

* There are VBA solutions like this one (I never tested it) : https://www.msofficeforums.com/word-vba/38290-update-fields-all-documents-folder.html
* Users are invited to set Word option "Field shading" value "Always" - see https://support.microsoft.com/en-au/office/update-fields-7339a049-cb0d-4d5a-8679-97c20c643d4e#:~:text=Update%20all%20fields%20in%20a%20document,-Press%20Ctrl%20%2B%20A&text=Tip%3A%20To%20make%20sure%20that,for%20Update%20fields%20before%20printing.
* and probably other solutions based on COM/OLE technologies

Finally, if the purpose is to be able to get a PDF from the Word document, I wrote `doconv::docx2pdf()` and it pops up documents and ask for refreshing the field values before creating the PDF file (but you need Word to be installed on your machine).

**Comment by tanho63** [comment]
Interesting, thank you! I'll instruct user on workaround for now, I guess. 

On a related topic - have you ever looked at the python package [docx-mailmerge](https://github.com/Bouke/docx-mailmerge/blob/master/mailmerge.py)? My python is a bit shaky but it looks like it's doing all the work in XML + python, so something similar could be implemented within officer? 

I'd be happy to try and deconstruct/work on it if you think it could be worthwhile

**Comment by davidgohel** [comment]
You can propose a PR of course. 

It is possible to mimic mailmerge, but I think users will also want automatic TOC calculations, references updates, page numbers updates, etc. So the function must warn users that it is only to prefill Word field of type `DOCPROPERTY` and the maintainer of this feature will have to be there to explain (again and again) to users it only replaces  `DOCPROPERTY` values ;)

**Comment by eusebe** [comment]
Hi, 

If you are on Windows, you can use powershell to update fields. From within R, you could try the following function:

```
update_fields <- function(x) {
    path <- normalizePath(x)
    script <- paste0(tempdir(), ".ps1")
    cat('$word = new-object -com Word.Application\n', file = script, sep = "")
    cat('$doc = $word.Documents.add("', path, '")\n', file = script, append = TRUE, sep = "")

    cat('$doc.Fields.Update()\n', file = script, append = TRUE, sep = "")
    
    cat('$tocs = $doc.TablesOfContents\n', file = script, append = TRUE, sep = "")
    cat('foreach ($toc in $tocs)\n', file = script, append = TRUE, sep = "")
    cat('{\n', file = script, append = TRUE, sep = "")
    cat('  $toc.update()\n', file = script, append = TRUE, sep = "")
    cat('}\n', file = script, append = TRUE, sep = "")
    
    cat('$word.Visible = $False\n', file = script, append = TRUE, sep = "")
    cat('$saveFormat = [Enum]::Parse([Microsoft.Office.Interop.Word.WdSaveFormat],"wdFormatTemplate")\n', file = script, append = TRUE, sep = "")
    cat('$doc.SaveAs("', path, '")\n', file = script, append = TRUE, sep = "")
    cat('$doc.Close()\n', file = script, append = TRUE, sep = "")
    cat('$word.Quit()\n', file = script, append = TRUE, sep = "")
    
    system2("powershell", args=c("-file", script))
    file.remove(script)
    invisible(path)
}
update_fields("output.docx")
```

I am not a powershell expert, so it could be improved, and I'm not sure it will work in all cases. But it seems to correctly update the fields of your document.

**Comment by davidgohel** [comment]
Thank you a lot David
We will try to had this soon

**Comment by davidgohel** [comment]
It should be now ok with package 'doconv' (the version 0.1.4 is not on cran yet).

```r
remotes::install_github("ardata-fr/doconv")
```

It makes this possible (see last call `docx_update()`):

```r
library(officer)
library(doconv)

read_docx() |> 
  body_add_fpar(
    value = fpar(
      run_word_field("DOCPROPERTY \"custom_field_one\" \\* MERGEFORMAT"))) |>
  body_add_fpar(
    value = fpar(
      run_word_field("DOCPROPERTY \"custom_field_two\" \\* MERGEFORMAT"))) |>
  set_doc_properties(
    custom_field_one = "Custom Field #1",
    custom_field_two = "Custom Field #2"
  ) |>
  print(target = "output.docx") |>
  docx_update()
```
[output.docx](https://github.com/davidgohel/officer/files/9160141/output.docx)

```
to_miniature("output.docx", fileout = "output.png")
```

![output](https://user-images.githubusercontent.com/4331618/180239148-76be3f75-f6e5-42f3-86d0-78e7bd942ec3.png)

**Comment by davidgohel** [comment]
I am cloing the issue as it is now implemented in doconv
