### ISSUE TITLE
Avoid Table splitting between two consecutive pages

### ISSUE THREAD

**Issue by sigeek** [davidgohel/officer#434]
Hi, 

I was wondering if there is the possibility of not letting a table split between two consecutive pages, if not, will it be possible to implement it? Please check the 'dummy' example below.

Current output:
![scenario-1](https://user-images.githubusercontent.com/48796281/173545597-872f6559-3774-403b-b685-0c53d5d1762e.PNG)

Expected output:
![scenario-2](https://user-images.githubusercontent.com/48796281/173545690-2f87c660-1f68-4ac1-8fbc-e12a70719027.PNG)

To add a table to the doc, I am using the following code:

`officer::read_docx()  -> my_doc`

`my_doc %>%`
  `body_add_table(df, style = "table_template")  -> my_doc`

  
Many thanks,
Silvia

**Comment by davidgohel** [comment]
Hello,

(Next time, provide a full reproducible example so I can give an answer that looks like the document you want.)

We advise to use 'flextable' package, it provides the option you want (and much more...)

```r
library(officer)
library(flextable)
library(magrittr)

ft <- flextable(head(iris))

my_doc <- read_docx() %>% 
  body_add_flextable(ft, split = FALSE) %>% 
  print(target = "example.docx")
```

See https://ardata-fr.github.io/flextable-book/ for more informations.
