### ISSUE TITLE
Cannot add text after adding flextable

### ISSUE THREAD

**Issue by bescoto** [davidgohel/officer#44]
I get an error when trying to add text to a slide after after adding a flextable.  My understanding is that the code below should work, but instead it raises a "subscript out of bounds" error.
```
library(tidyverse)
library(flextable)
library(officer)

ft <- flextable(data.frame(a=1:2, b=3:4))
ppt <- (read_pptx()
  %>% add_slide(layout="Title and Content", master="Office Theme")
  %>% ph_with_flextable_at(ft, left=1, top=1)
  %>% ph_with_text(type="body", str="foo")
  %>% ph_add_par(level=2)
  %>% ph_add_text(str="bar"))
```
Thanks!

**Comment by davidgohel** [comment]
Thanks for that. Can you update (with github version)? It should be solved.

**Comment by bescoto** [comment]
Works much better now, thanks for the fix!
