### ISSUE TITLE
Argument to close Slide Master when producing Powerpoint from template-file which was saved with Slide Master opened

### ISSUE THREAD

**Issue by thohan88** [davidgohel/officer#448]
First of all, thanks for this package - it is truly great!

One thing I have noticed in my workflow is that if you leave a PPT-template with the Slide Master opened, the new presentation produced by reading this template (`read_pptx`) and producing a new presentation (`print`) results in a presentation where the Slide Master is kept open.

I usually iterate back and forth in a template and forget to close the Slide Master and this stings me every time. I have seen it confuse some of my colleagues where they have delivered presentations to end-users with the caveat that "you have to close Slide Master every time you open this". 

I am humble that this may not be easy to achieve, but thought I would suggest it either way. Thanks again for the great package!

**Comment by davidgohel** [comment]
Thanks

I found the attribute to remove to make sure 'Slide Master View' is closed automatically. The fix is implemented.
