### ISSUE TITLE
Issue 360 not yet resolved

### ISSUE THREAD

**Issue by sda030** [davidgohel/officer#452]
Issue [ #360 ] is not yet resolved, at least for Windows 10. From what I can see from the [code](https://github.com/davidgohel/officer/blob/master/R/utils.R#L251), there is no check if the file is opened and write-accessible, just whether the file exists. Should it not be something like `tryCatch()` with an informative error message asking user to close the file first? (` file.access()` does not really work either for this kind of "check before writing").

``` r
library(officer)
x <- read_docx()
print(x, target="test.docx")
# File is opened
print(x, target="test.docx") 
# RStudio and Rgui crashes
```

<sup>Created on 2022-11-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.1 (2022-06-23 ucrt)
#>  os       Windows 10 x64 (build 22621)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  nb.utf8
#>  ctype    nb.utf8
#>  tz       Europe/Berlin
#>  date     2022-11-03
#>  pandoc   2.19.2 @ C:/Program Files/RStudio/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.4.1   2022-09-23 [1] CRAN (R 4.2.1)
#>  digest        0.6.30  2022-10-18 [1] CRAN (R 4.2.1)
#>  evaluate      0.17    2022-10-07 [1] CRAN (R 4.2.1)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.0.3)
#>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.1.2)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.1.2)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.0.5)
#>  htmltools     0.5.3   2022-07-18 [1] CRAN (R 4.2.1)
#>  knitr         1.40    2022-08-24 [1] CRAN (R 4.2.1)
#>  lifecycle     1.0.3   2022-10-07 [1] CRAN (R 4.2.1)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.1.3)
#>  officer     * 0.4.4   2022-09-09 [1] CRAN (R 4.2.1)
#>  purrr         0.3.5   2022-10-06 [1] CRAN (R 4.2.1)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.2.1)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [1] CRAN (R 4.2.0)
#>  R.utils       2.12.1  2022-10-30 [1] CRAN (R 4.2.1)
#>  R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.1)
#>  reprex        2.0.2   2022-08-17 [1] CRAN (R 4.2.1)
#>  rlang         1.0.6   2022-09-24 [1] CRAN (R 4.2.1)
#>  rmarkdown     2.17    2022-10-07 [1] CRAN (R 4.2.1)
#>  rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.1)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.1.2)
#>  stringi       1.7.8   2022-07-11 [1] CRAN (R 4.2.1)
#>  stringr       1.4.1   2022-08-20 [1] CRAN (R 4.2.1)
#>  styler        1.8.0   2022-10-22 [1] CRAN (R 4.2.1)
#>  uuid          1.1-0   2022-04-19 [1] CRAN (R 4.2.0)
#>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.1.2)
#>  xfun          0.34    2022-10-18 [1] CRAN (R 4.2.1)
#>  xml2          1.3.3   2021-11-30 [1] CRAN (R 4.1.2)
#>  yaml          2.3.6   2022-10-18 [1] CRAN (R 4.2.1)
#>  zip           2.2.2   2022-10-26 [1] CRAN (R 4.2.1)
#> 
#>  [1] C:/Users/py128/OneDrive - NIFU/R
#>  [2] C:/Users/py128/AppData/Local/Programs/R/R-4.2.1/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

<sup>Created on 2022-11-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sda030** [comment]
I recall Office used these temporary ~$-files, but apparently not anymore.
Not easy to fix this. a simple tryCatch(print()) does not work. And you already have a tryCatch in your [pack_folder()](https://github.com/davidgohel/officer/blob/8e8cb26c68d50088c6a9e9d13c5e8a3a2b8b06e2/R/pack_folder.R#L23). 

I identified the issue to be in zip::zipr(), as this also results in crash. I will bring the issue over to them.
``` r
library(officer)
x <- read_docx()  
print(x, target="test.docx")
# Open test.docx-file in Word
cat("test", file="testfile.txt")
zip::zipr(zipfile = "test.docx", files = "testfile.txt")
```

<sup>Created on 2022-11-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.1 (2022-06-23 ucrt)
#>  os       Windows 10 x64 (build 22621)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  nb.utf8
#>  ctype    nb.utf8
#>  tz       Europe/Berlin
#>  date     2022-11-03
#>  pandoc   2.19.2 @ C:/Program Files/RStudio/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.4.1   2022-09-23 [1] CRAN (R 4.2.1)
#>  digest        0.6.30  2022-10-18 [1] CRAN (R 4.2.1)
#>  evaluate      0.17    2022-10-07 [1] CRAN (R 4.2.1)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.0.3)
#>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.1.2)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.1.2)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.0.5)
#>  htmltools     0.5.3   2022-07-18 [1] CRAN (R 4.2.1)
#>  knitr         1.40    2022-08-24 [1] CRAN (R 4.2.1)
#>  lifecycle     1.0.3   2022-10-07 [1] CRAN (R 4.2.1)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.1.3)
#>  officer     * 0.4.4   2022-09-09 [1] CRAN (R 4.2.1)
#>  purrr         0.3.5   2022-10-06 [1] CRAN (R 4.2.1)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.2.1)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [1] CRAN (R 4.2.0)
#>  R.utils       2.12.1  2022-10-30 [1] CRAN (R 4.2.1)
#>  R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.1)
#>  reprex        2.0.2   2022-08-17 [1] CRAN (R 4.2.1)
#>  rlang         1.0.6   2022-09-24 [1] CRAN (R 4.2.1)
#>  rmarkdown     2.17    2022-10-07 [1] CRAN (R 4.2.1)
#>  rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.1)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.1.2)
#>  stringi       1.7.8   2022-07-11 [1] CRAN (R 4.2.1)
#>  stringr       1.4.1   2022-08-20 [1] CRAN (R 4.2.1)
#>  styler        1.8.0   2022-10-22 [1] CRAN (R 4.2.1)
#>  uuid          1.1-0   2022-04-19 [1] CRAN (R 4.2.0)
#>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.1.2)
#>  xfun          0.34    2022-10-18 [1] CRAN (R 4.2.1)
#>  xml2          1.3.3   2021-11-30 [1] CRAN (R 4.1.2)
#>  yaml          2.3.6   2022-10-18 [1] CRAN (R 4.2.1)
#>  zip           2.2.2   2022-10-26 [1] CRAN (R 4.2.1)
#> 
#>  [1] C:/Users/py128/OneDrive - NIFU/R
#>  [2] C:/Users/py128/AppData/Local/Programs/R/R-4.2.1/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by sda030** [comment]
I do notice that utils::zip() does not result in the crash, but simply returns:
`zip I/O error: Device or resource busy
zip error: Could not create output file (test.docx)`

Although I am as a huge fan of r-lib packages as I am of officeverse, perhaps returning to `utils` is an option. Though let us try to fix `zip` first.

**Comment by davidgohel** [comment]
Just a note to correct that `is_office_doc_edited()` is still used. Maybe it's buggy but it's used

`utils::zip()` is not really an option as it requires another external dependency 'zip.exe' on Windows.

**Comment by mtkerbeR** [comment]
I think windows still uses temporary lock files starting with ~$ generally, at least if the file is saved locally or on a network drive/fileshare. 

However, behaviour might be different if the file is saved at a location where it is editable by different users at the same time (I observed this behaviour on a SharePoint lately).
@sda030 
could you confirm such a difference between different locations the file is saved to?

@davidgohel 
Happy to provide a PR if this is something you would consider to put into the package - although this additional condition looks very very Windows-specific from my point if view.

**Comment by davidgohel** [comment]
For some reasons, Rstudio crash on Windows because package 'zip' try to write the doc that a user is editing with Office. 

That sounds as a weird collision with Vendor products, I am really not sure someone should spend his free time fixing that issue in officer, it's probably out of control of what can do officer. 

@mtkerbeR I would welcome a PR if you don't waste too much time on it and if it is a simple replacement to `is_office_doc_edited()`, is it possible?

**Comment by sda030** [comment]
I would wait until they fix it in the zip package, it is a bug in C code there. It should then resolved itself in officer. The $ temporary file Office used to leave seems to be phasing out with the cloud services? Dont know, but i do not (always) see it. Perhaps they now keep the lock file in a different temp folder?

**Comment by GegznaV** [comment]
Is the issue that you need to check if a file is open on Windows? If yes, you cannot rename the file, so `suppressWarnings(!file.rename(from = file, to = file))` may do the trick. In some of my code, I use, e.g.:

```r
# Part 1
library(officer)
x <- read_pptx()
print(x, "tmp.pptx")
# Open the file:
browseURL("tmp.pptx")
```
```r
# Part 2
file <- "tmp.pptx"

if (file.exists(file)) {
  print(paste0("File '", file, "' exists"))
  if (suppressWarnings(!file.rename(from = file, to = file))) {
    stop("Please close this PowerPoint file: \n", file)
  }
} else {
    print(paste0("File '", file, "' is not found."))
}
```

**Comment by GegznaV** [comment]
@sda030, I proposed a fix in #486. You may install `officer` with the fix via
```r
remotes::install_github("davidgohel/officer#486")
``` 

and try it.

**Comment by sda030** [comment]
This has also now been fixed upstream in the zip-package.

**Comment by davidgohel** [comment]
cool, I can now spend time again on that to delete all workarounds that has been written :)

**Comment by davidgohel** [comment]
yes true :)

But my initial intention is bad, the solution of @GegznaV is quite healthy and should be kept, even with the fix of zip, it still has an interest as it warns the user that the file is opened. 

So I think you're right to close the issue. There is nothing else to do, am I thinking right?

**Comment by sda030** [comment]
Yes, issue can be closed.
