### ISSUE TITLE
Open Source Licensing Issue

### ISSUE THREAD

**Issue by chunky** [davidgohel/officer#457]
We're trying to get a package released into the R ecosystem, but at the moment we're running afoul of licensing problems: Most notably, the inability to legally mix-n-match GPL-v2-only and GPL-v3-only packages. The R ecosystem at large doesn't consider this a big stopping issue, but my company is generally legally more risk-averse.

At the moment, I see that Officer is GPL-v3-only. Would it be possible to change the license of Officer to something more license-compatible with other R packages?

Tidyverse and R-lib took the steps, over the last few years, to license all of the modules under it as MIT: https://www.tidyverse.org/blog/2021/12/relicensing-packages/

I realise that MIT is strongly divergent from GPL in spirit; if you have strong feelings about copyleft licensing, would you be open to making the license for officer be "GPL-v2-or-higher", instead of "GPL-v3-only"?

Thank you for considering this

**Comment by davidgohel** [comment]
Hello,

OK for me

**Comment by davidgohel** [comment]
Dear @hangler, @elsander, @vectorson, @jonmcalder, @john-harrold, @muschellij2, @billdenney, @beckni, @trekonom, @gregleleu,

- [ ] Frank Hangler
- [ ] Liz Sander
- [ ] Anton Victorson
- [ ] Jon Calder
- [ ] John Harrold
- [ ] John Muschelli
- [ ] Bill Denney
- [ ] Nikolai Beck
- [ ] Stefan Moog
- [ ] Greg Leleu

Would you permit us to re-license officer with the MIT license? If so, please comment "I agree" below.

**Comment by gregleleu** [comment]
I agree

Grégoire Leleu
+1 (917) 714-7284
+33 6 63 01 53 39
***@***.***


________________________________

**Comment by muschellij2** [comment]
I agree
Best,
John

**Comment by john-harrold** [comment]
I agree.

**Comment by billdenney** [comment]
I agree

**Comment by jonmcalder** [comment]
I agree

**Comment by vectorson** [comment]
I agree

**Comment by hangler** [comment]
I agree.

**Comment by elsander** [comment]
I agree.

**Comment by beckni** [comment]
I agree

**Comment by trekonom** [comment]
I agree

**Comment by davidgohel** [comment]
Thanks to everybody, it's on CRAN now.
