### ISSUE TITLE
[regression] headers & footers replace_text_at_bkm

### ISSUE THREAD

**Issue by MRMHmdeleeuw** [davidgohel/officer#459]
Hello, thanks again for the officeverse. We use a fairly evolved MS Word template for knitting our R markdown reports and it has multiple sections with different headers and footers including a first section with a `Different first page` setting. These headers and footers contain bookmarked placeholders e.g. `doctitle` and `docversion` that get populated from YAML content respectively gitr using a custom knit function. This all worked with officer 0.4.4. Now with officer 0.5.0 and the current development version 0.5.1.003, we get errors like

```
Error: cannot find bookmark 'docversion'
```

seemingly for all bookmarks that are not systematically present at all pages, when calling for instance

```
officer::footers_replace_text_at_bkm("docversion", paste("version:", gitversion))
```

I should perhaps add that this all is done to a copy of the tempate before any rendered content is added with a `officer::body_add(template, officer::block_pour_docx(rendered))`. Now if I patch `docx_replace.R` from 0.5.1.003 with

```
123c123,124
<     xml_replace_text_at_bkm(node = header$get(), bookmark = bookmark, value = value)
---
>     if (header$has_bookmark(bookmark))
>       xml_replace_text_at_bkm(node = header$get(), bookmark = bookmark, value = value)
144c145,146
<     xml_replace_text_at_bkm(node = footer$get(), bookmark = bookmark, value = value)
---
>     if (footer$has_bookmark(bookmark))
>       xml_replace_text_at_bkm(node = footer$get(), bookmark = bookmark, value = value)
```

then all is back to normal. It seems these `has_bookmark` tests were removed in the Dec. 20 commit "internals: refactor docx cursor". IMHO these are still needed - could you please consider putting these tests back in place? 

I hope the explanation above is sufficient, I cannot share my company template for a reprex. Thanks and regards - Meilleurs voeux.

**Comment by davidgohel** [comment]
Sorry for that, I will push a fix soon.

I don't like these functions. They are essentially here because users want to change headers/footers and this could be replaced by a function that enable headers and footers definitions.  
Since version `0.5.0`, it is possible to defined (default/first/even) headers & footers content. Would you consider using `prop_section()` instead? I think it's far better because the process can be totally coded in R.

**Comment by davidgohel** [comment]
Could you try the new dev version please?

**Comment by davidgohel** [comment]
I will re-open if necessary :)

**Comment by MRMHmdeleeuw** [comment]
Many thanks for the quick follow-up, yes `officer 0.5.1.007` solves the issue. I agree replacing bookmarks in templates is not very much aligned with the spirit of the officeverse and that at the face of it, `officer::pop_section` provides required primitives to create our template in R code indeed. But this is a bit of a paradigm shift for us and the immediate gains of such endeavours are probably more on the side of powerpoint generation, which we will likely tackle first in 2023.

**Comment by davidgohel** [comment]
thanks for your feedback.

1. Glad your issue is fixed
2. no problem for “not migrating” now :) I understand time is limited!
