### ISSUE TITLE
The slides in Powerpoint are sorted/ordered alphabetically 

### ISSUE THREAD

**Issue by EmilBrink** [davidgohel/officer#46]
Dear Mr. David Gohel,

I'm a newbie in R and right in the beginning I have started working with ReporteRs and Officer. I have noticed after a while that Oficcer's pptx-slides are sorted alphabettically while ReportRs' not. 

For example: To adress the 10th. slide of a 23-pages pptx file, I have to write index = 2 instead of index = 10.
my_pres <- read_pptx(path = "*.pptx")
my_pres <- my_pres %>% 
  on_slide(index = 2)

I have managed to find the Officer-index for each slide of this 23-pages PowerPoint File, but when there's more pages, it would be a little bit time consuming. I hope that this issue would be fixed somewhen.

Update: Thank you very much! I updated the package and the problem is solved. Next time I'll ask a better question in the right way.

**Comment by davidgohel** [comment]
Dear Emil

Can you test with the new github version?

JTLYK, I couldn't use your code...

**Comment by davidgohel** [comment]
it should be fixed, I am closing the issue.
