### ISSUE TITLE
Some DOCX files created by officer (>= 0.5.0) can't be opened in Word

### ISSUE THREAD

**Issue by nkempkens** [davidgohel/officer#464]
Hello,

First of all, I very much appreciate your package that has greatly helped improving the workflow in my department.

Unfortunately, starting with version 0.5.0, the docx files created by _officer_ can't be opened in Word and are shown as corrupted:

![officer1](https://user-images.githubusercontent.com/122272797/211295641-9495a387-cdb6-4fa9-8bcb-58cb3a825733.png)
![officer2](https://user-images.githubusercontent.com/122272797/211295671-b3845c97-b052-4f95-93fb-4be26d97bd2f.png)
![officer3](https://user-images.githubusercontent.com/122272797/211295686-ae19266e-1a9e-41f8-91df-d3d846fda296.png)

The files can still be opened in LibreOffice without problems. By testing different versions of _officer_, I could track the problem back to the change from version 0.4.4 to 0.5.0. One colleague has confirmed me that files created with version >= 0.5.0 no longer open in Word.

I am using a Word template with a header and a footer and bookmarks that are automatically replaced with plots/text using officer. I'm using the print function to write docx files.

I can't easily provide a minimal working example since code and data used are confidential but I will try to provide one if necessary.

Best regards,

Niels

**Comment by davidgohel** [comment]
yes, please provide a reproducible example as I don't know how to see your issue.

**Comment by davidgohel** [comment]
here is a base that may help to recreate a repex:

```
  template <- system.file(package = "officer", "doc_examples/example.docx")
  img.file <- file.path( R.home("doc"), "html", "logo.jpg" )

  doc <- read_docx(path = template)
  doc <- headers_replace_img_at_bkm(x = doc, bookmark = "bmk_header",
                                    value = external_img(src = img.file, width = .53, height = .7))
  doc <- footers_replace_img_at_bkm(x = doc, bookmark = "bmk_footer",
                                    value = external_img(src = img.file, width = .53, height = .7))
  print(doc, target = "test_replace_img.docx")
```

**Comment by nkempkens** [comment]
Thank you very much for your reply. I have run some tests and found that the problem seems to be with my template file. It used to work with officer <= 0.4.4 but produces a corrupted Word output file from version 0.5.0 onwards.

Here is the code:
```
library(officer)

# template <- system.file(package = "officer", "doc_examples/example.docx") # this template works
template <- "template_test.docx" # this results in a corrupted file when printed (version >= 0.5.0) although the template itself can be opened without problem in Word

doc <- read_docx(path = template)
print(doc, target = "officer_print_test.docx")
```

Here are the files:
[template_test.docx](https://github.com/davidgohel/officer/files/10374342/template_test.docx)
[officer_print_test.docx](https://github.com/davidgohel/officer/files/10374343/officer_print_test.docx)

If make a new template in Word from scratch, the officer output is fine also. So I may have to do that for all my templates or just continue using version <= 0.4.4 of officer.

**Comment by davidgohel** [comment]
I can reproduce thanks

I will fix soon. It's related to #447

**Comment by andrewppurdy** [comment]
Hi David,

I wasn't sure whether to raise this as a separate issue, but it seems related to this one. Let me know if I should raise this separately.

I've started using the PowerPoint elements of officer (can't thank you enough for this package) and I'm having issues with the outputs needing to be repaired.

It seems like it's my template that is causing issues. I've done some tests, by reading in a blank .pptx file and saving it, then opening the output in PowerPoint and it doesn't need to be repaired. I checked the document properties, but couldn't see anything out of place - perhaps there's something else wrong with my template?

### reprex
`PPT<-officer::read_pptx("Template.pptx")%>%
      print(target="test.pptx")`

### template

[Template.pptx](https://github.com/davidgohel/officer/files/10487064/Template.pptx)

Thank you in advance,

Andrew

**Comment by davidgohel** [comment]
@andrewppurdy thanks, yet totally related. It is the same issue and the same code that make these docs invalid.

**Comment by davidgohel** [comment]
it should be fixed now, thanks for reporting
