### ISSUE TITLE
toc numbers of tables at the top automatically updated

### ISSUE THREAD

**Issue by jwijffels** [davidgohel/officer#467]
Hello David.

I've been looking and digging deep into the R code of officedown, pandoc, officer and rmarkdown to see what a possible solution could be to the following issue.
I'm using `officedown::rdocx_document` to render a markdown document. In the markdown document, it uses `block_pour_docx` to incorporate an external docx file. This file has tables with `Table Caption` and autonumbering similar as used in officer.
I want to add a table of content of the tables.
- If I add the table of content of the table at the top, the autonumbering is not updated, while the table of content of the tables at the bottom of the report the autonumbering are updated.
- How can I update the TOC of the 'Table Caption' elements at the top, without pressing refresh in MS Word?

I have the impression, this is coming from the sequence of code in `officer:::print.rdocx` as when I looked in the markdown that it generated, the 2 table of contents were the same, also just after `pandoccing` the markdown. I further looked at the post_processor to see how the intermediate steps gave resulting docx files but again there the top and bottom Table Caption table of content was different.

Hereby the test.Rmd, the extra external docx and the resulting test.docx Word file and the table of tables at the top and bottom
[toc-tables.zip](https://github.com/davidgohel/officer/files/10519650/toc-tables.zip)

![image](https://user-images.githubusercontent.com/1710810/215108117-56b26d49-db29-4836-b4ec-e8012d02c1c3.png)

![image](https://user-images.githubusercontent.com/1710810/215108243-67b2b831-a1d7-41cd-982d-576dad5c988f.png)

.

**Comment by davidgohel** [comment]
Hello

You probably need `doconv::docx_update()`, see here https://github.com/ardata-fr/doconv#update-word-fields-and-toc

**Comment by jwijffels** [comment]
Right. So that uses a powershell script. I was hoping to host things on Linux...
- What is the reason why the bottom TOC of Table Captions is correct and the top one is not? 
- Do you think it would be possible to run it at the end (such that it is updated) and insert it at the front of the Word document?

**Comment by davidgohel** [comment]
1. To me, without any manual intervention, the doc looks like that:

<img width="863" alt="Capture d’écran 2023-01-27 à 15 59 24" src="https://user-images.githubusercontent.com/4331618/215117870-41de56b2-9c5d-4587-9160-b40587080a55.png">
<img width="881" alt="Capture d’écran 2023-01-27 à 15 59 32" src="https://user-images.githubusercontent.com/4331618/215117875-b7990d2f-3374-4050-b303-7164761172da.png">

2. No. You're are using Word computed fields, they must be computed by Word, there is nothing officer can do here.

**Comment by jwijffels** [comment]
That's funny. 
About 1/ you are right, I can reproduce this on another machine.
About 2/ So word computes this at opening of the document?

**Comment by davidgohel** [comment]
yes, *something* (unfortunately Word only, LibreOffice is just a bad clone that can't do it) need to lay out the content to get the correct page number at the bottom for examples, same for tables references, TOC, etc

**Comment by davidgohel** [comment]
Not having linux as alternative is disappointing but in the other hand, it's better to have win and mac than nothing :)

**Comment by davidgohel** [comment]
See also https://ardata-fr.github.io/officeverse/faq.html#update-fields, why we can force their update

**Comment by jwijffels** [comment]
> Not having linux as alternative is disappointing but in the other hand, it's better to have win and mac than nothing :)
yes, but for the thing I was working on, this might have serious implications

And the reason why I saw the above screenshots while you saw something else and I could reproduce this on another Windows machine might be related to having an on-premises version of SharePoint that has the Word Automation Services?

**Comment by davidgohel** [comment]
I know nothing about SharePoint and Word Automation Services, sorry

**Comment by jwijffels** [comment]
Many thanks David for your time. Much appreciated!
