### ISSUE TITLE
block_pout_docx() dose not work as before

### ISSUE THREAD

**Issue by jimewu** [davidgohel/officer#473]
# Provide the code that is producing the error

I am running the example code:

```
library(officer)
docx <- tempfile(fileext = ".docx")
doc <- read_docx()
doc <- body_add(doc, iris[1:20,], style = "table_template")
print(doc, target = docx)

target <- tempfile(fileext = ".docx")
doc_1 <- read_docx()
doc_1 <- body_add(doc_1, block_pour_docx(docx))
print(doc_1, target = target)
```

while the output file of the variable 'docx' does contain the iris[1:20,] table, the output file of the variable 'target' is empty, *i.e.*, `block_pour_docx()` did not work.

It used to work on my machines (two), yet recently I try to regenerate my report file and found that it does not work anymore. I am wondering if it is caused by system upgrade of some libraries that broke this feature, yet I tried my own build of R (4.1.3) instead of the latest version (4.2.2) and re-build every package but no luck.

# SessionInfo

the sessionInfo for R-4.2.2 (official package by Archlinux) is as the following:

```
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libopenblas.so.0.3
LAPACK: /usr/lib/liblapack.so.3.11.0

locale:
 [1] LC_CTYPE=zh_TW.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=zh_TW.UTF-8        LC_COLLATE=zh_TW.UTF-8    
 [5] LC_MONETARY=zh_TW.UTF-8    LC_MESSAGES=zh_TW.UTF-8   
 [7] LC_PAPER=zh_TW.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=zh_TW.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.2
```

the sessionInfo for R-4.1.3 (my own build) is as the following:

```
R version 4.1.3 (2022-03-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS:   /opt/R/4.1.3/lib64/R/lib/libRblas.so
LAPACK: /opt/R/4.1.3/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=zh_TW.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=zh_TW.UTF-8        LC_COLLATE=zh_TW.UTF-8    
 [5] LC_MONETARY=zh_TW.UTF-8    LC_MESSAGES=zh_TW.UTF-8   
 [7] LC_PAPER=zh_TW.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=zh_TW.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] officer_0.5.2

loaded via a namespace (and not attached):
[1] compiler_4.1.3 R6_2.5.1       uuid_1.1-0     xml2_1.3.3     zip_2.2.2     
[6] openssl_2.0.5  askpass_1.1   
```

**Comment by davidgohel** [comment]
I am sorry I can't reproduce:

<img width="1294" alt="Capture d’écran 2023-02-15 à 11 14 25" src="https://user-images.githubusercontent.com/4331618/218999104-e65fc411-63a2-4633-b8d6-69715a3f1a51.png">


````
> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] officer_0.5.2

loaded via a namespace (and not attached):
[1] compiler_4.2.2  R6_2.5.1        tools_4.2.2     rstudioapi_0.14 uuid_1.1-0     
[6] xml2_1.3.3      zip_2.2.2       openssl_2.0.5   askpass_1.1
````

**Comment by davidgohel** [comment]
can you show/share the file you got (file `target`)

**Comment by jimewu** [comment]
![Screenshot_20230215_233500](https://user-images.githubusercontent.com/7069687/219074968-d24db157-f81a-4419-b5c0-d925906b7b55.png)

As shown in the above screenshot, the 'docx' is the 'file811b414b5.docx', and the 'target' is the 'file8486bdd5c.docx'

![Screenshot_20230215_233803](https://user-images.githubusercontent.com/7069687/219075907-35bb3a58-5f6d-4ae2-b091-a03622d3cc6d.png)


![Screenshot_20230215_233813](https://user-images.githubusercontent.com/7069687/219075921-ea97f166-9cd3-456d-8011-2e3fd3a6bf69.png)

both docx files are available in the below zip file

[file8.zip](https://github.com/davidgohel/officer/files/10744730/file8.zip)

**Comment by davidgohel** [comment]
<img width="1172" alt="Capture d’écran 2023-02-15 à 16 42 28" src="https://user-images.githubusercontent.com/4331618/219076863-b107d10d-c1cc-4a93-b8b0-8d9459d91cec.png">

**Comment by davidgohel** [comment]
So the problem is you are not using 'office Word' but another product. Only Word can interpret Word instructions (sometimes people are advising for LibreOffice but it never handled sections and many different details)

**Comment by jimewu** [comment]
Oh! Thank you. I never thought it is because the word processor. BTW, I tried wps-office and libreoffice-fresh, both yield a blank page. The only one I see the iris table successfully in the 'file8486bdd5c.docx' on linux is the onlyoffice suite.

Anyway, thanks a lot!
