### ISSUE TITLE
print word document create a reverse document

### ISSUE THREAD

**Issue by hg6ux** [davidgohel/officer#477]
I installed officer version 0.6.1 today and when I print the word document this document is reversed (eg. when I open the .docx file it is in reverse order compared to the doc object I have created in officer).
The routine I am using was working fine previously. 
Is there something new with this version that I missed.
Thanks in advance for your help.

**Comment by davidgohel** [comment]
see https://github.com/davidgohel/officer/discussions/476

**Comment by hg6ux** [comment]
Hi David,
Thanks for your quick response. 
It now works fine.
Also many thanks for providing this great package!
