### ISSUE TITLE
external_img(guess_size = T) segfaults with SVG images

### ISSUE THREAD

**Issue by hoeflerb** [davidgohel/officer#478]
When adding an image to a Powerpoint slide using ph_with(x, external_img) the option to guess the size of the image using magick does not work with SVG images. The issue seems to be with the magick::image_read function that is used by external_img.

From, R/ooxml_run_objects.R:
```
external_img <- function(src, width = .5, height = .2, unit = "in", guess_size = FALSE, alt = "") {
  ...
  if (guess_size) {
    if (!requireNamespace("magick", quietly = TRUE)) {
      stop("package magick is required when using `guess_size` option.")
    }
    sizes <- lapply(src, function(x) {
-->     z <- magick::image_read(x)    <--
      z <- magick::image_data(z)
      attr(z, "dim")[-1]
    })
    sizes <- do.call(rbind, sizes)
    width <- sizes[,1] / 72
    height <- sizes[,2] / 72
  }
```
This bug report to the magick project suggests that for SVG files image_read_svg should be used instead of image_read,
https://github.com/ropensci/magick/issues/156

I can confirm this with my own testing
`magick::image_read('./test.svg')`
  --> R session crashes

```
magick::image_read_svg('./test.svg')
format width height colorspace matte filesize density
1    PNG   504    324       sRGB  TRUE        0 +72x+72
```

**Comment by davidgohel** [comment]
Hello 

I could not reproduce on mac and windows. Could you try the latest github version please? I added a patch with your instructions about image_read_svg

**Comment by hoeflerb** [comment]
Strange...I can't get it to segfault anymore. The magick::image_read command still crashes the R session, but officer somehow isn't susceptible to that and just prints a warning message,
```
Warning message:
ImageMagick was built without librsvg which causes poor qualty of SVG rendering.
For better results use image_read_svg() which uses the rsvg package.
```
After installing the newest version from HEAD, the warning message goes away and everything seems to be working perfectly. Thanks!

**Comment by davidgohel** [comment]
well, I followed your instructions so thanks to you ;)
