### ISSUE TITLE
How to get the text of a paragraph and edit it?

### ISSUE THREAD

**Issue by MichaelTanger** [davidgohel/officer#48]
dear david:
    I have a word file,and it has some paragraphs. Now how  to get the text of a paragraph and edit it? Like edit <paragraphs.text>(in python ),thanks!

**Comment by davidgohel** [comment]
I don't know about ` <paragraphs.text>(in python )`.

You can get the content of a document, see here: https://davidgohel.github.io/officer/articles/officer_reader.html

You can insert, replace, remove content also, see here: https://davidgohel.github.io/officer/articles/word.html
