### ISSUE TITLE
Unable to print ppt where file does not have core properties

### ISSUE THREAD

**Issue by lajh87** [davidgohel/officer#487]
Hello - 

I recently updated officer from version 4.2 to 6.2. Now when trying to print the powerpoint I receive the error

`C:\Users\{user}\AppData\Local\Temp\RtmpG0nwwE\file449c4bb23647/docProps/app.xml does not exist`

Reverting back to a previous version of the package fixes the problem. I suspect it is related to the warning message

```
In read_core_properties(package_dir) :
  No properties found. Using properties from template file in officer.
```
When reading in the powerpoint. 

It looks like the original powerpoint was generated using google docs.

**Comment by davidgohel** [comment]
Hello

When submitting a new issue:

- [ ] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [ ] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [ ] Make sure you searched in the *open* and *closed* issues on the github repository.
