### ISSUE TITLE
pptx option to specify line spacing to be a multiple (e.g. 1.15)

### ISSUE THREAD

**Issue by las-matthew-bennett** [davidgohel/officer#490]
I've been using this package to automatically produce slides that we have until now been making manually. 

One thing that I can't seem to do though with fp_par is to set the line spacing to be a mutliple (in my case I'm trying to have 1.15, like you can in powerpoint). (I've seen the closed [issue 235](https://github.com/davidgohel/officer/issues/235) saying that line spacing per se is not supported, but I wonder if that's changed).

The only way I can mimic the spacing is to include a lot of blank lines with an appropriate font size interspersed between the lines containing the text. This is obviously not good if someone wants to edit the slides manually at a later date...

Would it be possible to add this feature to this already highly useful package?

Thanks!
Matt

**Comment by davidgohel** [comment]
Yes it changed, you can now use `fp_par(line_spacing = 3)`
