### ISSUE TITLE
Bug with docx_set_paragraph_style

### ISSUE THREAD

**Issue by datascienceadvice** [davidgohel/officer#495]
Hello!
Function **docx_set_paragraph_style** destroys heading property.
Initial state:
```
doc <- read_docx()
#doc <- docx_set_paragraph_style(doc, style_id = "Titre1", style_name = "heading 1")
doc <- body_add_par(doc, "Test", style = "heading 1")
print(doc, target = "D:/test.docx")
```

![image](https://user-images.githubusercontent.com/80515841/234916646-48e1f9c2-1b19-4088-89cb-00c7c6bf068d.png)
Modification:
```
doc <- read_docx()
doc <- docx_set_paragraph_style(doc, style_id = "Titre1", style_name = "heading 1")
doc <- body_add_par(doc, "Test", style = "heading 1")
print(doc, target = "D:/test.docx")
```

![image](https://user-images.githubusercontent.com/80515841/234916910-6fcf6774-b899-4833-bae1-3d63f9e4eef0.png)

**Comment by davidgohel** [comment]
see the doc `?officer::docx_set_paragraph_style`

> The function lets you add or replace a Word paragraph style.

In your case you *destroyed* your formatting properties of paragraph "heading 1" by replacing them by a new set of formatting properties - these new properties are defined as default argument.

I think you wanted "add or update one of these properties" but you get "replace a whole set of properties by another set of properties". 

You could instead create a new one based on an existing one (see argument `base_on` in the documentation), it will inherit all properties except those of the used `fp_par()` object. You should not replace headings unless you are OK with only the supported features of `fp_par()`.

```
library(officer)
doc <- read_docx()
doc <- docx_set_paragraph_style(doc, base_on = "heading 1", style_id = "myheading1", style_name = "my heading 1",
                                fp_p = fp_par(text.align = "right"))
doc <- body_add_par(doc, "Test", style = "my heading 1")
print(doc, target = "test.docx")
```

<img width="1145" alt="Capture d’écran 2023-05-02 à 22 49 02" src="https://user-images.githubusercontent.com/4331618/235782563-13230dc7-5daa-4dfb-b63c-46b1012c6c37.png">
