### ISSUE TITLE
docx bookmarks support?

### ISSUE THREAD

**Issue by t-kalinowski** [davidgohel/officer#5]
ReportRs supported bookmarks in docx files to replace content. The nearest functionality in `officer` appears to be `cursor_reach`, but that seems less precise and more dangerous than a bookmark. 

Are there plans to add support for bookmarks. Something like a `cursor_jump_to_bookmark()` function and/or a family of  `body_replace***(..., bookmark)` functions would be very nice.

**Comment by davidgohel** [comment]
Yes, there will be a support for bookmarks.

`cursor_reach` is not less precise (btw, since last commit, it supports regexpr in paragraphs). Bookmarks can be set up along several paragraph, that makes things more complicated.

[...]`body_replace***(..., bookmark)`[...]: use `body_add_par(pos = "on")` instead; `pos="on"` means *replace*. 

David

**Comment by t-kalinowski** [comment]
Thank you, that's good to hear.

Just to clarify: when I say it's less precise, I mean for my particular use case. I'm trying to shoehorn a reproducible workflow while collaborating with people over docx files... as such, I can't reliably depend on that within a certain document, "bookmark" phrases will consistently be there, or for that matter, be uniquely identifiable, when other people are editing the document. While, in theory, bookmarks share the same problem, in practice, nobody edits them.

**Comment by t-kalinowski** [comment]
To make this example a little more specific, for example, `cursor_reach` currently moves to the first instance of a snippet of text. In this case, if I am trying to move to a section by searching for the secion heading, I can't get past the corresponding entry in an already built TOC.

**Comment by davidgohel** [comment]
Hi

cursor can now reach paragraphs with a bookmark (functions `cursor_bookmark` to reach a bookmark and `body_bookmark` to set programmatically a bookmark).

David
