### ISSUE TITLE
Support for run_autonum in quarto

### ISSUE THREAD

**Issue by eeenilsson** [davidgohel/officer#501]
I have been using the code below in rmarkdown::knitr successfuly to reset the numbering counter for tables and figures, inserting it where I need to reset the counter. Unfortunately it does not work in Quarto docx documents.

It would be very nice to be able to use this in Quarto.

```

```{r} 
#| output: false
officer::run_autonum(
             seq_id = "fig",
             pre_label = "",
             start_at = 0,
             prop = fp_text(
  color = "white",
  font.size = 0)
  )
## Note: Reset figure numbering NOT working in qmd
``` 

```

**Comment by davidgohel** [comment]
It works, you chose `font.size = 0`, this makes a text with font size 0 (Quarto 1.3 is used).

``````
---
title: "Untitled"
format: docx
---

```{r} 
library(officer)
library(officedown)
run_autonum(seq_id = "fig")
```


```{r} 
library(officer)
library(officedown)
officer::run_autonum(
             seq_id = "fig",
             pre_label = "test",
             start_at = 0,
             prop = fp_text(color = "red")
  )
```


``````

<img width="1036" alt="Capture d’écran 2023-05-20 à 09 40 08" src="https://github.com/davidgohel/officer/assets/4331618/0e0c8d44-81f3-4192-8bf9-be4235111437">

Also, using a 0 index is maybe not a good idea (the doc states it should be a positive integer).


Please provide a minimal reproducible example next time

**Comment by eeenilsson** [comment]
Thanks! However, this does not work as in knitr (with `output: officedown::rdocx_document:`), where the r chunk with `run_autonum` **resets** the counter and all following figure numbers are based on that, ie starts again from 1, 2, 3 etc, without explicitly calling `run_autonum` again.

So, run_autonum does indeed run in quarto, producing output, but it does not not restart the innate figure counter in the Quarto `output: docx` and its not possible to render using `output: officedown::rdocx_document:` in Quarto. I suppose it could be used as a workaround in .qmd but then one would have to suppress the innate numbering and include `run_autonum` in each figure chunk.

I guess what im really asking for is a way to reset the figure/table counter innately in Quarto, but i realize thats not a question for Officer but for Quarto.

A minimal working example below.


````

---
title: "Test reset autonum for supplement"
format: docx
---

```{r} 
library(officer)
library(officedown)
run_autonum(seq_id = "fig")
```

## Figures

```{r} 
#| label: fig-plot
#| fig-cap: Plot.
plot(1:10, 1:10)

``` 
 
## Supplementary figures

These should _restart_ from "Figure S1" @fig-supplementary-figure-s1. Instead it continues the counter, ie "Figure 2".

```{r} 
officer::run_autonum(
             seq_id = "fig",
             pre_label = "This is output from run_autonum: ",
             start_at = 0, ## set to 0 so that next figure is Fig S1
             prop = fp_text(color = "red")
  )
## Note: The purpose of this chunk is to reset the counter like it does in knitr.
```

```{r} 
#| label: fig-supplementary-figure-s1
#| fig-cap: Histogram.

hist(airquality$Temp)

``` 

```{r} 
#| label: fig-supplementary-figure-s2
#| fig-cap: Boxplot.


boxplot(airquality$Temp)

``` 


````

**Comment by eeenilsson** [comment]
Tested using the workaround to use run_autonum in each figure block, but it messes up the cross-references plus I found no way to suppress the numbering that is also done by quarto.

**Comment by davidgohel** [comment]
It does work. You are not using `run_autonum` as it should be used and support for caption is working in Quarto, although there is no intention to. Here is a solution adapted from the documentation here https://ardata-fr.github.io/officeverse/officedown-for-word.html#custom-cross-reference: 


`````
---
title: "Untitled"
format: docx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(officer)
library(officedown)
library(flextable)
```



`r run_autonum(seq_id = "tab", bkm = "airquality1")`truc machin chose

```{r}
as_flextable(airquality)
```

This is a reference to bookmark `airquality`: `r run_reference(id = "airquality1")`

\newpage

`r run_autonum(seq_id = "tab", bkm = "airquality2")`truc machin chose

```{r}
as_flextable(airquality)
```

This is a reference to bookmark `airquality`: `r run_reference(id = "airquality2")`

\newpage

`r run_autonum(seq_id = "tab", bkm = "airquality3", start_at = 1)`truc machin chose

```{r}
as_flextable(airquality)
```

This is a reference to bookmark `airquality`: `r run_reference(id = "airquality3")`

\newpage

`r run_autonum(seq_id = "tab", bkm = "airquality4")`truc machin chose

```{r}
as_flextable(airquality)
```

This is a reference to bookmark `airquality`: `r run_reference(id = "airquality4")`

`````


The result as a miniature:

![image](https://github.com/davidgohel/officer/assets/4331618/7130dc5e-ace7-478e-b17d-0709db1acdb6)



Quarto is not 'R Markdown' and from my understanding it does or will do the job of managing captions, auto numbering, title references and whatever you'd like to have. 

Package 'officer' provides (**in addition to the main functions** to create Word or PowerPoint documents from R) tools that help to enrich 'R markdown' documents, the scope of the package is not to improve Quarto. See https://ardata-fr.github.io/officeverse/index.html#officer.
