### ISSUE TITLE
Figure and table titles integration in a new Word document

### ISSUE THREAD

**Issue by TSeuH** [davidgohel/officer#508]
Hello,

I use officer to output my results in a Word document. From this output, I then copy my figures and tables, and paste them to a new Word document (which is my final statistical report).

I wanted to have consistent titles for figures and tables, use bookmarks to create tables of contents in my statistical report, and be able to use cross-references to my figures and tables titles.

I have created the following functions:

```
body_add_caption_table <- function(x, title, bkm.name, pos = "after") {
  value <- block_caption(title,
                         style = "table title",
                         autonum = run_autonum(seq_id = "tab", 
                                               bkm = bkm.name, 
                                               bkm_all = TRUE,
                                               pre_label = "Table ", 
                                               post_label = ". "))
  
  out <- to_wml(value, add_ns = TRUE, base_document = x)
  body_add_xml(x = x, str = out, pos = pos)
}

body_add_caption_figure <- function(x, title, bkm.name, pos = "after") {
  value <- block_caption(title,
                         style = "graphic title",
                         autonum = run_autonum(seq_id = "fig", 
                                               bkm = bkm.name, 
                                               bkm_all = TRUE,
                                               pre_label = "Figure ", 
                                               post_label = ". "))
  
  out <- to_wml(value, add_ns = TRUE, base_document = x)
  body_add_xml(x = x, str = out, pos = pos)
}
```

I had two questions regarding my solution:
1. Could it be possible to change font family and size for the title AND the "pre_label"/"post_label" strings?
2. Once I copy/paste my results with titles into my statistical report, the only way I found to create a table of content is to do it manually by creating a "Table of Figures" and changing the options to find the styles created in R (either "table title" or "graphic title"). Then, to do a cross-reference, it has to be a bookmark, and not a "Figure" or a "Table". Plus, if I was to add a new figure or table manually directly into my statistical report, it wouldn't be a bookmark, thus the tables of content won't be correctly updated. Is there a way to tell R that my titles should be referenced as "Table" object or "Figure" object in Word, and not "bookmark"?

Thank you for your help.

Best regards, 
TS

**Comment by davidgohel** [comment]
I think your functions are a little bit complicated. I don't know why you are using `to_wml()` + `body_add_xml()`. But ok, maybe you have good reasons.

> I had two questions regarding my solution:

1. yes, with `fpar()`. See https://ardata-fr.github.io/officeverse/paragraphs-chunks.html
2. I am not sure if I get it, you are manually doing things and there is a lot of "if/then/thus" and I am lost :) I think if you are not satisfied with `run_autonum()` you need to invest time on Word computed fields that can be generated with `run_word_field()`. There are a lot of documentation on the web about that, and you can examine the content of the XML file to understand what you want to do if you don't want to use officer functions
