### ISSUE TITLE
Cursor_bookmark() looks inoperant in v0.6.2

### ISSUE THREAD

**Issue by dsapinho** [davidgohel/officer#509]
As explicited in the title, in the v0.6.2 the cursor_bookmark() function looks unable to point to the cursor in the word document, as it did well in the v0.4.3 
The script : 
library(remotes)
install_version("officer","0.4.3")
library(officer)
packageVersion("officer")
doc = read_docx(path = "Doc_Cursor.docx")
cursor_bookmark(doc, 'Pos_Cursor')
body_add_par(doc, "Text to add at the cursor")
print(doc,"Doc_Cursor_out_0_4_3.docx")

install_version("officer","0.6.1")
library(officer)
packageVersion("officer")
doc = read_docx(path = "Doc_Cursor.docx")
cursor_bookmark(doc, 'Pos_Cursor')
body_add_par(doc, "Text to add at the cursor")
print(doc,"Doc_Cursor_out_0_6_2.docx")

And the input/outputs :
[Doc_Cursor_out_0_6_2.docx](https://github.com/davidgohel/officer/files/11830177/Doc_Cursor_out_0_6_2.docx)
[Doc_Cursor_out_0_4_3.docx](https://github.com/davidgohel/officer/files/11830178/Doc_Cursor_out_0_4_3.docx)
[Doc_Cursor.docx](https://github.com/davidgohel/officer/files/11830179/Doc_Cursor.docx)

**Comment by davidgohel** [comment]
As explicated in the documentation, results need to be assigned.

You can read more about this in first paragraphs of the doc: https://ardata-fr.github.io/officeverse/officer-for-word.html

[...] use one of the body_add_* functions: [...]

They all have the same output and the same first argument: the R object representing the Word document, these functions are all taking as first input the document that needs to be filled with some R content and are all returning the document, that has been augmented with the new R content(s) after the function call.

See also #484 for example
