### ISSUE TITLE
add ph label in layout_properties

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/officer#51]

**Comment by xvrdm** [comment]
Hi David,

Thanks for the amazing package!!! It's one of the best things I found to convince people of R usefulness in the "traditional" corporate world!

This feature would be amazing, especially if we could target a specific ph label in ph_with_text without having to specify the type.

**Comment by davidgohel** [comment]
layout_properties returns new column `ph_label`.

@xvrdm sorry, not possible right now but thanks, very good suggestion. I keep that in mind for next run of improvements :)
