### ISSUE TITLE
Replacing bkm with flextable within textbox remove textbox

### ISSUE THREAD

**Issue by cataclysmic** [davidgohel/officer#523]
I have a rather complex document with a textbox, containing another textbox, containing a table or image with a bookmark for replacement.
The last is supposed to be replaced with a flextable using body_replace_flextable_at_bkm().
However, doing this removes all the mentioned textboxes and contained elements, only leaving the inserted flextable.

Using the identical script but replacing with an external image (body_replace_image_at_bkm() ) works without issues.
My current solution is to first save the flextable as png and then replacing the bkm using that image. However, using a PNG for a table is not a nice solution.

**Comment by davidgohel** [comment]
See https://ardata-fr.github.io/officeverse/officer-for-word.html#replacement

> [...] officer’s functions allow you to replace only the whole paragraph on which the bookmark is located. Many users would like to be able to replace only a part of the text in a paragraph but that is not what the function do. The operation replace a paragraph containing a bookmark by a new paragraph [...]


'officer' replaces the whole black that contains the bookmark. I don't think it can offer you a solution for this case.
