### ISSUE TITLE
Applying styles to parts of a table that was added via `body_add_table(style = ...)`

### ISSUE THREAD

**Issue by SchmidtPaul** [davidgohel/officer#529]
I have a template file: [UBA Template gruen table.docx](https://github.com/davidgohel/officer/files/13068595/UBA.Template.gruen.table.docx)

![image](https://github.com/davidgohel/officer/assets/31928213/42cadcb8-871f-4581-a3ac-f05378441ef7)

I want to create Word files with tables formatted exactly as in the template. However, afaik 

- I can only apply the table style (see top of screenshot),
- but I cannot also apply the styles for header and body within the table (see right-hand side of screenshot)

``` r
read_docx("UBA template gruen table.docx") %>%
   body_add_table(value = mtcars, style = "UBA_Tabellenformatvorlage") %>%
   print(target = "new.docx")
```

When running the code above, I obtain a table with the correct fill colors, but the content is not formatted in any specific style and thus not bold etc. 

Is there a solution for this?

**Comment by davidgohel** [comment]
you need to make sure your table theme specify header should be bold (it's not the case in your document)

<img width="589" alt="Capture d’écran 2023-10-23 à 12 10 40" src="https://github.com/davidgohel/officer/assets/4331618/281a7c76-a9e1-41a6-bff9-37fd7966a7a4">

And use the arguments `first_row`, etc. listed in the documentation

**Comment by SchmidtPaul** [comment]
Yes, thanks, I thought as much.
However, the template file is not mine. Thus, I can create a copy of it where I fix this as you said so that just applying the table style will lead to a table that **looks** exactly like the original. 
However, strictly speaking, my tables will not be identical to theirs, as the respective table content does not have the styles applied to it. But I guess their approach is the real issue here and I have to live with that.

**Comment by davidgohel** [comment]
I understand, this 'bold' setting may be part of a global settings but officer don't read them so there is not much to do, sorry
