### ISSUE TITLE
Invalid index with ph_with_text should generate an error

### ISSUE THREAD

**Issue by YourEconProf** [davidgohel/officer#53]
The pptx is nothing more than a blank pptx file opened & saved.

```
library(officer)
library(magrittr)

# Load PPTX file:
pptx_file = read_pptx(path = 'officer-test-blank.pptx')
pptx_file = pptx_file %>% on_slide(index = 1) %>%
  ph_with_text(type = "ctrTitle", str = "This is a title") %>%
  ph_with_text(type = "subTitle", str = "This is a subtitle") 
  
pptx_file = pptx_file %>% add_slide(layout="Title and Content", master="Office Theme") %>%
  ph_with_text(type = "body", str = "Test 1", index = 1) %>%
  ph_with_text(type = "body", str = "Test 2", index = 2) %>%
  ph_with_text(type = "title", str = "This is a title")

print(pptx_file, target = 'officer-test-out.pptx') %>%
  invisible()
```

This is all run on a Mac, and the result "needs repaired" and then lacks 'Test 2' bullet point.
[officer-test-out.pptx](https://github.com/davidgohel/officer/files/1304958/officer-test-out.pptx)
[officer-test-blank.pptx](https://github.com/davidgohel/officer/files/1304959/officer-test-blank.pptx)

**Comment by davidgohel** [comment]
The issue is not because of your pptx template but because you used layout *Title and Content* and then you tried to add two body parts while there is simply only one body part. 

Thanks for reporting this, I will generate an error to warn users in that case.
