### ISSUE TITLE
Unexpected behaviour from function ph_remove. Not removing the shape passed in ph_label parameter

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/officer#535]
### Discussed in https://github.com/davidgohel/officer/discussions/534

<div type='discussions-op-text'>

<sup>Originally posted by **AnaRosaMarques** November  2, 2023</sup>
Hello everyone, 

I am using the latest officer version 0.6.3 and noticed unexpected behaviour from function ph_remove. 

The function ph_remove is not always removing the shape passed to parameter ph_label. I am attaching an example PPT that I am using.  [Test_template.pptx](https://github.com/davidgohel/officer/files/13236788/Test_template.pptx)

`library(officer)`
`template_ppt <- officer::read_pptx("Test_template.pptx")`
`officer::slide_summary(template_ppt)`
`template_ppt <- officer::ph_remove(x = template_ppt, ph_label = "Subtitle 2")`
`officer::slide_summary(template_ppt)`

In the summary we see that "Subtitle 2" was not deleted. Instead "TextBox 7" was deleted.

Another example: 

`template_ppt <- officer::read_pptx("Test_template.pptx")`
`officer::slide_summary(template_ppt)`
`template_ppt <- officer::ph_remove(x = template_ppt, ph_label = "TextBox 7")`
`officer::slide_summary(template_ppt)`

"TextBox 7" was not deleted. Instead "Slide Number Placeholder 5" was deleted. 

Could this behaviour please be verified? I believe I am applying the function correctly.
Thank you

Information about my system: 

`$platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "4"

$minor
[1] "0.2"

$year
[1] "2020"

$month
[1] "06"

$day
[1] "22"

$`svn rev`
[1] "78730"

$language
[1] "R"

$version.string
[1] "R version 4.0.2 (2020-06-22)"

$nickname
[1] "Taking Off Again"`

Thank you</div>

**Comment by thebioengineer** [comment]
Apologies, I just noticed that you had this issue, opened issue #540 with a suggested solution
