### ISSUE TITLE
docx_summary() function doesn't work after caption insertion

### ISSUE THREAD

**Issue by mishinanya** [davidgohel/officer#536]
In case we add caption in the _doc_ object with _body_add_caption()_ the function _docx_summary()_ no longer works and came out with the following error:
**ERROR in data.frame(level = as.integer(xml_attr(xml_child(node, "w:pPr/w:numPr/w:ilvl"),  :
  the arguments imply different numbers of lines: 1, 0**

The R code to reproduce the error:
>library(officer)
>doc <- read_docx()
>caption_1 <- block_caption("This is Caption #1", style = "caption")
>doc <- body_add_caption(doc, caption_1)
>docx_summary(doc)

If you'll try another style, e.g., "Normal" as used in documentations the error will be still here.

**Comment by davidgohel** [comment]
Thanks it should be fixed now
