### ISSUE TITLE
PPTX get_shape_id identifying wrong ID

### ISSUE THREAD

**Issue by thebioengineer** [davidgohel/officer#540]
https://github.com/davidgohel/officer/blob/611328dba65904291ef308ae896b7bd2528df6b4/R/ppt_ph_manipulate.R#L7

I am having some problems with ph_remove not removing a placeholder for me. I think I have narrowed it down to "get_shape_id" returning an incorrect reference. It seems to be based on the assumption that the id numbers of the placeholders are sequential and start at 1. Also, the code requires the user to have passed an id and at least a type or a ph_label.

Additionally, is this expected to only ever return a single id, or multiple?

I would suggest updating the code logic to as follows:

```
get_shape_id <- function(x, type = NULL, id = NULL, ph_label = NULL ){
  slsmry <- slide_summary(x)
  
  if(is.null(type) & is.null(ph_label) & is.null(id)){
    stop("Provide at least one shape identifier: type, id, or ph_label")
  }
  
  error_message_prefix <- ""
  
  if( !is.null(type) ){
    slsmry <- slsmry[slsmry$type %in% type,]
    
    if( nrow(slsmry) < 1 ) {
      stop("no shape of type ", shQuote(type), " has been found")
    }else{
      error_message_prefix <- paste0(error_message_prefix," of type ", shQuote(type)," and")
    }
  }
  
  if( !is.null(ph_label)) {
    slsmry <- slsmry[slsmry$ph_label %in% ph_label,]
    if( nrow(slsmry) < 1 ){
      stop("no shape",error_message_prefix," with label ", shQuote(ph_label), " has been found")
    }else{
      error_message_prefix <- paste0(error_message_prefix," with label ", shQuote(ph_label)," and")
    }
  } 
  
  if(!is.null(id)){
    slsmry <- slsmry[sel == id]
    if( nrow(slsmry) < 1 ) {
      stop("no shape",error_message_prefix," with id ", id, " has been found")
    }
  }
  
  slsmry$id
}

```

**Comment by thebioengineer** [comment]
https://github.com/davidgohel/officer/blob/611328dba65904291ef308ae896b7bd2528df6b4/R/ppt_ph_manipulate.R#L66 
I think this line will also need to be updated to be more general & not just do the index of the placeholder but actually use the id:
```
for(id in office_id){
 current_elt <-  xml_find_first(slide$get(), sprintf("p:cSld/p:spTree/*[p:nvSpPr/p:cNvPr[@id=%.0f]", id) )
 xml_remove(current_elt)
}
```

**Comment by thebioengineer** [comment]
@davidgohel - Ive been looking into this more and I had a question. Often times throughout the code, it looks like you use the argument "id", and use it to identify which of the replicates of the p:sp nodes were used. 

I was curious if you'd be open to be using the Id's from the p:cNvPr id attributes instead.  I _think_ cNvPr is unique to each sp node so we could use that to uniquely identify the node to modify, edit, delete, add. 

I can open a preliminary PR with those changes to discuss that more.

**Comment by davidgohel** [comment]
> Also, the code requires the user to have passed an id and at least a type or a ph_label.

Yes, I added `If used, \code{type} and \code{id} are ignored.` in the documentation of `ph_label`so that it is clearer.

> Additionally, is this expected to only ever return a single id, or multiple?

A single id

> [...] use the id

Yes, it's safer to use an ID, I was tired when I did this change, sorry.

-----
The original issue is fixed now.
