### ISSUE TITLE
docx_comments bugs

### ISSUE THREAD

**Issue by linuxiaobai** [davidgohel/officer#541]
The docx_comments function was intruduced in version 0.6.3, and I found there are 2 bugs as below:
1. When the commented text across paragraphs, the function will put a error "Error in comment_range[[2]] : subscript out of bounds".
2. In word, we can add reply to a comment. Then is it possible link the "reply comment" with the "original comment"?

Happy New Year!

**Comment by trekonom** [comment]
As I authored `docx_comments`...

Thx for reporting. I can confirm that 1. is a bug. I already had a look at the issue and prepared a fix to account for comments spanning multiple paragraphs.

Concerning the 2. bug: Could you clarify what's the issue? This sounds more like a feature request.

**Comment by davidgohel** [comment]
This issue is fixed thanks to @trekonom (thanks for your time!)
