### ISSUE TITLE
Have body_replace_img_at_bkm use image size in document, not from external_img

### ISSUE THREAD

**Issue by kendonB** [davidgohel/officer#545]
The current default size for the image inserted using `body_replace_img_at_bkm` is the size defined in `external_img`. A potentially more natural alternative is to pull the size from the existing image inside the document. i.e., the value here in ms word

![image](https://github.com/davidgohel/officer/assets/5327505/f493ac2e-7fbb-41a3-9c73-67bb3a72187c)

When I open up the xml I can see it in the extent cx cy attribute for that image (don't know how to programmatically get these)

```
`<wp:extent cx="4995748" cy="7491432"/>`

> c(4995748/360000, 7491432/360000)
[1] 13.87708 20.80953
```

**Comment by kendonB** [comment]
Ok [phound](https://www.phind.com/search?home=true) this for how to extract

```
library(xml2)
library(officer)

# Read the Word document
doc <- read_docx(fn_word_doc)

# Access the underlying Word document XML
xml_content <- docx_body_xml(doc)

my_bookmark <- "model_outputs_by_region"
# find bookmark
bookmark <- xml_find_first(xml_content, paste0(".//w:bookmarkStart[@w:name='", my_bookmark, "']"))

# find image in xml_content but after bookmark

# Get the parent of the bookmark
siblings <- xml_siblings(bookmark)

# get index of image
image_index <- which(as.character(siblings) |> str_detect("w\\:drawing"))

# trim xml to just image
image <- as.character(siblings[image_index])
# extract extent of image
extent <- str_extract(image, "<wp:extent.*?/>")

# extract width and height
width <- parse_number(str_extract(extent, "cx=\"(.*?)\""))
height <- parse_number(str_extract(extent, "cy=\"(.*?)\""))

# convert to cm
width_cm <- as.numeric(width) / 360000
height_cm <- as.numeric(height) / 360000
print(paste0("width: ", width_cm, "cm"))
print(paste0("height: ", height_cm, "cm"))
[1] "width: 13.8770777777778cm"
[1] "height: 20.8095333333333cm"
```

**Comment by davidgohel** [comment]
We are not making any change or improvements to these functions, we'd like to deprecate them. Could you change your strategy and use `external_img(guess_size=TRUE)` instead?

I have updated the book to explain what are the recommendations:

https://ardata-fr.github.io/officeverse/officer-for-word.html#content-replacement

See also https://ardata-fr.github.io/officeverse/paragraphs-chunks.html
