### ISSUE TITLE
Quarto rendering problem due to check of `tbl-cap` as cell option

### ISSUE THREAD

**Issue by cderv** [davidgohel/officer#546]
````markdown
---
title: "Test"
format: docx
keep-md: true
---

```{r}
library(flextable)
```

## Results

@tbl-mtcars-summary summarises the cars in the mtcars dataset by transmission.

```{r}
#| label: tbl-mtcars
#| tbl-cap: Test
flextable(head(mtcars))
```
````

Error is 
````
Quitting from lines 16-19 [tbl-mtcars] (index.qmd)
Error in `opts_current_table()`:
! if a label (tbl-mtcars) is defined, chunk option `tbl-cap` should also be defined.
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
 22. knitr (local) value_fun(ev$value, ev$visible)
 23. knitr (local) fun(x, options = options)
 26. flextable:::knit_print.flextable(x, ...)
 27. flextable:::knitr_update_properties(...)
 28. officer::opts_current_table()
                                       
````

The problem is that with latest Quarto and latest **knitr** the `tbl-cap` is not passing through as a **knitr** option because 
- It is not a known  knitr option at first
- It is not used in R code but by Quarto directly for the tab caption feature. 

I don't think this need to be checked. Getting the `tbl-cap` value in **flextable** should not be needed. 

If it is required somehow, then we need to improve how things work - but currently only known **knitr** option will be seen in the options context like in `opts_current()`

**Comment by cderv** [comment]
Thoughts: I think in such check situation, warnings should probably be used instead of errors so that the whole rendering does not stop just because of this... It would lead to maybe undesired result for the table, but overall the rest of the document would work.

**Comment by davidgohel** [comment]
Thank you @cderv , I'll fix it soon

**Comment by davidgohel** [comment]
Thanks, I removed all attempts to read any Quarto settings
