### ISSUE TITLE
Error in doc_parse_raw: xmlParseEntityRef:

### ISSUE THREAD

**Issue by peeyooshc** [davidgohel/officer#55]
I get this error on some data frames and not others.

I attempted to force the encoding to UTF-8 on the source dataframe using 
`sem_account_costs$x <- stri_encode(sem_account_costs$x, "", "UTF-8")`
 but that didn't help.

Warning: Error in doc_parse_raw: xmlParseEntityRef: no name [68]
Stack trace (innermost first):
    73: <Anonymous>
    72: stop
    71: doc_parse_raw
    70: read_xml.raw
    69: as_xml_document.character
    68: as_xml_document
    67: inherits
    66: create_node
    65: xml_replace.xml_node
    64: xml_replace
    63: format.ms_chart
    62: format
    61: pml_chart
    60: ph_with_chart

The core dataframe I'm passing in is consistent with instances where it works.

Are you able to guide me to a solution or workaround ?

**Comment by peeyooshc** [comment]
Ok I managed to track it down. One of my rows contained the & symbol. 

I have a workaround for the moment, but what should I be escaping it with so that it passes through correctly?

**Comment by davidgohel** [comment]
Thanks for reporting the issue. I will fix it in the next development run.

**Comment by davidgohel** [comment]
It should be fixed now. You need to update mschart with command `devtools::install_github("ardata-fr/mschart")`

**Comment by peeyooshc** [comment]
Thank you !
