### ISSUE TITLE
"unreadable content" when inserting GIF images into slide

### ISSUE THREAD

**Issue by wdearden208** [davidgohel/officer#56]
![india](https://user-images.githubusercontent.com/10818050/30980179-aec6fe5e-a445-11e7-9c7d-116b65d84076.gif)

When I insert a gif image, PowerPoint gives the standard unreadable content warning and then repairs the presentation. When the file is "repaired", it appears exactly as intended with the gif inserted correctly.

```
library(officer)
library(magrittr)

gif_issue <- read_pptx() %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>%
  ph_with_text(type = "title", str = "A title") %>%
  ph_with_img(type = "body", src = "India.gif", height = 3, width = 3)

print(gif_issue, target = "gif_issue.pptx")
```

The same issue does not occur with png or jpg.

P.S. I tried to just attach the gif but it looks like github just prints the gif. Save the gif into the working directory as India.gif to run the snippet above.

**Comment by davidgohel** [comment]
OK, that one is easier than the previous one
