### ISSUE TITLE
It is hoped that `block_pour_docx()` can work in bookdown::word_document2

### ISSUE THREAD

**Issue by perlatex** [davidgohel/officer#562]
Maybe it shouldn't be written here, but I didn't get a response when I asked on the [forum](https://forum.posit.co/t/how-to-import-an-external-word-document-into-bookdown-word-document2/183937), So I have to seek your help here. 

In some cases, I use `bookdown::word_document2` template , Meanwhile I want to use `officer::block_pour_docx()` function which can import an external Word document into the current document.

````
---
title: "report"
output: bookdown::word_document2
---


```{r}
library(officer)
block_pour_docx("questionnaire.docx")
```
````

However, it seem that the `officer::block_pour_docx()` only works at `officedown::rdocx_document`.
it would be great if it could also run in `bookdown::word_document2`.

davidgohel,  thank you very much.

**Comment by davidgohel** [comment]
Why don't you change argument `base_format` ? See first argument of `rdocx_document()` https://davidgohel.github.io/officedown/reference/rdocx_document.html

**Comment by davidgohel** [comment]
yes, so use it as `base_format` value:

```
---
date: "`r Sys.Date()`"
author: "Your Name"
title: "officedown template"
output: 
  officedown::rdocx_document:
    base_format: "bookdown::word_document2"
---
```

**Comment by perlatex** [comment]
Maybe not the result I wanted, but thank you very much
