### ISSUE TITLE
Add comment to an existing paragraph

### ISSUE THREAD

**Issue by daviddiviny** [davidgohel/officer#566]
Thanks to @trekonom for adding the ability to add comments. 

It would be great to add a comment to an existing paragraph, rather than create a new paragraph. 

I have been trying to do this, but don't (yet) understand the xml structure well enough. 

This code works in this reprex but is not generalisable. 

```


x <- read_docx()

x <- body_add_par(x, "Paragraph")

comment<- run_comment(
    cmt =   block_list(
        fpar(ftext(comment_text))),
    run = ftext(""),
    author = "Proofreader",
    date = Sys.Date(),
    initials = "NP"
)

comment_para <- fpar(comment)

comment_wml <- to_wml(comment_para, add_ns = TRUE) %>% str_remove_all(".//w:pPr")

xml_elt <- as_xml_document(comment_wml)

x <- cursor_reach(x, "Paragraph")

cursor_elt <- docx_current_block_xml(x)

path_ <- paste0(xml_path(cursor_elt), "//w:r")

node <- xml_find_first(x$doc_obj$get(), path_)

xml_add_sibling(node, xml_elt, .where = "after")


print(x, "document_with_comment.docx")

```

**Comment by trekonom** [comment]
Hi David,

thanks for the suggestion. 

I prepared a first draft for a pull request to implement this functionality building on `body_bookmark`. Hence I called the function `body_comment`. (:

If you want to check out the functionality you can install my branch using:
```r
remotes::install_github("trekonom/officer", "issue-566")
```
Here is minimal reprex showing the new functionality in action:
``` r
library(officer)

doc <- read_docx()
doc <- body_add_par(doc, "Paragraph.")
doc <- body_comment(doc,
  cmt = block_list("Comment"),
  author = "Proofreader",
  date = Sys.Date(),
  initials = "NP"
)

docx_file <- print(doc, target = tempfile(fileext = ".docx"))

docx_comments(read_docx(docx_file))
#>   comment_id      author initials       date    text para_id commented_text
#> 1          0 Proofreader       NP 2024-04-20 Comment      NA     Paragraph.
```

<img width="932" alt="image" src="https://github.com/davidgohel/officer/assets/16198114/a03752cc-c7ae-40dc-8ebd-951ee3099b7f">

**Comment by davidgohel** [comment]
Hello @trekonom 

I think it's OK to PR your proposition, it looks good to me. I tested it and it worked perfectly.

**Comment by davidgohel** [comment]
Comments can now be added to an existing paragraph thanks to @trekonom
