### ISSUE TITLE
ppt template with background images not displayed in new deck

### ISSUE THREAD

**Issue by patr1ckm** [davidgohel/officer#57]
Big fan of officer! 

Ran into a small bug/issue where background images in a pptx slide template (master slide) aren't being displayed. 

Can be reproduced as follows:

```
library(officer)
doc <- read_pptx("calvin.pptx")
doc <- officer::add_slide(doc, layout = "Title Slide", master = "Office Theme") 
print(doc, "test.pptx")
```
[calvin.pptx](https://github.com/davidgohel/officer/files/1354232/calvin.pptx)
[test.pptx](https://github.com/davidgohel/officer/files/1354239/test.pptx)

**Comment by rlusch** [comment]
I have run into the same issue.  A similar issue occurred when there was an image as part of the master slide.  OfficeR would not read the image.

**Comment by davidgohel** [comment]
Nice pic!

It is solved in the dev version (on github) that will be submitted to CRAN next week

**Comment by davidgohel** [comment]
#43

**Comment by patr1ckm** [comment]
Even better, sorry fur the dupe!
