### ISSUE TITLE
cursor_bookmark does not find bookmarks returned by docx_bookmarks

### ISSUE THREAD

**Issue by LukasWallrich** [davidgohel/officer#583]
I am trying to remove bookmarks from Word files - yet on a simple [test file](https://github.com/user-attachments/files/15784688/test.docx), I cannot even set the cursor to the bookmarks identified by `officer`.  I tried to check all documentation, and believe this should work?

```r
library(officer)
doc <- read_docx(f)
officer::cursor_bookmark(doc, officer::docx_bookmarks(doc)[1])
```
`Error: bookmark 'replication-outcomes' has not been found in the document`

Sessioninfo:

```r
R version 4.4.0 (2024-04-24)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.2.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Africa/Nairobi
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] officer_0.6.6

loaded via a namespace (and not attached):
 [1] compiler_4.4.0    R6_2.5.1          cli_3.6.2        
 [4] ragg_1.3.2        tools_4.4.0       rstudioapi_0.16.0
 [7] uuid_1.2-0        xml2_1.3.6        zip_2.3.1        
[10] textshaping_0.3.7 lifecycle_1.0.4   rlang_1.1.3      
[13] systemfonts_1.1.0 openssl_2.2.0     askpass_1.2.0    
```

When submitting a new issue:

- [x ] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [x ] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [ x] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [ x] Make sure you searched in the *open* and *closed* issues on the github repository.

**Comment by davidgohel** [comment]
See https://ardata-fr.github.io/officeverse/officer-for-word.html#content-replacement

> While the ‘officer’ package does offer some functions for content replacement, it is important to note their limitations and potential difficulties in usage. The approach chosen by ‘officer’ involves using bookmarks placed inside paragraphs, which presents its own challenges:

> Placing bookmarks on successive paragraphs renders them unusable.  
> Placing bookmarks on single words within a paragraph allows for their use.

**Comment by davidgohel** [comment]
because your bookmark is set on multiple paragraph, officer ignore them

**Comment by LukasWallrich** [comment]
Thanks for clarifying that! OT but might you know of another way to do that in R?

**Comment by davidgohel** [comment]
You could use `officer::docx_body_xml()` and look for the tags and then delete them with `xml2::xml_remove()`
