### ISSUE TITLE
Citation in R using 'citation("officer")' should probably not include '_' symbols

### ISSUE THREAD

**Issue by Tristan-Kistler** [davidgohel/officer#585]
When running:
citation("officer")
in R, the output is:
> citation("officer")
Pour citer le package ‘officer’ dans une publication, utilisez :

  Gohel D, Moog S (2024). _officer: Manipulation of Microsoft Word and PowerPoint Documents_. R package version 0.6.6,
  <https://CRAN.R-project.org/package=officer>.

Une entrée BibTeX pour les utilisateurs LaTeX est

  @Manual{,
    title = {officer: Manipulation of Microsoft Word and PowerPoint Documents},
    author = {David Gohel and Stefan Moog},
    year = {2024},
    note = {R package version 0.6.6},
    url = {https://CRAN.R-project.org/package=officer},
  }

It seems to me the underscrores ('_') should not be present in:
 _officer: Manipulation of Microsoft Word and PowerPoint Documents_

PS: love your great work! Very useful package, thanks a lot! :)

**Comment by davidgohel** [comment]
Hello,

I am sorry, I can't see any `_`, where do you see it?

**Comment by Tristan-Kistler** [comment]
Hi, indeed, GitHub's editor interpreted the '_' symbols so that they were not visible anymore (seems to code for italic).

The console output is as attached as image (to avoid interpretation of the symbols).
![citation_officer](https://github.com/davidgohel/officer/assets/133857995/f1ca71a7-3737-45dc-8b39-e2cc4089c016)

Maybe they are wanted. While add.

**Comment by davidgohel** [comment]
Ah 😅 i see
These are mardown délimiters for italic

**Comment by Tristan-Kistler** [comment]
Ok, sorry for wasting your time! :p
Have a nice day and thanks again for your great work  :), I think I use your packages almost every day haha
