### ISSUE TITLE
Remove duplicated layout placeholder(s)

### ISSUE THREAD

**Issue by Majid-Eismann** [davidgohel/officer#589]
Thanks for your awesome package! When working with other people's PPTX layout files, there can be duplicated placeholders. Repairing those manually, as indicated [here](https://github.com/davidgohel/officer/issues/419#issuecomment-1104991259), can take a lot of time.

Therefore, I wrote functions to remove or rename duplicated placeholders. As I understand your package, this method is not easily integrated into the current classes, as the cursor is meant to read only slides. Maybe an optional cleaning feature can be added to the read_pptx function?

[Präsentation1.pptx](https://github.com/user-attachments/files/16393212/Prasentation1.pptx)

```r 
# rename function 
layout_duplicate_rename <- function(x) {
  
  for (slide_layout in split(x$slideLayouts$get_xfrm_data(),factor(x$slideLayouts$get_xfrm_data()$file))) {
    
    for(duplicated_layout in unique(slide_layout$ph_label[duplicated(slide_layout$ph_label)])) {
      
      duplicated_ids <- as.numeric(
        slide_layout[
          slide_layout$ph_label %in% slide_layout$ph_label[duplicated(slide_layout$ph_label)],
        ]$id
      )
      
      rename_ids <- 
        setdiff(duplicated_ids, min(duplicated_ids))
      
      layout_file <- 
        list.files(x$package_dir, paste0(slide_layout$file[1], "$"), recursive = T, full.names = T)
      
      layout_xml <- 
        xml2::read_xml(layout_file)
      
      for (rename_index in 1:length(rename_ids)) {
        
        layout_delete_nodes <-
          xml2::xml_find_all(layout_xml, sprintf("p:cSld/p:spTree/*[p:nvSpPr/p:cNvPr[@id='%s']]", rename_ids[rename_index]))
        
        xml2::xml_set_attr(
          xml2::xml_find_all(
            layout_xml, 
            sprintf("//p:cNvPr[@id='%s']", rename_ids[rename_index])
          ),
          "name", paste0(duplicated_layout, " ", rename_index)
        )
        
      }
      
      xml2::write_xml(layout_xml, file =layout_file)
      
    }
    
  }
}
# delete function 
layout_duplicate_delete <- function(x, keep_max_id = TRUE) {
  
  for (slide_layout in split(x$slideLayouts$get_xfrm_data(),factor(x$slideLayouts$get_xfrm_data()$file))) {
    
    for(duplicated_layout in unique(slide_layout$ph_label[duplicated(slide_layout$ph_label)])) {
      
      duplicated_ids <- as.numeric(
        slide_layout[
          slide_layout$ph_label %in% slide_layout$ph_label[duplicated(slide_layout$ph_label)],
        ]$id
      )
      
      delete_ids <- 
        setdiff(duplicated_ids, ifelse(keep_max_id, max(duplicated_ids), min(duplicated_ids)))
      
      layout_file <- 
        list.files(x$package_dir, paste0(slide_layout$file[1], "$"), recursive = T, full.names = T)
      
      layout_xml <- 
        xml2::read_xml(layout_file)
      
      for (delete_id in delete_ids) {
        
        layout_delete_node <-
          xml2::xml_find_all(layout_xml, sprintf("p:cSld/p:spTree/*[p:nvSpPr/p:cNvPr[@id='%s']]", delete_id))
        
        xml2::xml_remove(layout_delete_node)
        
      }
      
      xml2::write_xml(layout_xml, file =layout_file)
      
    }
    
  }
}

# import attached presentation via officer
ppt_rename <- read_pptx("Präsentation1.pptx")
ppt_delete <- read_pptx("Präsentation1.pptx")

# rename or delete duplicated placeholders
layout_duplicate_rename(ppt_rename)
layout_duplicate_delete(ppt_delete)

# export cleaned pptx files
print(ppt_rename, target = "Präsentation1_rename.pptx")
print(ppt_delete, target = "Präsentation1_delete.pptx")

# annotate
annotate_base("Präsentation1_rename.pptx")
annotate_base("Präsentation1_delete.pptx")

# vs error via original file
annotate_base("Präsentation1.pptx")
```

**Comment by markheckmann** [comment]
Hey @Majid-Eismann,

thanks for your code snippets and ideas to handle duplicate placeholder labels. 

I added a new function `layout_dedupe_ph_labels()` to the package in this [fork branch](https://github.com/markheckmann/officer/tree/issue_589_duplicated_ph_labels).

You can install it as follows:

    remotes::install_github("markheckmann/officer@issue_589_duplicated_ph_labels")

**Would you mind having a look at it, if it does what you need / expect?**

**Comment by markheckmann** [comment]
Hi @davidgohel, does the function naming `layout_dedupe_ph_labels()` work for you? If yes, I will prepare a PR.

**Comment by markheckmann** [comment]
Hi, @davidgohel, I would like to add some **colored console output**, to make it easier for the user to understand the results. 

Here an example with a legend for the output in grey color:

![image](https://github.com/user-attachments/assets/b645d3e0-a9c1-4c93-bee2-77d79d61df4b)

There are several options to achieve this, which one would you prefer?

1. Please, no colored output
2. Import `cli` package. `cli` is very lightweight, it only depends on the internal `utils` package, so minimal overhead.
3. Copy the relevant files from cli package over to officer (several 100 lines of code from 4 files to be copied; `cli` also has an MIT license)
4. Create a simplified version of `cli`'s implementation for color output (about 50-100 lines of code)

My preference is 2.

**Comment by davidgohel** [comment]
If it's sure it won't bring new dep. (there are lot of *suggests*), no problem. From a quick test, it seems ok. So `2` seems OK

**Comment by markheckmann** [comment]
PR is ready: https://github.com/davidgohel/officer/pull/594 :)

**Comment by davidgohel** [comment]
thank you @Majid-Eismann and @markheckmann
