### ISSUE TITLE
pptx add image file issue 

### ISSUE THREAD

**Issue by zhenqiangsu** [davidgohel/officer#59]
Using ph_with_img add image file to a slide. But the image can not be shown if the image file name has a space (windows file names with space)

**Comment by davidgohel** [comment]
Thanks. I will fix that in the next development run. Note it is not specific to windows.

**Comment by vrybkin** [comment]
Hi David,

I wasn't sure where to ask this question, but this seems appropriate enough. In this new package, is there still the ability to export ggplot/gtable objects into vectorized and editable files like in ReporteRs (i.e. [this example](https://stackoverflow.com/questions/9555889/producing-a-vector-graphics-image-i-e-metafile-in-r-suitable-for-printing-in))? I wasn't having any luck using ph_with_img whereas I used to be able to do this with addPlot.

Many thanks!

**Comment by davidgohel** [comment]
Hello

You need the rvg package

The help page is there: 
https://davidgohel.github.io/officer/articles/offcran/graphics.html

**Comment by davidgohel** [comment]
@zhenqiangsu Fixed, sorry for the delay.
