### ISSUE TITLE
layout_summary() layout order deviates from layout order in PPTX file

### ISSUE THREAD

**Issue by markheckmann** [davidgohel/officer#596]
The order of the layouts in `layout_summary()` may deviate from the layout order in the PPTX master. 

As this may irritate the user (in this case me :D), I suggest to return a layout order that matches the one in the PPTX file.

**Example**

File: [many_layouts.pptx](https://github.com/user-attachments/files/16825504/many_layouts.pptx) => This is the internal `template.pptx` with 4 new layouts (`layout_8` to `layout_11`) added at the end.

```r
url <- "https://github.com/user-attachments/files/16825504/many_layouts.pptx"
file <- tempfile(fileext = ".pptx")
download.file(url, file)
x <- read_pptx(file)
x$slideLayouts$get_metadata()
```
NB: I used `x$slideLayouts$get_metadata()` as `layout_summary()` calls this function internally.

```
        master_file              name          filename master_name
1  slideMaster1.xml       Title Slide  slideLayout1.xml    Master_1
2  slideMaster1.xml         layout_10 slideLayout10.xml    Master_1
3  slideMaster1.xml         layout_11 slideLayout11.xml    Master_1
4  slideMaster1.xml Title and Content  slideLayout2.xml    Master_1
5  slideMaster1.xml    Section Header  slideLayout3.xml    Master_1
6  slideMaster1.xml       Two Content  slideLayout4.xml    Master_1
7  slideMaster1.xml        Comparison  slideLayout5.xml    Master_1
8  slideMaster1.xml        Title Only  slideLayout6.xml    Master_1
9  slideMaster1.xml             Blank  slideLayout7.xml    Master_1
10 slideMaster1.xml          layout_8  slideLayout8.xml    Master_1
11 slideMaster1.xml          layout_9  slideLayout9.xml    Master_1
```

`layout_10` and `layout_11` should appear at the end, like in the PPTX file. However, the ordering in `x$slideLayouts$get_metadata()` appears to be lexicographical over `filename`. Hence, `10` and `11` come before `2`, yielding a layout order that deviates from the PPTX file.

**Analysis**

The reason for this lies in the way how the file names are read during initialization in class `dir_collection` (see [line 10](https://github.com/davidgohel/officer/blob/c966124912f13b75d3236056444f4f1ccfa992f2/R/ppt_class_dir_collection.R#L10) in file [ppt_class_dir_collection.R](https://github.com/davidgohel/officer/blob/master/R/ppt_class_dir_collection.R). 

```r
...
filenames <- list.files(path = dir_, pattern = "\\.xml$", full.names = TRUE)
...
```

As per the docs, `list.files` will apply an alphabetic sort here:

> The files are sorted in alphabetical order, on the full path if full.names = TRUE.

**Comment by markheckmann** [comment]
@davidgohel I changed the order in which files are added to the container in this [branch](https://github.com/markheckmann/officer/tree/issue_596_layout_summary_sorting) in [this file](https://github.com/markheckmann/officer/blob/5823fbeaaf16682325dd99ef0eae21bbaa15140b/R/ppt_class_dir_collection.R#L38). 

The layout order comes out as expected now:

```r
url <- "https://github.com/user-attachments/files/16825504/many_layouts.pptx"
file <- tempfile(fileext = ".pptx")
download.file(url, file)
x <- read_pptx(file)
layout_summary(x) 
```

```
              layout   master
1        Title Slide Master_1
2  Title and Content Master_1
3     Section Header Master_1
4        Two Content Master_1
5         Comparison Master_1
6         Title Only Master_1
7              Blank Master_1
8           layout_8 Master_1
9           layout_9 Master_1
10         layout_10 Master_1
11         layout_11 Master_1
```
 
All tests are still passed. However, this is a change in a central class. So I would like to make sure, that there are no unwanted side effects. 

An alternative to this approach would be to do the reordering directly in `get_metadata()` and other places where this may be relevant.

**@davidgohel What do you think?**

**Comment by davidgohel** [comment]
@markheckmann I think you are focused and accurate on these aspects. 

For professional reasons, I don't have the ability to focus on the subject these days (things should be better after September/October). So if you feel able to PR, again it will be welcome. 

If something break, I think the coverage test will show it (and if not, well I'll take time to fix what need to be fixed)

**Comment by markheckmann** [comment]
okay, great. [PR](https://github.com/davidgohel/officer/pull/598) is ready
