### ISSUE TITLE
new function ph_location_id() as a new way of referencing a ph location

### ISSUE THREAD

**Issue by markheckmann** [davidgohel/officer#599]
As one result of discussion [415](https://github.com/davidgohel/officer/discussions/415), a new function `ph_location_id()` as an addition to the `ph_location_*` family of functions, appears to be useful for certain use cases.

**Comment by davidgohel** [comment]
`ph_location_type()` has an `id` parameter, I think this would make a redundant function. 

```
library(officer)
read_pptx() |> 
  add_slide(layout = "Two Content") |> 
  ph_with(value = "a", location = ph_location_type(id = 1)) |> 
  ph_with(value = "b", location = ph_location_type(id = 2)) |> 
  print(target = "zzz.pptx")
```

**Comment by markheckmann** [comment]
Oh, thank, I missed that one. I will close the issue.
