### ISSUE TITLE
Replacement of ReporteRs?

### ISSUE THREAD

**Issue by eusebe** [davidgohel/officer#6]
Hi, 

I heavely use ReporteRs in my institution. Does officer will replace ReporteRs in the near future? 
Do we need to adapt our workflow to this new package soon? 

Thank you very much for you incredible work.
Best, 
David

**Comment by davidgohel** [comment]
Hi David

I'd like to but I will always maintain `ReporteRs` as I have users like your organisation that have implemented reporting with it. What will not happen is new features, they will be implemented in officer if not already available. 

The new package do not have all ReporteRs features yet but it will in the following months (and more, it is already possible to import a whole docx as a tibble for example). It's faster, it does not require java, it has a cursor concept (I am very proud of this feature ;)). 

Packages `officer` will be the main package and `flextable` the tabular package. I have split things to make maintenance easier.

To answer your question, I would say that you don't need to migrate but if you're writing new analytics, you can start using officer.

Let's leave that ticket open for now (if other users have the same question).

++
David

**Comment by MaximeBrt** [comment]
Hi David,

Do you plan on including the "as.vector" feature to have editable plots in pptx ? This is a feature I heavily rely upon and that was really nice to me. As you know there is an OutOfMemoryError with this feature in ReporteRs unfortunately that prevents any further use of the package in the same R session once reached the limit.

Thanks for your work,
Maxime

**Comment by davidgohel** [comment]
The feature is already available by using `rvg::ph_with_vg` (and soon `rvg::ph_with_vg_at`). 

... I will document that better next time I am working on it.

David

**Comment by MaximeBrt** [comment]
Oh that's great thank you so much ! :)

**Comment by LearnMoreR** [comment]
This is slightly off-topic, but is there a way to have rvg::ph_with_vg_at plot with a transparent background?

**Comment by davidgohel** [comment]
@LearnMoreR *slightly* :) Add as argument `bg="transparent"` in the call to `ph_with_vg_at()`, it should to the job

**Comment by LearnMoreR** [comment]
Thank for the quick response. I am trying to migrate workflow from ReporteRs to officer because of java issues. Both are excellent packages!
