### ISSUE TITLE
feat: issue more informative error if ph label does not exist

### ISSUE THREAD

**Issue by markheckmann** [davidgohel/officer#601]
The error message if the ph label does not exist is hard to understand for the user.

```r
x <- read_pptx()
x <- x |> add_slide()
x |> ph_with("test", ph_location_label("xxx"))

Error in fortify_location.location_label(location, doc = x) : 
  no selected row
```

It would be helpful to inform the user about what the problem is and give some guidance.

**Comment by davidgohel** [comment]
agree also on that, let me know if you want to PR or if you want me to do it

**Comment by markheckmann** [comment]
happy to do it
