### ISSUE TITLE
Shapes in templates shouldn't be 'body' tags (and the index order is strange)

### ISSUE THREAD

**Issue by patr1ckm** [davidgohel/officer#61]
In `0.1.8` of `officer`, I can add text to shapes (like line connectors) which are tagged as `type = "body"` placeholders.

This also causes the index order of valid `"body"` (text) placeholders to be unusual (shown in examples).

```
library(officer)
library(dplyr)
p <- read_pptx("plain_shape_nb.pptx") %>%
  add_slide("Title and Content", master = "Office Theme") %>%
  ph_with_text("1", type = "body", index = 1) %>%
  ph_with_text("2", type = "body", index = 2) %>%
  ph_with_text("3", type = "body", index = 3)
  

print(p, "generated.pptx")
system("open generated.pptx")
```
[plain_shape_nb.pptx](https://github.com/davidgohel/officer/files/1377405/plain_shape_nb.pptx)
[generated.pptx](https://github.com/davidgohel/officer/files/1377404/generated.pptx)

A fix might be as simple as changing a line in [read_xfrm](https://github.com/davidgohel/officer/blob/00bdd5a798776b50c6daf9fb106ae02fe802171c/R/utils.R#) to return `NA` for the type of these placeholders instead of marking them as `body`.

I think it relates to [#26](https://github.com/davidgohel/officer/issues/26). Currently I'm working around this behavior by making a template where the valid placeholders are already filled with my own text, and using `slide_summary` to get the right index for a placeholder. This works fine for one template, but I would need to repeat this process for arbitrary templates.

As always, thanks for all your awesome work! 

@elsander for vis.

**Comment by davidgohel** [comment]
`body` is not only for text.

From the output of `layout_properties` (see `ph_label`) I have enough information to know id associated with `body` placeholders.

```
> layout_properties(p, layout = "Title and Content", master = "Office Theme")
    master_name              name   type id                   ph_label      offx      offy        cx
15 Office Theme Title and Content  title  2                    Title 1 0.9166667 0.3993056 11.500000
16 Office Theme Title and Content   body  3      Content Placeholder 2 0.9166667 1.9965278 11.500000
17 Office Theme Title and Content     dt  4         Date Placeholder 3 0.9166667 6.9513889  3.000000
18 Office Theme Title and Content    ftr  5       Footer Placeholder 4 4.4166667 6.9513889  4.500000
19 Office Theme Title and Content sldNum  6 Slide Number Placeholder 5 9.4166667 6.9513889  3.000000
20 Office Theme Title and Content   body  8       Straight Connector 7 2.4320986 5.7160499  8.333333
21 Office Theme Title and Content   body  9         Text Placeholder 7 0.4982633 0.7003489  8.985624
           cy
15 1.44965332
16 4.75868110
17 0.39930556
18 0.39930556
19 0.39930556
20 0.01234471
21 0.38024606
```

Does that help? I can't return NA for body elements that are not text.

**Comment by patr1ckm** [comment]
Right, that's the issue. I don't think a `Straight Connector` should be a valid `body` placeholder (for example). If a plot is added to it, the resulting pptx can be corrupted. While adding text doesn't corrupt the pptx, it's not usually what I intend.

I might just be missing an easy feature for automatically adding text or objects to valid (that is `Text Placeholders`. In lieu of that, I'm not confident that a regex on `ph_label` from `layout_properties` always get valid text placeholders for any template.

`ReporteRs::addParagraph` would cycle through the placeholders without this issue, and it's tripping me up a bit.

**Comment by davidgohel** [comment]
In the windows version of PowerPoint, you can select a shape and edit its name, in the slidelayout view. 

That's what you will see in column `ph_label`. Some users asked about displaying them in `layout_properties`(#51).

**Comment by patr1ckm** [comment]
Thanks! Happy to close this.
