### ISSUE TITLE
feat: add `layout_rename_ph_labels()` to edit ph labels via officer

### ISSUE THREAD

**Issue by markheckmann** [davidgohel/officer#610]
It seems, that there are cases where users would like to change ph labels. It is of course possible to do so in PowerPoint (though not so obvious where in the menu one has to click, e.g. [here](https://stackoverflow.com/questions/58508859/r-officer-package-how-to-specify-a-certain-placeholder-when-there-are-multiple)). While not a core feature, it would still be nice to have this option directly in officer. 

*NB*: This would also allow for *custom* renaming in case of duplicated placeholders etc.  `layout_dedupe_ph_labels()` does not offer custom renaming.

**Comment by davidgohel** [comment]
If you think you have enough energy and time to do it, of course the idea is interesting. If not, I could do it, but not soon :)

**Comment by markheckmann** [comment]
I can do it. Still on holiday with some time on my hands...

**Comment by davidgohel** [comment]
(ah, I miss the days when I had time to do that :))

OK, waiting for this before releasing to CRAN then.

**Comment by markheckmann** [comment]
Completed via PR #614

**Comment by markheckmann** [comment]
Completed via PR #614
