### ISSUE TITLE
Question: undo R (>= 4.1) requirement caused by pipe usage?

### ISSUE THREAD

**Issue by markheckmann** [davidgohel/officer#615]
I just noticed that I introduced an R (>=4.1, May, 2021) min requirement by using the pipe `|>` in various places.

@davidgohel :**Do you prefer I remove it again before moving the version to CRAN? The current min requirement is R (>= 3.6, April, 2019) from {R6}.**

**Comment by markheckmann** [comment]
I just saw this line in `NEWS.md`.

> - let the package be used with R < 4 by not using `\(x)` syntax

I will remove the pipe and PR.

**Comment by davidgohel** [comment]
hello, sorry for not answering sooner

yes please

**Comment by markheckmann** [comment]
PR is ready: https://github.com/davidgohel/officer/pull/616
