### ISSUE TITLE
Feat: add `overwrite` arg to `print()`

### ISSUE THREAD

**Issue by markheckmann** [davidgohel/officer#619]
In [this SO post](https://stackoverflow.com/questions/79022175/officer-save-document-dont-overwrite), a user was looking for an `overwrite` arg in `print` (like for example in `openxlsx::write.xlsx()`). 

I like the suggestion to add an `overwrite` arg:

```r
print(x, target = "pres.pptx", overwrite = FALSE)  # default
print(x, target = "pres.pptx", overwrite = TRUE)  # optional
```

**Comment by davidgohel** [comment]
hello @markheckmann 

I prefer

```
print(x, target = tempfile(fileext = ".pptx")) |> browseURL() 
```

If you look at write.xslx, write_csv, etc, nobody uses `overwrite`. It seems weird to me to not be able to iterate over the same file over and over just because I created it once. 

Happy to discuss this if you think we should

**Comment by markheckmann** [comment]
After all, I agree. And in case someone needs to prevent overwriting, they can simply add an if statement. 

I will close the issue.
