### ISSUE TITLE
Bug with docx_summary?

### ISSUE THREAD

**Issue by hangler** [davidgohel/officer#62]
Please check out this attached doc, which is a simplified excerpt from a real-world one I am working with: [officer-table-error.docx](https://github.com/davidgohel/officer/files/1377876/officer-table-error.docx)

There's no problem reading in or editing this doc, but using `docx_summary()` generates an error:

```r
> doc <- read_docx("~/Desktop/officer-table-error.docx")
> docx_summary(doc)
Error in `[<-.data.frame`(`*tmp*`, dat$row_merge & dat$first, "row_span",  : 
  replacement has 2 rows, data has 93
```

From what investigation I was able to do, the error is thrown in this line in `docxtable_as_tibble()` in `fortify_docx.R`: https://github.com/davidgohel/officer/blob/427f6d0d40fa25f32156e5048cc4fd5b8f2c5a75/R/fortify_docx.R#L69

Deleting the last line of the doc (which I have commented in Word), re-loading and re-running `docx_summary()` works just fine.

**Comment by davidgohel** [comment]
Hi, thanks for the example. It should be solved now.

**Comment by davidgohel** [comment]
ask to re-open if necessary

david
