### ISSUE TITLE
feat: plot_layout_properties() accepts layout index as alternative to layout name

### ISSUE THREAD

**Issue by markheckmann** [davidgohel/officer#621]
Since [recently](https://github.com/davidgohel/officer/commit/182923ad441c5241b63b06073b645d5877b330fb), `plot_layout_properties()` accepts the layout index (as returned by `layout_summary()`) as an alternative to the layout name. Hence, the following two lines are now equivalent.

```r
plot_layout_properties(x, "Title Slide")  # using layout name
plot_layout_properties(x, 1)  # using layout index
```

The same mechanism could be added to `add_slide()` for convenience and consistency. Then the following two lines would also be equivalent. 

```r
add_slide(x, "Title Slide")  # using layout name
add_slide(x, 1)  # using layout index
```

**Comment by markheckmann** [comment]
> This is another way to add a slide but it requires to rewrite the whole documentation, and it's natural to me to specify the layout name. If "Title and Slide" is moved in the layout view, all programs using index will fail.

Fair enough and defenitely the case. For me its a bit like using an index for subsetting dataframe columns. Its more brittle than using column names in case the data changes, it's still convenient. Anyways, as it requires rewriting docs, I would agree to leave it for now.

> I would like to be able to send the current version on CRAN.

Happy to see 0.6.7 moving to CRAN 😀 

Thanks!

**Comment by davidgohel** [comment]
OK, I will prepare the CRAN submission soon

I'd like to thank you very much for all the time you spent on the package recently and the quality of your input. We are now 3 or 4 people capable of maintaining the package properly, and I think that's very healthy and good for 'officer'!

**Comment by john-harrold** [comment]
As someone who uses officer a lot and lurks with respect to the github issues I agree with David.

**Comment by markheckmann** [comment]
Thanks @davidgohel, thanks @john-harrold 

Happy to be involved!

**Comment by davidgohel** [comment]
> thanks, package officer_0.6.7.tar.gz is on its way to CRAN.
 
:)
