### ISSUE TITLE
[Feature request] Text Highlight Color with `fp_text()`

### ISSUE THREAD

**Issue by laresbernardo** [davidgohel/officer#624]
Would it be possible to include an option to highlight text with color maybe as new parameters within `fp_text()`? Sharing a screenshot of the PowerPoint (I guess also Word) functionality as a reference. Didn't see in `officer`'s documentation a way of doing this.

![image](https://github.com/user-attachments/assets/5e594477-e2a3-4a4b-bdf5-d975dbf40409)

Thanks a lot!

**Comment by davidgohel** [comment]
It already exists:

```
library(officer)
fpt <- fp_text(shading.color = "yellow")
doc <- read_pptx() |> 
  add_slide() |> 
  ph_with(fpar(ftext("dfsdf", prop = fpt)), location = ph_location()) |> 
  print(target = "test.pptx")
```

**Comment by laresbernardo** [comment]
Fantastic. Thanks for sharing. I wasn't able to find it because it's got a different naming. That was it!

Is there a way to mix `fpar()` with a placeholder so that the template's format doesn't get lost? By default in my case, vectors are passed and placed as orange bullet points using the template's text format (size and font). When using this approach, this gets lost:

```
# Build a block with several formated fpars
these <- block_list(
    fpar("This is a common string",
    fpar(
      "Included ", 
      ftext("[[X%]]", prop = fpt), " and ", 
      ftext("[[X%]]", prop = fpt), " highlighted texts"
    ),
  )

# Add it to the ppt
ph_with(ppt, these, location = ph_location_label(ph_label = "Placeholder")) 
```

Any recommendation with a different approach? Thanks again.
