### ISSUE TITLE
Testing/documentation help

### ISSUE THREAD

**Issue by elsander** [davidgohel/officer#64]
Hi! I'm going to be spending this week and some of next doing some open source work. I'm working on a project that uses `officer`, so I wanted to see if I can contribute! Your README mentions wanting help with testing and documentation. If you have specific areas you'd like help, let me know. Otherwise, I can look for areas that could use more testing/documentation on my own.

**Comment by davidgohel** [comment]
Hi and many thanks :)

I don't know... If you feel something is *bad english* or the documentation is lacking details, tell me (or better, tell me what I should change to make it clearer).

David

**Comment by elsander** [comment]
Great! I've started reading through the documentation and making changes as I notice things. Closing this since it's not a specific issue to be solved.
