### ISSUE TITLE
PPT - on_slide - index - greater than 10

### ISSUE THREAD

**Issue by VincentBlanchard** [davidgohel/officer#65]
Hello All.

First thanks for your great package!

The function **on_slide()**, with an index greater or equal to 10 generate a powerpoint error:
"PowerPoint found a problem with content..."

Thanks you for help.

**Comment by davidgohel** [comment]
Hello,

I can't reproduce.

Can you add a **reproducible example and `sessionInfo()`**?

**Comment by VincentBlanchard** [comment]
My bad, the issue might be due to my bad ppt Template.
Thanks you David
