### ISSUE TITLE
body_remove more than one paragraph

### ISSUE THREAD

**Issue by antuki** [davidgohel/officer#68]
Hello !

I'm testing today your wonderful officer package and I would like to find a way to use body_remove but not only a paragraph but many of them.

For example, I would like to be able to : 
* clear the first / last page
* delete all paragraphs which are after / before a paragraph containing "Drop that text"

I'm not sure it is possible (am i wrong ?) because you wrote in the doc that regular expressions are not supported..
but I think it would be a great and useful improvement !

Thanks

**Comment by davidgohel** [comment]
Hi,

I don't remember having written  `regular expressions are not supported..` Can you show me where is it?

What is the business case behind your need? You can already do it with the existing tools (and a for loop or a sapply, or...).

One important comment, in Word, you can't know on are on `page 1` (this is rendered by Word, not described in the document).


David

**Comment by davidgohel** [comment]
Cool, thanks, I need to correct that doc, this is no more true...

I think you can switch to french :) with single condition to summarize in english the answer for other if I can help you ;)

**Comment by davidgohel** [comment]
Sorry, not necessary, I got it

**Comment by davidgohel** [comment]
For a graphic, table, or paragraph, you need to add a bookmark `a_bkmk` into the paragraph preceding the content. Then with officer, something as following:

[test.docx](https://github.com/davidgohel/officer/files/1391613/test.docx)

```
library(officer)
library(magrittr)
read_docx("test.docx") %>% 
  cursor_bookmark("a_bkmk") %>% # set cursor on paragraph containing 'a_bkmk'
  cursor_forward() %>% # move cursor forward once, we will be on the content to be removed
  body_remove() %>% # remove
  body_add_par("replacement", style = "Normal") %>% # add new content
  print(target = "result.docx")

```

**Comment by antuki** [comment]
OK thank you for the bookmark trick, it can help me a bit  ! However, if we cannot add bookmarks from R when we add R plots / tables in a docx, i will still have to think about how I have to act to delete easily many R outputs from a document to replace it with new ones (actualized). 

By the way, is it also possible to add bookmarks before a png image ?

And when it is text, is only ONE paragraph concerned ? So, we have to add as many bookmarks as the number of paragraphs we want to delete ?

Thanks

**Comment by davidgohel** [comment]
You can add bookmarks from R with `body_bookmark`. Before or after an element can be reach with `cursor_forward` and `cursor_backward`. 

> And when it is text, is only ONE paragraph concerned? So, we have to add as many bookmarks as the number of paragraphs we want to delete ?

Yes.

I will try to make a doc about that when I will have time.

However, from your questions, I think you need rmarkdown instead officer.

**Comment by davidgohel** [comment]
Let's close this issue. 

David
