### ISSUE TITLE
print method that shows cursor

### ISSUE THREAD

**Issue by t-kalinowski** [davidgohel/officer#7]
Feature request: A better print method.

While interactively editing a document, it is a little cumbersome to check/confirm the cursor movement was successful, or to learn the current cursor position. Would it be possible to get a print method that perhaps prints to the console the paragraph before, current paragraph, and next paragraph after the current cursor position, with some unique ascii symbol showing exactly the current cursor position? Figures and tables could just have placeholders (e.g. `... [figure "figure title"]`

**Comment by davidgohel** [comment]
thanks for the suggestion
