### ISSUE TITLE
ph_with_table_at does not respect left, top, width and height

### ISSUE THREAD

**Issue by cocinerox** [davidgohel/officer#70]
The example for `ph_with_table_at` at https://davidgohel.github.io/officer/articles/powerpoint.html#add-table shows that these location parameters don't work as expected (e.g. the table is always at the top left corner). Tested locally with github version as well. There is a similar issue with `flextable::ph_with_flextable_at`.

**Comment by davidgohel** [comment]
thanks

**Comment by cocinerox** [comment]
Thank you for those are nice EMUs
