### ISSUE TITLE
Copy graphs to clipboard

### ISSUE THREAD

**Issue by danielsjf** [davidgohel/officer#77]
Is there a possibility to export powerpoints graphs to the clipboard? Now I can save them to a file, open the file and paste the chart in another powerpoint. However, it would be nice to have them copied to the clipboard so that I can immediately paste them in the larger presentations.

It could work similar to how the clipr package works:
https://github.com/mdlincoln/clipr

**Comment by davidgohel** [comment]
No but you can insert the graphics inside an existing presentation.
