### ISSUE TITLE
How to change the sequence of existing slides

### ISSUE THREAD

**Issue by ShuguangSun** [davidgohel/officer#78]
For example, I have 4 slides as 1, 2, 3, 4. How could change the order to 1, 3, 4, 2?

For example, I have 4 slides as 1, 2, 3, 4. How could add one slide at the very begining? for exampe a new slide 0, then 1, 2, 3, 4?

I mean in R/officer.

**Comment by davidgohel** [comment]
This is not implemented, that's why it is not documented ;)
