### ISSUE TITLE
R.home("doc") instead of file.path( Sys.getenv("R_HOME"), "doc")

### ISSUE THREAD

**Issue by HenrikBengtsson** [davidgohel/officer#80]
FYI, while inspecting revdep package checks on R.utils, I [stumbled upon](https://github.com/HenrikBengtsson/R.utils/blob/develop/revdep/problems.md#officer) one of your examples and saw:
```r
img.file <- file.path( Sys.getenv("R_HOME"), "doc", "html", "logo.jpg" )
```
FYI, R provides `R.home("doc")` for this.  Where it really matters is for `R.home("bin")` which is agile to multi-arch platforms.

**Comment by davidgohel** [comment]
Ok, thanks for letting me know, I didn't know about `R.home()`.

I will correct it soon
