### ISSUE TITLE
Error when opening PowerPoint file with images on Mac

### ISSUE THREAD

**Issue by zdong2017** [davidgohel/officer#83]
On MAC computer, created PPTX files with images. Files looks all right. But when I open them, an error message always pop up and ask me Repair the file. After click "Repair" button, all images are disappeared. Make the PPTX files useless. It might related to XML links in the PPTX files or something related to "Trusted View".

**Comment by davidgohel** [comment]
Please, add `sessionInfo()` and a reproducible code
