### ISSUE TITLE
Mention rvg and ph_with_vg in documentation and vignette

### ISSUE THREAD

**Issue by moodymudskipper** [davidgohel/officer#84]
This post was very useful for me :

[issues#3](https://github.com/davidgohel/officer/issues/3)

But it wasn't so obvious to find.  I suppose you have your reasons to keep these package separate but I suggest you give `rvg` a mention in the documentation. It's not mentioned at all and when searching for `plot` occurrences are only about the word functions. I also suggest you slip your example using `ph_with_vg` from link above in the vignette, along with a `ggplot `example.

**Comment by davidgohel** [comment]
Yes I have my reasons

It is mentioned. I will emphasis that on the readme.

https://davidgohel.github.io/officer/articles/offcran/graphics.html
