### ISSUE TITLE
Suggestion: Parallelisation of officer functions?

### ISSUE THREAD

**Issue by md0u80c9** [davidgohel/officer#85]
Hi David,

Just having a look at profiling for my analysis package which is producing sets of slides. The vast majority of time spent is sitting in rendering functions (RVG, add_slide, etc).

I was wondering whether there is scope to parallelise operations such as 'add slide'. Clearly there are parallel versions of 'for each' which would work quite nicely. The problem would be that they wouldn't necessarily be produced in the order that they went in.

I wondered whether with some minor redesign of the APIs the slides could be rendered in any given order, and then appended at the end, which would make them much more ripe for being done as a multi-core parallel process.

**Comment by slfan2013** [comment]
I want this feature as well.

**Comment by davidgohel** [comment]
@md0u80c9 @slfan2013 

The parallel processing capability is complicated if not impossible without rewriting most of the pptx code. It may be a feature one day but not now :)

But there was a need of refactoring `add_slide` and other functions. This is related to issue #95 where I will comment.

**Comment by AntoineBrisacier** [comment]
Hi david,
I have similar issue writing docx with officer using body_add_img, body_add_flextable ... Some of our program runs for more than 8 hours (time increase exponentially with number of pages created). Do you have any recommendation of use to decrease time processing ? use of parallelisation ?
Thanks
Antoine

**Comment by davidgohel** [comment]
@AntoineBrisacier could you open a new issue for that with a code that help me to figure out what  operations are guilty?

Thanks 
David
