### ISSUE TITLE
Search-and-replace _ body_replace_all_text

### ISSUE THREAD

**Issue by AnthisKon** [davidgohel/officer#87]
Amazing and very useful package! 

The other command from officer package that i have tried so far worked fine. This one does not seem to be included in the package even though there is documentation.

library(officer)

body_replace_all_text(doc, "Start_Date", "new", onlyAtCursor=F, fixed=TRUE)

Error in body_replace_all_text(doc, "Start_Date", "new", onlyAtCursor = F,  : 
  could not find function "body_replace_all_text"

officer::body_replace_all_text(doc, "Start_Date", "new", onlyAtCursor=F, fixed=TRUE)

Error: 'body_replace_all_text' is not an exported object from 'namespace:officer'

**Comment by hangler** [comment]
Are you using the development version of `officer`, or the CRAN version? This function has not yet been published to the version on CRAN.

**Comment by AnthisKon** [comment]
Thank you very much! Of course that's the reason. You can close it.

**Comment by AnthisKon** [comment]
Just to add another issue I faced: 

Error in body_replace_all_text(doc, "\\bn.*?\\b", "example") : 
  attempt to apply non-function

The problem was that I did not set the cursor position. Positioning the cursor at a random position solved this.

**Comment by davidgohel** [comment]
@hangler thanks

@AnthisKon I have not been able to reproduce your second issue, also avoid iterating new questions in a single issue.
