### ISSUE TITLE
ReporteR equivalent function

### ISSUE THREAD

**Issue by AnthisKon** [davidgohel/officer#88]
Is there an equivalent function as this one; : 

setFlextableBackroundColors()

My goal is to pass a data.frame and color = {a conditional to choose between 4 colors} and to do this task for i and j of the whole data frame, cell to cell. 

A workaround would be to use multiple bg() functions but for bigger data.frames that's way too much.

Example: 

test = data.frame(x = c(1,0, 'N/A',-7,1,-0.4), y= c(-1,-5,1,1, 'N/A',-0.5),l = c(-0.4,1,1,-10,-10,-0.5), k = c(-5,1,1,-0.4,-0.9,1))

  Flex = FlexTable(test) 
  Flex = setFlexTableBackgroundColors(
    Flex,
    i = 1:dim(test)[1] , 
    j = 1:dim(test[2], 
    colors = ifelse( test == 'N/A' ,'white' , ifelse(test >= 0 , 
        'green' ,ifelse(test >= -1 ,
          'yellow', 
          'red'
        )
      )
    )

**Comment by davidgohel** [comment]
Sorry, your code is not reproducible, there are syntax errors.

I don't understand what you mean with the workaround. 

---

You need to read the issue #37 

The help page is there: https://davidgohel.github.io/officer/

As you are talking about tables, you should have a look there: https://davidgohel.github.io/flextable/

Hope it will help.
