### ISSUE TITLE
New function: Bulk text with hierarchy insert to pptx placeholder

### ISSUE THREAD

**Issue by eregmig** [davidgohel/officer#89]
Hello David,

First of all, congrats for the created library, I really like it.

I have been creating some PowerPoint files with the library and have found quite difficult to insert paragraphs with hierarchies into a single object. First, it requires many sentences of ph_add_par and ph_add_text doing the code long and also need to find out the id_chr that changes from slide to slide. I have created a function to provide a list of texts to include and a list of hierarchy levels, so in a single line all text is inserted and there is no need to use slide_summary to identify id_chr of the empty placeholder created.

My created function is as follows, if you find it interesting and good enough for your project, feel free to use it:

```
#' Fill slide object with provided text.
#'
#' Fill slide object with provided text list and each string is identified with certain hierarchy level.
#'
#' @importFrom magrittr "%>%"
#' @param x rpptx object
#' @param type placeholder type
#' @param index placeholder index (integer). This is to be used when a placeholder type is not unique in the current slide, e.g. two placeholders with type 'body'.
#' @param str_list List of strings to be included in the object
#' @param level_list List of levels for hierarchy structure
#' @param style text style, a fp_text object
#' @export
#' @examples 
#' pptx <- officer::read_pptx()
#' pptx <- officer::add_slide(x = pptx, layout = "Title and Content", master = "Office Theme")
#' pptx <- officer::ph_with_text(x = pptx, type = "title", str = "Example title")
#' pptx <- ph_add_new_paragraph_text(x = pptx, type = "body", index = 1, str_list = c("Level1", "Level2"), level_list = c(1,2))
#' print(pptx, target = "example2.pptx") %>% invisible()
ph_add_new_paragraph_text <- function(x, type, index = 1, str_list = c(), level_list = C(), style = officer::fp_text(font.size = 0)) {
  stopifnot(is.character(str_list))
  stopifnot(is.numeric(level_list))
  stopifnot(type %in% c("ctrTitle", "subTitle", "dt", "ftr",
                        "sldNum", "title", "body"))
  if (length(str_list) != length(level_list) & length(str_list) > 0) {
    stop("str_list and level_list have different lenghts.")
  }
  
  x <- officer::ph_empty(x = x, type = type, index = index)
  id <- officer::slide_summary(x) %>%
    dplyr::filter(type == type & text == "") %>%
    dplyr::select(id) %>%
    as.character()
  
  for (i in 1:length(str_list)) {
    x <- officer::ph_add_par(x = x, type = type, id_chr = id, level = level_list[i])
    x <- officer::ph_add_text(x = x, type = type, id_chr = id, str = str_list[i], style = style)
  }
  
  return(x)
}

```

Provided example produce the following pptx file:
[example2.pptx](https://github.com/davidgohel/officer/files/1510985/example2.pptx)

**Comment by davidgohel** [comment]
Thanks!

I used your function but changed few things. It's named `ph_with_ul`(unordered list).

https://github.com/davidgohel/officer/blob/master/R/ppt_ph_with.R#L245

David

PS: yes, `id_chr` manipulation should be easier... I will think about a solution
