### ISSUE TITLE
cursor_reach(): support for other language?

### ISSUE THREAD

**Issue by minghao-wu** [davidgohel/officer#9]
Hi,

I was trying to use keyword to match some Chinese characters but failed.

I noticed that the text search is made via xpath 1.0, but I have no idea about it and am still working on it.

how can I match those Chinese characters with xpath 1.0?

Thank you.

**Comment by minghao-wu** [comment]
problem on my own computer.

problem solved.

**Comment by davidgohel** [comment]
Hi

> I noticed that the text search is made via xpath 1.0, but I have no idea about it and am still working on it.

It's been changed to regular expression :)
