### ISSUE TITLE
Add content to 'notes' pane in powerpoint

### ISSUE THREAD

**Issue by dgJacks0n** [davidgohel/officer#90]
A feature request- would it be possible to add content to the 'notes' pane of a powerpoint slide?

This package makes generating slide decks more reproducible; it would be great to be able to include information about how a slide was generated (such as a git repo/commit) but that's not info that needs to be displayed in the slide body.

Thanks!

**Comment by davidgohel** [comment]
Hi sorry for the delay

I don't have enough time for that but maybe later this year.

**Comment by davidgohel** [comment]
This issue is opened since too much time. Sorry. I will re open when I will find time for it

KR
David

**Comment by creager** [comment]
Any updates on if/when this might be reopened?

Thanks!

**Comment by davidgohel** [comment]
No update (on this 4 yo issue). I am not planning to spend time on it soon
