### ISSUE TITLE
Error when reading content with pptx_summary

### ISSUE THREAD

**Issue by alexiscanizares** [davidgohel/officer#94]
Hi David,
I am getting the same error when trying to read the content of my pptx files. It happens in all files. The file contains only one slide with some boxes of text. 
Please see below:

> doc
pptx document with 1 slide(s)
Available layouts and their associated master(s) are:
                              layout          master
1                      Title Slide 1 Global Template
2 1_Table of Content-Agenda no photo Global Template
3                     Content Master Global Template
4         1_Content_Subtitle_Heading Global Template
5                 2_Heading_Subtitle Global Template

> pptx_summary(doc)
Error in `$<-.data.frame`(`*tmp*`, "id", value = "28") : 
  replacement has 1 row, data has 0

**Comment by alexiscanizares** [comment]
What does invalid mean?

**Comment by davidgohel** [comment]
Hi, 

Sorry, I wanted to set up a form for issues, it's done :)

Can you open a new issue and follow the process. I think you need to update from CRAN.
